'use client';

import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useBusinessHubStyles = createUseStyles((theme: Theme) => ({
  container: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    backgroundColor: "#F8FAFC",
    position: "relative",
    overflow: "hidden",
  },
  scrollableContent: {
    flex: 1,
    overflowY: "auto",
    paddingBottom: "68px",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },

  // ─── APP BAR / HEADER ───
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #F1F5F9",
    position: "sticky",
    top: 0,
    zIndex: 5,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  headerTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  iconBtn: {
    background: "none",
    border: "none",
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0F172A",
    cursor: "pointer",
  },

  // ─── LOCATION BAR ───
  locationBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px 6px 12px",
    backgroundColor: "#FFFFFF",
  },
  unitTitle: {
    fontSize: "13.5px",
    fontWeight: 800,
    color: "#0F172A",
    margin: 0,
  },
  locationPickerBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "4px 8px",
    borderRadius: "6px",
    border: "1px solid #CBD5E1",
    backgroundColor: "#FFFFFF",
    fontSize: "10px",
    color: "#475569",
    fontWeight: 500,
    cursor: "pointer",
  },

  // ─── HORIZONTAL SUB TABS ───
  subTabsRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "6px 12px 0 12px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #E2E8F0",
    overflowX: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  subTabItem: {
    fontSize: "11px",
    fontWeight: 500,
    color: "#64748B",
    paddingBottom: "6px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    borderBottom: "2px solid transparent",
  },
  subTabItemActive: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#0072C4",
    paddingBottom: "6px",
    borderBottom: "2px solid #0072C4",
    whiteSpace: "nowrap",
  },

  // ─── STAT CARDS ROW (Business Hub) ───
  statsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
    padding: "10px 12px 4px 12px",
  },
  statCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    border: "1px solid #E2E8F0",
    padding: "10px",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  },
  statTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "8px",
  },
  statLabel: {
    fontSize: "10.5px",
    fontWeight: 600,
    color: "#475569",
  },
  statIconBlue: {
    width: "22px",
    height: "22px",
    borderRadius: "6px",
    backgroundColor: "#EFF6FF",
    color: "#2563EB",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  statIconPurple: {
    width: "22px",
    height: "22px",
    borderRadius: "6px",
    backgroundColor: "#FAF5FF",
    color: "#9333EA",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  statNumber: {
    fontSize: "22px",
    fontWeight: 800,
    color: "#0F172A",
    lineHeight: 1.1,
    margin: 0,
  },
  statSubBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    fontSize: "8.5px",
    fontWeight: 700,
    color: "#059669",
    marginTop: "4px",
  },

  // ─── CARD CONTAINERS ───
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    border: "1px solid #E2E8F0",
    padding: "10px 12px",
    margin: "6px 12px",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  },
  cardTitle: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 8px 0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardActionLink: {
    fontSize: "9.5px",
    fontWeight: 600,
    color: "#0072C4",
    textDecoration: "none",
    cursor: "pointer",
  },

  // ─── PROJECTS OVERVIEW ITEMS ───
  projectItem: {
    padding: "6px 0",
    borderBottom: "1px solid #F1F5F9",
    "&:last-child": {
      borderBottom: "none",
      paddingBottom: 0,
    },
  },
  projectHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "3px",
  },
  projectName: {
    fontSize: "10.5px",
    fontWeight: 600,
    color: "#0F172A",
  },
  projectBadge: {
    fontSize: "8px",
    fontWeight: 700,
    padding: "1px 5px",
    borderRadius: "4px",
  },
  badgeEmerald: {
    backgroundColor: "#ECFDF5",
    color: "#059669",
  },
  badgeBlue: {
    backgroundColor: "#EFF6FF",
    color: "#2563EB",
  },
  badgeAmber: {
    backgroundColor: "#FEF3C7",
    color: "#D97706",
  },
  progressBarTrack: {
    width: "100%",
    height: "4px",
    backgroundColor: "#F1F5F9",
    borderRadius: "2px",
    overflow: "hidden",
    margin: "4px 0",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: "2px",
  },
  projectMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "8.5px",
    color: "#64748B",
  },

  // ─── EMPLOYEE OVERVIEW ITEMS ───
  employeePillsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "4px",
    marginBottom: "8px",
  },
  employeePill: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "4px 2px",
    textAlign: "center",
  },
  employeePillNum: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#0F172A",
    lineHeight: 1,
  },
  employeePillLabel: {
    fontSize: "7.5px",
    color: "#64748B",
    marginTop: "2px",
  },
  deptRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "3px 0",
    fontSize: "9px",
  },
  deptName: {
    color: "#334155",
    fontWeight: 500,
  },
  deptCount: {
    fontWeight: 700,
    color: "#0F172A",
  },

  // ─── ORG DETAILS (Accounts tab) ───
  orgHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 12px 2px 12px",
  },
  orgSectionTitle: {
    fontSize: "13px",
    fontWeight: 800,
    color: "#0F172A",
    margin: 0,
  },
  editBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "5px",
    padding: "3px 8px",
    fontSize: "9.5px",
    fontWeight: 600,
    cursor: "pointer",
  },
  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    border: "1px solid #E2E8F0",
    padding: "10px 12px",
    margin: "6px 12px",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  },
  detailCardTitle: {
    fontSize: "11.5px",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 6px 0",
    paddingBottom: "4px",
    borderBottom: "1px solid #F1F5F9",
  },
  detailRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "3px 0",
    fontSize: "9.5px",
  },
  detailLabel: {
    color: "#64748B",
    fontWeight: 500,
  },
  detailValue: {
    color: "#0F172A",
    fontWeight: 600,
    textAlign: "right",
    maxWidth: "58%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  // ─── BILLING TAB ───
  billingCardTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "8px",
  },
  toggleSwitchActive: {
    width: "28px",
    height: "16px",
    borderRadius: "10px",
    backgroundColor: "#0072C4",
    position: "relative",
    cursor: "pointer",
    "&::after": {
      content: '""',
      position: "absolute",
      width: "12px",
      height: "12px",
      borderRadius: "50%",
      backgroundColor: "#FFFFFF",
      top: "2px",
      right: "2px",
      transition: "all 0.2s ease",
    },
  },
  manageDomainBtn: {
    border: "1px solid #CBD5E1",
    borderRadius: "6px",
    backgroundColor: "#FFFFFF",
    color: "#334155",
    fontSize: "9px",
    fontWeight: 600,
    padding: "3px 8px",
    cursor: "pointer",
  },
  activeDomainBox: {
    border: "1.5px solid #10B981",
    borderRadius: "8px",
    backgroundColor: "#F0FDF4",
    padding: "8px 10px",
    margin: "6px 0",
  },
  activeDomainDomain: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#0F172A",
  },
  activePill: {
    backgroundColor: "#059669",
    color: "#FFFFFF",
    fontSize: "8px",
    fontWeight: 700,
    padding: "1px 5px",
    borderRadius: "4px",
    marginLeft: "6px",
  },
  domainRenewalText: {
    fontSize: "9px",
    color: "#059669",
    fontWeight: 600,
    marginTop: "2px",
  },
  upcomingBillBox: {
    borderRadius: "8px",
    backgroundColor: "#EFF6FF",
    border: "1px solid #BFDBFE",
    padding: "10px",
    marginTop: "8px",
  },
  upcomingBillLabel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "9.5px",
    fontWeight: 600,
    color: "#1E3A8A",
  },
  upcomingBillAmount: {
    fontSize: "24px",
    fontWeight: 800,
    color: "#0F172A",
    margin: "4px 0",
    lineHeight: 1.1,
  },
  upcomingBillMeta: {
    fontSize: "8px",
    color: "#475569",
    borderTop: "1px solid #DBEAFE",
    paddingTop: "4px",
    marginTop: "4px",
  },
  planActionRow: {
    display: "flex",
    gap: "6px",
    marginTop: "6px",
  },
  viewPlansBtn: {
    flex: 1,
    border: "1px solid #CBD5E1",
    backgroundColor: "#FFFFFF",
    borderRadius: "6px",
    padding: "4px",
    fontSize: "9.5px",
    fontWeight: 600,
    color: "#334155",
    cursor: "pointer",
  },
  changePlanBtn: {
    flex: 1,
    border: "none",
    backgroundColor: "#0072C4",
    borderRadius: "6px",
    padding: "4px",
    fontSize: "9.5px",
    fontWeight: 600,
    color: "#FFFFFF",
    cursor: "pointer",
  },

  // ─── SUPPORT TAB ───
  supportCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    border: "1px solid #E2E8F0",
    padding: "10px 12px",
    margin: "6px 12px",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  },
  fieldGroup: {
    marginBottom: "8px",
  },
  fieldLabel: {
    display: "block",
    fontSize: "9.5px",
    fontWeight: 600,
    color: "#334155",
    marginBottom: "3px",
  },
  fieldSelect: {
    width: "100%",
    padding: "5px 8px",
    borderRadius: "6px",
    border: "1px solid #CBD5E1",
    fontSize: "9.5px",
    color: "#0F172A",
    backgroundColor: "#FFFFFF",
    outline: "none",
    boxSizing: "border-box",
  },
  fieldInput: {
    width: "100%",
    padding: "5px 8px",
    borderRadius: "6px",
    border: "1px solid #CBD5E1",
    fontSize: "9.5px",
    color: "#0F172A",
    outline: "none",
    boxSizing: "border-box",
  },
  fieldTextarea: {
    width: "100%",
    padding: "5px 8px",
    borderRadius: "6px",
    border: "1px solid #CBD5E1",
    fontSize: "9px",
    color: "#0F172A",
    outline: "none",
    resize: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  priorityRow: {
    display: "flex",
    gap: "6px",
    marginTop: "4px",
  },
  priorityBtn: {
    flex: 1,
    padding: "4px",
    borderRadius: "6px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    fontSize: "9px",
    fontWeight: 600,
    color: "#475569",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    cursor: "pointer",
  },
  priorityBtnActive: {
    flex: 1,
    padding: "4px",
    borderRadius: "6px",
    border: "1.5px solid #0072C4",
    backgroundColor: "#EFF6FF",
    fontSize: "9px",
    fontWeight: 700,
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    cursor: "pointer",
  },
  priorityDotBlue: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#2563EB",
  },
  priorityDotPurple: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#9333EA",
  },
  priorityDotAmber: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#F59E0B",
  },
  submitTicketBtn: {
    width: "100%",
    padding: "6px",
    borderRadius: "6px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    fontSize: "10px",
    fontWeight: 600,
    cursor: "pointer",
    marginTop: "6px",
  },

  // ─── BOTTOM TAB BAR (4 TABS) ───
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    borderTop: "1px solid #E2E8F0",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    padding: "6px 4px 10px 4px",
    zIndex: 10,
  },
  tabBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "2px",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "2px 6px",
    minWidth: "52px",
  },
  tabIconWrapperActive: {
    width: "46px",
    height: "22px",
    borderRadius: "11px",
    backgroundColor: "#DBEAFE",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  tabIconWrapperInactive: {
    width: "46px",
    height: "22px",
    borderRadius: "11px",
    backgroundColor: "transparent",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  tabLabelActive: {
    fontSize: "8.5px",
    fontWeight: 700,
    color: "#0072C4",
    lineHeight: 1,
  },
  tabLabelInactive: {
    fontSize: "8.5px",
    fontWeight: 500,
    color: "#64748B",
    lineHeight: 1,
  },
  homeIndicator: {
    position: "absolute",
    bottom: "2px",
    left: "50%",
    transform: "translateX(-50%)",
    width: "70px",
    height: "3px",
    backgroundColor: "#0F172A",
    borderRadius: "2px",
    opacity: 0.8,
  },
}));
