import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes pulseGreen": {
    "0%, 100%": { opacity: 1, transform: "scale(1)" },
    "50%": { opacity: 0.4, transform: "scale(0.85)" },
  },
  "@keyframes pulseBlue": {
    "0%, 100%": { opacity: 1 },
    "50%": { opacity: 0.5 },
  },

  /* Smartphone Outer Chassis — realistic 1:2 aspect ratio */
  frame: {
    position: "relative",
    margin: "0 auto",
    width: "100%",
    maxWidth: "308px",
    height: "616px",
    backgroundColor: "#0B0F17",
    borderRadius: "48px",
    padding: "10px",
    boxShadow:
      "0 25px 50px -12px rgba(15, 23, 42, 0.35), 0 0 0 1px rgba(255, 255, 255, 0.1), inset 0 0 0 2px rgba(15, 23, 42, 0.9), 0 0 0 4px #1E293B",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    userSelect: "none",
    "@media (max-width: 480px)": {
      maxWidth: "280px",
      height: "560px",
      borderRadius: "42px",
      padding: "8px",
    },
  },

  /* Hardware buttons on chassis */
  volumeButtonTop: {
    position: "absolute",
    left: "-6px",
    top: "100px",
    width: "4px",
    height: "40px",
    backgroundColor: "#334155",
    borderRadius: "3px 0 0 3px",
  },
  volumeButtonBottom: {
    position: "absolute",
    left: "-6px",
    top: "150px",
    width: "4px",
    height: "40px",
    backgroundColor: "#334155",
    borderRadius: "3px 0 0 3px",
  },
  powerButton: {
    position: "absolute",
    right: "-6px",
    top: "120px",
    width: "4px",
    height: "58px",
    backgroundColor: "#334155",
    borderRadius: "0 3px 3px 0",
  },

  /* Screen containers */
  screenLight: {
    position: "relative",
    width: "100%",
    height: "100%",
    backgroundColor: "#F8FAFC",
    borderRadius: "38px",
    overflow: "hidden",
    border: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxSizing: "border-box",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },
  screenDark: {
    position: "relative",
    width: "100%",
    height: "100%",
    backgroundColor: "#030712",
    borderRadius: "38px",
    overflow: "hidden",
    border: "1px solid #1E293B",
    color: "#FFFFFF",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxSizing: "border-box",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },

  /* Top Status Bar & Dynamic Island */
  statusBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 16px 2px",
    zIndex: 20,
  },
  statusTime: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0F172A",
    letterSpacing: "-0.02em",
    width: "40px",
  },
  statusTimeDark: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#F8FAFC",
    letterSpacing: "-0.02em",
    width: "40px",
  },
  statusIcons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "4px",
    color: "#0F172A",
    width: "44px",
  },
  statusIconsDark: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "4px",
    color: "#F8FAFC",
    width: "44px",
  },

  /* Dynamic Island Pill */
  dynamicIsland: {
    position: "relative",
    width: "100px",
    height: "26px",
    backgroundColor: "#000000",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 10px",
    boxShadow: "0 2px 5px rgba(0,0,0,0.3)",
    boxSizing: "border-box",
  },
  islandCamera: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    backgroundColor: "#0B0F19",
    border: "1px solid #1E293B",
    position: "relative",
    "&::after": {
      content: '""',
      position: "absolute",
      top: "2px",
      left: "2px",
      width: "3px",
      height: "3px",
      borderRadius: "50%",
      backgroundColor: "rgba(56, 189, 248, 0.7)",
    },
  },
  islandSensor: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#0A0D14",
  },
  islandIndicatorGreen: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    boxShadow: "0 0 6px #10B981",
    animation: "$pulseGreen 2s infinite ease-in-out",
  },

  /* Scrollable/Clean App Screen Content */
  appContent: {
    flex: 1,
    padding: "6px 12px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    overflow: "hidden",
  },

  /* App Navigation / Header Inside Screen */
  appHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "2px 2px 4px",
  },
  userProfile: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  avatarLight: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #0072C4 0%, #38BDF8 100%)",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    fontWeight: 700,
  },
  avatarDark: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #1E293B 0%, #0F172A 100%)",
    border: "1px solid #38BDF8",
    color: "#38BDF8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    fontWeight: 700,
  },
  userName: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0F172A",
    lineHeight: 1.2,
  },
  userRole: {
    fontSize: "10px",
    color: "#64748B",
  },
  userNameDark: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#F8FAFC",
    lineHeight: 1.2,
  },
  userRoleDark: {
    fontSize: "10px",
    color: "#94A3B8",
  },
  headerActionBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    position: "relative",
  },
  notifBadgeDot: {
    position: "absolute",
    top: "4px",
    right: "4px",
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#EF4444",
  },

  /* Primary Notification Card */
  notifCardLight: {
    backgroundColor: "#FFFFFF",
    padding: "10px 12px",
    borderRadius: "14px",
    border: "1px solid rgba(226, 232, 240, 0.9)",
    boxShadow: "0 3px 10px rgba(15, 23, 42, 0.05)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  notifCardDark: {
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    padding: "10px 12px",
    borderRadius: "14px",
    border: "1px solid #1E293B",
    boxShadow: "0 3px 10px rgba(0, 0, 0, 0.3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  notifLeft: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    minWidth: 0,
  },
  notifIconLight: {
    width: "32px",
    height: "32px",
    borderRadius: "10px",
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    color: "#059669",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "13px",
    flexShrink: 0,
  },
  notifIconDark: {
    width: "32px",
    height: "32px",
    borderRadius: "10px",
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    color: "#38BDF8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "13px",
    flexShrink: 0,
  },
  notifTitleLight: {
    fontWeight: 700,
    color: "#0F172A",
    fontSize: "11px",
    lineHeight: 1.2,
    margin: 0,
  },
  notifSubLight: {
    fontSize: "10px",
    color: "#64748B",
    marginTop: "2px",
    margin: 0,
  },
  notifTitleDark: {
    fontWeight: 700,
    color: "#F1F5F9",
    fontSize: "11px",
    lineHeight: 1.2,
    margin: 0,
  },
  notifSubDark: {
    fontSize: "10px",
    color: "#94A3B8",
    marginTop: "2px",
    margin: 0,
  },
  notifBadgeLight: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#059669",
    backgroundColor: "rgba(16, 185, 129, 0.08)",
    padding: "2px 7px",
    borderRadius: "9999px",
    whiteSpace: "nowrap",
  },
  notifBadgeDark: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#38BDF8",
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    border: "1px solid rgba(56, 189, 248, 0.3)",
    padding: "2px 7px",
    borderRadius: "9999px",
    whiteSpace: "nowrap",
  },

  /* Quick Actions Row */
  quickActionsRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "6px",
    margin: "2px 0",
  },
  quickActionItem: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    padding: "7px 2px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
  },
  quickActionItemDark: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    padding: "7px 2px",
    borderRadius: "12px",
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    border: "1px solid #1E293B",
  },
  quickActionIcon: {
    width: "20px",
    height: "20px",
    color: "#0072C4",
  },
  quickActionIconDark: {
    width: "20px",
    height: "20px",
    color: "#38BDF8",
  },
  quickActionLabel: {
    fontSize: "9px",
    fontWeight: 600,
    color: "#475569",
  },
  quickActionLabelDark: {
    fontSize: "9px",
    fontWeight: 600,
    color: "#94A3B8",
  },

  /* Meeting Card (Employee) */
  meetingCard: {
    backgroundColor: "#FFFFFF",
    padding: "10px 12px",
    borderRadius: "14px",
    border: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  meetingHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  meetingTitle: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#0F172A",
  },
  meetingTimeTag: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#6366F1",
    backgroundColor: "rgba(99, 102, 241, 0.08)",
    padding: "1px 6px",
    borderRadius: "6px",
  },
  meetingSub: {
    fontSize: "10px",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  joinBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "6px",
    padding: "3px 8px",
    fontSize: "10px",
    fontWeight: 600,
    cursor: "pointer",
  },

  /* Feed Item */
  feedCard: {
    backgroundColor: "rgba(241, 245, 249, 0.8)",
    padding: "8px 10px",
    borderRadius: "10px",
    border: "1px solid rgba(226, 232, 240, 0.6)",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedCardDark: {
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    padding: "8px 10px",
    borderRadius: "10px",
    border: "1px solid #1E293B",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedTextLight: {
    fontWeight: 600,
    color: "#334155",
  },
  feedTextDark: {
    fontWeight: 600,
    color: "#94A3B8",
  },
  feedValueLight: {
    color: "#059669",
    fontWeight: 600,
  },
  feedValueDark: {
    fontFamily: "monospace, sans-serif",
    color: "#34D399",
    fontWeight: 700,
  },

  /* Executive Telemetry Grid (Dark) */
  telemetryGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
  },
  telemetryBox: {
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    border: "1px solid #1E293B",
    borderRadius: "12px",
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  telemetryLabel: {
    fontSize: "9px",
    color: "#94A3B8",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  telemetryValue: {
    fontSize: "14px",
    fontWeight: 800,
    color: "#F8FAFC",
  },
  telemetryStatus: {
    fontSize: "9px",
    color: "#34D399",
    fontWeight: 600,
  },

  /* Branch Health Rows (Dark) */
  branchHealthList: {
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    border: "1px solid #1E293B",
    borderRadius: "12px",
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  branchHeader: {
    fontSize: "9px",
    fontWeight: 700,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    display: "flex",
    justifyContent: "space-between",
  },
  branchRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "10px",
    color: "#CBD5E1",
  },
  branchDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    display: "inline-block",
    marginRight: "6px",
  },

  /* Bottom In-App Tab Bar */
  tabBar: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    padding: "6px 0 2px",
    borderTop: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  tabBarDark: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    padding: "6px 0 2px",
    borderTop: "1px solid #1E293B",
    backgroundColor: "#030712",
  },
  tabItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "2px",
    fontSize: "9px",
    color: "#94A3B8",
    fontWeight: 500,
  },
  tabItemActive: {
    color: "#0072C4",
    fontWeight: 700,
  },
  tabItemActiveDark: {
    color: "#38BDF8",
    fontWeight: 700,
  },

  /* Home Indicator Bar */
  homeIndicatorContainer: {
    padding: "4px 0 6px",
    display: "flex",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  homeIndicator: {
    width: "108px",
    height: "4px",
    borderRadius: "9999px",
    backgroundColor: "#CBD5E1",
  },
  homeIndicatorDark: {
    width: "108px",
    height: "4px",
    borderRadius: "9999px",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
}));
