import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes fabPulse": {
    "0%, 100%": {
      boxShadow: "0 2px 8px rgba(0, 114, 196, 0.35)",
    },
    "50%": {
      boxShadow: "0 3px 12px rgba(0, 114, 196, 0.5)",
    },
  },
  "@keyframes ringGlow": {
    "0%, 100%": { filter: "drop-shadow(0 0 1px rgba(16, 185, 129, 0.3))" },
    "50%": { filter: "drop-shadow(0 0 4px rgba(16, 185, 129, 0.6))" },
  },

  /* Smartphone Outer Chassis — authentic 1:2 iPhone Pro proportions */
  frame: {
    position: "relative",
    margin: "0 auto",
    width: "100%",
    maxWidth: "308px",
    height: "624px",
    backgroundColor: "#0B0F17",
    borderRadius: "44px",
    padding: "8px",
    boxShadow:
      "0 20px 50px -12px rgba(15, 23, 42, 0.35), 0 0 0 1px rgba(255, 255, 255, 0.1), inset 0 0 0 2px rgba(15, 23, 42, 0.9), 0 0 0 3px #1E293B",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    userSelect: "none",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow:
        "0 28px 60px -12px rgba(0, 114, 196, 0.22), 0 0 0 1px rgba(0, 114, 196, 0.25), inset 0 0 0 2px rgba(15, 23, 42, 0.9), 0 0 0 3px #0072C4",
    },
    "@media (max-width: 480px)": {
      maxWidth: "284px",
      height: "580px",
      borderRadius: "40px",
      padding: "7px",
    },
  },

  /* Physical hardware buttons */
  volumeButtonTop: {
    position: "absolute",
    left: "-5px",
    top: "95px",
    width: "3.5px",
    height: "38px",
    backgroundColor: "#334155",
    borderRadius: "3px 0 0 3px",
  },
  volumeButtonBottom: {
    position: "absolute",
    left: "-5px",
    top: "142px",
    width: "3.5px",
    height: "38px",
    backgroundColor: "#334155",
    borderRadius: "3px 0 0 3px",
  },
  powerButton: {
    position: "absolute",
    right: "-5px",
    top: "115px",
    width: "3.5px",
    height: "54px",
    backgroundColor: "#334155",
    borderRadius: "0 3px 3px 0",
  },

  /* Inner Screen — smoothly clipped corners */
  screen: {
    position: "relative",
    width: "100%",
    height: "100%",
    backgroundColor: "#F4F7FB",
    borderRadius: "36px",
    overflow: "hidden",
    border: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxSizing: "border-box",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif",
  },

  /* iOS Status Bar */
  statusBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 16px 2px",
    backgroundColor: "#FFFFFF",
    zIndex: 30,
  },
  statusTime: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#0F172A",
    letterSpacing: "-0.02em",
    width: "38px",
  },
  statusIcons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "4px",
    color: "#0F172A",
    width: "42px",
  },

  /* Dynamic Island — solid black pill, centered dark aperture, NO bright blue dot */
  dynamicIsland: {
    position: "relative",
    width: "84px",
    height: "20px",
    backgroundColor: "#000000",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
    boxSizing: "border-box",
  },
  islandCenterLens: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#111827",
  },

  /* Scrollable Screen Body */
  screenContent: {
    flex: 1,
    padding: "6px 11px 64px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    overflowY: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },

  /* App Navigation Header */
  appHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 2px 5px",
    backgroundColor: "#FFFFFF",
    margin: "-6px -11px 2px",
    paddingLeft: "12px",
    paddingRight: "12px",
    borderBottom: "1px solid #EEF2F6",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
  },
  headerLogo: {
    width: "18px",
    height: "18px",
    color: "#0072C4",
  },
  headerTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  headerMenuBtn: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "#0F172A",
    display: "flex",
    alignItems: "center",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  userAvatarCircle: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#F1F5F9",
    border: "1.5px solid #0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    overflow: "hidden",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     DASHBOARD SCREEN (Image 2)
     ───────────────────────────────────────────────────────────── */
  announcementCard: {
    background: "linear-gradient(135deg, #0284C7 0%, #0072C4 50%, #0369A1 100%)",
    borderRadius: "12px",
    padding: "10px 12px",
    color: "#FFFFFF",
    boxShadow: "0 2px 8px rgba(0, 114, 196, 0.15)",
    cursor: "pointer",
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "translateY(-1px)",
    },
  },
  announcementTitle: {
    fontSize: "11px",
    fontWeight: 700,
    lineHeight: 1.35,
    margin: "0 0 3px",
    color: "#FFFFFF",
  },
  announcementSub: {
    fontSize: "9px",
    color: "rgba(255, 255, 255, 0.8)",
    margin: 0,
    lineHeight: 1.3,
  },

  /* 2-Column KPI Row */
  kpiRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "7px",
  },
  kpiCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    padding: "8px 10px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 4px rgba(15, 23, 42, 0.02)",
    transition: "all 0.15s ease",
    cursor: "pointer",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-1px)",
    },
  },
  kpiLabel: {
    fontSize: "8.5px",
    fontWeight: 700,
    color: "#0072C4",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    margin: "0 0 2px",
  },
  kpiSubLabel: {
    fontSize: "9px",
    color: "#64748B",
    margin: "0 0 3px",
  },
  kpiValue: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 2px",
  },
  kpiDate: {
    fontSize: "8.5px",
    color: "#94A3B8",
    margin: 0,
  },

  /* Dashboard Attendance Card */
  dashboardAttendanceCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    padding: "10px 12px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 4px rgba(15, 23, 42, 0.02)",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    transition: "border-color 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
    },
  },
  cardHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardHeaderTitle: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  viewMoreLink: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#0072C4",
    textDecoration: "none",
    cursor: "pointer",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  clockInTimeRow: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
  },
  clockInLabel: {
    fontSize: "9.5px",
    color: "#64748B",
    margin: 0,
  },
  clockInValue: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  arrivalStatsRow: {
    display: "flex",
    gap: "16px",
    fontSize: "9px",
    color: "#64748B",
  },
  clockOutRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "5px",
    borderTop: "1px solid #F1F5F9",
  },
  notClockedInGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
  },
  notClockedInLabel: {
    fontSize: "9px",
    color: "#64748B",
    margin: 0,
  },
  avatarStack: {
    display: "flex",
    alignItems: "center",
  },
  avatarPill: {
    width: "19px",
    height: "19px",
    borderRadius: "50%",
    backgroundColor: "#EFF6FF",
    border: "1.5px solid #FFFFFF",
    color: "#0072C4",
    fontSize: "8px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "-3px",
    transition: "transform 0.15s ease",
    "&:first-child": {
      marginLeft: 0,
    },
    "&:hover": {
      transform: "translateY(-2px)",
      zIndex: 10,
    },
  },
  avatarPillCount: {
    width: "19px",
    height: "19px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    border: "1.5px solid #FFFFFF",
    color: "#FFFFFF",
    fontSize: "8px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "-3px",
  },
  clockOutBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "7px",
    padding: "6px 12px",
    fontSize: "10.5px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.2)",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#0284C7",
      transform: "translateY(-1px)",
    },
    "&:active": {
      transform: "scale(0.96)",
    },
  },

  /* Leave Balance Card */
  leaveBalanceCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    padding: "10px 12px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 4px rgba(15, 23, 42, 0.02)",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    transition: "border-color 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
    },
  },
  gaugeArea: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "2px 6px",
  },
  gaugeContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    margin: "0 auto",
  },
  gaugeRingSvg: {
    width: "48px",
    height: "48px",
    transform: "rotate(-90deg)",
    "&:hover": {
      animation: "$ringGlow 1.5s infinite ease-in-out",
    },
  },
  gaugeSubText: {
    fontSize: "9px",
    color: "#64748B",
    marginTop: "2px",
  },
  applyLeaveFab: {
    width: "28px",
    height: "28px",
    borderRadius: "8px",
    backgroundColor: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#FFFFFF",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.25)",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     ATTENDANCE SCREEN (Image 1)
     ───────────────────────────────────────────────────────────── */
  clockInBanner: {
    backgroundColor: "#EFF6FF",
    border: "1px solid #BFDBFE",
    borderRadius: "12px",
    padding: "10px 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 1px 4px rgba(0, 114, 196, 0.05)",
    transition: "border-color 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
    },
  },
  clockInBannerLeft: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
  },
  clockInDate: {
    fontSize: "10px",
    color: "#64748B",
    margin: 0,
  },
  clockInTimeBig: {
    fontSize: "16px",
    fontWeight: 800,
    color: "#0F172A",
    margin: 0,
  },
  clockInActionBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "7px",
    padding: "7px 15px",
    fontSize: "11px",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.25)",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#0284C7",
      transform: "translateY(-1px)",
    },
    "&:active": {
      transform: "scale(0.96)",
    },
  },

  /* Shift Details Card */
  shiftDetailsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    padding: "10px 12px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 4px rgba(15, 23, 42, 0.02)",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    transition: "border-color 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
    },
  },
  shiftTitle: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  shiftMetricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "4px",
    paddingBottom: "6px",
    borderBottom: "1px solid #F1F5F9",
  },
  shiftMetricCol: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
  },
  shiftMetricLabel: {
    fontSize: "8.5px",
    color: "#94A3B8",
    margin: 0,
    whiteSpace: "nowrap",
  },
  shiftMetricValue: {
    fontSize: "9.5px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
    whiteSpace: "nowrap",
  },
  shiftSubTitle: {
    fontSize: "10.5px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  weekDaysRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "3px",
  },
  dayCircle: {
    width: "23px",
    height: "23px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "9.5px",
    fontWeight: 600,
    border: "1px solid #E2E8F0",
    color: "#64748B",
    backgroundColor: "#F8FAFC",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.08)",
      color: "#0072C4",
    },
  },
  dayCircleActive: {
    width: "23px",
    height: "23px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "9.5px",
    fontWeight: 700,
    border: "1.5px solid #0072C4",
    color: "#0072C4",
    backgroundColor: "#EFF6FF",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.08)",
    },
  },
  legendRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "8.5px",
    color: "#64748B",
  },
  legendDotBlue: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    display: "inline-block",
    marginRight: "3px",
  },
  legendDotGray: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#94A3B8",
    display: "inline-block",
    marginRight: "3px",
  },
  shiftFooterInfo: {
    fontSize: "8.5px",
    color: "#0F172A",
    fontWeight: 600,
    lineHeight: 1.35,
    margin: 0,
  },
  shiftFooterSub: {
    fontSize: "8.5px",
    color: "#64748B",
    fontWeight: 400,
  },

  /* 2x2 Grid of Actions — compact, non-popping icons */
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "7px",
  },
  actionGridCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    padding: "9px 6px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 3px rgba(15, 23, 42, 0.02)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "5px",
    cursor: "pointer",
    transition: "all 0.18s ease",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 10px rgba(0, 114, 196, 0.08)",
    },
  },
  actionGridIcon: {
    width: "17px",
    height: "17px",
    color: "#0072C4",
  },
  actionGridLabel: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#0F172A",
    margin: 0,
    textAlign: "center",
  },

  /* ─────────────────────────────────────────────────────────────
     BOTTOM FIXED NAVIGATION BAR (Contained strictly inside screen)
     ───────────────────────────────────────────────────────────── */
  tabBarFixed: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "52px",
    backgroundColor: "rgba(255, 255, 255, 0.98)",
    backdropFilter: "blur(10px)",
    borderTop: "1px solid #EEF2F6",
    borderBottomLeftRadius: "36px",
    borderBottomRightRadius: "36px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "3px 6px 5px",
    zIndex: 40,
    boxSizing: "border-box",
  },
  tabRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
  },
  tabItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1px",
    color: "#64748B",
    fontSize: "7.5px",
    fontWeight: 500,
    cursor: "pointer",
    padding: "2px 3px",
    borderRadius: "6px",
    transition: "color 0.15s ease",
    "&:hover": {
      color: "#0072C4",
    },
  },
  tabItemActive: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1px",
    color: "#0072C4",
    fontSize: "7.5px",
    fontWeight: 700,
    padding: "2px 5px",
    borderRadius: "8px",
    backgroundColor: "#EFF6FF",
    cursor: "pointer",
  },
  tabIcon: {
    width: "14px",
    height: "14px",
  },

  /* Center FAB — sleek, compact, non-overlapping */
  centerFab: {
    position: "relative",
    top: "-6px",
    width: "34px",
    height: "34px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 8px rgba(0, 114, 196, 0.35)",
    cursor: "pointer",
    border: "2px solid #FFFFFF",
    transition: "all 0.2s ease",
    animation: "$fabPulse 3s infinite ease-in-out",
    "&:hover": {
      transform: "scale(1.06)",
      backgroundColor: "#0284C7",
    },
    "&:active": {
      transform: "scale(0.95)",
    },
  },

  /* Home Indicator Bar — safely inset inside the tab bar */
  homeIndicator: {
    width: "76px",
    height: "3px",
    borderRadius: "9999px",
    backgroundColor: "#CBD5E1",
    margin: "1px auto 0",
  },

  /* Mail Screen Styles in Phone Mockup */
  mailAppHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #F1F5F9",
  },
  mailHeaderTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  mailHeaderTitle: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 800,
    color: "#0F172A",
    letterSpacing: "-0.01em",
  },
  mailUnreadBadge: {
    padding: "1px 6px",
    borderRadius: "9999px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "10px",
    fontWeight: 700,
  },
  mailUserAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#8133F1",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.04em",
  },
  mailSearchBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "8px 12px 6px",
    padding: "6px 10px",
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    border: "1px solid #E2E8F0",
    color: "#94A3B8",
    fontSize: "11px",
  },
  mailListWrapper: {
    padding: "6px 12px 60px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    position: "relative",
  },
  mailPhoneCard: {
    position: "relative",
    padding: "10px 12px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    overflow: "hidden",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      borderColor: "#CBD5E1",
    },
  },
  mailPhoneCardActive: {
    position: "relative",
    padding: "10px 12px 10px 16px",
    borderRadius: "12px",
    backgroundColor: "#F0F7FF",
    border: "1px solid #BAE6FD",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.08)",
    cursor: "pointer",
    overflow: "hidden",
  },
  mailActiveBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "3.5px",
    backgroundColor: "#0072C4",
  },
  mailPhoneCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "2px",
  },
  mailPhoneSender: {
    fontSize: "11.5px",
    fontWeight: 700,
    color: "#0F172A",
  },
  mailPhoneTime: {
    fontSize: "9.5px",
    color: "#0072C4",
    fontWeight: 600,
  },
  mailPhoneTimeMuted: {
    fontSize: "9.5px",
    color: "#94A3B8",
  },
  mailPhoneSubject: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#1E293B",
    margin: "2px 0 3px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  mailPhoneSnippet: {
    margin: 0,
    fontSize: "10px",
    color: "#64748B",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.4,
  },
  mailComposeFab: {
    position: "absolute",
    bottom: "16px",
    right: "14px",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 14px rgba(0, 114, 196, 0.4)",
    cursor: "pointer",
    border: "none",
    transition: "transform 0.2s ease, background-color 0.2s ease",
    "&:hover": {
      transform: "scale(1.08)",
      backgroundColor: "#0284C7",
    },
    "&:active": {
      transform: "scale(0.95)",
    },
  },
}));
