import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes pulseDot": {
    "0%, 100%": { opacity: 1, transform: "scale(1)" },
    "50%": { opacity: 0.4, transform: "scale(0.85)" },
  },
  "@keyframes glowPulse": {
    "0%, 100%": { opacity: 0.6, transform: "scale(1)" },
    "50%": { opacity: 0.9, transform: "scale(1.05)" },
  },

  pageWrapper: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────────────────────── */
  heroSection: {
    position: "relative",
    paddingTop: "64px",
    paddingBottom: "88px",
    paddingLeft: "24px",
    paddingRight: "24px",
    maxWidth: "1280px",
    margin: "0 auto",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      paddingTop: "40px",
      paddingBottom: "60px",
      paddingLeft: "16px",
      paddingRight: "16px",
    },
  },
  heroGlow: {
    position: "absolute",
    top: "20%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "680px",
    height: "380px",
    background: "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.15) 0%, rgba(2, 132, 199, 0.06) 50%, rgba(255, 255, 255, 0) 75%)",
    filter: "blur(90px)",
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
    animation: "$glowPulse 6s infinite ease-in-out",
  },
  heroContent: {
    position: "relative",
    zIndex: 1,
    maxWidth: "1080px",
    margin: "0 auto",
  },
  eyebrowBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.22)",
    color: "#0072C4",
    fontSize: "0.875rem",
    fontWeight: 600,
    letterSpacing: "-0.01em",
    marginBottom: "28px",
    boxShadow: "0 2px 8px rgba(0, 114, 196, 0.06)",
  },
  pulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    animation: "$pulseDot 2s infinite ease-in-out",
  },
  heroTitle: {
    fontSize: "3.5rem",
    lineHeight: 1.15,
    fontWeight: 800,
    color: "#0F172A",
    letterSpacing: "-0.03em",
    margin: "0 auto 24px auto",
    maxWidth: "1000px",
    "@media (max-width: 960px)": {
      fontSize: "2.75rem",
      lineHeight: 1.2,
    },
    "@media (max-width: 640px)": {
      fontSize: "2.1rem",
      lineHeight: 1.25,
    },
  },
  heroTitleAccent: {
    color: "#0072C4",
    background: "linear-gradient(135deg, #0072C4 0%, #0284C7 60%, #0369A1 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    display: "inline",
  },
  heroParagraph: {
    fontSize: "1.15rem",
    lineHeight: 1.75,
    color: "#475569",
    maxWidth: "920px",
    margin: "0 auto 36px auto",
    fontWeight: 400,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      lineHeight: 1.65,
    },
  },
  heroBtnRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "56px",
    position: "relative",
  },
  primaryBtnWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
  },
  primaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "1.0625rem",
    fontWeight: 700,
    padding: "14px 34px",
    borderRadius: "12px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 4px 20px rgba(0, 114, 196, 0.35)",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    "&:hover": {
      backgroundColor: "#005ea6",
      transform: "translateY(-2px)",
      boxShadow: "0 8px 28px rgba(0, 114, 196, 0.45)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  primaryBtnSubtext: {
    fontSize: "0.75rem",
    color: "#64748B",
    marginTop: "8px",
    fontWeight: 500,
  },
  secondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    fontSize: "1.0625rem",
    fontWeight: 600,
    padding: "14px 32px",
    borderRadius: "12px",
    border: "1px solid #CBD5E1",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.04)",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      borderColor: "#94A3B8",
      transform: "translateY(-2px)",
    },
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     OS CONSOLE MOCKUP (INTERACTIVE)
     ───────────────────────────────────────────────────────────────────────────── */
  consoleMockupWrapper: {
    position: "relative",
    maxWidth: "1080px",
    margin: "0 auto",
    borderRadius: "20px",
    backgroundColor: "#0F172A",
    border: "1px solid #334155",
    overflow: "hidden",
    boxShadow:
      "0 25px 50px -12px rgba(0, 114, 196, 0.25), 0 0 0 1px rgba(255, 255, 255, 0.08)",
    textAlign: "left",
    color: "#F8FAFC",
  },
  consoleHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    borderBottom: "1px solid #1E293B",
    backgroundColor: "#0B132B",
  },
  macDots: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  dotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#EF4444",
  },
  dotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#F59E0B",
  },
  dotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
  },
  consoleTitleText: {
    fontSize: "0.8125rem",
    fontWeight: 500,
    color: "#94A3B8",
    letterSpacing: "0.02em",
    "& span": {
      color: "#38BDF8",
      fontWeight: 600,
    },
  },
  statusHealthyPill: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    color: "#34D399",
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    border: "1px solid rgba(16, 185, 129, 0.25)",
    padding: "3px 10px",
    borderRadius: "9999px",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  consoleBodyGrid: {
    display: "grid",
    gridTemplateColumns: "220px 1fr 310px",
    minHeight: "480px",
    "@media (max-width: 990px)": {
      gridTemplateColumns: "1fr",
    },
  },
  consoleSidebar: {
    borderRight: "1px solid #1E293B",
    padding: "16px",
    backgroundColor: "#090D1A",
    "@media (max-width: 990px)": {
      display: "none",
    },
  },
  sidebarHeader: {
    fontSize: "0.6875rem",
    fontWeight: 800,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    marginBottom: "14px",
  },
  sidebarNavList: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  sidebarNavItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    borderRadius: "8px",
    fontSize: "0.875rem",
    color: "#94A3B8",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#1E293B",
      color: "#F8FAFC",
    },
  },
  sidebarNavItemActive: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "#38BDF8",
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    border: "1px solid rgba(56, 189, 248, 0.25)",
    cursor: "pointer",
  },
  sidebarPill: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    padding: "2px 6px",
    borderRadius: "4px",
    backgroundColor: "#1E293B",
    color: "#CBD5E1",
  },
  sidebarPillActive: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: "4px",
    backgroundColor: "rgba(56, 189, 248, 0.2)",
    color: "#38BDF8",
  },
  sidebarPillRed: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: "4px",
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    color: "#F87171",
  },
  consoleCenterPanel: {
    padding: "24px",
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    display: "flex",
    flexDirection: "column",
  },
  centerTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
  },
  centerSprintTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#F8FAFC",
    margin: 0,
  },
  centerSprintSub: {
    fontSize: "0.78125rem",
    color: "#94A3B8",
    margin: "4px 0 0 0",
  },
  createTicketBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "0.84375rem",
    fontWeight: 600,
    padding: "6px 14px",
    borderRadius: "6px",
    border: "none",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#005ea6",
    },
  },
  sprintColumnsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    flex: 1,
    "@media (max-width: 600px)": {
      gridTemplateColumns: "1fr",
    },
  },
  sprintColBox: {
    backgroundColor: "rgba(30, 41, 59, 0.6)",
    border: "1px solid #334155",
    borderRadius: "12px",
    padding: "14px",
    backdropFilter: "blur(12px)",
  },
  colHeaderYellow: {
    fontSize: "0.75rem",
    fontWeight: 800,
    color: "#EAB308",
    letterSpacing: "0.06em",
    marginBottom: "12px",
  },
  colHeaderGreen: {
    fontSize: "0.75rem",
    fontWeight: 800,
    color: "#10B981",
    letterSpacing: "0.06em",
    marginBottom: "12px",
  },
  ticketCard: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "12px",
    marginBottom: "10px",
    transition: "border-color 0.15s ease, transform 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-1px)",
    },
  },
  ticketTag: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    backgroundColor: "#334155",
    color: "#CBD5E1",
    padding: "2px 6px",
    borderRadius: "4px",
    display: "inline-block",
  },
  ticketTitle: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "#F8FAFC",
    margin: "8px 0 6px 0",
  },
  ticketAssignee: {
    fontSize: "0.75rem",
    color: "#94A3B8",
  },
  ticketVerified: {
    fontSize: "0.75rem",
    color: "#34D399",
    fontWeight: 600,
  },
  consoleRightPanel: {
    borderLeft: "1px solid #1E293B",
    padding: "16px",
    backgroundColor: "#090D1A",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    "@media (max-width: 990px)": {
      display: "none",
    },
  },
  channelHeader: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#F8FAFC",
    paddingBottom: "10px",
    borderBottom: "1px solid #1E293B",
    marginBottom: "14px",
  },
  chatMessagesStack: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  chatMsgCard: {
    backgroundColor: "rgba(30, 41, 59, 0.5)",
    border: "1px solid #1E293B",
    borderRadius: "8px",
    padding: "10px 12px",
  },
  chatMsgCardPurple: {
    backgroundColor: "rgba(30, 41, 59, 0.5)",
    border: "1px solid #1E293B",
    borderLeft: "3px solid #A855F7",
    borderRadius: "8px",
    padding: "10px 12px",
  },
  chatSenderBlue: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#38BDF8",
    marginBottom: "4px",
  },
  chatSenderPurple: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#C084FC",
    marginBottom: "4px",
  },
  chatMsgText: {
    fontSize: "0.78125rem",
    color: "#CBD5E1",
    lineHeight: 1.5,
    margin: 0,
  },
  chatInputPlaceholder: {
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "0.75rem",
    color: "#64748B",
    marginTop: "16px",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     TICKER SECTION (TOOL REPLACEMENT)
     ───────────────────────────────────────────────────────────────────────────── */
  tickerSection: {
    borderTop: "1px solid #E2E8F0",
    borderBottom: "1px solid #E2E8F0",
    backgroundColor: "#F8FAFC",
    padding: "36px 24px",
    textAlign: "center",
  },
  tickerKicker: {
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "18px",
  },
  tickerList: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: "24px 36px",
  },
  strikethroughTool: {
    fontSize: "1.15rem",
    fontWeight: 700,
    color: "#94A3B8",
    textDecoration: "line-through",
    textDecorationColor: "#EF4444",
    textDecorationThickness: "2.5px",
    letterSpacing: "-0.01em",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     AI ENGINE SECTION (DUAL-ENGINE INTELLIGENCE)
     ───────────────────────────────────────────────────────────────────────────── */
  aiSection: {
    padding: "96px 24px",
    maxWidth: "1280px",
    margin: "0 auto",
    borderBottom: "1px solid #E2E8F0",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "60px 16px",
    },
  },
  sectionHeaderCenter: {
    textAlign: "center",
    maxWidth: "800px",
    margin: "0 auto 56px auto",
  },
  dualEngineBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: "9999px",
    backgroundColor: "#FAF5FF",
    border: "1px solid #E9D5FF",
    color: "#7E22CE",
    fontSize: "0.875rem",
    fontWeight: 700,
    marginBottom: "16px",
  },
  purpleDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#A855F7",
  },
  cyanDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#06B6D4",
  },
  sectionTitle: {
    fontSize: "2.5rem",
    lineHeight: 1.22,
    fontWeight: 800,
    color: "#0F172A",
    letterSpacing: "-0.025em",
    margin: "0 0 16px 0",
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  sectionSubtitle: {
    fontSize: "1.1rem",
    lineHeight: 1.7,
    color: "#475569",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  engineBlock: {
    marginBottom: "56px",
    "&:last-child": {
      marginBottom: 0,
    },
  },
  engineHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "24px",
  },
  engineBadgeA: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    backgroundColor: "#F3E8FF",
    border: "1px solid #D8B4FE",
    color: "#7E22CE",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    fontWeight: 800,
  },
  engineBadgeB: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    backgroundColor: "#ECFEFF",
    border: "1px solid #A5F3FC",
    color: "#0891B2",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1rem",
    fontWeight: 800,
  },
  engineHeadingPurple: {
    fontSize: "1.375rem",
    fontWeight: 800,
    color: "#7E22CE",
    margin: 0,
  },
  engineHeadingCyan: {
    fontSize: "1.375rem",
    fontWeight: 800,
    color: "#0E7490",
    margin: 0,
  },
  threeCardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "20px",
    },
  },
  flowCardPurple: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderTop: "3px solid #A855F7",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 16px rgba(168, 85, 247, 0.06)",
    transition: "all 0.2s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: "0 12px 30px rgba(168, 85, 247, 0.14)",
      borderColor: "#D8B4FE",
    },
  },
  flowCardCyan: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderTop: "3px solid #06B6D4",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 16px rgba(6, 182, 212, 0.06)",
    transition: "all 0.2s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: "0 12px 30px rgba(6, 182, 212, 0.14)",
      borderColor: "#A5F3FC",
    },
  },
  flowCardIconBox: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: "16px",
    flexShrink: 0,
  },
  flowCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 8px 0",
  },
  flowCardText: {
    fontSize: "0.9375rem",
    lineHeight: 1.65,
    color: "#475569",
    margin: 0,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     AUTOMATIONS SECTION (HOW THE ENGINE RUNS TOGETHER)
     ───────────────────────────────────────────────────────────────────────────── */
  automationsSection: {
    padding: "96px 24px",
    maxWidth: "1280px",
    margin: "0 auto",
    borderBottom: "1px solid #E2E8F0",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "60px 16px",
    },
  },
  automationsStack: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    maxWidth: "880px",
    margin: "0 auto",
  },
  automationRow: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "16px",
    padding: "28px 32px",
    display: "flex",
    gap: "24px",
    alignItems: "flex-start",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.03)",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#FAFCFF",
      borderColor: "#0072C4",
      transform: "translateY(-2px)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.08)",
    },
    "@media (max-width: 640px)": {
      flexDirection: "column",
      gap: "16px",
      padding: "20px 20px",
    },
  },
  autoNumberBox: {
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    color: "#0072C4",
    fontSize: "1.15rem",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  autoTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 8px 0",
  },
  autoText: {
    fontSize: "0.96875rem",
    lineHeight: 1.7,
    color: "#475569",
    margin: 0,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     MOBILE APPS SECTION (STAY IN THE LOOP ANYWHERE)
     ───────────────────────────────────────────────────────────────────────────── */
  mobileSection: {
    padding: "96px 24px",
    backgroundColor: "#F8FAFC",
    borderBottom: "1px solid #E2E8F0",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 768px)": {
      padding: "60px 16px",
    },
  },
  mobileContainer: {
    maxWidth: "1280px",
    margin: "0 auto",
  },
  mobileSplitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    marginTop: "48px",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  mobileCardsCol: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  mobileCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "20px",
    padding: "32px",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.03)",
    transition: "all 0.2s ease",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-2px)",
      boxShadow: "0 10px 24px rgba(0, 114, 196, 0.08)",
    },
  },
  mobileCardIconBox: {
    width: "56px",
    height: "56px",
    borderRadius: "16px",
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: "20px",
    flexShrink: 0,
  },
  mobileCardTitle: {
    fontSize: "1.375rem",
    fontWeight: 800,
    color: "#0F172A",
    margin: "0 0 6px 0",
  },
  mobileCardAudiencePill: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#0072C4",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "14px",
  },
  mobileCardText: {
    fontSize: "0.96875rem",
    lineHeight: 1.7,
    color: "#475569",
    margin: "0 0 20px 0",
  },
  mobileTagRow: {
    display: "flex",
    gap: "10px",
  },
  mobilePlatformTag: {
    fontSize: "0.75rem",
    fontWeight: 600,
    padding: "4px 12px",
    borderRadius: "9999px",
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    color: "#475569",
  },
  mobilePhoneCol: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     FOUNDER CONTROL SECTION (BUILT FOR GROWING BUSINESSES)
     ───────────────────────────────────────────────────────────────────────────── */
  founderSection: {
    padding: "96px 24px",
    maxWidth: "1280px",
    margin: "0 auto",
    borderBottom: "1px solid #E2E8F0",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "60px 16px",
    },
  },
  founderGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "36px",
    marginTop: "48px",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
      gap: "24px",
    },
  },
  founderItem: {
    display: "flex",
    gap: "18px",
    alignItems: "flex-start",
    cursor: "pointer",
  },
  founderIcon: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    backgroundColor: "#EFF6FF",
    border: "1px solid #DBEAFE",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    flexShrink: 0,
  },
  founderItemTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 8px 0",
  },
  founderItemText: {
    fontSize: "0.96875rem",
    lineHeight: 1.7,
    color: "#475569",
    margin: 0,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     HESITATION & MIGRATION SECTION (TERRIFIED OF MIGRATING? DON'T BE.)
     ───────────────────────────────────────────────────────────────────────────── */
  migrationSection: {
    padding: "96px 24px",
    maxWidth: "1280px",
    margin: "0 auto",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "60px 16px",
    },
  },
  migrationGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    marginTop: "48px",
    "@media (max-width: 990px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  migrationCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.03)",
    transition: "all 0.2s ease",
    cursor: "pointer",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-3px)",
      boxShadow: "0 10px 24px rgba(0, 114, 196, 0.08)",
    },
  },
  migrationCardTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
  },
  migrationBadgeIcon: {
    display: "flex",
    alignItems: "center",
    color: "#0072C4",
    flexShrink: 0,
  },
  migrationCardTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  migrationCardText: {
    fontSize: "0.90625rem",
    lineHeight: 1.65,
    color: "#475569",
    margin: 0,
  },
  bottomCtaBanner: {
    marginTop: "64px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  bottomCtaBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "1.125rem",
    fontWeight: 700,
    padding: "16px 40px",
    borderRadius: "14px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 6px 24px rgba(0, 114, 196, 0.35)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "#005ea6",
      transform: "translateY(-2px)",
      boxShadow: "0 10px 32px rgba(0, 114, 196, 0.45)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  bottomCtaSub: {
    fontSize: "0.875rem",
    color: "#64748B",
    marginTop: "12px",
    fontWeight: 500,
  },
  socialProofRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    marginTop: "20px",
    flexWrap: "wrap",
  },
  socialAvatarStack: {
    display: "flex",
    alignItems: "center",
  },
  socialAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#1E293B",
    border: "2px solid #0F172A",
    color: "#94A3B8",
    fontSize: "10.5px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "-8px",
    letterSpacing: "-0.02em",
    "&:first-child": {
      marginLeft: 0,
    },
  },
  socialAvatarPlus: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#2563EB",
    border: "2px solid #0F172A",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "-8px",
  },
  socialProofText: {
    fontSize: "0.875rem",
    color: "#94A3B8",
    fontWeight: 500,
    letterSpacing: "0.01em",
  },
}));
