import { createUseStyles } from "react-jss";
import { Theme } from "../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  page: {
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily: "'Open Sans', sans-serif",
    overflow: "hidden",
  },
  hero: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "56px 32px 80px",
    textAlign: "center",
    position: "relative",
    "@media (max-width: 600px)": { padding: "40px 20px 56px" },
  },
  heroGlow: {
    position: "absolute",
    width: "420px",
    height: "320px",
    top: "54px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(80px)",
    opacity: 0.8,
    borderRadius: "50%",
    pointerEvents: "none",
  },
  heroContent: { position: "relative", zIndex: 1 },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "7px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
    fontSize: "0.875rem",
    fontWeight: 700,
  },
  title: {
    maxWidth: "900px",
    margin: "24px auto 20px",
    fontSize: "clamp(2.3rem, 5vw, 4.25rem)",
    lineHeight: 1.12,
    letterSpacing: "0.01em",
    fontWeight: 800,
  },
  titleAccent: { color: theme.light.brand.surface.dark, display: "block" },
  heroDescription: {
    maxWidth: "820px",
    margin: "0 auto 32px",
    color: theme.light.neutral.onSurface.medium,
    fontSize: "1.0625rem",
    lineHeight: 1.75,
  },
  primaryButton: {
    border: "none",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: theme.light.brand.surface.dark,
    color: theme.light.neutral.onSurface.inverse,
    padding: "14px 24px",
    fontFamily: "inherit",
    fontSize: "1rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: theme.elevation.m,
    transition: "transform 0.2s ease, background-color 0.2s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.medium,
      transform: "translateY(-2px)",
    },
  },
  workspace: {
    maxWidth: "1120px",
    minHeight: "560px",
    margin: "72px auto 0",
    display: "grid",
    gridTemplateColumns: "210px minmax(0, 1fr) 300px",
    textAlign: "left",
    overflow: "hidden",
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderRadius: theme.borderRadius.b500,
    boxShadow: theme.elevation.l,
    position: "relative",
    "@media (max-width: 960px)": { gridTemplateColumns: "190px minmax(0, 1fr)" },
    "@media (max-width: 700px)": { display: "block", minHeight: "auto" },
  },
  workspaceBar: {
    gridColumn: "1 / -1",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px",
    backgroundColor: theme.light.neutral.surface.light,
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.75rem",
  },
  dots: { display: "flex", gap: "6px" },
  dot: { width: "9px", height: "9px", borderRadius: "50%", backgroundColor: theme.light.neutral.border.medium },
  avatar: {
    width: "27px",
    height: "27px",
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    fontSize: "0.625rem",
    fontWeight: 800,
  },
  sidebar: {
    padding: "18px 14px",
    backgroundColor: theme.light.neutral.surface.light,
    borderRight: `1px solid ${theme.light.neutral.border.light}`,
    "@media (max-width: 700px)": { display: "none" },
  },
  uploadButton: {
    width: "100%",
    border: "none",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: theme.light.brand.surface.dark,
    color: theme.light.neutral.onSurface.inverse,
    padding: "10px 8px",
    fontFamily: "inherit",
    fontWeight: 700,
    cursor: "pointer",
  },
  navList: { display: "grid", gap: "4px", marginTop: "18px" },
  navItem: {
    padding: "10px 11px",
    borderRadius: theme.borderRadius.b100,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.8125rem",
  },
  navItemActive: {
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    borderLeft: `3px solid ${theme.light.brand.surface.medium}`,
    fontWeight: 700,
  },
  tagHeading: {
    marginTop: "auto",
    padding: "28px 8px 10px",
    color: theme.light.neutral.onSurface.dark,
    fontSize: "0.625rem",
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  tagDots: { display: "flex", gap: "8px", padding: "0 8px" },
  tagDot: { width: "10px", height: "10px", borderRadius: "50%" },
  tagDotNegative: { backgroundColor: theme.light.negative.surface.medium },
  tagDotWarning: { backgroundColor: theme.light.warning.surface.medium },
  tagDotBrand: { backgroundColor: theme.light.brand.border.medium },
  files: { minWidth: 0, backgroundColor: theme.light.neutral.surface.lighter },
  filesHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "18px 20px",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    fontSize: "0.875rem",
    fontWeight: 700,
  },
  filter: {
    padding: "6px 9px",
    borderRadius: theme.borderRadius.b100,
    backgroundColor: theme.light.neutral.surface.light,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.6875rem",
    fontWeight: 600,
  },
  fileList: { padding: "14px" },
  fileRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    padding: "12px",
    borderRadius: theme.borderRadius.b200,
    border: `1px solid transparent`,
    marginBottom: "6px",
    "&:hover": { backgroundColor: theme.light.neutral.surface.light, borderColor: theme.light.neutral.border.light },
  },
  fileRowActive: {
    backgroundColor: theme.light.brand.surface.lighter,
    borderColor: theme.light.brand.border.light,
    borderLeft: `3px solid ${theme.light.brand.surface.medium}`,
  },
  fileMeta: { display: "flex", alignItems: "center", gap: "10px", minWidth: 0 },
  fileIcon: {
    width: "38px",
    height: "38px",
    borderRadius: theme.borderRadius.b100,
    display: "grid",
    placeItems: "center",
    backgroundColor: theme.light.negative.surface.lighter,
    border: `1px solid ${theme.light.negative.border.light}`,
    color: theme.light.negative.onSurface.medium,
    flexShrink: 0,
  },
  fileIconBlue: { backgroundColor: theme.light.brand.surface.lighter, borderColor: theme.light.brand.border.light, color: theme.light.brand.onSurface.default },
  fileName: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: "0.8125rem", fontWeight: 700 },
  fileDetail: { marginTop: "3px", color: theme.light.neutral.onSurface.dark, fontSize: "0.6875rem" },
  fileBadge: { color: theme.light.negative.onSurface.medium, fontSize: "0.5625rem", fontWeight: 800, letterSpacing: "0.06em", textTransform: "uppercase" },
  aiButton: { border: `1px solid ${theme.light.brand.border.light}`, borderRadius: theme.borderRadius.b100, backgroundColor: theme.light.brand.surface.lighter, color: theme.light.brand.onSurface.default, padding: "6px 8px", fontFamily: "inherit", fontSize: "0.625rem", fontWeight: 700, whiteSpace: "nowrap" },
  aiPanel: {
    backgroundColor: theme.light.neutral.surface.light,
    borderLeft: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexDirection: "column",
    "@media (max-width: 960px)": { display: "none" },
  },
  aiHeader: { padding: "18px", borderBottom: `1px solid ${theme.light.neutral.border.light}`, fontSize: "0.8125rem", fontWeight: 800 },
  aiContent: { flex: 1, padding: "18px", display: "grid", alignContent: "start", gap: "14px" },
  chatBubble: { padding: "10px", borderRadius: theme.borderRadius.b150, backgroundColor: theme.light.neutral.surface.medium, color: theme.light.neutral.onSurface.medium, fontSize: "0.6875rem", lineHeight: 1.6 },
  chatBubbleAi: { backgroundColor: theme.light.brand.surface.lighter, border: `1px solid ${theme.light.brand.border.light}`, color: theme.light.neutral.onSurface.medium },
  aiFooter: { margin: "0 14px 14px", padding: "10px", borderRadius: theme.borderRadius.b100, border: `1px solid ${theme.light.neutral.border.medium}`, color: theme.light.neutral.onSurface.dark, fontSize: "0.6875rem" },
  section: { maxWidth: "1200px", margin: "0 auto", padding: "88px 32px", borderTop: `1px solid ${theme.light.neutral.border.light}`, "@media (max-width: 600px)": { padding: "60px 20px" } },
  split: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "64px", alignItems: "center", "@media (max-width: 800px)": { gridTemplateColumns: "1fr", gap: "32px" } },
  kicker: { color: theme.light.brand.onSurface.default, fontSize: "0.8125rem", fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase" },
  sectionTitle: { margin: "12px 0 18px", fontSize: "clamp(1.9rem, 4vw, 3rem)", lineHeight: 1.18, fontWeight: 800 },
  sectionText: { color: theme.light.neutral.onSurface.medium, fontSize: "1rem", lineHeight: 1.75 },
  points: { display: "grid", gap: "24px", marginTop: "30px" },
  point: { display: "flex", alignItems: "flex-start", gap: "12px" },
  pointNumber: { width: "25px", height: "25px", borderRadius: "50%", display: "grid", placeItems: "center", backgroundColor: theme.light.brand.surface.lighter, border: `1px solid ${theme.light.brand.border.light}`, color: theme.light.brand.onSurface.default, fontSize: "0.75rem", fontWeight: 800, flexShrink: 0 },
  pointTitle: { margin: 0, fontSize: "1rem", fontWeight: 800 },
  pointText: { margin: "5px 0 0", color: theme.light.neutral.onSurface.medium, fontSize: "0.875rem", lineHeight: 1.6 },
  demoCard: { padding: "28px", borderRadius: theme.borderRadius.b400, backgroundColor: theme.light.neutral.surface.light, border: `1px solid ${theme.light.neutral.border.light}`, boxShadow: theme.elevation.m },
  demoFile: { padding: "16px", borderRadius: theme.borderRadius.b200, backgroundColor: theme.light.neutral.surface.lighter, border: `1px solid ${theme.light.neutral.border.light}` },
  demoFileTitle: { fontSize: "0.875rem", fontWeight: 800 },
  demoFileMeta: { marginTop: "4px", color: theme.light.neutral.onSurface.dark, fontSize: "0.6875rem" },
  capabilityGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "24px", "@media (max-width: 700px)": { gridTemplateColumns: "1fr" } },
  capability: { padding: "28px", borderRadius: theme.borderRadius.b300, backgroundColor: theme.light.neutral.surface.light, border: `1px solid ${theme.light.neutral.border.light}` },
  capabilityIcon: { fontSize: "1.5rem", marginBottom: "16px" },
  capabilityTitle: { margin: "0 0 10px", fontSize: "1.125rem", fontWeight: 800 },
  capabilityText: { margin: 0, color: theme.light.neutral.onSurface.medium, fontSize: "0.875rem", lineHeight: 1.7 },
  pillRow: { display: "flex", flexWrap: "wrap", gap: "8px", marginTop: "18px" },
  pill: { padding: "6px 9px", borderRadius: theme.borderRadius.b100, backgroundColor: theme.light.neutral.surface.medium, color: theme.light.neutral.onSurface.medium, fontSize: "0.625rem", fontWeight: 800 },
  taxonomy: { padding: "28px", borderRadius: theme.borderRadius.b400, backgroundColor: theme.light.neutral.surface.light, border: `1px solid ${theme.light.neutral.border.light}` },
  taxonomyRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: "12px", padding: "13px", marginTop: "10px", borderRadius: theme.borderRadius.b150, backgroundColor: theme.light.neutral.surface.medium, fontSize: "0.8125rem" },
  taxonomyStatus: { color: theme.light.brand.onSurface.default, fontSize: "0.6875rem", fontWeight: 700 },
}));
