import { createUseStyles } from "react-jss";
import { Theme } from "../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes floatVaultOrb1": {
    "0%, 100%": {
      transform: "translate(0, 0) scale(1)",
    },
    "50%": {
      transform: "translate(26px, -22px) scale(1.06)",
    },
  },
  "@keyframes floatVaultOrb2": {
    "0%, 100%": {
      transform: "translate(0, 0) scale(1)",
    },
    "50%": {
      transform: "translate(-24px, 24px) scale(0.95)",
    },
  },
  "@keyframes pulseGlow": {
    "0%, 100%": {
      opacity: 0.35,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.75,
      transform: "scale(1.08)",
    },
  },
  "@keyframes nodeBlink": {
    "0%, 100%": {
      opacity: 0.15,
      transform: "scale(0.85)",
    },
    "50%": {
      opacity: 0.95,
      transform: "scale(1.3)",
    },
  },
  "@keyframes perimeterScan": {
    "0%": {
      left: "-25%",
      opacity: 0,
    },
    "20%": {
      opacity: 0.9,
    },
    "80%": {
      opacity: 0.9,
    },
    "100%": {
      left: "120%",
      opacity: 0,
    },
  },
  page: {
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    width: "100%",
    maxWidth: "100vw",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────── */
  hero: {
    maxWidth: "1280px",
    margin: "0 auto",
    padding: "56px 24px 80px",
    textAlign: "center",
    position: "relative",
    zIndex: 1,
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 768px)": {
      padding: "36px 14px 50px",
    },
  },
  heroGlow: {
    position: "absolute",
    width: "700px",
    height: "450px",
    top: "-80px",
    left: "50%",
    transform: "translateX(-50%)",
    background: "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.12) 0%, rgba(2, 132, 199, 0.05) 50%, rgba(255, 255, 255, 0) 75%)",
    filter: "blur(60px)",
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
    "@media (max-width: 768px)": {
      width: "100%",
      maxWidth: "340px",
      height: "260px",
      top: "-20px",
    },
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    maxWidth: "960px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "7px 16px",
    borderRadius: "9999px",
    backgroundColor: "#F0F9FF",
    border: "1px solid #BAE6FD",
    color: "#0284C7",
    fontSize: "0.84rem",
    fontWeight: 700,
    letterSpacing: "0.02em",
    boxShadow: "0 1px 3px rgba(2, 132, 199, 0.08)",
    marginBottom: "20px",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 4px 12px rgba(2, 132, 199, 0.15)",
    },
    "@media (max-width: 480px)": {
      padding: "6px 12px",
      fontSize: "0.78rem",
      gap: "6px",
    },
  },
  badgeDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0284C7",
    boxShadow: "0 0 8px rgba(2, 132, 199, 0.6)",
  },
  title: {
    fontSize: "3.75rem",
    lineHeight: 1.12,
    letterSpacing: "-0.035em",
    fontWeight: 800,
    color: "#0F172A",
    margin: "0 auto 20px auto",
    "@media (max-width: 1024px)": {
      fontSize: "3rem",
    },
    "@media (max-width: 768px)": {
      fontSize: "2.15rem",
      lineHeight: 1.2,
      margin: "0 auto 16px auto",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.85rem",
      lineHeight: 1.22,
    },
  },
  titleAccent: {
    background: "linear-gradient(135deg, #0072C4 0%, #0284C7 60%, #0369A1 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    display: "inline",
  },
  heroDescription: {
    maxWidth: "800px",
    margin: "0 auto 36px auto",
    color: "#475569",
    fontSize: "1.18rem",
    lineHeight: 1.7,
    fontWeight: 400,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      lineHeight: 1.6,
      padding: "0 4px",
      margin: "0 auto 24px auto",
    },
  },
  heroBtnRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    flexWrap: "wrap",
    marginBottom: "48px",
    "@media (max-width: 768px)": {
      marginBottom: "32px",
      gap: "10px",
    },
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    border: "none",
    borderRadius: "10px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    padding: "14px 34px",
    fontFamily: "inherit",
    fontSize: "1.02rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 16px rgba(0, 114, 196, 0.28)",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    "&:hover": {
      backgroundColor: "#005ea6",
      transform: "translateY(-2px)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.36)",
    },
    "@media (max-width: 480px)": {
      width: "100%",
      padding: "12px 20px",
      fontSize: "0.95rem",
    },
  },
  secondaryBadgePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    borderRadius: "10px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    color: "#475569",
    fontSize: "0.92rem",
    fontWeight: 600,
    "@media (max-width: 480px)": {
      width: "100%",
      justifyContent: "center",
      padding: "10px 14px",
      fontSize: "0.82rem",
    },
  },
  mockupWrapper: {
    maxWidth: "1240px",
    width: "100%",
    margin: "0 auto",
    position: "relative",
    zIndex: 3,
    overflow: "hidden",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION: VAULT AMBIENT CANVAS & WRAPPER
     ───────────────────────────────────────────────────────────── */
  sectionWrapper: {
    maxWidth: "100%",
    width: "100%",
    margin: "0 auto",
    padding: "88px 24px",
    position: "relative",
    overflow: "hidden",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "52px 14px",
    },
  },
  sectionWrapperAnimated: {
    backgroundColor: "#FAFBFD",
    borderTop: "1px solid rgba(226, 232, 240, 0.7)",
    borderBottom: "1px solid rgba(226, 232, 240, 0.7)",
  },
  sectionInner: {
    position: "relative",
    zIndex: 1,
    maxWidth: "1240px",
    margin: "0 auto",
  },
  vaultAmbientCanvas: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    overflow: "hidden",
    zIndex: 0,
  },
  vaultGridOverlay: {
    position: "absolute",
    inset: 0,
    backgroundImage: `
      linear-gradient(to right, rgba(0, 114, 196, 0.045) 1px, transparent 1px),
      linear-gradient(to bottom, rgba(147, 51, 234, 0.04) 1px, transparent 1px)
    `,
    backgroundSize: "40px 40px",
    maskImage: "radial-gradient(ellipse 75% 65% at 50% 50%, #000 35%, transparent 90%)",
    WebkitMaskImage: "radial-gradient(ellipse 75% 65% at 50% 50%, #000 35%, transparent 90%)",
  },
  vaultBlobBlue: {
    position: "absolute",
    top: "30px",
    left: "-60px",
    width: "560px",
    height: "560px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(0, 114, 196, 0.13) 0%, rgba(2, 132, 199, 0.035) 50%, transparent 70%)",
    filter: "blur(75px)",
    animation: "$floatVaultOrb1 18s ease-in-out infinite",
  },
  vaultBlobPurple: {
    position: "absolute",
    bottom: "30px",
    right: "-60px",
    width: "560px",
    height: "560px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(147, 51, 234, 0.12) 0%, rgba(168, 85, 247, 0.035) 50%, transparent 70%)",
    filter: "blur(75px)",
    animation: "$floatVaultOrb2 22s ease-in-out infinite",
  },
  vaultBlobCenter: {
    position: "absolute",
    top: "48%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "520px",
    height: "380px",
    borderRadius: "50%",
    background: "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.06) 0%, transparent 70%)",
    filter: "blur(70px)",
    animation: "$pulseGlow 8s ease-in-out infinite",
  },
  vaultScanTrack: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "1px",
    background: "linear-gradient(90deg, transparent 0%, rgba(0, 114, 196, 0.25) 30%, rgba(147, 51, 234, 0.25) 70%, transparent 100%)",
    overflow: "hidden",
  },
  vaultScanLight: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "160px",
    height: "100%",
    background: "linear-gradient(90deg, transparent 0%, rgba(0, 114, 196, 0.85) 50%, rgba(147, 51, 234, 0.95) 80%, transparent 100%)",
    boxShadow: "0 0 6px rgba(0, 114, 196, 0.45)",
    animation: "$perimeterScan 7s cubic-bezier(0.4, 0, 0.2, 1) infinite",
  },
  vaultScanTrackBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "1px",
    background: "linear-gradient(90deg, transparent 0%, rgba(147, 51, 234, 0.25) 30%, rgba(0, 114, 196, 0.25) 70%, transparent 100%)",
    overflow: "hidden",
  },
  vaultScanLightBottom: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "160px",
    height: "100%",
    background: "linear-gradient(90deg, transparent 0%, rgba(147, 51, 234, 0.95) 40%, rgba(0, 114, 196, 0.85) 80%, transparent 100%)",
    boxShadow: "0 0 6px rgba(147, 51, 234, 0.45)",
    animation: "$perimeterScan 8s cubic-bezier(0.4, 0, 0.2, 1) infinite 2.5s",
  },
  vaultNodeDot: {
    position: "absolute",
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    animation: "$nodeBlink 4s ease-in-out infinite",
  },
  vaultNodeBlue1: {
    top: "22%",
    left: "14%",
    backgroundColor: "rgba(0, 114, 196, 0.75)",
    boxShadow: "0 0 10px rgba(0, 114, 196, 0.8)",
  },
  vaultNodeBlue2: {
    bottom: "28%",
    left: "24%",
    backgroundColor: "rgba(0, 114, 196, 0.75)",
    boxShadow: "0 0 10px rgba(0, 114, 196, 0.8)",
    animationDelay: "1.8s",
  },
  vaultNodePurple1: {
    top: "30%",
    right: "16%",
    backgroundColor: "rgba(147, 51, 234, 0.75)",
    boxShadow: "0 0 10px rgba(147, 51, 234, 0.8)",
    animationDelay: "1s",
  },
  vaultNodePurple2: {
    bottom: "20%",
    right: "22%",
    backgroundColor: "rgba(147, 51, 234, 0.75)",
    boxShadow: "0 0 10px rgba(147, 51, 234, 0.8)",
    animationDelay: "2.6s",
  },
  sectionHeaderCenter: {
    textAlign: "center",
    maxWidth: "760px",
    width: "100%",
    margin: "0 auto 48px auto",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      margin: "0 auto 32px auto",
    },
  },
  kicker: {
    display: "inline-block",
    color: "#0072C4",
    fontSize: "0.82rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    marginBottom: "10px",
    "@media (max-width: 480px)": {
      fontSize: "0.75rem",
    },
  },
  sectionTitle: {
    fontSize: "2.45rem",
    lineHeight: 1.22,
    fontWeight: 800,
    letterSpacing: "-0.025em",
    color: "#0F172A",
    margin: "0 0 16px 0",
    "@media (max-width: 768px)": {
      fontSize: "1.75rem",
      lineHeight: 1.25,
      margin: "0 0 12px 0",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.45rem",
      lineHeight: 1.25,
    },
  },
  sectionDescription: {
    color: "#475569",
    fontSize: "1.1rem",
    lineHeight: 1.65,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "0.95rem",
      lineHeight: 1.55,
    },
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "24px",
    width: "100%",
    alignItems: "stretch",
    boxSizing: "border-box",
    "@media (max-width: 1024px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "16px",
    },
  },
  featureCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    padding: "28px 24px",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    transition: "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
    position: "relative",
    overflow: "hidden",
    boxSizing: "border-box",
    cursor: "default",
    "&:hover": {
      transform: "translateY(-4px)",
      borderColor: "#BAE6FD",
      boxShadow: "0 12px 30px rgba(0, 114, 196, 0.1)",
    },
    "@media (max-width: 600px)": {
      padding: "20px 16px",
      borderRadius: "14px",
    },
  },
  featureCardHovered: {
    transform: "translateY(-4px)",
    borderColor: "#0072C4",
    boxShadow: "0 14px 34px rgba(0, 114, 196, 0.12)",
  },
  featureIconWrapper: {
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    backgroundColor: "#F0F9FF",
    border: "1px solid #E0F2FE",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: "20px",
    flexShrink: 0,
    "@media (max-width: 600px)": {
      width: "42px",
      height: "42px",
      marginBottom: "14px",
      borderRadius: "10px",
    },
  },
  cardTitle: {
    fontSize: "1.15rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 10px 0",
    "@media (max-width: 600px)": {
      fontSize: "1.02rem",
      margin: "0 0 6px 0",
    },
  },
  cardDescription: {
    fontSize: "0.93rem",
    lineHeight: 1.6,
    color: "#64748B",
    margin: 0,
    flex: 1,
    "@media (max-width: 600px)": {
      fontSize: "0.85rem",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 2: DOCUMENT AI SPLIT SECTION (RESPONSIVE)
     ───────────────────────────────────────────────────────────── */
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "56px",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
    "& > *": {
      minWidth: 0,
      width: "100%",
      boxSizing: "border-box",
    },
    "@media (max-width: 960px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "36px",
    },
  },
  stepperList: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    marginTop: "28px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 600px)": {
      marginTop: "20px",
      gap: "10px",
    },
  },
  stepItem: {
    display: "flex",
    gap: "14px",
    padding: "18px",
    borderRadius: "14px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    cursor: "pointer",
    transition: "all 0.25s ease",
    boxSizing: "border-box",
    width: "100%",
    "&:hover": {
      borderColor: "#BAE6FD",
      backgroundColor: "#F8FAFC",
    },
    "@media (max-width: 600px)": {
      padding: "14px 12px",
      gap: "12px",
      borderRadius: "12px",
    },
  },
  stepItemActive: {
    borderColor: "#0072C4",
    backgroundColor: "#F0F9FF",
    boxShadow: "0 4px 16px rgba(0, 114, 196, 0.08)",
    "@media (min-width: 961px)": {
      transform: "translateX(6px)",
    },
    "&:hover": {
      borderColor: "#0072C4",
      backgroundColor: "#F0F9FF",
    },
  },
  stepNumber: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    backgroundColor: "#F1F5F9",
    color: "#64748B",
    fontSize: "0.92rem",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "all 0.2s ease",
    "@media (max-width: 600px)": {
      width: "30px",
      height: "30px",
      fontSize: "0.82rem",
      borderRadius: "8px",
    },
  },
  stepNumberActive: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
  },
  stepHeading: {
    fontSize: "1.05rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 4px 0",
    lineHeight: 1.3,
    "@media (max-width: 600px)": {
      fontSize: "0.94rem",
    },
  },
  stepText: {
    fontSize: "0.9rem",
    color: "#64748B",
    lineHeight: 1.5,
    margin: 0,
    "@media (max-width: 600px)": {
      fontSize: "0.82rem",
      lineHeight: 1.45,
    },
  },

  /* Right interactive preview card for Document AI */
  aiPreviewCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "18px",
    border: "1px solid #E2E8F0",
    padding: "26px",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.06)",
    position: "relative",
    width: "100%",
    boxSizing: "border-box",
    overflow: "hidden",
    "@media (max-width: 600px)": {
      padding: "16px 12px",
      borderRadius: "14px",
    },
  },
  aiDocHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "10px",
    borderBottom: "1px solid #F1F5F9",
    paddingBottom: "14px",
    marginBottom: "18px",
    width: "100%",
    boxSizing: "border-box",
  },
  aiDocMeta: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    flex: 1,
  },
  aiBadgePdf: {
    width: "34px",
    height: "34px",
    borderRadius: "8px",
    backgroundColor: "#FEE2E2",
    color: "#EF4444",
    fontSize: "0.78rem",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  aiDocTitle: {
    fontSize: "0.92rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
    wordBreak: "break-all",
    lineHeight: 1.25,
    "@media (max-width: 600px)": {
      fontSize: "0.85rem",
    },
  },
  aiDocSubtitle: {
    fontSize: "0.78rem",
    color: "#64748B",
    margin: "2px 0 0 0",
    lineHeight: 1.3,
  },
  aiConfidenceBadge: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#059669",
    backgroundColor: "#ECFDF5",
    padding: "3px 8px",
    borderRadius: "10px",
    border: "1px solid #A7F3D0",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  aiQuestionBubble: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "12px",
    padding: "12px 14px",
    fontSize: "0.88rem",
    color: "#1E293B",
    fontWeight: 600,
    marginBottom: "14px",
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    boxSizing: "border-box",
    lineHeight: 1.45,
    width: "100%",
  },
  aiAnswerCard: {
    backgroundColor: "#F0F9FF",
    border: "1px solid #BAE6FD",
    borderRadius: "12px",
    padding: "16px",
    marginBottom: "14px",
    position: "relative",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 600px)": {
      padding: "12px",
    },
  },
  aiAnswerText: {
    fontSize: "0.9rem",
    color: "#0C4A6E",
    lineHeight: 1.6,
    margin: 0,
    "@media (max-width: 600px)": {
      fontSize: "0.825rem",
    },
  },
  citationBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "12px",
    padding: "5px 10px",
    borderRadius: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #BAE6FD",
    color: "#0284C7",
    fontSize: "0.78rem",
    fontWeight: 700,
    maxWidth: "100%",
    boxSizing: "border-box",
  },
  highlightSnippet: {
    backgroundColor: "#FEF08A",
    color: "#713F12",
    padding: "2px 6px",
    borderRadius: "4px",
    fontWeight: 700,
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 3: FORT KNOX PERMISSIONS & EXPIRING LINKS (RESPONSIVE)
     ───────────────────────────────────────────────────────────── */
  perimeterGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    marginTop: "28px",
    width: "100%",
    boxSizing: "border-box",
    "& > *": {
      minWidth: 0,
      width: "100%",
      boxSizing: "border-box",
    },
    "@media (max-width: 860px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "20px",
    },
  },
  perimeterCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "18px",
    border: "1px solid #E2E8F0",
    padding: "28px",
    boxShadow: "0 4px 16px rgba(15, 23, 42, 0.04)",
    boxSizing: "border-box",
    width: "100%",
    overflow: "hidden",
    "@media (max-width: 600px)": {
      padding: "18px 14px",
      borderRadius: "14px",
    },
  },
  permissionList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    marginTop: "16px",
    width: "100%",
    boxSizing: "border-box",
  },
  permissionItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 14px",
    borderRadius: "10px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #EEF2F6",
    gap: "10px",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 480px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "8px",
    },
  },
  permLevelBadge: {
    fontSize: "0.72rem",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    padding: "3px 8px",
    borderRadius: "6px",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },

  /* Expiring link interactive simulator */
  expiringSimulator: {
    marginTop: "16px",
    backgroundColor: "#FFFBEB",
    border: "1px solid #FDE68A",
    borderRadius: "12px",
    padding: "16px",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 600px)": {
      padding: "14px 10px",
    },
  },
  linkInputRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    padding: "8px 10px",
    marginTop: "12px",
    fontFamily: "monospace",
    fontSize: "0.8rem",
    color: "#0F172A",
    boxSizing: "border-box",
    width: "100%",
    overflow: "hidden",
    "@media (max-width: 500px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "6px",
    },
  },
  timerCountdownBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "14px",
    paddingTop: "12px",
    borderTop: "1px dashed #FCD34D",
    fontSize: "0.84rem",
    gap: "8px",
    flexWrap: "wrap",
    boxSizing: "border-box",
    width: "100%",
  },
  revokeBtn: {
    backgroundColor: "#DC2626",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "0.78rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    whiteSpace: "nowrap",
    "&:hover": {
      backgroundColor: "#B91C1C",
    },
    "@media (max-width: 480px)": {
      width: "100%",
      padding: "8px 12px",
    },
  },
  restoreBtn: {
    backgroundColor: "#059669",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "0.78rem",
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    "&:hover": {
      backgroundColor: "#047857",
    },
    "@media (max-width: 480px)": {
      width: "100%",
      padding: "8px 12px",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 4: TAXONOMY & RETENTION POLICIES (RESPONSIVE)
     ───────────────────────────────────────────────────────────── */
  taxonomyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    padding: "26px",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 600px)": {
      padding: "16px 12px",
    },
  },
  chipRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginTop: "14px",
    width: "100%",
    boxSizing: "border-box",
  },
  tagChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "5px 12px",
    borderRadius: "20px",
    fontSize: "0.8rem",
    fontWeight: 600,
  },
  policyTable: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    marginTop: "16px",
    width: "100%",
    boxSizing: "border-box",
  },
  policyRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 14px",
    borderRadius: "10px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    fontSize: "0.85rem",
    gap: "8px",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 540px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "6px",
    },
  },
  policyStatusPill: {
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "3px 8px",
    borderRadius: "6px",
    whiteSpace: "nowrap",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 5: UNIFIED MOBILE EXPERIENCE
     ───────────────────────────────────────────────────────────── */
  mobileSectionWrapper: {
    backgroundColor: "#FFFFFF",
    borderTop: "1px solid #E2E8F0",
    padding: "80px 24px",
    position: "relative",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 768px)": {
      padding: "48px 16px",
    },
  },
  mobileGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    maxWidth: "1240px",
    width: "100%",
    margin: "0 auto",
    boxSizing: "border-box",
    "& > *": {
      minWidth: 0,
      width: "100%",
      boxSizing: "border-box",
    },
    "@media (max-width: 960px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      textAlign: "center",
      gap: "40px",
    },
  },
  mobilePhoneWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
  },
  mobilePillsList: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    marginTop: "28px",
    textAlign: "left",
    width: "100%",
    boxSizing: "border-box",
  },
  mobilePillItem: {
    display: "flex",
    gap: "14px",
    alignItems: "flex-start",
    width: "100%",
    boxSizing: "border-box",
  },
  mobilePillIcon: {
    width: "38px",
    height: "38px",
    borderRadius: "10px",
    backgroundColor: "#EFF6FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 6: ENTERPRISE FEATURES GRID
     ───────────────────────────────────────────────────────────── */
  enterpriseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "24px",
    marginTop: "40px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 600px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "16px",
    },
  },
  enterpriseCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    padding: "24px",
    boxSizing: "border-box",
    transition: "all 0.25s ease",
    "&:hover": {
      borderColor: "#BAE6FD",
      transform: "translateY(-3px)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.08)",
    },
    "@media (max-width: 600px)": {
      padding: "18px 14px",
      borderRadius: "14px",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     FINAL CTA BLOCK
     ───────────────────────────────────────────────────────────── */
  ctaSection: {
    maxWidth: "1240px",
    width: "100%",
    margin: "40px auto 80px",
    padding: "0 24px",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      margin: "24px auto 60px",
      padding: "0 14px",
    },
  },
  ctaCard: {
    background: "linear-gradient(135deg, #0F172A 0%, #1E293B 100%)",
    borderRadius: "24px",
    padding: "56px 40px",
    textAlign: "center",
    color: "#FFFFFF",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 20px 40px rgba(15, 23, 42, 0.18)",
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 768px)": {
      padding: "36px 18px",
      borderRadius: "18px",
    },
  },
  ctaTitle: {
    fontSize: "2.5rem",
    fontWeight: 800,
    letterSpacing: "-0.03em",
    margin: "0 0 14px 0",
    "@media (max-width: 768px)": {
      fontSize: "1.75rem",
    },
  },
  ctaText: {
    color: "#94A3B8",
    fontSize: "1.08rem",
    maxWidth: "680px",
    margin: "0 auto 32px auto",
    lineHeight: 1.6,
    "@media (max-width: 768px)": {
      fontSize: "0.95rem",
      margin: "0 auto 24px auto",
    },
  },
  ctaBtnRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  ctaPrimaryBtn: {
    border: "none",
    borderRadius: "10px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    padding: "14px 32px",
    fontFamily: "inherit",
    fontSize: "1rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 16px rgba(0, 114, 196, 0.4)",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#0284C7",
      transform: "translateY(-2px)",
    },
    "@media (max-width: 480px)": {
      width: "100%",
      padding: "12px 20px",
    },
  },
  ctaSecondaryBtn: {
    border: "1px solid #475569",
    borderRadius: "10px",
    backgroundColor: "transparent",
    color: "#FFFFFF",
    padding: "14px 26px",
    fontFamily: "inherit",
    fontSize: "0.98rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderColor: "#94A3B8",
    },
    "@media (max-width: 480px)": {
      width: "100%",
      padding: "12px 20px",
    },
  },
  /* ─────────────────────────────────────────────────────────────
     SECTION 1: POINTS & DEMO CARD STYLES (MATCHING ORIGINAL HEAD)
     ───────────────────────────────────────────────────────────── */
  points: {
    display: "grid",
    gap: "24px",
    marginTop: "30px",
  },
  point: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
  },
  pointNumber: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    backgroundColor: "#EFF6FF",
    border: "1px solid #BAE6FD",
    color: "#0072C4",
    fontSize: "0.8rem",
    fontWeight: 800,
    flexShrink: 0,
  },
  pointTitle: {
    margin: "0 0 6px 0",
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  pointText: {
    margin: 0,
    color: "#475569",
    fontSize: "0.9375rem",
    lineHeight: 1.6,
  },
  demoCard: {
    padding: "28px",
    borderRadius: "16px",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    backdropFilter: "blur(12px)",
    border: "1px solid #E2E8F0",
    boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.05)",
    boxSizing: "border-box",
  },
  demoFile: {
    padding: "16px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    marginBottom: "16px",
  },
  demoFileTitle: {
    fontSize: "0.95rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  demoFileMeta: {
    marginTop: "4px",
    color: "#64748B",
    fontSize: "0.75rem",
  },
  chatBubble: {
    padding: "12px 16px",
    borderRadius: "10px",
    backgroundColor: "#F1F5F9",
    color: "#334155",
    fontSize: "0.85rem",
    lineHeight: 1.6,
  },
  chatBubbleAi: {
    padding: "16px",
    borderRadius: "12px",
    backgroundColor: "#EFF6FF",
    border: "1px solid #BAE6FD",
    color: "#0F172A",
    fontSize: "0.88rem",
    lineHeight: 1.6,
  },

  /* ─────────────────────────────────────────────────────────────
     CAPABILITY & TAXONOMY SECTION STYLES (MATCHING ORIGINAL HEAD)
     ───────────────────────────────────────────────────────────── */
  capabilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "24px",
    alignItems: "stretch",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
      gap: "20px",
    },
  },
  capability: {
    padding: "32px",
    borderRadius: "16px",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    backdropFilter: "blur(12px)",
    border: "1px solid #E2E8F0",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: "0 12px 28px rgba(0, 0, 0, 0.06)",
    },
    "@media (max-width: 480px)": {
      padding: "22px 18px",
    },
  },
  capabilityIcon: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    backgroundColor: "#EFF6FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "16px",
    flexShrink: 0,
  },
  capabilityTitle: {
    margin: "0 0 12px 0",
    fontSize: "1.28rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  capabilityText: {
    margin: 0,
    color: "#475569",
    fontSize: "0.95rem",
    lineHeight: 1.7,
    flex: 1,
  },
  pillRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginTop: "18px",
  },
  pill: {
    padding: "6px 12px",
    borderRadius: "6px",
    backgroundColor: "#E2E8F0",
    color: "#334155",
    fontSize: "0.72rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  taxonomy: {
    padding: "32px",
    borderRadius: "16px",
    backgroundColor: "#F0F9FF",
    border: "1px solid #BAE6FD",
    boxSizing: "border-box",
    "@media (max-width: 480px)": {
      padding: "22px 18px",
    },
  },
  taxonomyRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    padding: "13px 16px",
    marginTop: "10px",
    borderRadius: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E0F2FE",
    fontSize: "0.85rem",
    fontWeight: 600,
    color: "#0F172A",
    boxSizing: "border-box",
  },
  taxonomyStatus: {
    color: "#0284C7",
    fontSize: "0.75rem",
    fontWeight: 700,
  },

  /* ─────────────────────────────────────────────────────────────
     ENTERPRISE RESILIENCE SECTION (LIGHT)
     ───────────────────────────────────────────────────────────── */
  resilienceSection: {
    backgroundColor: "#F8FAFC",
    padding: "96px 24px",
    width: "100%",
    boxSizing: "border-box",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "72px 20px",
    },
  },
  resilienceInner: {
    maxWidth: "1100px",
    margin: "0 auto",
  },
  resilienceHeader: {
    textAlign: "center",
    marginBottom: "56px",
  },
  resilienceEyebrow: {
    display: "inline-block",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "#0284C7",
    marginBottom: "16px",
  },
  resilienceTitle: {
    fontSize: "clamp(2rem, 4vw, 2.75rem)",
    fontWeight: 800,
    color: "#0F172A",
    lineHeight: 1.2,
    margin: "0 0 20px",
  },
  resilienceSubtitle: {
    fontSize: "1rem",
    color: "#64748B",
    lineHeight: 1.75,
    maxWidth: "640px",
    margin: "0 auto",
  },
  resilienceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
    },
  },
  resilienceCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "16px",
    padding: "32px 28px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    transition: "border-color 0.25s ease, transform 0.25s ease, box-shadow 0.25s ease",
    cursor: "default",
    "&:hover": {
      borderColor: "#CBD5E1",
      transform: "translateY(-4px)",
      boxShadow: "0 16px 40px rgba(15,23,42,0.08)",
    },
  },
  resilienceIconBox: {
    width: "42px",
    height: "42px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  resilienceCardTitle: {
    fontSize: "1.1rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  resilienceCardDesc: {
    fontSize: "0.875rem",
    color: "#64748B",
    lineHeight: 1.7,
    margin: 0,
    flexGrow: 1,
  },
  resilienceTerminal: {
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    padding: "10px 14px",
    fontFamily: "'Roboto Mono', 'Courier New', monospace",
    fontSize: "0.78rem",
    color: "#475569",
    marginTop: "auto",
    "&::before": {
      content: '"›"',
      color: "#0284C7",
      marginRight: "8px",
      fontWeight: 700,
    },
  },
  resiliencePill: {
    display: "inline-block",
    backgroundColor: "rgba(5,150,105,0.08)",
    color: "#059669",
    border: "1px solid rgba(5,150,105,0.25)",
    borderRadius: "6px",
    padding: "6px 14px",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    marginTop: "auto",
    alignSelf: "flex-start",
  },
}));
