import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
  /* ─────────────────────────────────────────────────────────────
     MOCKUP APP SHELL (WINDOW FRAME)
     ───────────────────────────────────────────────────────────── */
  mockupFrame: {
    width: "100%",
    maxWidth: "1180px",
    margin: "0 auto",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 20px 40px -15px rgba(15, 23, 42, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.03)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    textAlign: "left",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  mockupFrameEmbedded: {
    maxWidth: "100%",
    margin: "0 !important",
    borderRadius: "0 !important",
    border: "none !important",
    boxShadow: "none !important",
    width: "100%",
    height: "100%",
  },

  /* ─────────────────────────────────────────────────────────────
     TOP APPLICATION BAR
     ───────────────────────────────────────────────────────────── */
  topBar: {
    height: "50px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #EAECF0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    zIndex: 10,
    gap: "16px",
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  brandTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: "#0F172A",
    letterSpacing: "-0.01em",
  },
  workspacePill: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#0072C4",
    backgroundColor: "#EFF6FF",
    border: "1px solid #DBEAFE",
    padding: "3px 10px",
    borderRadius: "6px",
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  topSearchBox: {
    flex: 1,
    maxWidth: "420px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    padding: "5px 12px",
    transition: "all 0.15s ease",
    "&:focus-within": {
      borderColor: "#0072C4",
      backgroundColor: "#FFFFFF",
      boxShadow: "0 0 0 2px rgba(0, 114, 196, 0.1)",
    },
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  topSearchInput: {
    border: "none",
    outline: "none",
    backgroundColor: "transparent",
    fontSize: "0.8125rem",
    color: "#0F172A",
    width: "100%",
    "&::placeholder": {
      color: "#94A3B8",
    },
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  storageMeterPill: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#64748B",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    padding: "3px 10px",
    borderRadius: "6px",
    "@media (max-width: 860px)": {
      display: "none",
    },
  },
  bellBtn: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "transparent",
    color: "#475569",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  topProfileAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#EFF6FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.8125rem",
    border: "1px solid #DBEAFE",
    cursor: "pointer",
  },

  /* ─────────────────────────────────────────────────────────────
     MAIN BODY: RAILS + FILE STAGE + AI PANEL
     ───────────────────────────────────────────────────────────── */
  mainBody: {
    display: "flex",
    minHeight: "600px",
    backgroundColor: "#FFFFFF",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      minHeight: "auto",
    },
  },

  /* OUTER SUITE RAIL */
  outerRail: {
    width: "50px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "10px 0",
    flexShrink: 0,
    gap: "8px",
    zIndex: 4,
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  railCollapseBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "transparent",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  railAvatarCircle: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    backgroundColor: "#EFF6FF",
    border: "1px solid #DBEAFE",
    color: "#0072C4",
    fontSize: "13px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "4px",
  },
  railItem: {
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    cursor: "pointer",
    transition: "all 0.2s cubic-bezier(0.34, 1.4, 0.64, 1)",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      color: "#0F172A",
      transform: "scale(1.1)",
    },
  },
  railItemActive: {
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    backgroundColor: "#EFF6FF",
    borderLeft: "3px solid #0072C4",
    cursor: "pointer",
    fontWeight: 700,
  },

  /* INNER DRIVE SIDEBAR */
  driveSidebar: {
    width: "210px",
    backgroundColor: "#F8FAFC",
    borderRight: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    padding: "16px 12px",
    flexShrink: 0,
    gap: "16px",
    zIndex: 3,
    "@media (max-width: 900px)": {
      width: "100%",
      borderRight: "none",
      borderBottom: "1px solid #EAECF0",
    },
  },
  uploadBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    padding: "9px 14px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 114, 196, 0.2)",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#005ea6",
      boxShadow: "0 4px 8px rgba(0, 114, 196, 0.3)",
      transform: "translateY(-1px)",
    },
  },
  sidebarSectionTitle: {
    fontSize: "0.6875rem",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#94A3B8",
    padding: "0 6px",
    marginBottom: "4px",
  },
  sidebarNavList: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  sidebarNavItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 10px",
    borderRadius: "6px",
    fontSize: "0.8125rem",
    fontWeight: 500,
    color: "#475569",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  sidebarNavItemActive: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 10px",
    borderRadius: "6px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0072C4",
    backgroundColor: "#EFF6FF",
    cursor: "pointer",
  },
  navItemLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  navCountBadge: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#64748B",
    backgroundColor: "#F1F5F9",
    padding: "1px 6px",
    borderRadius: "10px",
  },
  activePillBadge: {
    fontSize: "0.625rem",
    fontWeight: 800,
    color: "#16A34A",
    backgroundColor: "#DCFCE7",
    padding: "1px 6px",
    borderRadius: "10px",
  },
  tagsList: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  tagItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.75rem",
    color: "#475569",
    padding: "5px 8px",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  tagColorDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
  },
  sidebarStorageArea: {
    marginTop: "auto",
    paddingTop: "12px",
    borderTop: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  storageBarTrack: {
    height: "5px",
    backgroundColor: "#E2E8F0",
    borderRadius: "3px",
    overflow: "hidden",
  },
  storageBarFill: {
    height: "100%",
    width: "48%",
    backgroundColor: "#0072C4",
    borderRadius: "3px",
  },
  storageTextRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.6875rem",
    color: "#64748B",
    fontWeight: 500,
  },

  /* ─────────────────────────────────────────────────────────────
     CENTER FILES WORKSPACE STAGE
     ───────────────────────────────────────────────────────────── */
  filesStage: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    minWidth: 0,
    padding: "16px 20px",
    gap: "14px",
  },
  filesHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "12px",
    paddingBottom: "10px",
    borderBottom: "1px solid #F1F5F9",
  },
  breadcrumbRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "0.875rem",
    color: "#64748B",
  },
  breadcrumbCurrent: {
    fontWeight: 700,
    color: "#0F172A",
  },
  stageActionsRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  filterBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px 10px",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#475569",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      borderColor: "#CBD5E1",
      backgroundColor: "#F8FAFC",
      color: "#0F172A",
    },
  },
  viewToggleGroup: {
    display: "flex",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    overflow: "hidden",
  },
  viewToggleBtn: {
    padding: "5px 8px",
    background: "#FFFFFF",
    border: "none",
    color: "#64748B",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      color: "#0F172A",
    },
  },
  viewToggleBtnActive: {
    padding: "5px 8px",
    background: "#EFF6FF",
    border: "none",
    color: "#0072C4",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  /* FILES TABLE & LIST */
  filesTable: {
    width: "100%",
    borderCollapse: "collapse",
  },
  filesTableHeader: {
    borderBottom: "1px solid #E2E8F0",
  },
  filesTableHeaderCell: {
    padding: "8px 12px",
    fontSize: "0.6875rem",
    fontWeight: 700,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    textAlign: "left",
  },
  fileRowItem: {
    borderBottom: "1px solid #F1F5F9",
    transition: "all 0.15s ease",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#F8FAFC",
    },
  },
  fileRowItemActive: {
    backgroundColor: "#EFF6FF !important",
    borderLeft: "3px solid #0072C4",
  },
  fileCell: {
    padding: "10px 12px",
    fontSize: "0.8125rem",
    verticalAlign: "middle",
  },
  filePrimaryCol: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  fileIconWrapper: {
    width: "32px",
    height: "32px",
    borderRadius: "6px",
    backgroundColor: "#F1F5F9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  fileNameText: {
    fontWeight: 600,
    color: "#0F172A",
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: "240px",
  },
  fileSubtext: {
    fontSize: "0.6875rem",
    color: "#64748B",
  },
  fileTagPill: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: "10px",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  askAiMiniBtn: {
    backgroundColor: "#F5F3FF",
    color: "#7C3AED",
    border: "1px solid #DDD6FE",
    borderRadius: "6px",
    padding: "4px 10px",
    fontSize: "0.6875rem",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#EDE9FE",
      borderColor: "#C4B5FD",
      transform: "scale(1.03)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     RIGHT DOCUMENT AI ASSISTANT DRAWER PANEL
     ───────────────────────────────────────────────────────────── */
  aiDrawer: {
    width: "320px",
    backgroundColor: "#FAFAFD",
    borderLeft: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    zIndex: 2,
    "@media (max-width: 1040px)": {
      display: "none",
    },
  },
  aiDrawerHeader: {
    padding: "12px 16px",
    borderBottom: "1px solid #EAECF0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
  },
  aiHeaderTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#7C3AED",
  },
  aiActiveFileBadge: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#475569",
    backgroundColor: "#F1F5F9",
    padding: "2px 8px",
    borderRadius: "4px",
    maxWidth: "140px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  aiChatStream: {
    flex: 1,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    overflowY: "auto",
  },
  userQuestionBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "0.75rem",
    lineHeight: 1.45,
    padding: "8px 12px",
    borderRadius: "12px 12px 2px 12px",
    maxWidth: "85%",
    boxShadow: "0 1px 3px rgba(0, 114, 196, 0.2)",
  },
  aiAnswerBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E9D5FF",
    color: "#1E1B4B",
    fontSize: "0.75rem",
    lineHeight: 1.5,
    padding: "10px 12px",
    borderRadius: "12px 12px 12px 2px",
    maxWidth: "92%",
    boxShadow: "0 2px 6px rgba(124, 58, 237, 0.05)",
  },
  citationBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    marginTop: "8px",
    fontSize: "0.625rem",
    fontWeight: 700,
    color: "#7C3AED",
    backgroundColor: "#F5F3FF",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  suggestedPromptsSection: {
    padding: "0 16px 10px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  promptPill: {
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    borderRadius: "6px",
    padding: "5px 10px",
    fontSize: "0.6875rem",
    color: "#475569",
    textAlign: "left",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      borderColor: "#C4B5FD",
      backgroundColor: "#FAF5FF",
      color: "#7C3AED",
    },
  },
  aiInputContainer: {
    padding: "12px 16px",
    borderTop: "1px solid #EAECF0",
    backgroundColor: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  aiInputField: {
    flex: 1,
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "6px 10px",
    fontSize: "0.75rem",
    outline: "none",
    "&:focus": {
      borderColor: "#7C3AED",
      boxShadow: "0 0 0 2px rgba(124, 58, 237, 0.1)",
    },
  },
  aiSendBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    backgroundColor: "#7C3AED",
    border: "none",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#6D28D9",
    },
  },
});
