import { createUseStyles } from "react-jss";
import principle_background from "../../assets/icons/background.svg";
import { Theme } from "../../theme/themeType";

export const usestyles = createUseStyles((theme: Theme) => ({
  "@keyframes pulse": {
    "0%, 100%": {
      opacity: 1,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.4,
      transform: "scale(0.85)",
    },
  },
  mainSecCon: {
    width: "100%",
    height: "auto",
    aspectRatio: "1279 / 626",
    maxHeight: "92vh",
    minHeight: "540px",
    position: "relative",
    overflow: "hidden",
    margin: 0,
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(180deg, #CFDEF9 0%, #FFFFFF 100%)",
    "@media (max-width: 768px)": {
      width: "100%",
      height: "auto",
      aspectRatio: "unset",
      minHeight: "65vh",
      padding: "80px 20px 40px 20px",
      boxSizing: "border-box",
    },
  },
  heroSvgContainer: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "auto",
    zIndex: 1,
    "& svg": {
      width: "100%",
      height: "100%",
      objectFit: "contain",
    },
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  NavBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "48px",
    width: "100%",
    padding: theme.spacing.s300,
  },
  NavBarLogo: {
    width: "200px",
    height: "auto",
  },
  NavBarLinks: {
    listStyle: "none",
    display: "flex",
    gap: theme.spacing.s500,
    cursor: "pointer",
  },
  NavBarLink: {
    textDecoration: "none",
    color: "#3A3A3A",
  },
  NavText: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing.s500,
  },
  HeaderSection: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 2,
    width: "90%",
    maxWidth: "780px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    gap: "16px",
    padding: "0 20px",
    boxSizing: "border-box",
    margin: 0,
    "@media (max-width: 1200px)": {
      top: "52%",
      gap: "14px",
    },
    "@media (max-width: 768px)": {
      position: "relative",
      top: "auto",
      left: "auto",
      transform: "none",
      width: "100%",
      maxWidth: "600px",
      gap: "16px",
      padding: 0,
      margin: "0 auto",
    },
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    fontSize: "13px",
    fontWeight: 600,
    border: "1px solid rgba(0, 114, 196, 0.25)",
    marginBottom: "4px",
  },
  pulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    animation: "$pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  },
  headTitle: {
    color: theme.light.neutral.onSurface.title,
    maxWidth: "760px",
    width: "100%",
    textAlign: "center",
    fontSize: "2.25rem",
    fontWeight: 700,
    lineHeight: 1.25,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1.75rem",
    },
  },
  titleHighlight: {
    color: "#0072C4",
    display: "block",
    marginTop: "6px",
    fontSize: "24px",

  },
  headTitleDescription: {
    color: theme.light.neutral.onSurface.dark,
    maxWidth: "680px",
    width: "100%",
    textAlign: "center",
    fontSize: "1rem",
    lineHeight: 1.6,
  },
  heroBtnContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
    marginTop: "8px",
  },
  heroButtons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  heroPrimaryBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    padding: "10px 24px",
    borderRadius: "10px",
    fontWeight: 600,
    fontSize: "15px",
    boxShadow: "0 6px 18px rgba(0, 114, 196, 0.28)",
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 8px 22px rgba(0, 114, 196, 0.38)",
    },
  },
  heroSecondaryBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    color: "#0F172A",
    border: "1px solid rgba(0, 0, 0, 0.12)",
    padding: "10px 22px",
    borderRadius: "10px",
    fontWeight: 600,
    fontSize: "15px",
    backdropFilter: "blur(6px)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#FFFFFF",
      transform: "translateY(-1px)",
    },
  },
  heroSubtext: {
    fontSize: "12px",
    color: "#64748B",
    marginTop: "2px",
  },
  headbutton: {
    display: "flex",
    alignItems: "center",
    backgroundColor: theme.light.brand.surface.dark,
  },
  ActionLabel: {
    display: "flex",
    alignItems: "center",
  },
  HeadChrovnImg: {
    width: "24px",
    height: "24px",
  },

  /* Ticker Section */
  tickerSection: {
    width: "100%",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    borderBottom: "1px solid #E2E8F0",
    padding: "24px 20px",
    boxSizing: "border-box",
    textAlign: "center",
  },
  tickerInner: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  tickerTitle: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "16px",
  },
  tickerTools: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: "20px 36px",
  },
  tickerItem: {
    fontSize: "17px",
    fontWeight: 600,
    color: "#94A3B8",
    textDecoration: "line-through",
    textDecorationColor: "rgba(239, 68, 68, 0.6)",
    textDecorationThickness: "2px",
  },

  /* Dashboard Mockup Section */
  dashboardMockupContainer: {
    position: "relative",
    width: "100%",
    maxWidth: "1080px",
    margin: "48px auto 72px",
    padding: "0 24px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    "@media (max-width: 768px)": {
      margin: "28px auto 44px",
      padding: "0 16px",
    },
  },
  dashboardMockupGlow: {
    position: "absolute",
    top: "5%",
    left: "50%",
    transform: "translateX(-50%)",
    width: "90%",
    height: "85%",
    background:
      "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.18) 0%, rgba(138, 194, 255, 0.1) 45%, rgba(255, 255, 255, 0) 72%)",
    filter: "blur(60px)",
    pointerEvents: "none",
    zIndex: 0,
  },
  dashboardMockupFrame: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: "18px",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    boxShadow:
      "0 32px 85px -15px rgba(0, 52, 107, 0.22), 0 0 0 1px rgba(0, 114, 196, 0.08), 0 12px 28px -5px rgba(0, 0, 0, 0.06)",
    overflow: "hidden",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow:
        "0 40px 95px -15px rgba(0, 52, 107, 0.28), 0 0 0 1px rgba(0, 114, 196, 0.14), 0 16px 32px -5px rgba(0, 0, 0, 0.08)",
    },
    "@media (max-width: 768px)": {
      borderRadius: "12px",
    },
  },
  dashboardMockupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "12px 18px",
    backgroundColor: "#F8FAFC",
    borderBottom: "1px solid rgba(0, 114, 196, 0.1)",
    boxSizing: "border-box",
  },
  windowControls: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  windowDotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#FF5F56",
  },
  windowDotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#FFBD2E",
  },
  windowDotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#27C93F",
  },
  browserNavIcons: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#64748B",
    marginLeft: "4px",
    "@media (max-width: 680px)": {
      display: "none",
    },
  },
  windowUrlBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    backgroundColor: "#FFFFFF",
    border: "1px solid rgba(0, 114, 196, 0.16)",
    borderRadius: "9999px",
    fontSize: "12px",
    color: "#475569",
    maxWidth: "440px",
    flex: 1,
    justifyContent: "center",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
    "@media (max-width: 768px)": {
      fontSize: "11px",
      padding: "4px 10px",
    },
  },
  lockIcon: {
    color: "#16A34A",
    flexShrink: 0,
  },
  windowUrlText: {
    fontFamily: "monospace, sans-serif",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  windowLiveBadge: {
    fontSize: "10px",
    fontWeight: 700,
    color: "#0072C4",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    padding: "2px 6px",
    borderRadius: "4px",
    marginLeft: "4px",
    letterSpacing: "0.04em",
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  windowActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    "@media (max-width: 600px)": {
      display: "none",
    },
  },
  windowActionTag: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#0072C4",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    padding: "3px 10px",
    borderRadius: "6px",
  },
  dashboardMockupScreen: {
    position: "relative",
    width: "100%",
    lineHeight: 0,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  dashboardMockupImg: {
    width: "100%",
    height: "auto",
    display: "block",
    objectFit: "contain",
    imageRendering: "-webkit-optimize-contrast",
    transform: "translateZ(0)",
    backfaceVisibility: "hidden",
  },

  /* AI Dual-Engine Section */
  aiSection: {
    width: "100%",
    maxWidth: "1200px",
    margin: "80px auto 40px",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  aiHeader: {
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    marginBottom: "48px",
  },
  aiBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: "9999px",
    background: `linear-gradient(90deg, ${theme.light.info.surface.lighter} 0%, ${theme.light.brand.surface.lighter} 100%)`,
    border: `1px solid ${theme.light.neutral.border.light}`,
    fontSize: "13px",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.title,
  },
  aiBadgeDotPurple: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.medium,
  },
  aiBadgeDotCyan: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
  },
  aiTitle: {
    fontSize: "2.2rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.25,
    textAlign: "center",
    margin: 0,
    whiteSpace: "pre-line",
    "@media (max-width: 768px)": {
      fontSize: "1.7rem",
    },
  },
  aiDesc: {
    fontSize: "1.05rem",
    color: theme.light.neutral.onSurface.dark,
    maxWidth: "750px",
    lineHeight: 1.6,
    textAlign: "center",
    margin: 0,
  },
  aiFlowBlock: {
    marginBottom: "48px",
  },
  aiFlowHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "24px",
    fontSize: "1.25rem",
    fontWeight: 700,
  },
  purpleFlowText: {
    color: theme.light.info.onSurface.medium,
  },
  cyanFlowText: {
    color: theme.light.brand.onSurface.default,
  },
  flowBadgePurple: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: theme.light.info.surface.lighter,
    border: `1px solid ${theme.light.info.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    color: theme.light.info.onSurface.medium,
    fontSize: "14px",
  },
  flowBadgeCyan: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    color: theme.light.brand.onSurface.default,
    fontSize: "14px",
  },
  aiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "1fr",
    },
  },
  aiCardPurple: {
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: "16px",
    padding: "24px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderTop: `3px solid ${theme.light.info.surface.medium}`,
    boxShadow: "0 4px 20px -2px rgba(0, 0, 0, 0.04)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 12px 28px -4px rgba(129, 51, 241, 0.18)",
    },
  },
  aiCardCyan: {
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: "16px",
    padding: "24px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderTop: `3px solid ${theme.light.brand.surface.medium}`,
    boxShadow: "0 4px 20px -2px rgba(0, 0, 0, 0.04)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 12px 28px -4px rgba(0, 114, 196, 0.18)",
    },
  },
  aiCardIcon: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "10px",
  },
  aiCardIconPurple: {
    backgroundColor: theme.light.info.surface.lighter,
    color: theme.light.info.onSurface.medium,
    border: `1px solid ${theme.light.info.border.light}`,
  },
  aiCardIconCyan: {
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
  },
  aiCardTitle: {
    fontSize: "1.1rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: 0,
  },
  aiCardDesc: {
    fontSize: "0.9rem",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.6,
    margin: 0,
  },

  /* Automations Section */
  automationsSection: {
    width: "100%",
    maxWidth: "1000px",
    margin: "80px auto",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  autoHeader: {
    textAlign: "center",
    marginBottom: "40px",
  },
  autoTitle: {
    fontSize: "2.2rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "8px",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1.7rem",
    },
  },
  autoSubtitle: {
    fontSize: "1.05rem",
    color: "#64748B",
    margin: 0,
  },
  autoList: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  autoCard: {
    display: "flex",
    gap: "24px",
    padding: "28px",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 10px rgba(0,0,0,0.03)",
    transition: "all 0.2s ease",
    alignItems: "flex-start",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      transform: "translateY(-2px)",
      boxShadow: "0 8px 24px rgba(0,0,0,0.06)",
    },
    "@media (max-width: 640px)": {
      flexDirection: "column",
      gap: "12px",
    },
  },
  autoNum: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#0072C4",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    padding: "12px 16px",
    borderRadius: "12px",
    border: "1px solid rgba(0, 114, 196, 0.15)",
    flexShrink: 0,
  },
  autoCardContent: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  autoCardTitle: {
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  autoCardDesc: {
    fontSize: "0.95rem",
    color: "#475569",
    lineHeight: 1.65,
    margin: 0,
  },

  /* Mobile Apps Section */
  mobileSection: {
    width: "100%",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    borderBottom: "1px solid #E2E8F0",
    padding: "80px 24px",
    boxSizing: "border-box",
  },
  mobileInner: {
    maxWidth: "1100px",
    margin: "0 auto",
  },
  mobileHeader: {
    textAlign: "center",
    marginBottom: "48px",
  },
  mobileTitle: {
    fontSize: "2.2rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "8px",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1.7rem",
    },
  },
  mobileDesc: {
    fontSize: "1.05rem",
    color: "#64748B",
    maxWidth: "750px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
  mobileGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "32px",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
    },
  },
  mobileCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "20px",
    padding: "36px",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 4px 20px rgba(0,0,0,0.04)",
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "translateY(-4px)",
    },
  },
  mobileIcon: {
    width: "56px",
    height: "56px",
    borderRadius: "16px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "20px",
  },
  mobileTarget: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0072C4",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "6px",
  },
  mobileCardTitle: {
    fontSize: "1.4rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "12px",
    margin: 0,
  },
  mobileCardDesc: {
    fontSize: "0.95rem",
    color: "#475569",
    lineHeight: 1.6,
    flexGrow: 1,
    marginBottom: "24px",
  },
  mobileBadges: {
    display: "flex",
    gap: "10px",
  },
  mobileBadge: {
    backgroundColor: "#F1F5F9",
    color: "#334155",
    padding: "6px 16px",
    borderRadius: "9999px",
    fontSize: "12px",
    fontWeight: 600,
    border: "1px solid #CBD5E1",
  },

  /* Founder Control / Multi-Location Section */
  founderSection: {
    width: "100%",
    maxWidth: "1200px",
    margin: "80px auto",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  founderHeader: {
    textAlign: "center",
    marginBottom: "48px",
  },
  founderTitle: {
    fontSize: "2.2rem",
    fontWeight: 700,
    color: "#0F172A",
    lineHeight: 1.25,
    marginBottom: "8px",
    margin: 0,
    whiteSpace: "pre-line",
    "@media (max-width: 768px)": {
      fontSize: "1.7rem",
    },
  },
  founderDesc: {
    fontSize: "1.05rem",
    color: "#64748B",
    maxWidth: "650px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
  founderGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "40px",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
      gap: "28px",
    },
  },
  founderItem: {
    display: "flex",
    gap: "16px",
    alignItems: "flex-start",
  },
  founderIcon: {
    fontSize: "28px",
    flexShrink: 0,
    marginTop: "2px",
  },
  founderItemTitle: {
    fontSize: "1.15rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "6px",
    margin: 0,
  },
  founderItemDesc: {
    fontSize: "0.95rem",
    color: "#475569",
    lineHeight: 1.6,
    margin: 0,
  },

  /* Hesitation & Migration Section */
  migrationSection: {
    width: "100%",
    maxWidth: "1200px",
    margin: "80px auto 40px",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  migrationHeader: {
    textAlign: "center",
    marginBottom: "48px",
  },
  migrationTitle: {
    fontSize: "2.2rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "8px",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1.7rem",
    },
  },
  migrationDesc: {
    fontSize: "1.05rem",
    color: "#64748B",
    maxWidth: "750px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
  migrationGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 600px)": {
      gridTemplateColumns: "1fr",
    },
  },
  migrationCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.03)",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    transition: "all 0.2s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: "0 8px 24px rgba(0,0,0,0.06)",
    },
  },
  migrationCardTitle: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#0F172A",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    margin: 0,
  },
  migrationIconWrapper: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    flexShrink: 0,
  },
  greenIcon: {
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    color: "#16A34A",
    border: "1px solid rgba(34, 197, 94, 0.25)",
  },
  blueIcon: {
    backgroundColor: "rgba(59, 130, 246, 0.12)",
    color: "#2563EB",
    border: "1px solid rgba(59, 130, 246, 0.25)",
  },
  yellowIcon: {
    backgroundColor: "rgba(234, 179, 8, 0.12)",
    color: "#CA8A04",
    border: "1px solid rgba(234, 179, 8, 0.25)",
  },
  orangeIcon: {
    backgroundColor: "rgba(249, 115, 22, 0.12)",
    color: "#EA580C",
    border: "1px solid rgba(249, 115, 22, 0.25)",
  },
  purpleIcon: {
    backgroundColor: "rgba(168, 85, 247, 0.12)",
    color: "#9333EA",
    border: "1px solid rgba(168, 85, 247, 0.25)",
  },
  pinkIcon: {
    backgroundColor: "rgba(236, 72, 153, 0.12)",
    color: "#DB2777",
    border: "1px solid rgba(236, 72, 153, 0.25)",
  },
  migrationCardDesc: {
    fontSize: "0.875rem",
    color: "#475569",
    lineHeight: 1.6,
    margin: 0,
  },
  migrationCTA: {
    marginTop: "56px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
  },
  migrationBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "1.1rem",
    fontWeight: 700,
    padding: "16px 36px",
    borderRadius: "12px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 10px 25px -5px rgba(0, 114, 196, 0.4)",
    transition: "background-color 0.2s ease, transform 0.2s ease",
    "&:hover": {
      backgroundColor: "#005ea6",
      transform: "translateY(-1px)",
    },
  },
  migrationSubtext: {
    fontSize: "0.875rem",
    color: "#64748B",
  },

  BannerSection: {
    minHeight: "55vh",
    width: "100%",
    maxWidth: "1200px",
    margin: "auto",
    display: "flex",
    marginTop: "10%",
    backgroundColor: "#FFEE34",
    borderRadius: theme.spacing.s300,
    padding: `${theme.spacing.s1000} 100px`,
    alignItems: "flex-end",
    justifyContent: "space-between",
    boxSizing: "border-box",

    "@media (max-width: 1200px)": {
      maxWidth: "95%",
      padding: `${theme.spacing.s1000} 60px`,
    },

    "@media (max-width: 750px)": {
      flexWrap: "wrap",
      gap: "20px",
      maxWidth: "90%",
      padding: `${theme.spacing.s800} 32px`,
      justifyContent: "center",
    },

    "@media (max-width: 480px)": {
      padding: "32px 20px",
      borderRadius: "16px",
    },
  },
  BannerHeadSectionDiv: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "48px",
    "@media (max-width: 750px)": {
      width: "100%",
      alignItems: "center",
    },
  },
  BannerTitleSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: theme.spacing.s600,
  },
  BannerTitleDescription: {
    maxWidth: "400px",
    "@media (max-width: 750px)": {
      maxWidth: "100%",
    },
  },
  BannerButton: {
    backgroundColor: "transparent",
    color: theme.light.neutral.onSurface.title,
  },
  BannerLabel: {
    display: "flex",
    alignItems: "center",
  },
  BannerHeadSection: {
    display: "flex",
    gap: theme.spacing.s500,
    alignItems: "end",
    width: "100%",
    flexWrap: "wrap",
  },
  ChevronRightImg: {
    height: "24px",
    width: "24px",
  },
  suite: {
    borderRadius: theme.borderRadius.b200,
    border: `1px solid ${theme.light.neutral.onSurface.title}`,
    padding: `${theme.spacing.s0} ${theme.spacing.s200}`,
  },
  BannerTitle: {
    display: "flex",
    flexDirection: "column",
  },
  SideImageContainer: {
    "@media (max-width: 750px)": {
      width: "100%",
    },
  },
  SideImage: {
    width: "100%",
    maxWidth: "425px",
  },
  FeatureContainer: {
    minHeight: "80vh",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginTop: theme.spacing.s2000,
    gap: theme.spacing.s2000,
    boxSizing: "border-box",
    overflow: "hidden",
    position: "relative",
    zIndex: 10,
    backgroundColor: "#FFFFFF",
    "@media (max-width: 1000px)": {
      marginTop: "80px",
    },
    "@media (max-width: 768px)": {
      minHeight: "auto",
      marginTop: theme.spacing.s1000,
      gap: theme.spacing.s1000,
      padding: "0 24px",
    },
  },
  FeatureHeading: {
    display: "flex",
    flexDirection: "column",
    textAlign: "center",
    gap: theme.spacing.s600,
    maxWidth: "755px",
    width: "100%",
  },
  FeaturesFlex: {
    width: "100%",
    display: "flex",
    flexWrap: "wrap",
    gap: theme.spacing.s500,
    justifyContent: "center",
    marginTop: theme.spacing.s500,
    marginBottom: theme.spacing.s1600,
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      flexDirection: "column",
      alignItems: "center",
      gap: theme.spacing.s600,
      width: "100%",
    },
  },
  LeftImg: {
    width: "54px",
    height: "55px",
    position: "absolute",
    top: "-25px",
    left: "-22px",
    zIndex: -1,
    transform: "translateZ(-1px)",
    "@media (max-width: 768px)": {
      left: "-10px",
      top: "-20px",
    },
  },
  RightImg: {
    width: "54px",
    height: "55px",
    position: "absolute",
    bottom: "-18px",
    right: "-22px",
    zIndex: -1,
    transform: "translateZ(-1px)",
    "@media (max-width: 768px)": {
      right: "-10px",
      bottom: "-15px",
    },
  },
  FeaturesBlue: {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing.s600,
    padding: theme.spacing.s500,
    borderRadius: theme.borderRadius.b400,
    boxSizing: "border-box",
    width: "50%",
    backgroundColor: "#CEE2FF",
    position: "relative",
    overflow: "visible",
    boxShadow: theme.elevation.m,
    "@media (max-width: 768px)": {
      width: "100%",
      maxWidth: "100%",
    },
  },
  FeatureDiv: {
    width: "80%",
    maxWidth: "1200px",
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing.s2000,
    alignItems: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      width: "100%",
      maxWidth: "100%",
      gap: theme.spacing.s1000,
      padding: 0,
      margin: "0 auto",
    },
  },
  FeatureIcon: {
    width: "48px",
    height: "48px",
  },

  purple: {
    backgroundColor: "#EDDAF5",
    width: "40%",
    "@media (max-width: 768px)": {
      width: "100%",
    },
  },

  red: {
    backgroundColor: "#FFD0C7",
    width: "40%",
    "@media (max-width: 768px)": {
      width: "100%",
    },
  },

  green: {
    backgroundColor: "#ACE9AF",
    width: "50%",
    "@media (max-width: 768px)": {
      width: "100%",
    },
  },
  titleSubtext: {
    color: "#3C69D7",
  },
  purpleText: {
    color: "#B96ED5",
  },
  redText: {
    color: "#BF392F",
  },
  greenText: {
    color: "#00812B",
  },
  ValuesContainer: {
    width: "100%",
    aspectRatio: "1280 / 1323",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: "35vw",
    paddingBottom: "3vw",
    boxSizing: "border-box",
    marginTop: theme.spacing.s2000,
    backgroundImage: `url(${(principle_background as any)?.src || principle_background})`,
    backgroundSize: "100% auto",
    backgroundPosition: "top center",
    backgroundRepeat: "no-repeat",
  },
  ValuesDescription: {
    maxWidth: "930px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    marginTop: "24px",
    color: "#ffffff",
    padding: "0 24px",
  },
  StarLogo: {
    position: "absolute",
    top: "-13px",
    left: "-25px",
    width: "22px",
    height: "26px",
  },
  StarLogo2: {
    position: "absolute",
    width: "22px",
    height: "26px",
    bottom: "-12px",
    right: "-25px",
  },
  HeadSection: {
    position: "relative",
    color: "#ffffff",
    textAlign: "center",
  },
  CardContainer: {
    display: "flex",
    gap: theme.spacing.s1000,
    width: "100%",
    flexWrap: "wrap",
    marginTop: "50px",
    height: "auto",
    justifyContent: "center",
    alignItems: "center",
  },
  ValuesImgContainer: {
    display: "flex",
    width: "225px",
    height: "116px",
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing.s200,
    borderRadius: theme.borderRadius.b300,
    border: `1px solid ${theme.light.neutral.border.medium}`,
    backgroundColor: theme.light.negative.surface.medium,
  },
  valueBlue: {
    backgroundColor: theme.light.brand.surface.medium,
  },
  valuePurple: {
    backgroundColor: theme.light.info.surface.medium,
  },
  valueGreen: {
    backgroundColor: theme.light.positive.surface.medium,
  },
  valuesSubTitle: {
    color: theme.light.negative.surface.medium,
  },
  valueBluetitle: {
    color: theme.light.brand.surface.medium,
  },
  valuePurpletitle: {
    color: theme.light.info.surface.medium,
  },
  valueGreentitle: {
    color: theme.light.positive.surface.medium,
  },
  Card: {
    display: "flex",
    flexDirection: "column",
    width: "245px",
    height: "auto",
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing.s300,
    padding: theme.spacing.s200,
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: theme.borderRadius.b300,
  },
  ValuesTitle: {
    display: "flex",
    flexDirection: "column",
    padding: theme.spacing.s300,
    alignItems: "flex-start",
    gap: theme.spacing.s300,
  },
  ButtonDiv: {
    display: "flex",
    alignItems: "center",
  },
  ButtonImg: {
    width: "24px",
    height: "24px",
  },
  button: {
    boxShadow: theme.elevation.m,
    backgroundColor: theme.light.neutral.surface.light,
    marginTop: theme.spacing.s2000,
    minHeight: "32px",
    padding: theme.spacing.s300,
  },

  MainSubscribe: {
    minHeight: "50vh",
    padding: "80px 20px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      minHeight: "auto",
      padding: "60px 16px",
    },
  },
  SubscribeDiv: {
    display: "flex",
    flexDirection: "column",
    justifyItems: "center",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
    maxWidth: "500px",
    boxSizing: "border-box",
  },
  Description: {
    color: theme.light.neutral.onSurface.dark,
    textAlign: "center",
    maxWidth: "100%",
    boxSizing: "border-box",
    padding: "0 8px",
  },
  Subscribe: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing.s600,
    width: "100%",
    maxWidth: "500px",
    boxSizing: "border-box",
  },
  NewsLetterImg: {
    width: "184px",
    height: "120px",
    maxWidth: "100%",
    "& svg": {
      width: "100%",
      height: "100%",
      objectFit: "contain",
    },
    "@media (max-width: 480px)": {
      width: "140px",
      height: "90px",
    },
  },
  InputDiv: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.s300,
    marginTop: theme.spacing.s1000,
    width: "100%",
    maxWidth: "450px",
    boxSizing: "border-box",
    "@media (max-width: 480px)": {
      flexDirection: "column",
      gap: "12px",
      width: "100%",
      "& > button, & > div": {
        width: "100%",
      },
    },
  },
  InputText: {
    width: "100%",
    maxWidth: "320px",
    minWidth: "0",
    height: "40px",
    boxSizing: "border-box",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderRadius: theme.borderRadius.b100,
    padding: `0 ${theme.spacing.s300}`,
    outline: "none",
    fontSize: "14px",
    "@media (max-width: 480px)": {
      maxWidth: "100%",
    },
  },
  HasDropdown: {
    position: "relative",
    "&:hover $DropdownMenu": {
      display: "block",
    },
  },
  DropdownMenu: {
    display: "none",
    position: "absolute",
    top: theme.spacing.s800,
    left: 0,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    height: "300px",
    width: "1000px",
    listStyleType: "none",
    borderRadius: theme.borderRadius.b150,
    zIndex: "1000",
  },
  DropdownLink: {
    padding: `${theme.spacing.s300} ${theme.spacing.s500}`,
    textDecoration: "none",
    position: "absolute",
    top: -10,
    right: 0,
    color: "#333",
  },

  product: {
    top: 43,
  },

  chat: {
    top: 103,
  },
  DropDownLogo: {
    width: "48px",
    height: "48px",
  },
  ProductItem: {
    display: "flex",
    gap: theme.spacing.s500,
    alignItems: "center",
  },
  ProductHeadings: {
    display: "flex",
    flexDirection: "column",
  },
  LeftSide: {
    padding: theme.spacing.s300,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    gap: theme.spacing.s1200,
    width: "300px",
  },
  RightSide: {
    padding: theme.spacing.s300,
    display: "flex",
    flex: "1",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: "300px",
  },
  DropDownContainer: {
    display: "flex",
    alignItems: "flex-start",
    position: "relative",
  },
  NavLinks: {
    textDecoration: "none",
    color: theme.light.neutral.onSurface.medium,
  },
  SectionOne: {
    flex: 0.1,
    backgroundColor: theme.light.neutral.surface.light,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing.s300,
    borderRadius: theme.borderRadius.b200,
    padding: theme.spacing.s300,
  },
  SectionTwo: {
    flex: 0.4,
    padding: theme.spacing.s300,
  },
  SectionThree: {
    flex: 0.4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing.s300,
  },
  SectionTitle: {
    marginBottom: theme.spacing.s600,
  },
  Hover: {
    "&:hover": {
      color: theme.light.brand.onSurface.default,
      transform: "scale(1.02)",
      transition: "color 0.3s",
    },
  },

  LinksDiv: {
    display: "flex",
    gap: theme.spacing.s200,
    justifyContent: "space-between",
    position: "relative",
    "&:hover $chevronright": {
      opacity: 1,
    },
  },

  chevronright: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    opacity: 0,
    transition: "opacity 0.3s ease",
  },

  rightIcon: {
    "& path": {
      fill: theme.light.neutral.surface.lighter,
    },
  },

  heroFirstAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "2%",
    top: "13%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroFirstRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroSecondAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "11%",
    top: "50%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroFirstRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "2%",
    top: "85%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroThirdInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdInsideCon: {
    width: "75px",
    height: "75px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    position: "relative",
  },

  heroFirstRightAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: "17%",
    top: "18%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroFirstRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroFirstRightInsideCon: {
    width: "75px",
    height: "75px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    position: "relative",
  },

  heroSecondRightAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: "2%",
    top: "60%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroThirdRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdRightAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: "10%",
    top: "103%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroThirdRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdRightInsideCon: {
    width: "75px",
    height: "75px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    position: "relative",
  },

  StorageContainer: {
    width: "100%",
    backgroundColor: "#F0F5FC",
    padding: "20px 40px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    margin: "60px 0",
    "@media (max-width: 900px)": {
      padding: "50px 24px",
      margin: "40px 0",
    },
    "@media (max-width: 480px)": {
      padding: "36px 16px",
      margin: "24px 0",
    },
  },
  StorageWrapper: {
    width: "100%",
    maxWidth: "1200px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "48px",
    boxSizing: "border-box",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "36px",
    },
  },
  StorageContentLeft: {
    flex: "1.1",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "8px",
    maxWidth: "560px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 900px)": {
      maxWidth: "100%",
    },
  },
  StorageCategory: {
    color: "#0072C4",
    fontWeight: 600,
    fontSize: "1.125rem",
    marginBottom: "4px",
    letterSpacing: "0.2px",
  },
  StorageTitle: {
    color: "#222222",
    fontWeight: 700,
    fontSize: "2.4rem",
    lineHeight: 1.25,
    margin: 0,
    "@media (max-width: 900px)": {
      fontSize: "2rem",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.6rem",
      lineHeight: 1.3,
    },
  },
  StorageDescription: {
    color: "#4A5568",
    fontSize: "1.05rem",
    lineHeight: 1.6,
    marginTop: "8px",
    maxWidth: "500px",
    "@media (max-width: 900px)": {
      maxWidth: "100%",
    },
    "@media (max-width: 480px)": {
      fontSize: "0.95rem",
    },
  },
  StorageGraphicRight: {
    flex: "1",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    maxWidth: "560px",
    boxSizing: "border-box",
    "& svg": {
      width: "100%",
      height: "auto",
      maxHeight: "360px",
      display: "block",
    },
    "@media (max-width: 900px)": {
      maxWidth: "100%",
    },
  },
}));
