import { createUseStyles } from "react-jss";
import principle_background from "../../assets/icons/background.svg";
import { Theme } from "../../theme/themeType";

export const usestyles = createUseStyles((theme: Theme) => ({
  "@keyframes pulse": {
    "0%, 100%": {
      opacity: 1,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.4,
      transform: "scale(0.85)",
    },
  },
  mainSecCon: {
    width: "100%",
    height: "auto",
    aspectRatio: "1279 / 626",
    maxHeight: "92vh",
    minHeight: "540px",
    position: "relative",
    overflow: "hidden",
    margin: 0,
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(180deg, #CFDEF9 0%, #FFFFFF 100%)",
    "@media (max-width: 768px)": {
      width: "100%",
      height: "auto",
      aspectRatio: "unset",
      minHeight: "65vh",
      padding: "80px 20px 40px 20px",
      boxSizing: "border-box",
    },
  },
  heroSvgContainer: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "auto",
    zIndex: 1,
    "& svg": {
      width: "100%",
      height: "100%",
      objectFit: "contain",
    },
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  NavBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: "48px",
    width: "100%",
    padding: theme.spacing.s300,
  },
  NavBarLogo: {
    width: "200px",
    height: "auto",
  },
  NavBarLinks: {
    listStyle: "none",
    display: "flex",
    gap: theme.spacing.s500,
    cursor: "pointer",
  },
  NavBarLink: {
    textDecoration: "none",
    color: "#3A3A3A",
  },
  NavText: {
    display: "flex",
    alignItems: "center",
    gap: theme.spacing.s500,
  },
  HeaderSection: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 2,
    width: "90%",
    maxWidth: "780px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    gap: "16px",
    padding: "0 20px",
    boxSizing: "border-box",
    margin: 0,
    "@media (max-width: 1200px)": {
      top: "52%",
      gap: "14px",
    },
    "@media (max-width: 768px)": {
      position: "relative",
      top: "auto",
      left: "auto",
      transform: "none",
      width: "100%",
      maxWidth: "600px",
      gap: "16px",
      padding: 0,
      margin: "0 auto",
    },
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    fontSize: "13px",
    fontWeight: 600,
    border: "1px solid rgba(0, 114, 196, 0.25)",
    marginBottom: "4px",
  },
  pulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    animation: "$pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  },
  headTitle: {
    color: theme.light.neutral.onSurface.title,
    maxWidth: "760px",
    width: "100%",
    textAlign: "center",
    fontSize: "2.25rem",
    fontWeight: 700,
    lineHeight: 1.25,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1.75rem",
    },
  },
  titleHighlight: {
    color: "#0072C4",
    display: "block",
    marginTop: "6px",
    fontSize: "24px",

  },
  headTitleDescription: {
    color: theme.light.neutral.onSurface.dark,
    maxWidth: "680px",
    width: "100%",
    textAlign: "center",
    fontSize: "1rem",
    lineHeight: 1.6,
  },
  heroBtnContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
    marginTop: "8px",
  },
  heroButtons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  heroPrimaryBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    padding: "10px 24px",
    borderRadius: "10px",
    fontWeight: 600,
    fontSize: "15px",
    boxShadow: "0 6px 18px rgba(0, 114, 196, 0.28)",
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 8px 22px rgba(0, 114, 196, 0.38)",
    },
  },
  heroSecondaryBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    color: "#0F172A",
    border: "1px solid rgba(0, 0, 0, 0.12)",
    padding: "10px 22px",
    borderRadius: "10px",
    fontWeight: 600,
    fontSize: "15px",
    backdropFilter: "blur(6px)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#FFFFFF",
      transform: "translateY(-1px)",
    },
  },
  heroSubtext: {
    fontSize: "12px",
    color: "#64748B",
    marginTop: "2px",
  },
  headbutton: {
    display: "flex",
    alignItems: "center",
    backgroundColor: theme.light.brand.surface.dark,
  },
  ActionLabel: {
    display: "flex",
    alignItems: "center",
  },
  HeadChrovnImg: {
    width: "24px",
    height: "24px",
  },

  /* Ticker Section */
  tickerSection: {
    width: "100%",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    borderBottom: "1px solid #E2E8F0",
    padding: "24px 20px",
    boxSizing: "border-box",
    textAlign: "center",
  },
  tickerInner: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  tickerTitle: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "16px",
  },
  tickerTools: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: "20px 36px",
  },
  tickerItem: {
    fontSize: "17px",
    fontWeight: 600,
    color: "#94A3B8",
    textDecoration: "line-through",
    textDecorationColor: "rgba(239, 68, 68, 0.6)",
    textDecorationThickness: "2px",
  },

  /* Dashboard Mockup Section */
  dashboardMockupContainer: {
    position: "relative",
    width: "100%",
    maxWidth: "1080px",
    margin: "48px auto 72px",
    padding: "0 24px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    "@media (max-width: 768px)": {
      margin: "28px auto 44px",
      padding: "0 16px",
    },
  },
  dashboardMockupGlow: {
    position: "absolute",
    top: "5%",
    left: "50%",
    transform: "translateX(-50%)",
    width: "90%",
    height: "85%",
    background:
      "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.18) 0%, rgba(138, 194, 255, 0.1) 45%, rgba(255, 255, 255, 0) 72%)",
    filter: "blur(60px)",
    pointerEvents: "none",
    zIndex: 0,
  },
  dashboardMockupFrame: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: "18px",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    boxShadow:
      "0 32px 85px -15px rgba(0, 52, 107, 0.22), 0 0 0 1px rgba(0, 114, 196, 0.08), 0 12px 28px -5px rgba(0, 0, 0, 0.06)",
    overflow: "hidden",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow:
        "0 40px 95px -15px rgba(0, 52, 107, 0.28), 0 0 0 1px rgba(0, 114, 196, 0.14), 0 16px 32px -5px rgba(0, 0, 0, 0.08)",
    },
    "@media (max-width: 768px)": {
      borderRadius: "12px",
    },
  },
  dashboardMockupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "12px 18px",
    backgroundColor: "#F8FAFC",
    borderBottom: "1px solid rgba(0, 114, 196, 0.1)",
    boxSizing: "border-box",
  },
  windowControls: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  windowDotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#FF5F56",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.25)",
    },
  },
  windowDotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#FFBD2E",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.25)",
    },
  },
  windowDotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#27C93F",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.25)",
    },
  },
  browserNavIcons: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#64748B",
    marginLeft: "4px",
    cursor: "pointer",
    "& svg": {
      transition: "all 0.15s ease",
      "&:hover": {
        opacity: "1 !important",
        color: "#0072C4",
        transform: "scale(1.15)",
      },
    },
    "@media (max-width: 680px)": {
      display: "none",
    },
  },
  windowUrlBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    backgroundColor: "#FFFFFF",
    border: "1px solid rgba(0, 114, 196, 0.16)",
    borderRadius: "9999px",
    fontSize: "12px",
    color: "#475569",
    maxWidth: "440px",
    flex: 1,
    justifyContent: "center",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      borderColor: "rgba(0, 114, 196, 0.4)",
      boxShadow: "0 2px 8px rgba(0, 114, 196, 0.1)",
    },
    "@media (max-width: 768px)": {
      fontSize: "11px",
      padding: "4px 10px",
    },
  },
  lockIcon: {
    color: "#16A34A",
    flexShrink: 0,
  },
  windowUrlText: {
    fontFamily: "monospace, sans-serif",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  windowLiveBadge: {
    fontSize: "9px",
    fontWeight: 700,
    color: "#16A34A",
    backgroundColor: "rgba(22, 163, 74, 0.1)",
    padding: "2px 8px",
    borderRadius: "9999px",
    letterSpacing: "0.04em",
    flexShrink: 0,
  },
  windowActions: {
    display: "flex",
    alignItems: "center",
  },
  windowActionTag: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#0072C4",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    padding: "4px 10px",
    borderRadius: "6px",
    border: "1px solid rgba(0, 114, 196, 0.15)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "rgba(0, 114, 196, 0.15)",
      transform: "scale(1.03)",
    },
  },
  dashboardMockupScreen: {
    position: "relative",
    width: "100%",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  dashboardMockupImg: {
    width: "100%",
    height: "auto",
    display: "block",
    objectFit: "contain",
    imageRendering: "-webkit-optimize-contrast",
    transform: "translateZ(0)",
    backfaceVisibility: "hidden",
  },

  /* AI Dual-Engine Section */
  aiSection: {
    width: "100%",
    maxWidth: "1200px",
    margin: "80px auto 40px",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  aiHeader: {
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    marginBottom: "48px",
  },
  aiBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: "9999px",
    background: `linear-gradient(90deg, ${theme.light.info.surface.lighter} 0%, ${theme.light.brand.surface.lighter} 100%)`,
    border: `1px solid ${theme.light.neutral.border.light}`,
    fontSize: "13px",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.title,
  },
  aiBadgeDotPurple: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.medium,
  },
  aiBadgeDotCyan: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
  },
  aiTitle: {
    fontSize: "2.5rem",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.2,
    textAlign: "center",
    margin: 0,
    whiteSpace: "pre-line",
    "@media (max-width: 768px)": {
      fontSize: "1.875rem",
    },
  },
  aiDesc: {
    fontSize: "1.125rem",
    color: theme.light.neutral.onSurface.medium,
    maxWidth: "820px",
    lineHeight: 1.7,
    textAlign: "center",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  aiFlowBlock: {
    marginBottom: "48px",
  },
  aiFlowHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "24px",
    fontSize: "1.25rem",
    fontWeight: 700,
  },
  purpleFlowText: {
    color: theme.light.info.onSurface.medium,
  },
  cyanFlowText: {
    color: theme.light.brand.onSurface.default,
  },
  flowBadgePurple: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: theme.light.info.surface.lighter,
    border: `1px solid ${theme.light.info.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    color: theme.light.info.onSurface.medium,
    fontSize: "14px",
  },
  flowBadgeCyan: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    color: theme.light.brand.onSurface.default,
    fontSize: "14px",
  },
  aiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "1fr",
    },
  },
  aiCardPurple: {
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: "16px",
    padding: "24px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderTop: `3px solid ${theme.light.info.surface.medium}`,
    boxShadow: "0 4px 20px -2px rgba(0, 0, 0, 0.04)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 12px 28px -4px rgba(129, 51, 241, 0.18)",
    },
  },
  aiCardCyan: {
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: "16px",
    padding: "24px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderTop: `3px solid ${theme.light.brand.surface.medium}`,
    boxShadow: "0 4px 20px -2px rgba(0, 0, 0, 0.04)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 12px 28px -4px rgba(0, 114, 196, 0.18)",
    },
  },
  aiCardIcon: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "10px",
  },
  aiCardIconPurple: {
    backgroundColor: theme.light.info.surface.lighter,
    color: theme.light.info.onSurface.medium,
    border: `1px solid ${theme.light.info.border.light}`,
  },
  aiCardIconCyan: {
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
  },
  aiCardTitle: {
    fontSize: "1.375rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 12px 0",
  },
  aiCardDesc: {
    fontSize: "0.9375rem",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.7,
    margin: 0,
  },

  /* Workflow / Pipeline Section */
  workflowSection: {
    position: "relative",
    width: "100%",
    padding: "96px 0",
    overflow: "hidden",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    "@media (max-width: 768px)": {
      padding: "60px 0",
    },
  },
  workflowGridPattern: {
    position: "absolute",
    inset: 0,
    backgroundSize: "32px 32px",
    backgroundImage:
      "linear-gradient(to right, rgba(148, 163, 184, 0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(148, 163, 184, 0.08) 1px, transparent 1px)",
    pointerEvents: "none",
    opacity: 0.8,
  },
  workflowGlow: {
    position: "absolute",
    top: "25%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "700px",
    height: "400px",
    background: `linear-gradient(135deg, rgba(0, 114, 196, 0.15) 0%, ${theme.light.brand.surface.lighter}40 50%, rgba(99, 102, 241, 0.1) 100%)`,
    filter: "blur(80px)",
    zIndex: -1,
    pointerEvents: "none",
    borderRadius: "50%",
  },
  workflowInner: {
    position: "relative",
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  workflowHeader: {
    textAlign: "center",
    maxWidth: "740px",
    margin: "0 auto 64px",
  },
  workflowBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.onSurface.default,
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "16px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  workflowBadgeDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    animation: "$pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  },
  workflowTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.12,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  workflowSubtitle: {
    marginTop: "16px",
    fontSize: "1.125rem",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.6,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  workflowGrid: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
  },
  pipelineColumn: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    width: "100%",
    maxWidth: "1000px",
  },
  pipelineLine: {
    position: "absolute",
    left: "59px",
    top: "48px",
    bottom: "48px",
    width: "2px",
    zIndex: 0,
    background: `linear-gradient(to bottom, ${theme.light.brand.surface.medium}, ${theme.light.brand.surface.dark}, rgba(99, 102, 241, 0.2))`,
    pointerEvents: "none",
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  hudColumn: {
    display: "none",
  },


  /* Mobile Experience Section */
  mobileSection: {
    width: "100%",
    padding: "96px 0",
    background: "linear-gradient(180deg, #FFFFFF 0%, #F8FAFC 50%, #FFFFFF 100%)",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "60px 0",
    },
  },
  mobileDotPattern: {
    position: "absolute",
    inset: 0,
    backgroundImage: `radial-gradient(${theme.light.brand.surface.medium}20 1px, transparent 1px)`,
    backgroundSize: "20px 20px",
    opacity: 0.6,
    pointerEvents: "none",
  },
  mobileInner: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 24px",
    boxSizing: "border-box",
    position: "relative",
  },
  mobileHeader: {
    textAlign: "center",
    maxWidth: "740px",
    margin: "0 auto 64px",
  },
  mobileBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.onSurface.default,
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "16px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  mobileBadgeIcon: {
    width: "14px",
    height: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.12,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  mobileDesc: {
    marginTop: "16px",
    fontSize: "1.125rem",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.7,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  mobileGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "40px",
    alignItems: "stretch",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gap: "32px",
    },
  },
  personaCard: {
    position: "relative",
    backgroundColor: "#FFFFFF",
    borderRadius: "24px",
    padding: "32px 36px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: "0 4px 20px -2px rgba(15, 23, 42, 0.05), 0 2px 6px -1px rgba(15, 23, 42, 0.02)",
    transition: "all 0.3s ease",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    overflow: "hidden",
    "&:hover": {
      boxShadow: "0 20px 35px -5px rgba(0, 114, 196, 0.12), 0 10px 10px -5px rgba(15, 23, 42, 0.04)",
      "& .phone-body": {
        animation: "dotToPhoneGrow 0.5s cubic-bezier(0.34, 1.45, 0.64, 1) forwards",
      },
      "& .trending-group": {
        animation: "growLeftRightChart 0.5s cubic-bezier(0.2, 0.9, 0.4, 1) forwards",
      },
    },
    "@media (max-width: 768px)": {
      padding: "24px",
      borderRadius: "20px",
    },
  },
  personaGlow: {
    position: "absolute",
    right: "-64px",
    top: "-64px",
    width: "256px",
    height: "256px",
    borderRadius: "50%",
    filter: "blur(60px)",
    pointerEvents: "none",
  },
  personaGlowSky: {
    background: `${theme.light.brand.surface.light}40`,
  },
  personaGlowBlue: {
    background: `${theme.light.brand.surface.light}40`,
  },
  roleBadgeRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "20px",
  },
  roleIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: `1px solid ${theme.light.brand.border.light}`,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
  },
  roleIconSky: {
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
  },
  roleIconBlue: {
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.surface.dark,
  },
  roleLabel: {
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    padding: "6px 14px",
    borderRadius: "8px",
    border: `1px solid ${theme.light.brand.border.light}`,
  },
  roleLabelSky: {
    color: theme.light.brand.onSurface.default,
    backgroundColor: theme.light.brand.surface.lighter,
  },
  roleLabelBlue: {
    color: theme.light.brand.surface.dark,
    backgroundColor: theme.light.brand.surface.lighter,
  },
  personaTitle: {
    fontSize: "1.5rem",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.3,
    marginBottom: "12px",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1.3rem",
    },
  },
  personaDesc: {
    fontSize: "15px",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.7,
    marginBottom: "28px",
  },
  phoneMockupContainer: {
    display: "flex",
    justifyContent: "center",
    margin: "24px 0",
  },
  downloadFooter: {
    paddingTop: "20px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  downloadLabel: {
    fontSize: "12px",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.dark,
  },
  downloadBtns: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "10px",
  },
  iosBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 14px",
    borderRadius: "12px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    fontSize: "12px",
    fontWeight: 600,
    border: "none",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    "&:hover": {
      backgroundColor: "#1E293B",
    },
  },
  androidBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 14px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    fontSize: "12px",
    fontWeight: 600,
    border: `1px solid ${theme.light.neutral.border.light}`,
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      borderColor: theme.light.neutral.border.medium,
    },
  },

  /* Founder Control / Multi-Location Section */
  founderSection: {
    width: "100%",
    maxWidth: "1200px",
    margin: "80px auto",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  founderHeader: {
    textAlign: "center",
    marginBottom: "48px",
  },
  founderTitle: {
    fontSize: "2.5rem",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.2,
    margin: 0,
    whiteSpace: "pre-line",
    "@media (max-width: 768px)": {
      fontSize: "1.875rem",
    },
  },
  founderDesc: {
    fontSize: "1.125rem",
    color: theme.light.neutral.onSurface.medium,
    maxWidth: "820px",
    margin: "0 auto",
    lineHeight: 1.7,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  founderGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "40px",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
      gap: "28px",
    },
  },
  founderItem: {
    display: "flex",
    gap: "16px",
    alignItems: "flex-start",
  },
  founderIcon: {
    fontSize: "28px",
    flexShrink: 0,
    marginTop: "2px",
  },
  founderItemTitle: {
    fontSize: "1.375rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 12px 0",
  },
  founderItemDesc: {
    fontSize: "0.9375rem",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.7,
    margin: 0,
  },

  /* Migration / Trust Section — Dark Theme */
  migrationSection: {
    width: "100%",
    padding: "96px 0",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    borderTop: "1px solid #1E293B",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "60px 0",
    },
  },
  migrationGlowTop: {
    position: "absolute",
    top: "-160px",
    left: "33%",
    width: "600px",
    height: "600px",
    background: "rgba(14, 165, 233, 0.08)",
    borderRadius: "50%",
    filter: "blur(80px)",
    pointerEvents: "none",
  },
  migrationGlowBottom: {
    position: "absolute",
    bottom: "-160px",
    right: "25%",
    width: "600px",
    height: "600px",
    background: "rgba(99, 102, 241, 0.08)",
    borderRadius: "50%",
    filter: "blur(80px)",
    pointerEvents: "none",
  },
  migrationInner: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 24px",
    boxSizing: "border-box",
    position: "relative",
  },
  migrationHeader: {
    textAlign: "center",
    maxWidth: "740px",
    margin: "0 auto 64px",
  },
  migrationBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(30, 41, 59, 0.8)",
    border: "1px solid #334155",
    color: "#38BDF8",
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "16px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
  },
  migrationBadgeIcon: {
    width: "14px",
    height: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  migrationTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    color: "#FFFFFF",
    lineHeight: 1.12,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  migrationDesc: {
    marginTop: "16px",
    fontSize: "1.125rem",
    color: "#94A3B8",
    lineHeight: 1.6,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  migrationGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    marginBottom: "64px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 600px)": {
      gridTemplateColumns: "1fr",
    },
  },
  migrationCard: {
    backgroundColor: "rgba(30, 41, 59, 0.6)",
    backdropFilter: "blur(8px)",
    borderRadius: "24px",
    padding: "32px",
    border: "1px solid rgba(51, 65, 85, 0.8)",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(30, 41, 59, 0.9)",
      transform: "translateY(-4px)",
    },
  },
  migrationCardGreen: {
    "&:hover": { borderColor: "rgba(16, 185, 129, 0.5)" },
  },
  migrationCardSky: {
    "&:hover": { borderColor: "rgba(14, 165, 233, 0.5)" },
  },
  migrationCardAmber: {
    "&:hover": { borderColor: "rgba(245, 158, 11, 0.5)" },
  },
  migrationCardOrange: {
    "&:hover": { borderColor: "rgba(249, 115, 22, 0.5)" },
  },
  migrationCardPurple: {
    "&:hover": { borderColor: "rgba(168, 85, 247, 0.5)" },
  },
  migrationCardRose: {
    "&:hover": { borderColor: "rgba(244, 63, 94, 0.5)" },
  },
  migrationCardIcon: {
    width: "48px",
    height: "48px",
    borderRadius: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "20px",
    transition: "transform 0.2s ease",
    "$migrationCard:hover &": {
      transform: "scale(1.05)",
    },
  },
  migrationIconGreen: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "#34D399",
    border: "1px solid rgba(16, 185, 129, 0.2)",
  },
  migrationIconSky: {
    backgroundColor: "rgba(14, 165, 233, 0.1)",
    color: "#38BDF8",
    border: "1px solid rgba(14, 165, 233, 0.2)",
  },
  migrationIconAmber: {
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    color: "#FBBF24",
    border: "1px solid rgba(245, 158, 11, 0.2)",
  },
  migrationIconOrange: {
    backgroundColor: "rgba(249, 115, 22, 0.1)",
    color: "#FB923C",
    border: "1px solid rgba(249, 115, 22, 0.2)",
  },
  migrationIconPurple: {
    backgroundColor: "rgba(168, 85, 247, 0.1)",
    color: "#C084FC",
    border: "1px solid rgba(168, 85, 247, 0.2)",
  },
  migrationIconRose: {
    backgroundColor: "rgba(244, 63, 94, 0.1)",
    color: "#FB7185",
    border: "1px solid rgba(244, 63, 94, 0.2)",
  },
  migrationCardTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#FFFFFF",
    marginBottom: "12px",
    margin: 0,
  },
  migrationCardDesc: {
    fontSize: "0.875rem",
    color: "#94A3B8",
    lineHeight: 1.7,
    margin: 0,
  },
  /* Floating CTA Card */
  migrationCTA: {
    position: "relative",
    maxWidth: "900px",
    margin: "0 auto",
    borderRadius: "24px",
    padding: "56px 40px",
    background: "linear-gradient(180deg, #1E293B 0%, #0F172A 100%)",
    border: "1px solid #334155",
    boxShadow: "0 25px 60px -15px rgba(15, 23, 42, 0.5)",
    textAlign: "center",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "40px 24px",
      borderRadius: "20px",
    },
  },
  ctaGlowOverlay: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(90deg, rgba(14, 165, 233, 0.08) 0%, rgba(59, 130, 246, 0.08) 50%, rgba(99, 102, 241, 0.08) 100%)",
    pointerEvents: "none",
  },
  ctaContent: {
    position: "relative",
    zIndex: 1,
  },
  migrationBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px 40px",
    fontSize: "1rem",
    fontWeight: 700,
    color: "#FFFFFF",
    background: `linear-gradient(90deg, ${theme.light.brand.surface.medium} 0%, ${theme.light.brand.surface.dark} 50%, #4F46E5 100%)`,
    borderRadius: "16px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 10px 25px -5px rgba(14, 165, 233, 0.3)",
    transition: "all 0.2s ease",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 15px 35px -5px rgba(14, 165, 233, 0.45)",
    },
    "@media (max-width: 768px)": {
      padding: "14px 32px",
      fontSize: "0.9375rem",
    },
  },
  migrationSubtext: {
    marginTop: "16px",
    fontSize: "0.875rem",
    color: "#64748B",
    fontWeight: 500,
    letterSpacing: "0.01em",
  },

  BannerSection: {
    minHeight: "55vh",
    width: "100%",
    maxWidth: "1200px",
    margin: "auto",
    display: "flex",
    marginTop: "10%",
    backgroundColor: "#FFEE34",
    borderRadius: theme.spacing.s300,
    padding: `${theme.spacing.s1000} 100px`,
    alignItems: "flex-end",
    justifyContent: "space-between",
    boxSizing: "border-box",

    "@media (max-width: 1200px)": {
      maxWidth: "95%",
      padding: `${theme.spacing.s1000} 60px`,
    },

    "@media (max-width: 750px)": {
      flexWrap: "wrap",
      gap: "20px",
      maxWidth: "90%",
      padding: `${theme.spacing.s800} 32px`,
      justifyContent: "center",
    },

    "@media (max-width: 480px)": {
      padding: "32px 20px",
      borderRadius: "16px",
    },
  },
  BannerHeadSectionDiv: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "48px",
    "@media (max-width: 750px)": {
      width: "100%",
      alignItems: "center",
    },
  },
  BannerTitleSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: theme.spacing.s600,
  },
  BannerTitleDescription: {
    maxWidth: "400px",
    "@media (max-width: 750px)": {
      maxWidth: "100%",
    },
  },
  BannerButton: {
    backgroundColor: "transparent",
    color: theme.light.neutral.onSurface.title,
  },
  BannerLabel: {
    display: "flex",
    alignItems: "center",
  },
  BannerHeadSection: {
    display: "flex",
    gap: theme.spacing.s500,
    alignItems: "end",
    width: "100%",
    flexWrap: "wrap",
  },
  ChevronRightImg: {
    height: "24px",
    width: "24px",
  },
  suite: {
    borderRadius: theme.borderRadius.b200,
    border: `1px solid ${theme.light.neutral.onSurface.title}`,
    padding: `${theme.spacing.s0} ${theme.spacing.s200}`,
  },
  BannerTitle: {
    display: "flex",
    flexDirection: "column",
  },
  SideImageContainer: {
    "@media (max-width: 750px)": {
      width: "100%",
    },
  },
  SideImage: {
    width: "100%",
    maxWidth: "425px",
  },
  /* Multi-Location Bento Grid Section */
  bentoSection: {
    width: "100%",
    padding: "96px 0",
    backgroundColor: "#FFFFFF",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    "@media (max-width: 768px)": {
      padding: "60px 0",
    },
  },
  bentoInner: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 24px",
    boxSizing: "border-box",
  },
  bentoHeader: {
    textAlign: "center",
    maxWidth: "740px",
    margin: "0 auto 64px",
  },
  bentoBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(99, 102, 241, 0.08)",
    border: "1px solid rgba(99, 102, 241, 0.25)",
    color: "#4F46E5",
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "16px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  bentoBadgeIcon: {
    width: "14px",
    height: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  bentoTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    letterSpacing: "-0.02em",
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1.12,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  bentoSubtitle: {
    marginTop: "16px",
    fontSize: "1.125rem",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.6,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  bentoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "32px",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
      gap: "24px",
    },
  },
  /* Hidden old feature stubs (referenced in old commented-out code) */
  FeatureContainer: { display: "none" },
  FeatureDiv: { display: "none" },
  FeatureHeading: { display: "none" },
  FeaturesFlex: { display: "none" },
  FeaturesBlue: { display: "none" },
  FeatureIcon: { display: "none" },
  LeftImg: { display: "none" },
  RightImg: { display: "none" },
  purple: { display: "none" },
  red: { display: "none" },
  green: { display: "none" },
  titleSubtext: { display: "none" },
  purpleText: { display: "none" },
  redText: { display: "none" },
  greenText: { display: "none" },
  ValuesContainer: {
    width: "100%",
    aspectRatio: "1280 / 1323",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: "35vw",
    paddingBottom: "3vw",
    boxSizing: "border-box",
    marginTop: theme.spacing.s2000,
    backgroundImage: `url(${(principle_background as any)?.src || principle_background})`,
    backgroundSize: "100% auto",
    backgroundPosition: "top center",
    backgroundRepeat: "no-repeat",
  },
  ValuesDescription: {
    maxWidth: "930px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    marginTop: "24px",
    color: "#ffffff",
    padding: "0 24px",
  },
  StarLogo: {
    position: "absolute",
    top: "-13px",
    left: "-25px",
    width: "22px",
    height: "26px",
  },
  StarLogo2: {
    position: "absolute",
    width: "22px",
    height: "26px",
    bottom: "-12px",
    right: "-25px",
  },
  HeadSection: {
    position: "relative",
    color: "#ffffff",
    textAlign: "center",
  },
  CardContainer: {
    display: "flex",
    gap: theme.spacing.s1000,
    width: "100%",
    flexWrap: "wrap",
    marginTop: "50px",
    height: "auto",
    justifyContent: "center",
    alignItems: "center",
  },
  ValuesImgContainer: {
    display: "flex",
    width: "225px",
    height: "116px",
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing.s200,
    borderRadius: theme.borderRadius.b300,
    border: `1px solid ${theme.light.neutral.border.medium}`,
    backgroundColor: theme.light.negative.surface.medium,
  },
  valueBlue: {
    backgroundColor: theme.light.brand.surface.medium,
  },
  valuePurple: {
    backgroundColor: theme.light.info.surface.medium,
  },
  valueGreen: {
    backgroundColor: theme.light.positive.surface.medium,
  },
  valuesSubTitle: {
    color: theme.light.negative.surface.medium,
  },
  valueBluetitle: {
    color: theme.light.brand.surface.medium,
  },
  valuePurpletitle: {
    color: theme.light.info.surface.medium,
  },
  valueGreentitle: {
    color: theme.light.positive.surface.medium,
  },
  Card: {
    display: "flex",
    flexDirection: "column",
    width: "245px",
    height: "auto",
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing.s300,
    padding: theme.spacing.s200,
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: theme.borderRadius.b300,
  },
  ValuesTitle: {
    display: "flex",
    flexDirection: "column",
    padding: theme.spacing.s300,
    alignItems: "flex-start",
    gap: theme.spacing.s300,
  },
  ButtonDiv: {
    display: "flex",
    alignItems: "center",
  },
  ButtonImg: {
    width: "24px",
    height: "24px",
  },
  button: {
    boxShadow: theme.elevation.m,
    backgroundColor: theme.light.neutral.surface.light,
    marginTop: theme.spacing.s2000,
    minHeight: "32px",
    padding: theme.spacing.s300,
  },

  MainSubscribe: {
    minHeight: "50vh",
    padding: "80px 20px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      minHeight: "auto",
      padding: "60px 16px",
    },
  },
  SubscribeDiv: {
    display: "flex",
    flexDirection: "column",
    justifyItems: "center",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
    maxWidth: "500px",
    boxSizing: "border-box",
  },
  Description: {
    color: theme.light.neutral.onSurface.dark,
    textAlign: "center",
    maxWidth: "100%",
    boxSizing: "border-box",
    padding: "0 8px",
  },
  Subscribe: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing.s600,
    width: "100%",
    maxWidth: "500px",
    boxSizing: "border-box",
  },
  NewsLetterImg: {
    width: "184px",
    height: "120px",
    maxWidth: "100%",
    "& svg": {
      width: "100%",
      height: "100%",
      objectFit: "contain",
    },
    "@media (max-width: 480px)": {
      width: "140px",
      height: "90px",
    },
  },
  InputDiv: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.s300,
    marginTop: theme.spacing.s1000,
    width: "100%",
    maxWidth: "450px",
    boxSizing: "border-box",
    "@media (max-width: 480px)": {
      flexDirection: "column",
      gap: "12px",
      width: "100%",
      "& > button, & > div": {
        width: "100%",
      },
    },
  },
  InputText: {
    width: "100%",
    maxWidth: "320px",
    minWidth: "0",
    height: "40px",
    boxSizing: "border-box",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderRadius: theme.borderRadius.b100,
    padding: `0 ${theme.spacing.s300}`,
    outline: "none",
    fontSize: "14px",
    "@media (max-width: 480px)": {
      maxWidth: "100%",
    },
  },
  HasDropdown: {
    position: "relative",
    "&:hover $DropdownMenu": {
      display: "block",
    },
  },
  DropdownMenu: {
    display: "none",
    position: "absolute",
    top: theme.spacing.s800,
    left: 0,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    height: "300px",
    width: "1000px",
    listStyleType: "none",
    borderRadius: theme.borderRadius.b150,
    zIndex: "1000",
  },
  DropdownLink: {
    padding: `${theme.spacing.s300} ${theme.spacing.s500}`,
    textDecoration: "none",
    position: "absolute",
    top: -10,
    right: 0,
    color: "#333",
  },

  product: {
    top: 43,
  },

  chat: {
    top: 103,
  },
  DropDownLogo: {
    width: "48px",
    height: "48px",
  },
  ProductItem: {
    display: "flex",
    gap: theme.spacing.s500,
    alignItems: "center",
  },
  ProductHeadings: {
    display: "flex",
    flexDirection: "column",
  },
  LeftSide: {
    padding: theme.spacing.s300,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    gap: theme.spacing.s1200,
    width: "300px",
  },
  RightSide: {
    padding: theme.spacing.s300,
    display: "flex",
    flex: "1",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: "300px",
  },
  DropDownContainer: {
    display: "flex",
    alignItems: "flex-start",
    position: "relative",
  },
  NavLinks: {
    textDecoration: "none",
    color: theme.light.neutral.onSurface.medium,
  },
  SectionOne: {
    flex: 0.1,
    backgroundColor: theme.light.neutral.surface.light,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing.s300,
    borderRadius: theme.borderRadius.b200,
    padding: theme.spacing.s300,
  },
  SectionTwo: {
    flex: 0.4,
    padding: theme.spacing.s300,
  },
  SectionThree: {
    flex: 0.4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing.s300,
  },
  SectionTitle: {
    marginBottom: theme.spacing.s600,
  },
  Hover: {
    "&:hover": {
      color: theme.light.brand.onSurface.default,
      transform: "scale(1.02)",
      transition: "color 0.3s",
    },
  },

  LinksDiv: {
    display: "flex",
    gap: theme.spacing.s200,
    justifyContent: "space-between",
    position: "relative",
    "&:hover $chevronright": {
      opacity: 1,
    },
  },

  chevronright: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    opacity: 0,
    transition: "opacity 0.3s ease",
  },

  rightIcon: {
    "& path": {
      fill: theme.light.neutral.surface.lighter,
    },
  },

  heroFirstAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "2%",
    top: "13%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroFirstRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroSecondAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "11%",
    top: "50%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroFirstRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "2%",
    top: "85%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroThirdInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdInsideCon: {
    width: "75px",
    height: "75px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    position: "relative",
  },

  heroFirstRightAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: "17%",
    top: "18%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroFirstRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroFirstRightInsideCon: {
    width: "75px",
    height: "75px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    position: "relative",
  },

  heroSecondRightAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: "2%",
    top: "60%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroThirdRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdRightAvatarCon: {
    width: "112px",
    height: "112px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: "10%",
    top: "103%",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "rgba(245, 247, 248, 0.8)",
      boxShadow: theme.elevation.m,
    },
    "&:hover $heroThirdRightInsideCon": {
      backgroundColor: theme.light.brand.surface.lighter,
    },
  },

  heroThirdRightInsideCon: {
    width: "75px",
    height: "75px",
    borderRadius: "50%",
    backgroundColor: "transparent",
    position: "relative",
  },

  StorageContainer: {
    width: "100%",
    backgroundColor: "#F0F5FC",
    padding: "20px 40px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    margin: "60px 0",
    "@media (max-width: 900px)": {
      padding: "50px 24px",
      margin: "40px 0",
    },
    "@media (max-width: 480px)": {
      padding: "36px 16px",
      margin: "24px 0",
    },
  },
  StorageWrapper: {
    width: "100%",
    maxWidth: "1200px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "48px",
    boxSizing: "border-box",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "36px",
    },
  },
  StorageContentLeft: {
    flex: "1.1",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "8px",
    maxWidth: "560px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 900px)": {
      maxWidth: "100%",
    },
  },
  StorageCategory: {
    color: "#0072C4",
    fontWeight: 600,
    fontSize: "1.125rem",
    marginBottom: "4px",
    letterSpacing: "0.2px",
  },
  StorageTitle: {
    color: "#222222",
    fontWeight: 700,
    fontSize: "2.4rem",
    lineHeight: 1.25,
    margin: 0,
    "@media (max-width: 900px)": {
      fontSize: "2rem",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.6rem",
      lineHeight: 1.3,
    },
  },
  StorageDescription: {
    color: "#4A5568",
    fontSize: "1.05rem",
    lineHeight: 1.6,
    marginTop: "8px",
    maxWidth: "500px",
    "@media (max-width: 900px)": {
      maxWidth: "100%",
    },
    "@media (max-width: 480px)": {
      fontSize: "0.95rem",
    },
  },
  StorageGraphicRight: {
    flex: "1",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    maxWidth: "560px",
    boxSizing: "border-box",
    "& svg": {
      width: "100%",
      height: "auto",
      maxHeight: "360px",
      display: "block",
    },
    "@media (max-width: 900px)": {
      maxWidth: "100%",
    },
  },
}));
