import { createUseStyles } from 'react-jss';
import { Theme } from '../../theme/themeType';

export const useStyles = createUseStyles((theme: Theme) => ({
  mockupWrapper: {
    position: 'relative',
    zIndex: 2,
    marginTop: '24px',
    width: '100%',
  },
  mockupContainer: {
    width: '100%',
    maxWidth: '1140px',
    margin: '0 auto',
    borderRadius: '18px',
    border: '1px solid #E2E8F0',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    boxShadow: '0 24px 70px -12px rgba(15, 23, 42, 0.14), 0 0 0 1px rgba(0, 114, 196, 0.06)',
    position: 'relative',
    zIndex: 1,
    textAlign: 'left',
    boxSizing: 'border-box',
  },
  mockupContainerEmbedded: {
    width: '100%',
    margin: '0',
    borderRadius: '0',
    border: 'none',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    boxShadow: 'none',
    position: 'relative',
    zIndex: 1,
    textAlign: 'left',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: '720px',
  },

  // Chrome Title Bar
  mockupHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    backgroundColor: '#F8FAFC',
    borderBottom: '1px solid #E2E8F0',
    gap: '10px',
    flexWrap: 'wrap',
  },
  windowDots: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  dotRed: {
    width: '11px',
    height: '11px',
    borderRadius: '50%',
    backgroundColor: '#EF4444',
  },
  dotYellow: {
    width: '11px',
    height: '11px',
    borderRadius: '50%',
    backgroundColor: '#F59E0B',
  },
  dotGreen: {
    width: '11px',
    height: '11px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
  },
  mockupUrlChip: {
    fontSize: '0.75rem',
    color: '#64748B',
    fontWeight: 500,
    fontFamily: 'monospace',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  liveSyncBadge: {
    padding: '2px 8px',
    borderRadius: '6px',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    color: '#059669',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    fontSize: '0.6875rem',
    fontWeight: 700,
    letterSpacing: '0.04em',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  liveSyncDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
  },
  userStatusRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  todayIndicatorText: {
    fontSize: '0.75rem',
    color: '#64748B',
    fontWeight: 600,
    '@media (max-width: 640px)': {
      display: 'none',
    },
  },
  avatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: '#0072C4',
    border: '1.5px solid rgba(0, 114, 196, 0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.6875rem',
    fontWeight: 700,
    color: '#FFFFFF',
    position: 'relative',
  },
  avatarOnlineDot: {
    position: 'absolute',
    bottom: '-1px',
    right: '-1px',
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
    border: '1.5px solid #FFFFFF',
  },

  // Interactive Toolbar
  filterBar: {
    borderBottom: '1px solid #E2E8F0',
    backgroundColor: '#FFFFFF',
    padding: '14px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '14px',
  },
  filterBarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap',
  },
  monthNavGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  monthNavBtn: {
    width: '28px',
    height: '28px',
    borderRadius: '8px',
    border: '1px solid #E2E8F0',
    backgroundColor: '#F8FAFC',
    color: '#475569',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: 700,
    transition: 'all 0.15s ease',
    '&:hover': {
      backgroundColor: '#EDF2F7',
      color: '#0F172A',
    },
  },
  filterMonthTitle: {
    fontSize: '1.125rem',
    fontWeight: 800,
    color: '#0F172A',
    margin: 0,
    minWidth: '140px',
  },
  todayResetBtn: {
    padding: '4px 10px',
    borderRadius: '6px',
    border: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#475569',
    fontSize: '0.6875rem',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    '&:hover': {
      backgroundColor: '#F1F5F9',
      borderColor: '#94A3B8',
    },
  },
  viewToggleGroup: {
    display: 'inline-flex',
    padding: '3px',
    borderRadius: '10px',
    backgroundColor: '#F1F5F9',
    border: '1px solid #E2E8F0',
  },
  viewToggleBtn: {
    padding: '5px 12px',
    borderRadius: '7px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#64748B',
    fontSize: '0.75rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  viewToggleBtnActive: {
    padding: '5px 12px',
    borderRadius: '7px',
    border: 'none',
    backgroundColor: '#FFFFFF',
    color: '#0072C4',
    fontSize: '0.75rem',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 1px 3px rgba(15, 23, 42, 0.1)',
  },
  filterDivider: {
    width: '1px',
    height: '24px',
    backgroundColor: '#E2E8F0',
    '@media (max-width: 900px)': {
      display: 'none',
    },
  },
  toggleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  toggleItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    userSelect: 'none',
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#475569',
    padding: '4px 8px',
    borderRadius: '8px',
    transition: 'background-color 0.15s ease',
    '&:hover': {
      backgroundColor: '#F8FAFC',
      color: '#0F172A',
    },
  },
  toggleCountBadge: {
    marginLeft: '2px',
    padding: '1px 5px',
    borderRadius: '9999px',
    fontSize: '0.625rem',
    fontWeight: 700,
  },
  toggleSwitch: {
    position: 'relative',
    width: '30px',
    height: '17px',
    borderRadius: '10px',
    transition: 'all 0.2s ease',
    display: 'inline-block',
  },
  toggleKnob: {
    position: 'absolute',
    top: '1.5px',
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    backgroundColor: '#FFFFFF',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 1px 2px rgba(0,0,0,0.2)',
  },
  switchStreamlineOn: {
    backgroundColor: '#0072C4',
    '& $toggleKnob': {
      transform: 'translateX(14px)',
    },
  },
  switchCallsOn: {
    backgroundColor: '#E11D48',
    '& $toggleKnob': {
      transform: 'translateX(14px)',
    },
  },
  switchCustomOn: {
    backgroundColor: '#D97706',
    '& $toggleKnob': {
      transform: 'translateX(14px)',
    },
  },
  switchOff: {
    backgroundColor: '#CBD5E1',
    '& $toggleKnob': {
      transform: 'translateX(2px)',
    },
  },
  newEventBtn: {
    backgroundColor: '#0072C4',
    color: '#FFFFFF',
    fontSize: '0.75rem',
    fontWeight: 700,
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0, 114, 196, 0.25)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#005a9e',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 10px rgba(0, 114, 196, 0.35)',
    },
  },

  // Calendar Month Grid
  gridHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    borderBottom: '1px solid #E2E8F0',
    backgroundColor: '#F8FAFC',
    fontSize: '0.6875rem',
    fontWeight: 800,
    color: '#64748B',
    textAlign: 'center',
    padding: '10px 0',
    letterSpacing: '0.06em',
  },
  gridBody: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    backgroundColor: '#FFFFFF',
    minHeight: '450px',
  },
  calendarCell: {
    borderRight: '1px solid #F1F5F9',
    borderBottom: '1px solid #F1F5F9',
    padding: '6px 8px',
    minHeight: '88px',
    position: 'relative',
    boxSizing: 'border-box',
    transition: 'background-color 0.15s ease',
    cursor: 'pointer',
    '&:nth-child(7n)': {
      borderRight: 'none',
    },
    '&:hover': {
      backgroundColor: '#F8FAFC',
    },
    '@media (max-width: 640px)': {
      padding: '4px 3px',
      minHeight: '68px',
    },
  },
  cellDimmed: {
    opacity: 0.35,
  },
  cellWeekend: {
    backgroundColor: '#FAFAFA',
  },
  cellActiveDay: {
    backgroundColor: '#F0F7FF !important',
  },
  cellSelectedDay: {
    backgroundColor: '#F0F7FF !important',
    boxShadow: 'inset 0 0 0 2px #0072C4',
  },
  cellTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  dayNumber: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#475569',
  },
  todayBadge: {
    width: '22px',
    height: '22px',
    borderRadius: '50%',
    backgroundColor: '#0072C4',
    color: '#FFFFFF',
    fontWeight: 800,
    fontSize: '0.75rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 2px 5px rgba(0, 114, 196, 0.35)',
  },

  // Event Pills
  eventPill: {
    marginTop: '4px',
    fontSize: '0.6875rem',
    padding: '3px 7px',
    borderRadius: '6px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    boxSizing: 'border-box',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 3px 8px rgba(0, 0, 0, 0.08)',
    },
    '@media (max-width: 640px)': {
      fontSize: '0.625rem',
      padding: '2px 4px',
      gap: '2px',
    },
  },
  eventPillRose: {
    backgroundColor: 'rgba(225, 29, 72, 0.08)',
    border: '1px solid rgba(225, 29, 72, 0.25)',
    color: '#E11D48',
  },
  eventPillAmber: {
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
    border: '1px solid rgba(245, 158, 11, 0.28)',
    color: '#D97706',
  },
  eventPillCyan: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    border: '1px solid rgba(16, 185, 129, 0.25)',
    color: '#059669',
  },
  eventPillBlue: {
    backgroundColor: 'rgba(0, 114, 196, 0.08)',
    border: '1px solid rgba(0, 114, 196, 0.25)',
    color: '#0072C4',
  },

  // Spanning Multi-Day Epic Bar
  spanningEpicBar: {
    position: 'absolute',
    top: '32px',
    left: '6px',
    width: 'calc(200% - 12px)',
    background: 'linear-gradient(90deg, #0072C4 0%, #0284C7 100%)',
    color: '#FFFFFF',
    fontSize: '0.6875rem',
    padding: '4px 10px',
    borderRadius: '7px',
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontWeight: 600,
    boxShadow: '0 4px 12px rgba(0, 114, 196, 0.3)',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 6px 16px rgba(0, 114, 196, 0.4)',
    },
    '@media (max-width: 640px)': {
      fontSize: '0.5625rem',
      padding: '2px 6px',
      top: '26px',
    },
  },
  epicCodeBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    color: '#FFFFFF',
    padding: '1px 5px',
    borderRadius: '4px',
    fontSize: '0.5625rem',
    fontWeight: 800,
    letterSpacing: '0.04em',
  },

  // Week View Timeline
  weekViewContainer: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    backgroundColor: '#FFFFFF',
  },
  weekDaysHeader: {
    display: 'grid',
    gridTemplateColumns: '70px repeat(7, 1fr)',
    gap: '8px',
    borderBottom: '1px solid #E2E8F0',
    paddingBottom: '12px',
    textAlign: 'center',
  },
  weekDayColTitle: {
    fontSize: '0.75rem',
    fontWeight: 700,
    color: '#0F172A',
  },
  weekDayColSub: {
    fontSize: '0.6875rem',
    color: '#64748B',
    marginTop: '2px',
  },
  weekSlotRow: {
    display: 'grid',
    gridTemplateColumns: '70px repeat(7, 1fr)',
    gap: '8px',
    minHeight: '56px',
    alignItems: 'center',
    borderBottom: '1px dashed #F1F5F9',
  },
  timeLabel: {
    fontSize: '0.6875rem',
    fontWeight: 600,
    color: '#94A3B8',
    fontFamily: 'monospace',
  },
  weekCell: {
    minHeight: '50px',
    borderRadius: '8px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #F1F5F9',
    padding: '4px 6px',
    boxSizing: 'border-box',
    position: 'relative',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#F1F5F9',
    },
  },

  // Event Inspector Popover
  eventInspectorModal: {
    position: 'absolute',
    bottom: '20px',
    right: '20px',
    maxWidth: '380px',
    width: 'calc(100% - 40px)',
    backgroundColor: '#FFFFFF',
    borderRadius: '16px',
    border: '1px solid #E2E8F0',
    boxShadow: '0 20px 45px -10px rgba(15, 23, 42, 0.25)',
    padding: '20px',
    zIndex: 50,
    boxSizing: 'border-box',
  },
  inspectorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  inspectorCategoryBadge: {
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '0.6875rem',
    fontWeight: 800,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#94A3B8',
    cursor: 'pointer',
    fontSize: '1.125rem',
    lineHeight: 1,
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '6px',
    transition: 'all 0.15s ease',
    '&:hover': {
      color: '#0F172A',
      backgroundColor: 'rgba(0, 0, 0, 0.05)',
    },
  },
  inspectorTitle: {
    margin: '0 0 6px 0',
    fontSize: '1.0625rem',
    fontWeight: 700,
    color: '#0F172A',
  },
  inspectorTimeText: {
    fontSize: '0.8125rem',
    color: '#64748B',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '14px',
  },
  inspectorSyncBox: {
    padding: '10px 12px',
    borderRadius: '10px',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    fontSize: '0.75rem',
    color: '#334155',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '16px',
  },
  inspectorActionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  actionBtnSecondary: {
    padding: '6px 14px',
    borderRadius: '8px',
    border: '1px solid #CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#475569',
    fontSize: '0.75rem',
    fontWeight: 600,
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#F1F5F9',
    },
  },
  actionBtnPrimary: {
    padding: '6px 14px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#0072C4',
    color: '#FFFFFF',
    fontSize: '0.75rem',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0, 114, 196, 0.25)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#005a9e',
    },
  },

  // New Event Quick Creator
  newEventModal: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    maxWidth: '420px',
    width: 'calc(100% - 32px)',
    backgroundColor: '#FFFFFF',
    borderRadius: '18px',
    border: '1.5px solid #0072C4',
    boxShadow: '0 25px 50px -12px rgba(0, 114, 196, 0.25)',
    padding: '24px',
    zIndex: 60,
    boxSizing: 'border-box',
  },
  modalTitle: {
    margin: '0 0 16px 0',
    fontSize: '1.125rem',
    fontWeight: 700,
    color: '#0F172A',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalInput: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid #CBD5E1',
    fontSize: '0.875rem',
    color: '#0F172A',
    boxSizing: 'border-box',
    marginBottom: '14px',
    fontFamily: 'inherit',
    '&:focus': {
      outline: 'none',
      borderColor: '#0072C4',
      boxShadow: '0 0 0 3px rgba(0, 114, 196, 0.15)',
    },
  },
  quickPillOptions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '16px',
  },
  quickPill: {
    padding: '4px 10px',
    borderRadius: '9999px',
    border: '1px solid #E2E8F0',
    backgroundColor: '#F8FAFC',
    fontSize: '0.6875rem',
    fontWeight: 600,
    color: '#475569',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.15s ease',
    '&:hover': {
      borderColor: '#0072C4',
      color: '#0072C4',
      backgroundColor: '#F0F7FF',
    },
  },
  categorySelectorRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '20px',
  },
  categoryBtn: {
    flex: 1,
    padding: '8px 6px',
    borderRadius: '8px',
    border: '1px solid #E2E8F0',
    backgroundColor: '#F8FAFC',
    color: '#64748B',
    fontSize: '0.75rem',
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.15s ease',
  },
  categoryBtnActiveStreamline: {
    flex: 1,
    padding: '8px 6px',
    borderRadius: '8px',
    border: '1.5px solid #0072C4',
    backgroundColor: '#F0F7FF',
    color: '#0072C4',
    fontWeight: 700,
  },
  categoryBtnActiveCall: {
    flex: 1,
    padding: '8px 6px',
    borderRadius: '8px',
    border: '1.5px solid #E11D48',
    backgroundColor: '#FFF1F2',
    color: '#E11D48',
    fontWeight: 700,
  },
  categoryBtnActiveCustom: {
    flex: 1,
    padding: '8px 6px',
    borderRadius: '8px',
    border: '1.5px solid #D97706',
    backgroundColor: '#FFFBEB',
    color: '#D97706',
    fontWeight: 700,
  },
}));
