import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes floatChrono1": {
    "0%, 100%": {
      transform: "translate(0, 0) scale(1)",
    },
    "50%": {
      transform: "translate(24px, -20px) scale(1.06)",
    },
  },
  "@keyframes floatChrono2": {
    "0%, 100%": {
      transform: "translate(0, 0) scale(1)",
    },
    "50%": {
      transform: "translate(-20px, 22px) scale(0.95)",
    },
  },
  "@keyframes pulseGlow": {
    "0%, 100%": {
      opacity: 0.35,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.75,
      transform: "scale(1.08)",
    },
  },
  "@keyframes nodeBlink": {
    "0%, 100%": {
      opacity: 0.15,
      transform: "scale(0.85)",
    },
    "50%": {
      opacity: 0.95,
      transform: "scale(1.3)",
    },
  },
  "@keyframes timelineSweep": {
    "0%": {
      left: "-20%",
      opacity: 0,
    },
    "15%": {
      opacity: 0.8,
    },
    "85%": {
      opacity: 0.8,
    },
    "100%": {
      left: "120%",
      opacity: 0,
    },
  },
  pageWrapper: {
    width: "100%",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────────────────────── */
  heroSection: {
    position: "relative",
    paddingTop: "56px",
    paddingBottom: "80px",
    paddingLeft: "24px",
    paddingRight: "24px",
    maxWidth: "1280px",
    margin: "0 auto",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      paddingTop: "40px",
      paddingBottom: "56px",
      paddingLeft: "16px",
      paddingRight: "16px",
    },
  },
  heroGlow: {
    position: "absolute",
    top: "30%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "600px",
    height: "380px",
    background: theme.light.brand.surface.lighter,
    filter: "blur(110px)",
    opacity: 0.85,
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobBrand: {
    position: "absolute",
    top: "80px",
    left: "12%",
    width: "420px",
    height: "420px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobInfo: {
    position: "absolute",
    bottom: "60px",
    right: "10%",
    width: "380px",
    height: "380px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.65,
    pointerEvents: "none",
    zIndex: 0,
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "40px",
  },
  eyebrowPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    marginBottom: "20px",
    boxShadow: theme.elevation.s,
    width: "fit-content",
  },
  pingDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    boxShadow: `0 0 0 3px ${theme.light.brand.surface.lighter}`,
  },
  eyebrowText: {
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
  },
  heroTitle: {
    fontSize: "3.5rem",
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 20px 0",
    maxWidth: "920px",
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
  },
  heroTitleAccent: {
    display: "block",
    backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`,
    WebkitBackgroundClip: "text",
    backgroundClip: "text",
    color: "transparent",
  },
  heroParagraph: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    maxWidth: "820px",
    margin: "0 auto 32px auto",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroCtaButton: {
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "14px 34px",
    borderRadius: theme.borderRadius.b300,
    fontSize: "1.0625rem",
    fontWeight: 700,
    border: "none",
    cursor: "pointer",
    boxShadow: theme.elevation.m,
    transition: "transform 0.2s ease, background-color 0.2s ease, box-shadow 0.2s ease",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.darker,
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.l,
    },
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     INTERACTIVE CALENDAR WEB MOCKUP
     ───────────────────────────────────────────────────────────────────────────── */
  mockupWrapper: {
    position: "relative",
    zIndex: 2,
    marginTop: "24px",
    width: "100%",
  },
  mockupContainer: {
    width: "100%",
    maxWidth: "1140px",
    margin: "0 auto",
    borderRadius: "18px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    boxShadow:
      "0 24px 70px -12px rgba(15, 23, 42, 0.14), 0 0 0 1px rgba(0, 114, 196, 0.06)",
    position: "relative",
    zIndex: 1,
    textAlign: "left",
    boxSizing: "border-box",
  },

  // Chrome Title Bar
  mockupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    backgroundColor: "#F8FAFC",
    borderBottom: "1px solid #E2E8F0",
    gap: "10px",
    flexWrap: "wrap",
  },
  windowDots: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  dotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#EF4444",
  },
  dotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#F59E0B",
  },
  dotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
  },
  mockupUrlChip: {
    fontSize: "0.75rem",
    color: "#64748B",
    fontWeight: 500,
    fontFamily: "monospace",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  liveSyncBadge: {
    padding: "2px 8px",
    borderRadius: "6px",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "#059669",
    border: "1px solid rgba(16, 185, 129, 0.2)",
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.04em",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  liveSyncDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
  },
  userStatusRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  todayIndicatorText: {
    fontSize: "0.75rem",
    color: "#64748B",
    fontWeight: 600,
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  avatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    border: "1.5px solid rgba(0, 114, 196, 0.3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.6875rem",
    fontWeight: 700,
    color: "#FFFFFF",
    position: "relative",
  },
  avatarOnlineDot: {
    position: "absolute",
    bottom: "-1px",
    right: "-1px",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    border: "1.5px solid #FFFFFF",
  },

  // Interactive Toolbar
  filterBar: {
    borderBottom: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: "14px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "14px",
  },
  filterBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  monthNavGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  monthNavBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#F8FAFC",
    color: "#475569",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 700,
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#EDF2F7",
      color: "#0F172A",
    },
  },
  filterMonthTitle: {
    fontSize: "1.125rem",
    fontWeight: 800,
    color: "#0F172A",
    margin: 0,
    minWidth: "140px",
  },
  todayResetBtn: {
    padding: "4px 10px",
    borderRadius: "6px",
    border: "1px solid #CBD5E1",
    backgroundColor: "#FFFFFF",
    color: "#475569",
    fontSize: "0.6875rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      borderColor: "#94A3B8",
    },
  },
  viewToggleGroup: {
    display: "inline-flex",
    padding: "3px",
    borderRadius: "10px",
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
  },
  viewToggleBtn: {
    padding: "5px 12px",
    borderRadius: "7px",
    border: "none",
    backgroundColor: "transparent",
    color: "#64748B",
    fontSize: "0.75rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  viewToggleBtnActive: {
    padding: "5px 12px",
    borderRadius: "7px",
    border: "none",
    backgroundColor: "#FFFFFF",
    color: "#0072C4",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 1px 3px rgba(15, 23, 42, 0.1)",
  },
  filterDivider: {
    width: "1px",
    height: "24px",
    backgroundColor: "#E2E8F0",
    "@media (max-width: 900px)": {
      display: "none",
    },
  },
  toggleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  toggleItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    userSelect: "none",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#475569",
    padding: "4px 8px",
    borderRadius: "8px",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      color: "#0F172A",
    },
  },
  toggleCountBadge: {
    marginLeft: "2px",
    padding: "1px 5px",
    borderRadius: "9999px",
    fontSize: "0.625rem",
    fontWeight: 700,
  },
  toggleSwitch: {
    position: "relative",
    width: "30px",
    height: "17px",
    borderRadius: "10px",
    transition: "all 0.2s ease",
    display: "inline-block",
  },
  toggleKnob: {
    position: "absolute",
    top: "1.5px",
    width: "14px",
    height: "14px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 1px 2px rgba(0,0,0,0.2)",
  },
  switchStreamlineOn: {
    backgroundColor: "#0072C4",
    "& $toggleKnob": {
      transform: "translateX(14px)",
    },
  },
  switchCallsOn: {
    backgroundColor: "#E11D48",
    "& $toggleKnob": {
      transform: "translateX(14px)",
    },
  },
  switchCustomOn: {
    backgroundColor: "#D97706",
    "& $toggleKnob": {
      transform: "translateX(14px)",
    },
  },
  switchOff: {
    backgroundColor: "#CBD5E1",
    "& $toggleKnob": {
      transform: "translateX(2px)",
    },
  },
  newEventBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "8px 16px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.25)",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#005a9e",
      transform: "translateY(-1px)",
      boxShadow: "0 4px 10px rgba(0, 114, 196, 0.35)",
    },
  },

  // Calendar Month Grid
  gridHeader: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    borderBottom: "1px solid #E2E8F0",
    backgroundColor: "#F8FAFC",
    fontSize: "0.6875rem",
    fontWeight: 800,
    color: "#64748B",
    textAlign: "center",
    padding: "10px 0",
    letterSpacing: "0.06em",
  },
  gridBody: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    backgroundColor: "#FFFFFF",
    minHeight: "450px",
  },
  calendarCell: {
    borderRight: "1px solid #F1F5F9",
    borderBottom: "1px solid #F1F5F9",
    padding: "6px 8px",
    minHeight: "88px",
    position: "relative",
    boxSizing: "border-box",
    transition: "background-color 0.15s ease",
    cursor: "pointer",
    "&:nth-child(7n)": {
      borderRight: "none",
    },
    "&:hover": {
      backgroundColor: "#F8FAFC",
    },
    "@media (max-width: 640px)": {
      padding: "4px 3px",
      minHeight: "68px",
    },
  },
  cellDimmed: {
    opacity: 0.35,
  },
  cellWeekend: {
    backgroundColor: "#FAFAFA",
  },
  cellActiveDay: {
    backgroundColor: "#F0F7FF !important",
  },
  cellSelectedDay: {
    backgroundColor: "#F0F7FF !important",
    boxShadow: "inset 0 0 0 2px #0072C4",
  },
  cellTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "4px",
  },
  dayNumber: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#475569",
  },
  todayBadge: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontWeight: 800,
    fontSize: "0.75rem",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 5px rgba(0, 114, 196, 0.35)",
  },

  // Event Pills
  eventPill: {
    marginTop: "4px",
    fontSize: "0.6875rem",
    padding: "3px 7px",
    borderRadius: "6px",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "5px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    cursor: "pointer",
    transition: "transform 0.15s ease, box-shadow 0.15s ease",
    boxSizing: "border-box",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 3px 8px rgba(0, 0, 0, 0.08)",
    },
    "@media (max-width: 640px)": {
      fontSize: "0.625rem",
      padding: "2px 4px",
      gap: "2px",
    },
  },
  eventPillRose: {
    backgroundColor: "rgba(225, 29, 72, 0.08)",
    border: "1px solid rgba(225, 29, 72, 0.25)",
    color: "#E11D48",
  },
  eventPillAmber: {
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    border: "1px solid rgba(245, 158, 11, 0.28)",
    color: "#D97706",
  },
  eventPillCyan: {
    backgroundColor: "rgba(16, 185, 129, 0.08)",
    border: "1px solid rgba(16, 185, 129, 0.25)",
    color: "#059669",
  },
  eventPillBlue: {
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    color: "#0072C4",
  },

  // Spanning Multi-Day Epic Bar
  spanningEpicBar: {
    position: "absolute",
    top: "32px",
    left: "6px",
    right: "-200%",
    background: "linear-gradient(90deg, #0072C4 0%, #0284C7 100%)",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    padding: "4px 10px",
    borderRadius: "7px",
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: 600,
    boxShadow: "0 4px 12px rgba(0, 114, 196, 0.3)",
    cursor: "pointer",
    transition: "transform 0.15s ease, box-shadow 0.15s ease",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 6px 16px rgba(0, 114, 196, 0.4)",
    },
    "@media (max-width: 640px)": {
      fontSize: "0.5625rem",
      padding: "2px 6px",
      top: "26px",
    },
  },
  epicCodeBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    color: "#FFFFFF",
    padding: "1px 5px",
    borderRadius: "4px",
    fontSize: "0.5625rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
  },

  // Week View Timeline
  weekViewContainer: {
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    backgroundColor: "#FFFFFF",
  },
  weekDaysHeader: {
    display: "grid",
    gridTemplateColumns: "70px repeat(7, 1fr)",
    gap: "8px",
    borderBottom: "1px solid #E2E8F0",
    paddingBottom: "12px",
    textAlign: "center",
  },
  weekDayColTitle: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  weekDayColSub: {
    fontSize: "0.6875rem",
    color: "#64748B",
    marginTop: "2px",
  },
  weekSlotRow: {
    display: "grid",
    gridTemplateColumns: "70px repeat(7, 1fr)",
    gap: "8px",
    minHeight: "56px",
    alignItems: "center",
    borderBottom: "1px dashed #F1F5F9",
  },
  timeLabel: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#94A3B8",
    fontFamily: "monospace",
  },
  weekCell: {
    minHeight: "50px",
    borderRadius: "8px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #F1F5F9",
    padding: "4px 6px",
    boxSizing: "border-box",
    position: "relative",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#F1F5F9",
    },
  },

  // Event Inspector Popover
  eventInspectorModal: {
    position: "absolute",
    bottom: "20px",
    right: "20px",
    maxWidth: "380px",
    width: "calc(100% - 40px)",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 20px 45px -10px rgba(15, 23, 42, 0.25)",
    padding: "20px",
    zIndex: 50,
    boxSizing: "border-box",
    animation: "$fadeIn 0.25s ease",
  },
  inspectorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  inspectorCategoryBadge: {
    padding: "3px 8px",
    borderRadius: "6px",
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "#94A3B8",
    cursor: "pointer",
    fontSize: "1.125rem",
    lineHeight: 1,
    padding: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "all 0.15s ease",
    "&:hover": {
      color: "#0F172A",
      backgroundColor: "rgba(0, 0, 0, 0.05)",
    },
  },
  inspectorTitle: {
    margin: "0 0 6px 0",
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  inspectorTimeText: {
    fontSize: "0.8125rem",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "14px",
  },
  inspectorSyncBox: {
    padding: "10px 12px",
    borderRadius: "10px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    fontSize: "0.75rem",
    color: "#334155",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "16px",
  },
  inspectorActionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "10px",
  },
  actionBtnSecondary: {
    padding: "6px 14px",
    borderRadius: "8px",
    border: "1px solid #CBD5E1",
    backgroundColor: "#FFFFFF",
    color: "#475569",
    fontSize: "0.75rem",
    fontWeight: 600,
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#F1F5F9",
    },
  },
  actionBtnPrimary: {
    padding: "6px 14px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.25)",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#005a9e",
    },
  },

  // New Event Quick Creator
  newEventModal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    maxWidth: "420px",
    width: "calc(100% - 32px)",
    backgroundColor: "#FFFFFF",
    borderRadius: "18px",
    border: "1.5px solid #0072C4",
    boxShadow: "0 25px 50px -12px rgba(0, 114, 196, 0.25)",
    padding: "24px",
    zIndex: 60,
    boxSizing: "border-box",
    animation: "$fadeIn 0.2s ease",
  },
  modalTitle: {
    margin: "0 0 16px 0",
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#0F172A",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalInput: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid #CBD5E1",
    fontSize: "0.875rem",
    color: "#0F172A",
    boxSizing: "border-box",
    marginBottom: "14px",
    fontFamily: "inherit",
    "&:focus": {
      outline: "none",
      borderColor: "#0072C4",
      boxShadow: "0 0 0 3px rgba(0, 114, 196, 0.15)",
    },
  },
  quickPillOptions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginBottom: "16px",
  },
  quickPill: {
    padding: "4px 10px",
    borderRadius: "9999px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#F8FAFC",
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#475569",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
      color: "#0072C4",
      backgroundColor: "#F0F7FF",
    },
  },
  categorySelectorRow: {
    display: "flex",
    gap: "8px",
    marginBottom: "20px",
  },
  categoryBtn: {
    flex: 1,
    padding: "8px 6px",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#F8FAFC",
    color: "#64748B",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "center",
    transition: "all 0.15s ease",
  },
  categoryBtnActiveStreamline: {
    flex: 1,
    padding: "8px 6px",
    borderRadius: "8px",
    border: "1.5px solid #0072C4",
    backgroundColor: "#F0F7FF",
    color: "#0072C4",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "center",
  },
  categoryBtnActiveCall: {
    flex: 1,
    padding: "8px 6px",
    borderRadius: "8px",
    border: "1.5px solid #E11D48",
    backgroundColor: "rgba(225, 29, 72, 0.08)",
    color: "#E11D48",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "center",
  },
  categoryBtnActiveCustom: {
    flex: 1,
    padding: "8px 6px",
    borderRadius: "8px",
    border: "1.5px solid #D97706",
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    color: "#D97706",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "center",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 2 & 3: CALENDAR AMBIENT & CONTENT
     ───────────────────────────────────────────────────────────────────────────── */
  sectionContainer: {
    padding: "96px 24px",
    maxWidth: "100%",
    width: "100%",
    margin: "0 auto",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  sectionContainerAnimated: {
    backgroundColor: "#FAFBFD",
    borderTop: "1px solid rgba(226, 232, 240, 0.7)",
    borderBottom: "1px solid rgba(226, 232, 240, 0.7)",
  },
  sectionInner: {
    position: "relative",
    zIndex: 1,
    maxWidth: "1240px",
    margin: "0 auto",
  },
  chronoAmbientCanvas: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    overflow: "hidden",
    zIndex: 0,
  },
  chronoGridOverlay: {
    position: "absolute",
    inset: 0,
    backgroundImage: `
      linear-gradient(to right, rgba(0, 114, 196, 0.045) 1px, transparent 1px),
      linear-gradient(to bottom, rgba(99, 102, 241, 0.04) 1px, transparent 1px)
    `,
    backgroundSize: "40px 40px",
    maskImage: "radial-gradient(ellipse 75% 65% at 50% 50%, #000 35%, transparent 90%)",
    WebkitMaskImage: "radial-gradient(ellipse 75% 65% at 50% 50%, #000 35%, transparent 90%)",
  },
  chronoBlobBrand: {
    position: "absolute",
    top: "30px",
    left: "-60px",
    width: "560px",
    height: "560px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(0, 114, 196, 0.13) 0%, rgba(0, 114, 196, 0.035) 50%, transparent 70%)",
    filter: "blur(75px)",
    animation: "$floatChrono1 18s ease-in-out infinite",
  },
  chronoBlobInfo: {
    position: "absolute",
    bottom: "30px",
    right: "-60px",
    width: "560px",
    height: "560px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(99, 102, 241, 0.12) 0%, rgba(99, 102, 241, 0.035) 50%, transparent 70%)",
    filter: "blur(75px)",
    animation: "$floatChrono2 22s ease-in-out infinite",
  },
  chronoBlobCenter: {
    position: "absolute",
    top: "48%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "520px",
    height: "380px",
    borderRadius: "50%",
    background: "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.06) 0%, transparent 70%)",
    filter: "blur(70px)",
    animation: "$pulseGlow 8s ease-in-out infinite",
  },
  chronoTimelineTrack: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "1px",
    background: "linear-gradient(90deg, transparent 0%, rgba(0, 114, 196, 0.25) 30%, rgba(99, 102, 241, 0.25) 70%, transparent 100%)",
    overflow: "hidden",
  },
  chronoTimelineBar: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "160px",
    height: "100%",
    background: "linear-gradient(90deg, transparent 0%, rgba(0, 114, 196, 0.85) 50%, rgba(99, 102, 241, 0.95) 80%, transparent 100%)",
    boxShadow: "0 0 6px rgba(0, 114, 196, 0.45)",
    animation: "$timelineSweep 7s cubic-bezier(0.4, 0, 0.2, 1) infinite",
  },
  chronoTimelineTrackBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "1px",
    background: "linear-gradient(90deg, transparent 0%, rgba(99, 102, 241, 0.25) 30%, rgba(0, 114, 196, 0.25) 70%, transparent 100%)",
    overflow: "hidden",
  },
  chronoTimelineBarBottom: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "160px",
    height: "100%",
    background: "linear-gradient(90deg, transparent 0%, rgba(99, 102, 241, 0.95) 40%, rgba(0, 114, 196, 0.85) 80%, transparent 100%)",
    boxShadow: "0 0 6px rgba(99, 102, 241, 0.45)",
    animation: "$timelineSweep 8s cubic-bezier(0.4, 0, 0.2, 1) infinite 2.5s",
  },
  chronoNodeDot: {
    position: "absolute",
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    animation: "$nodeBlink 4s ease-in-out infinite",
  },
  chronoNodeBrand1: {
    top: "22%",
    left: "14%",
    backgroundColor: "rgba(0, 114, 196, 0.75)",
    boxShadow: "0 0 10px rgba(0, 114, 196, 0.8)",
  },
  chronoNodeBrand2: {
    bottom: "28%",
    left: "24%",
    backgroundColor: "rgba(0, 114, 196, 0.75)",
    boxShadow: "0 0 10px rgba(0, 114, 196, 0.8)",
    animationDelay: "1.8s",
  },
  chronoNodeInfo1: {
    top: "30%",
    right: "16%",
    backgroundColor: "rgba(99, 102, 241, 0.75)",
    boxShadow: "0 0 10px rgba(99, 102, 241, 0.8)",
    animationDelay: "1s",
  },
  chronoNodeInfo2: {
    bottom: "20%",
    right: "22%",
    backgroundColor: "rgba(99, 102, 241, 0.75)",
    boxShadow: "0 0 10px rgba(99, 102, 241, 0.8)",
    animationDelay: "2.6s",
  },
  sectionHeaderCentered: {
    textAlign: "center",
    maxWidth: "800px",
    margin: "0 auto 56px auto",
  },
  kicker: {
    fontSize: "0.75rem",
    fontWeight: 800,
    color: "#0072C4",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "14px",
    display: "block",
  },
  sectionTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    lineHeight: 1.2,
    color: "#0F172A",
    margin: "0 0 16px 0",
    letterSpacing: "-0.03em",
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  sectionDescription: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: "#64748B",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  twoCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "32px",
    width: "100%",
    maxWidth: "1200px",
    margin: "0 auto",
    alignItems: "stretch",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "24px",
    },
  },
  glassCard: {
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    backdropFilter: "blur(12px)",
    border: "1px solid #E2E8F0",
    borderRadius: "24px",
    padding: "36px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "100%",
    boxShadow: "0 4px 20px -2px rgba(15, 23, 42, 0.04)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 20px 35px -5px rgba(0, 114, 196, 0.12)",
      borderColor: "rgba(0, 114, 196, 0.3)",
    },
    "@media (max-width: 600px)": {
      padding: "24px",
      borderRadius: "18px",
    },
  },
  cardBorderIndigo: {
    borderTop: "3px solid #0072C4",
  },
  cardBorderRose: {
    borderTop: "3px solid #E11D48",
  },
  cardIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "22px",
  },
  cardIconBoxRose: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    backgroundColor: "rgba(225, 29, 72, 0.08)",
    border: "1px solid rgba(225, 29, 72, 0.18)",
    color: "#E11D48",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "22px",
  },
  cardTitle: {
    fontSize: "1.375rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 12px 0",
  },
  cardParagraph: {
    fontSize: "0.9375rem",
    lineHeight: 1.7,
    color: "#64748B",
    margin: "0 0 24px 0",
    flexGrow: 1,
  },
  cardChipContainer: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "12px",
    padding: "12px 16px",
    fontSize: "0.8125rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    flexWrap: "wrap",
  },
  chipBadgeIndigo: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    padding: "3px 8px",
    borderRadius: "6px",
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
  },
  chipBadgeRose: {
    backgroundColor: "#E11D48",
    color: "#FFFFFF",
    padding: "3px 8px",
    borderRadius: "6px",
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
  },
  chipTextIndigo: {
    color: "#0072C4",
    fontWeight: 600,
    fontFamily: "monospace",
  },
  chipTextRose: {
    color: "#E11D48",
    fontWeight: 600,
    fontFamily: "monospace",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 3: INTELLIGENT ORGANIZATION
     ───────────────────────────────────────────────────────────────────────────── */
  splitSection: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.1fr) minmax(0, 0.9fr)",
    gap: "clamp(32px, 4vw, 64px)",
    alignItems: "center",
    boxSizing: "border-box",
    "@media (max-width: 1040px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "44px",
    },
  },
  splitLeft: {
    minWidth: 0,
    width: "100%",
  },
  splitRight: {
    minWidth: 0,
    width: "100%",
  },
  pointsList: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    marginTop: "32px",
  },
  pointItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
  },
  pointBadge: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1.5px solid rgba(0, 114, 196, 0.25)",
    color: "#0072C4",
    fontSize: "0.875rem",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: "2px",
  },
  pointTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 6px 0",
  },
  pointDesc: {
    fontSize: "0.9375rem",
    lineHeight: 1.65,
    color: "#64748B",
    margin: 0,
  },

  // Filter Graphic Card (Studio Right Side)
  graphicCard: {
    position: "relative",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "24px",
    padding: "36px",
    overflow: "hidden",
    boxSizing: "border-box",
    boxShadow:
      "0 20px 40px -10px rgba(15, 23, 42, 0.08), 0 4px 12px -2px rgba(15, 23, 42, 0.03)",
    "@media (max-width: 600px)": {
      padding: "20px 16px",
      borderRadius: "18px",
    },
  },
  graphicTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  tagChipsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginBottom: "28px",
  },
  tagChip: {
    padding: "6px 14px",
    fontSize: "0.75rem",
    fontWeight: 700,
    borderRadius: "9999px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    userSelect: "none",
  },
  tagRose: {
    backgroundColor: "rgba(225, 29, 72, 0.1)",
    color: "#E11D48",
    border: "1px solid rgba(225, 29, 72, 0.25)",
    "&:hover": {
      backgroundColor: "rgba(225, 29, 72, 0.16)",
      transform: "scale(1.04)",
    },
  },
  tagIndigo: {
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    "&:hover": {
      backgroundColor: "rgba(0, 114, 196, 0.16)",
      transform: "scale(1.04)",
    },
  },
  tagEmerald: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "#059669",
    border: "1px solid rgba(16, 185, 129, 0.25)",
    "&:hover": {
      backgroundColor: "rgba(16, 185, 129, 0.16)",
      transform: "scale(1.04)",
    },
  },
  tagPurple: {
    backgroundColor: "rgba(124, 58, 237, 0.1)",
    color: "#7C3AED",
    border: "1px solid rgba(124, 58, 237, 0.25)",
    "&:hover": {
      backgroundColor: "rgba(124, 58, 237, 0.16)",
      transform: "scale(1.04)",
    },
  },
  tagMuted: {
    backgroundColor: "#F1F5F9",
    color: "#94A3B8",
    border: "1px solid #E2E8F0",
    "&:hover": {
      color: "#475569",
      backgroundColor: "#E2E8F0",
    },
  },
  layersContainer: {
    borderTop: "1px solid #E2E8F0",
    paddingTop: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  layerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    padding: "14px 18px",
    borderRadius: "14px",
    border: "1px solid #E2E8F0",
    transition: "all 0.2s ease",
  },
  layerRowMuted: {
    opacity: 0.6,
  },
  layerLabel: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "#334155",
  },
  layerSwitchActive: {
    width: "42px",
    height: "22px",
    borderRadius: "11px",
    backgroundColor: "#0072C4",
    position: "relative",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  layerSwitchKnobActive: {
    position: "absolute",
    right: "3px",
    top: "3px",
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    transition: "all 0.2s ease",
    boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
  },
  layerSwitchInactive: {
    width: "42px",
    height: "22px",
    borderRadius: "11px",
    backgroundColor: "#CBD5E1",
    position: "relative",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  layerSwitchKnobInactive: {
    position: "absolute",
    left: "3px",
    top: "3px",
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    transition: "all 0.2s ease",
    boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
  },
  filterSummaryRow: {
    marginTop: "20px",
    paddingTop: "16px",
    borderTop: "1px solid #F1F5F9",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "0.75rem",
    color: "#64748B",
    fontFamily: "monospace",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 4: UNIFIED MOBILE EXPERIENCE
     ───────────────────────────────────────────────────────────────────────────── */
  sectionFour: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    boxSizing: "border-box",
    borderTop: "1px solid #E2E8F0",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  sectionFourContainer: {
    maxWidth: "1200px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  mobileDownloadCard: {
    maxWidth: "840px",
    width: "100%",
    margin: "56px auto 0 auto",
    padding: "40px 36px 32px",
    backgroundColor: "#F8FAFC",
    borderRadius: "24px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 10px 30px -5px rgba(15, 23, 42, 0.05)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 600px)": {
      padding: "28px 18px 24px",
      margin: "36px auto 0 auto",
      borderRadius: "18px",
    },
  },
  mobileDownloadHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: "12px",
    marginBottom: "4px",
  },
  mobileDownloadIcon: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    backgroundColor: "#EFF6FF",
    border: "1px solid #BAE6FD",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileDownloadTitle: {
    fontSize: "1.35rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 6px 0",
    "@media (max-width: 600px)": {
      fontSize: "1.15rem",
    },
  },
  mobileDownloadSubtitle: {
    fontSize: "0.95rem",
    color: "#475569",
    maxWidth: "520px",
    lineHeight: 1.6,
    margin: 0,
  },
  mobileCardIcon: {
    width: "56px",
    height: "56px",
    borderRadius: "16px",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "20px",
  },
  mobileKicker: {
    fontSize: "0.75rem",
    fontWeight: 800,
    color: "#0072C4",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    margin: "4px 0 14px 0",
  },
  badgeRow: {
    display: "flex",
    gap: "10px",
    marginTop: "20px",
    flexWrap: "wrap",
  },
  platformPill: {
    backgroundColor: "#F1F5F9",
    color: "#475569",
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "5px 14px",
    borderRadius: "9999px",
    border: "1px solid #E2E8F0",
  },
  downloadButtonsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
    marginTop: "44px",
  },
  storeButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 24px",
    borderRadius: "14px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    textDecoration: "none",
    boxShadow: "0 10px 25px -4px rgba(15, 23, 42, 0.18)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    transition: "all 0.25s cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: "pointer",
    boxSizing: "border-box",
    "&:hover": {
      backgroundColor: "#1E293B",
      transform: "translateY(-3px)",
      boxShadow: "0 16px 32px -4px rgba(0, 114, 196, 0.25)",
      borderColor: "rgba(0, 114, 196, 0.4)",
    },
    "@media (max-width: 480px)": {
      padding: "10px 16px",
      gap: "10px",
    },
  },
  storeIcon: {
    width: "24px",
    height: "24px",
    fill: "currentColor",
    flexShrink: 0,
  },
  storeTextCol: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
  },
  storeSubtitle: {
    fontSize: "0.6875rem",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    opacity: 0.75,
  },
  storeTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    lineHeight: 1.2,
  },
  reviewsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
    marginTop: "32px",
  },
  starRatingGroup: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  starsGroup: {
    display: "flex",
    color: "#F59E0B",
  },
  ratingNumber: {
    marginLeft: "6px",
    fontSize: "1.125rem",
    fontWeight: 800,
    color: "#0F172A",
  },
  reviewsCountText: {
    fontSize: "0.875rem",
    color: "#64748B",
  },

  "@keyframes fadeIn": {
    "0%": { opacity: 0, transform: "scale(0.96)" },
    "100%": { opacity: 1, transform: "scale(1)" },
  },
}));
