import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  pageWrapper: {
    width: "100%",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily: "'Inter', 'Open Sans', sans-serif",
    overflowX: "hidden",
    position: "relative",
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // HERO SECTION
  // ─────────────────────────────────────────────────────────────────────────────
  heroSection: {
    position: "relative",
    paddingTop: "60px",
    paddingBottom: theme.spacing.s1600,
    paddingLeft: theme.spacing.s400,
    paddingRight: theme.spacing.s400,
    maxWidth: "1280px",
    margin: "0 auto",
    textAlign: "center",
    boxSizing: "border-box",
  },
  heroGlow: {
    position: "absolute",
    top: "35%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "650px",
    height: "420px",
    background: theme.light.brand.surface.lighter,
    filter: "blur(90px)",
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
  },
  heroContent: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    fontSize: "0.875rem",
    fontWeight: 600,
    border: `1px solid ${theme.light.brand.border.light}`,
    marginBottom: theme.spacing.s500,
    boxShadow: theme.elevation.s,
  },
  badgeIcon: {
    fontSize: "1.1rem",
    lineHeight: 1,
  },
  heroTitle: {
    fontSize: "3.5rem",
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: "-0.025em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 24px 0",
    maxWidth: "900px",
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
  },
  titleGradient: {
    color: theme.light.brand.surface.medium,
    display: "block",
  },
  heroParagraph: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    maxWidth: "820px",
    margin: "0 auto 36px auto",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroCtaButton: {
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "14px 32px",
    borderRadius: theme.borderRadius.b300,
    fontSize: "1.0625rem",
    fontWeight: 700,
    border: "none",
    cursor: "pointer",
    boxShadow: theme.elevation.m,
    transition: "all 0.25s ease",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.dark,
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.l,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CALENDAR MOCKUP
  // ─────────────────────────────────────────────────────────────────────────────
  mockupContainer: {
    marginTop: theme.spacing.s1000,
    width: "100%",
    maxWidth: "1040px",
    margin: "0 auto",
    borderRadius: theme.borderRadius.b400,
    border: `1px solid ${theme.light.neutral.border.light}`,
    backgroundColor: theme.light.neutral.surface.light,
    overflow: "hidden",
    boxShadow: theme.elevation.l,
    position: "relative",
    zIndex: 1,
    textAlign: "left",
  },
  mockupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 20px",
    backgroundColor: theme.light.neutral.surface.lighter,
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
  },
  windowDots: {
    display: "flex",
    gap: "8px",
  },
  dot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    backgroundColor: theme.light.neutral.border.medium,
  },
  mockupUrlChip: {
    fontSize: "0.75rem",
    color: theme.light.neutral.onSurface.medium,
    fontWeight: 500,
    letterSpacing: "0.03em",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  monthBadge: {
    backgroundColor: theme.light.neutral.surface.medium,
    color: theme.light.neutral.onSurface.dark,
    padding: "2px 8px",
    borderRadius: theme.borderRadius.b100,
    fontSize: "0.6875rem",
  },
  avatar: {
    width: "26px",
    height: "26px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    border: `1px solid ${theme.light.brand.border.medium}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.625rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.inverse,
  },

  // Smart Filters Bar inside mockup
  filterBar: {
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    backgroundColor: theme.light.neutral.surface.light,
    padding: "14px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "14px",
  },
  filterBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  filterMonthTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: 0,
  },
  filterDivider: {
    width: "1px",
    height: "18px",
    backgroundColor: theme.light.neutral.border.medium,
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  toggleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  toggleItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    userSelect: "none",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.medium,
    transition: "color 0.2s ease",
    "&:hover": {
      color: theme.light.neutral.onSurface.title,
    },
  },
  toggleSwitch: {
    position: "relative",
    width: "32px",
    height: "18px",
    borderRadius: "10px",
    transition: "all 0.2s ease",
    display: "inline-block",
  },
  toggleKnob: {
    position: "absolute",
    top: "2px",
    width: "14px",
    height: "14px",
    borderRadius: "50%",
    backgroundColor: theme.light.neutral.surface.lighter,
    transition: "all 0.2s ease",
  },

  // Switch specific styles
  switchIndigoOn: {
    backgroundColor: theme.light.info.surface.lighter,
    border: `1px solid ${theme.light.info.border.medium}`,
    "& $toggleKnob": {
      transform: "translateX(15px)",
      backgroundColor: theme.light.info.surface.medium,
    },
  },
  switchRoseOn: {
    backgroundColor: theme.light.negative.surface.lighter,
    border: `1px solid ${theme.light.negative.border.medium}`,
    "& $toggleKnob": {
      transform: "translateX(15px)",
      backgroundColor: theme.light.negative.surface.medium,
    },
  },
  switchAmberOn: {
    backgroundColor: theme.light.warning.surface.lighter,
    border: `1px solid ${theme.light.warning.border.medium}`,
    "& $toggleKnob": {
      transform: "translateX(15px)",
      backgroundColor: theme.light.warning.surface.medium,
    },
  },
  switchOff: {
    backgroundColor: theme.light.neutral.surface.medium,
    border: `1px solid ${theme.light.neutral.border.medium}`,
    "& $toggleKnob": {
      transform: "translateX(2px)",
      backgroundColor: theme.light.neutral.onSurface.dark,
    },
  },

  newEventBtn: {
    backgroundColor: theme.light.brand.surface.dark,
    color: theme.light.neutral.onSurface.inverse,
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b150,
    border: "none",
    cursor: "pointer",
    boxShadow: theme.elevation.s,
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.medium,
    },
  },

  // Calendar Grid
  gridHeader: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    backgroundColor: theme.light.neutral.surface.light,
    fontSize: "0.6875rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.medium,
    textAlign: "center",
    padding: "8px 0",
    letterSpacing: "0.05em",
  },
  gridBody: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    backgroundColor: theme.light.neutral.surface.lighter,
    minHeight: "440px",
  },
  calendarCell: {
    borderRight: `1px solid ${theme.light.neutral.border.light}`,
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    padding: "6px",
    minHeight: "78px",
    position: "relative",
    boxSizing: "border-box",
    "&:nth-child(7n)": {
      borderRight: "none",
    },
  },
  cellDimmed: {
    opacity: 0.35,
  },
  cellWeekend: {
    backgroundColor: theme.light.neutral.surface.light,
  },
  cellActiveDay: {
    backgroundColor: theme.light.brand.surface.lighter,
  },
  dayNumber: {
    fontSize: "0.75rem",
    fontWeight: 500,
    color: theme.light.neutral.onSurface.medium,
    marginLeft: "4px",
  },
  todayBadge: {
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    fontWeight: 800,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "4px",
  },

  // Event pills inside calendar
  eventPillRose: {
    marginTop: "6px",
    backgroundColor: theme.light.negative.surface.lighter,
    border: `1px solid ${theme.light.negative.border.light}`,
    color: theme.light.negative.onSurface.medium,
    fontSize: "0.625rem",
    padding: "2px 6px",
    borderRadius: theme.borderRadius.b100,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  eventPillAmber: {
    marginTop: "6px",
    backgroundColor: theme.light.warning.surface.lighter,
    border: `1px solid ${theme.light.warning.border.light}`,
    color: theme.light.warning.onSurface.medium,
    fontSize: "0.625rem",
    padding: "2px 6px",
    borderRadius: theme.borderRadius.b100,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  eventPillCyan: {
    marginTop: "6px",
    backgroundColor: theme.light.positive.surface.lighter,
    border: `1px solid ${theme.light.positive.border.light}`,
    color: theme.light.positive.onSurface.medium,
    fontSize: "0.625rem",
    padding: "2px 6px",
    borderRadius: theme.borderRadius.b100,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },

  // Spanning multi-day bar (STR-104 Backend Migration Epic)
  spanningEpicBar: {
    position: "absolute",
    top: "32px",
    left: "4px",
    right: "-200%", // spans 3 grid columns (Day 7, 8, 9)
    backgroundColor: theme.light.info.surface.lighter,
    border: `1px solid ${theme.light.info.border.light}`,
    color: theme.light.info.onSurface.medium,
    fontSize: "0.625rem",
    padding: "3px 8px",
    borderRadius: theme.borderRadius.b100,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontWeight: 600,
    boxShadow: theme.elevation.s,
    pointerEvents: "auto",
  },
  epicCodeBadge: {
    backgroundColor: theme.light.info.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "1px 5px",
    borderRadius: "3px",
    fontSize: "0.5625rem",
    fontWeight: 700,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 2: ZERO DOUBLE-ENTRY
  // ─────────────────────────────────────────────────────────────────────────────
  sectionContainer: {
    padding: "96px 24px",
    maxWidth: "1240px",
    margin: "0 auto",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
  },
  sectionHeaderCentered: {
    textAlign: "center",
    maxWidth: "780px",
    margin: "0 auto 64px auto",
  },
  kicker: {
    fontSize: "0.8125rem",
    fontWeight: 800,
    color: theme.light.brand.onSurface.default,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    marginBottom: "12px",
    display: "block",
  },
  sectionTitle: {
    fontSize: "2.5rem",
    fontWeight: 800,
    lineHeight: 1.2,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 16px 0",
    letterSpacing: "-0.02em",
    "@media (max-width: 768px)": {
      fontSize: "1.875rem",
    },
  },
  sectionDescription: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  twoCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "32px",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "1fr",
      gap: "24px",
    },
  },
  glassCard: {
    backgroundColor: theme.light.neutral.surface.light,
    backdropFilter: "blur(14px)",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderRadius: "24px",
    padding: "36px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: theme.light.neutral.surface.medium,
      transform: "translateY(-4px)",
      boxShadow: theme.elevation.l,
    },
  },
  cardBorderIndigo: {
    borderTop: `3px solid ${theme.light.info.border.medium}`,
  },
  cardBorderRose: {
    borderTop: `3px solid ${theme.light.negative.border.medium}`,
  },
  cardIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    backgroundColor: theme.light.neutral.surface.medium,
    border: `1px solid ${theme.light.neutral.border.medium}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.375rem",
    marginBottom: "24px",
  },
  cardTitle: {
    fontSize: "1.375rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 12px 0",
  },
  cardParagraph: {
    fontSize: "0.9375rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 24px 0",
    flexGrow: 1,
  },
  cardChipContainer: {
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.medium}`,
    borderRadius: "10px",
    padding: "10px 14px",
    fontSize: "0.8125rem",
    fontFamily: "monospace",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  chipBadgeIndigo: {
    backgroundColor: theme.light.info.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "0.6875rem",
    fontWeight: 700,
  },
  chipBadgeRose: {
    backgroundColor: theme.light.negative.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "0.6875rem",
    fontWeight: 700,
  },
  chipTextIndigo: {
    color: theme.light.info.onSurface.medium,
  },
  chipTextRose: {
    color: theme.light.negative.onSurface.medium,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 3: INTELLIGENT ORGANIZATION
  // ─────────────────────────────────────────────────────────────────────────────
  splitSection: {
    display: "flex",
    alignItems: "center",
    gap: "64px",
    "@media (max-width: 960px)": {
      flexDirection: "column",
      gap: "48px",
    },
  },
  splitLeft: {
    flex: "1 1 50%",
    minWidth: 0,
  },
  splitRight: {
    flex: "1 1 50%",
    minWidth: 0,
    width: "100%",
  },
  pointsList: {
    display: "flex",
    flexDirection: "column",
    gap: "28px",
    marginTop: "32px",
  },
  pointItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
  },
  pointBadge: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.onSurface.default,
    fontSize: "0.8125rem",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: "2px",
  },
  pointTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 6px 0",
  },
  pointDesc: {
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  // Filter Graphic Card (Right side)
  graphicCard: {
    position: "relative",
    backgroundColor: theme.light.neutral.surface.light,
    backdropFilter: "blur(16px)",
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderRadius: "28px",
    padding: "36px",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  graphicAmbientGlow: {
    position: "absolute",
    top: "-40px",
    right: "-40px",
    width: "180px",
    height: "180px",
    background: theme.light.brand.surface.lighter,
    filter: "blur(40px)",
    borderRadius: "50%",
    pointerEvents: "none",
  },
  graphicTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    marginBottom: "16px",
  },
  tagChipsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginBottom: "32px",
  },
  tagChip: {
    padding: "6px 14px",
    fontSize: "0.75rem",
    fontWeight: 700,
    borderRadius: theme.borderRadius.b2500,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  tagRose: {
    backgroundColor: theme.light.negative.surface.lighter,
    color: theme.light.negative.onSurface.medium,
    border: `1px solid ${theme.light.negative.border.light}`,
    "&:hover": {
      backgroundColor: theme.light.negative.surface.light,
    },
  },
  tagIndigo: {
    backgroundColor: theme.light.info.surface.lighter,
    color: theme.light.info.onSurface.medium,
    border: `1px solid ${theme.light.info.border.light}`,
    "&:hover": {
      backgroundColor: theme.light.info.surface.light,
    },
  },
  tagEmerald: {
    backgroundColor: theme.light.positive.surface.lighter,
    color: theme.light.positive.onSurface.medium,
    border: `1px solid ${theme.light.positive.border.light}`,
    "&:hover": {
      backgroundColor: theme.light.positive.surface.light,
    },
  },
  tagCyanMuted: {
    backgroundColor: theme.light.neutral.surface.light,
    color: theme.light.neutral.onSurface.dark,
    border: `1px solid ${theme.light.neutral.border.light}`,
    opacity: 0.5,
    "&:hover": {
      opacity: 0.8,
    },
  },
  layersContainer: {
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    paddingTop: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  layerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: theme.light.neutral.surface.medium,
    padding: "14px 18px",
    borderRadius: "14px",
    border: `1px solid ${theme.light.neutral.border.medium}`,
  },
  layerRowMuted: {
    opacity: 0.6,
  },
  layerLabel: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.medium,
  },
  layerSwitchActive: {
    width: "42px",
    height: "22px",
    borderRadius: "11px",
    backgroundColor: theme.light.brand.surface.medium,
    position: "relative",
    cursor: "pointer",
  },
  layerSwitchKnobActive: {
    position: "absolute",
    right: "3px",
    top: "3px",
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    backgroundColor: theme.light.neutral.surface.lighter,
  },
  layerSwitchInactive: {
    width: "42px",
    height: "22px",
    borderRadius: "11px",
    backgroundColor: theme.light.neutral.border.medium,
    position: "relative",
    cursor: "pointer",
  },
  layerSwitchKnobInactive: {
    position: "absolute",
    left: "3px",
    top: "3px",
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    backgroundColor: theme.light.neutral.onSurface.dark,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SECTION 4: MOBILE APP
  // ─────────────────────────────────────────────────────────────────────────────
  mobileCardIcon: {
    width: "60px",
    height: "60px",
    borderRadius: "18px",
    backgroundColor: theme.light.neutral.surface.medium,
    border: `1px solid ${theme.light.neutral.border.medium}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.75rem",
    marginBottom: "24px",
  },
  mobileKicker: {
    fontSize: "0.75rem",
    fontWeight: 800,
    color: theme.light.brand.onSurface.default,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    margin: "6px 0 16px 0",
  },
  badgeRow: {
    display: "flex",
    gap: "10px",
    marginTop: "24px",
  },
  platformPill: {
    backgroundColor: theme.light.neutral.surface.medium,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.75rem",
    fontWeight: 600,
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    border: `1px solid ${theme.light.neutral.border.medium}`,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // COMPARISON SECTION WRAPPER
  // ─────────────────────────────────────────────────────────────────────────────
  comparisonWrapper: {
    width: "100%",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
  },
}));
