'use client';

import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes fadeIn": {
    "0%": {
      opacity: 0,
    },
    "100%": {
      opacity: 1,
    },
  },
  "@keyframes modalPop": {
    "0%": {
      opacity: 0,
      transform: "scale(0.95) translateY(14px)",
    },
    "100%": {
      opacity: 1,
      transform: "scale(1) translateY(0)",
    },
  },
  backdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 99999,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    boxSizing: "border-box",
    animation: "$fadeIn 0.2s ease-out forwards",
  },
  modalCard: {
    position: "relative",
    backgroundColor: "#FFFFFF",
    borderRadius: "20px",
    border: "1px solid rgba(226, 232, 240, 0.9)",
    boxShadow: "0 20px 45px -10px rgba(15, 23, 42, 0.3)",
    width: "100%",
    maxWidth: "440px",
    padding: "32px 28px 24px 28px",
    textAlign: "left",
    boxSizing: "border-box",
    animation: "$modalPop 0.28s cubic-bezier(0.16, 1, 0.3, 1) forwards",
    "@media (max-width: 480px)": {
      padding: "26px 20px 20px 20px",
      borderRadius: "18px",
    },
  },
  closeBtn: {
    position: "absolute",
    top: "16px",
    right: "16px",
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#F1F5F9",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    zIndex: 10,
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#E2E8F0",
      color: "#0F172A",
    },
  },
  iconRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "16px",
    paddingRight: "36px",
  },
  capsule: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    borderRadius: "999px",
    padding: "6px 12px",
  },
  iconDivider: {
    width: "1px",
    height: "12px",
    backgroundColor: "rgba(255, 255, 255, 0.25)",
  },
  launchBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 12px",
    borderRadius: "999px",
    backgroundColor: "#ECFDF5",
    border: "1px solid #A7F3D0",
    color: "#059669",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  dot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
  },
  title: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#0F172A",
    lineHeight: 1.3,
    margin: "0 0 12px 0",
  },
  bodyText: {
    fontSize: "0.875rem",
    color: "#475569",
    lineHeight: 1.6,
    margin: "0 0 12px 0",
  },
  highlightBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "12px",
    padding: "12px 14px",
    fontSize: "0.8125rem",
    color: "#334155",
    lineHeight: 1.5,
    margin: "14px 0 20px 0",
    "& strong": {
      color: "#0F172A",
    },
  },
  actionBtn: {
    width: "100%",
    height: "44px",
    borderRadius: "10px",
    backgroundColor: "#0072C6",
    color: "#FFFFFF",
    fontSize: "0.875rem",
    fontWeight: 600,
    border: "none",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
    boxShadow: "0 2px 8px rgba(0, 114, 196, 0.25)",
    "&:hover": {
      backgroundColor: "#005ea3",
      transform: "translateY(-1px)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
}));
