import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes pulse": {
    "0%, 100%": { opacity: 1, transform: "scale(1)" },
    "50%": { opacity: 0.4, transform: "scale(0.85)" },
  },
  step: {
    position: "relative",
    zIndex: 1,
    borderRadius: "16px",
    border: `1px solid ${theme.light.brand.border.light}`,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    backdropFilter: "blur(8px)",
    padding: "28px 32px",
    boxShadow: "0 4px 20px -2px rgba(15, 23, 42, 0.05), 0 2px 6px -1px rgba(15, 23, 42, 0.02)",
    transition: "all 0.3s ease",
    "&:hover": {
      boxShadow: "0 20px 35px -5px rgba(0, 114, 196, 0.12), 0 10px 10px -5px rgba(15, 23, 42, 0.04)",
      borderColor: theme.light.brand.border.medium,
    },
    "@media (max-width: 768px)": {
      padding: "20px 20px",
    },
  },
  stepInner: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: "20px",
    "@media (max-width: 640px)": {
      flexDirection: "column",
      gap: "16px",
    },
  },
  stepBadge: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "56px",
    height: "56px",
    borderRadius: "16px",
    background: `linear-gradient(135deg, ${theme.light.brand.surface.lighter} 0%, rgba(0, 114, 196, 0.12) 100%)`,
    color: theme.light.brand.onSurface.default,
    fontWeight: 800,
    fontSize: "20px",
    border: `1px solid ${theme.light.brand.border.light}`,
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    transition: "all 0.3s ease",
    "$step:hover &": {
      backgroundColor: theme.light.brand.surface.medium,
      color: "#FFFFFF",
      transform: "scale(1.05)",
    },
  },
  stepContent: {
    flex: 1,
    minWidth: 0,
  },
  stepHeader: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    marginBottom: "12px",
  },
  stepTitle: {
    fontSize: "1.5rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    letterSpacing: "-0.01em",
    margin: 0,
  },
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 12px",
    borderRadius: "9999px",
    fontSize: "12px",
    fontWeight: 600,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
  },
  statusBadgeEmerald: {
    backgroundColor: "rgba(16, 185, 129, 0.08)",
    color: "#059669",
    border: "1px solid rgba(16, 185, 129, 0.25)",
  },
  statusBadgeSky: {
    backgroundColor: "rgba(14, 165, 233, 0.08)",
    color: "#0284C7",
    border: "1px solid rgba(14, 165, 233, 0.25)",
  },
  statusBadgeIndigo: {
    backgroundColor: "rgba(99, 102, 241, 0.08)",
    color: "#4F46E5",
    border: "1px solid rgba(99, 102, 241, 0.25)",
  },
  statusIcon: {
    width: "14px",
    height: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  stepDesc: {
    fontSize: "15px",
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.7,
    margin: 0,
  },
  stepFooter: {
    marginTop: "16px",
    paddingTop: "14px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "12px",
    fontSize: "13px",
    color: theme.light.neutral.onSurface.dark,
    fontWeight: 500,
  },
  footerDot: {
    color: "#CBD5E1",
    fontSize: "12px",
    userSelect: "none",
  },
  footerLive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: theme.light.neutral.onSurface.title,
    fontWeight: 600,
  },
  liveDotEmerald: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    boxShadow: "0 0 0 3px rgba(16, 185, 129, 0.2)",
  },
  liveDotSky: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0284C7",
    boxShadow: "0 0 0 3px rgba(14, 165, 233, 0.2)",
  },
  liveDotIndigo: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#6366F1",
    boxShadow: "0 0 0 3px rgba(99, 102, 241, 0.2)",
  },
  footerItem: {
    color: theme.light.neutral.onSurface.medium,
    fontWeight: 500,
    fontSize: "13px",
  },
  footerHighlightEmerald: {
    color: "#059669",
    fontWeight: 600,
  },
  footerHighlightSky: {
    color: "#0284C7",
    fontWeight: 600,
  },
  footerHighlightIndigo: {
    color: "#4F46E5",
    fontWeight: 600,
  },
}));
