import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  videoSectionContainer: {
    backgroundColor: "#F7F8FA",
    width: "100%",
    padding: "80px 24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    marginTop: "60px",
  },
  videoSectionContent: {
    maxWidth: "1100px",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "54px",
    boxSizing: "border-box",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      gap: "32px",
    },
  },
  videoBoxWrapper: {
    flex: "1 1 50%",
    width: "100%",
    minHeight: "320px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E8EBEF",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 6px 24px rgba(0, 0, 0, 0.03)",
    cursor: "pointer",
    transition: "transform 0.25s ease, box-shadow 0.25s ease",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 10px 30px rgba(0, 0, 0, 0.06)",
    },
    "@media (max-width: 600px)": {
      minHeight: "220px",
    },
  },
  playIconWrapper: {
    width: "72px",
    height: "72px",
    borderRadius: "50%",
    backgroundColor: "rgba(0, 0, 0, 0.04)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  playTriangle: {
    width: 0,
    height: 0,
    borderLeft: "24px solid #D1D5DB",
    borderTop: "14px solid transparent",
    borderBottom: "14px solid transparent",
    marginLeft: "6px",
  },
  textWrapper: {
    flex: "1 1 50%",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    textAlign: "left",
    alignItems: "flex-start",
  },
  subtitle: {
    color: "#0072C4",
    fontSize: "1rem",
    fontWeight: 600,
    letterSpacing: "0.2px",
    textAlign: "left",
  },
  title: {
    color: "#1F2937",
    fontSize: "2.375rem",
    fontWeight: 700,
    lineHeight: 1.2,
    margin: 0,
    textAlign: "left",
    "@media (max-width: 600px)": {
      fontSize: "1.75rem",
    },
  },
  description: {
    color: "#4B5563",
    fontSize: "1.0625rem",
    lineHeight: 1.65,
    margin: 0,
    textAlign: "left",
  },
});
