import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const usestyles = createUseStyles((theme: Theme) => ({
  NavBar: {
    position: "fixed",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "80%",
    maxWidth: "1200px",
    height: "80px",
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.06)",
    zIndex: 1000,
    padding: "0 24px",
    borderBottomLeftRadius: "16px",
    borderBottomRightRadius: "16px",
    boxSizing: "border-box",
    transition: "border-radius 0.2s ease, box-shadow 0.2s ease",
  },
  NavBarOpen: {
    borderBottomLeftRadius: "0 !important",
    borderBottomRightRadius: "0 !important",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.03) !important",
  },
  NavBarLogo: {
    width: "180px",
    height: "auto",
    display: "block",
  },
  NavText: {
    display: "flex",
    alignItems: "center",
    gap: "32px",
  },
  NavBarLinks: {
    listStyle: "none",
    display: "flex",
    alignItems: "center",
    gap: "28px",
    margin: 0,
    padding: 0,
  },
  NavBarItem: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  NavBarLink: {
    textDecoration: "none",
    color: theme.light.neutral.onSurface.title || "#3A3A3A",
    fontWeight: 600,
    fontSize: "0.9375rem",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    cursor: "pointer",
    padding: "8px 12px",
    borderRadius: "8px",
    transition: "color 0.2s ease, background-color 0.2s ease",
    "&:hover": {
      color: theme.light.brand.onSurface.default || "#0072C4",
      backgroundColor: "#F4F8FC",
    },
  },
  ActiveLink: {
    color: theme.light.brand.onSurface.default || "#0072C4",
  },
  DropdownArrowIcon: {
    transition: "transform 0.25s ease",
    display: "flex",
    alignItems: "center",
  },
  ArrowRotated: {
    transform: "rotate(180deg)",
  },

  // ─────────────────────────────────────────────────────────────────────
  // Desktop Beautified Dropdown Menu Card
  // ─────────────────────────────────────────────────────────────────────
  DropdownMenu: {
    position: "absolute",
    top: "50px",
    left: "-20px",
    zIndex: 1100,
    backgroundColor: "#FFFFFF",
    border: `1px solid ${theme.light.neutral.border.light || "rgba(0, 0, 0, 0.08)"}`,
    width: "820px",
    maxWidth: "92vw",
    borderRadius: "16px",
    boxShadow: "0 16px 40px -8px rgba(0, 0, 0, 0.12)",
    padding: "16px",
    display: "flex",
    flexDirection: "row",
    gap: "16px",
    boxSizing: "border-box",
    animation: "$fadeIn 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  "@keyframes fadeIn": {
    from: {
      opacity: 0,
      transform: "translateY(8px)",
    },
    to: {
      opacity: 1,
      transform: "translateY(0)",
    },
  },
  "@keyframes wavePulse": {
    "0%": {
      height: "3px",
    },
    "100%": {
      height: "10px",
    },
  },

  // Left Column: Product Links List
  SectionOne: {
    flex: "0 0 280px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  ProductLinkCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 14px",
    borderRadius: "10px",
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.2s ease",
    backgroundColor: "transparent",
    border: "1px solid transparent",
    "&:hover": {
      backgroundColor: "#F4F8FC",
      transform: "translateX(3px)",
      "& $ProductLabel": {
        color: theme.light.brand.onSurface.default || "#0072C4",
      },
      "& $ProductIcon": {
        backgroundColor: "#FFFFFF",
        color: theme.light.brand.onSurface.default || "#0072C4",
        boxShadow: "0 2px 6px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  ActiveProductCard: {
    backgroundColor: "#E6F2FF !important",
    border: "1px solid #C2E0FF !important",
  },
  ProductItemContent: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  ProductIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    backgroundColor: "#EBF5FF",
    color: "#0072C4",
  },
  ActiveProductIcon: {
    backgroundColor: "#FFFFFF",
    color: theme.light.brand.onSurface.default || "#0072C4",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.06)",
  },
  ProductLabel: {
    fontWeight: 600,
    fontSize: "0.9375rem",
    color: theme.light.neutral.onSurface.title,
  },
  ActiveProductLabel: {
    color: theme.light.brand.onSurface.default || "#0072C4",
  },

  // Right Column: Active Item Detail & Preview Card
  SectionTwo: {
    flex: "1",
    backgroundColor: "#F8FAFC",
    borderRadius: "14px",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: "12px",
    border: `1px solid ${theme.light.neutral.border.light || "#E2E8F0"}`,
    boxSizing: "border-box",
    minHeight: "440px",
  },
  PreviewHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  PreviewEyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "3px 10px",
    borderRadius: "999px",
    border: "1px solid #E2E8F0",
    fontSize: "10.5px",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    width: "fit-content",
  },
  PreviewEyebrowDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
  },
  PreviewTitle: {
    color: theme.light.neutral.onSurface.title || "#0F172A",
    fontWeight: 700,
    fontSize: "1.15rem",
    lineHeight: 1.25,
    margin: "2px 0 0 0",
  },
  PreviewDescription: {
    color: theme.light.neutral.onSurface.medium || "#64748B",
    fontSize: "0.825rem",
    lineHeight: 1.5,
    margin: 0,
  },
  PreviewTagList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginTop: "2px",
  },
  PreviewTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "11px",
    fontWeight: 500,
    color: "#334155",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    padding: "2px 8px",
    borderRadius: "6px",
  },

  // Miniature Window Mockup Container
  MiniWindow: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    boxShadow: "0 4px 16px -2px rgba(15, 23, 42, 0.05), 0 1px 3px rgba(15, 23, 42, 0.03)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  MiniWindowHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 12px",
    backgroundColor: "#F8FAFC",
    borderBottom: "1px solid #E2E8F0",
  },
  MiniWindowDots: {
    display: "flex",
    gap: "5px",
    alignItems: "center",
  },
  MiniWindowDotRed: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#FF5F56",
  },
  MiniWindowDotYellow: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#FFBD2E",
  },
  MiniWindowDotGreen: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#27C93F",
  },
  MiniWindowUrl: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "10px",
    color: "#475569",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    padding: "2px 8px",
    borderRadius: "4px",
  },
  MiniWindowBadge: {
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    padding: "2px 7px",
    borderRadius: "999px",
  },
  MiniWindowBody: {
    padding: "12px 14px",
    backgroundColor: "#FBFDFF",
    minHeight: "148px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    boxSizing: "border-box",
  },

  // Shared Micro Utilities
  MicroRowBetween: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  MicroTextMuted: {
    fontSize: "10.5px",
    color: "#64748B",
    fontWeight: 500,
  },
  MicroTitle: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#0F172A",
    lineHeight: 1.2,
  },
  MicroSubtitle: {
    fontSize: "9.5px",
    color: "#64748B",
    lineHeight: 1.2,
  },
  MicroBadgeGreen: {
    fontSize: "9.5px",
    fontWeight: 600,
    color: "#16A34A",
    backgroundColor: "#DCFCE7",
    padding: "1px 6px",
    borderRadius: "4px",
  },

  // Worksuite Micro Styles
  WorksuitePreview: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  WorksuiteModulesGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
  },
  WorksuiteModuleCard: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "6px 8px",
  },
  WorksuiteModuleIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    borderRadius: "5px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #F1F5F9",
    flexShrink: 0,
  },
  WorksuiteProgressBar: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    marginTop: "2px",
  },
  WorksuiteProgressTrack: {
    width: "100%",
    height: "4px",
    backgroundColor: "#E2E8F0",
    borderRadius: "2px",
    overflow: "hidden",
  },
  WorksuiteProgressFill: {
    width: "98%",
    height: "100%",
    background: "linear-gradient(90deg, #0070E8, #38BDF8)",
    borderRadius: "2px",
  },
  MicroProgressText: {
    fontSize: "9.5px",
    color: "#0070E8",
    fontWeight: 600,
  },

  // Mail Micro Styles
  MailPreview: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  MicroSearchBar: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "4px 8px",
  },
  MicroSearchPlaceholder: {
    fontSize: "10.5px",
    color: "#94A3B8",
  },
  MailItemActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#EFF6FF",
    border: "1px solid #BFDBFE",
    borderRadius: "6px",
    padding: "5px 8px",
  },
  MailItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px 8px",
  },
  MailDotBlue: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#0070E8",
    flexShrink: 0,
  },
  MailDotGrey: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#CBD5E1",
    flexShrink: 0,
  },
  MailTextCol: {
    flex: 1,
    minWidth: 0,
  },
  MailSender: {
    fontSize: "10.5px",
    fontWeight: 700,
    color: "#0F172A",
  },
  MailTime: {
    fontSize: "9px",
    color: "#64748B",
  },
  MailSubject: {
    fontSize: "10px",
    color: "#475569",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  MailPillBlue: {
    fontSize: "9px",
    fontWeight: 600,
    color: "#0070E8",
    backgroundColor: "#DBEAFE",
    padding: "1px 5px",
    borderRadius: "4px",
    flexShrink: 0,
  },
  MailPillGreen: {
    fontSize: "9px",
    fontWeight: 600,
    color: "#16A34A",
    backgroundColor: "#DCFCE7",
    padding: "1px 5px",
    borderRadius: "4px",
    flexShrink: 0,
  },

  // Calendar Micro Styles
  CalendarPreview: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
  },
  CalendarDaysRow: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    gap: "4px",
    textAlign: "center",
  },
  CalendarDayItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "3px 2px",
    borderRadius: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
  },
  CalendarDayToday: {
    backgroundColor: "#EFF6FF",
    borderColor: "#93C5FD",
  },
  CalendarDayName: {
    fontSize: "8px",
    color: "#64748B",
    fontWeight: 600,
  },
  CalendarDayNum: {
    fontSize: "10.5px",
    fontWeight: 700,
    color: "#0F172A",
  },
  CalendarEventsList: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  CalendarEventBlue: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#F0F9FF",
    border: "1px solid #BAE6FD",
    borderRadius: "6px",
    padding: "4px 7px",
  },
  CalendarEventIndigo: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#EEF2FF",
    border: "1px solid #C7D2FE",
    borderRadius: "6px",
    padding: "4px 7px",
  },
  CalendarEventDotBlue: {
    width: "5px",
    height: "5px",
    borderRadius: "50%",
    backgroundColor: "#0284C7",
    flexShrink: 0,
  },
  CalendarEventDotIndigo: {
    width: "5px",
    height: "5px",
    borderRadius: "50%",
    backgroundColor: "#6366F1",
    flexShrink: 0,
  },
  CalendarEventTitle: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#0F172A",
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  CalendarEventTime: {
    fontSize: "9px",
    color: "#64748B",
    flexShrink: 0,
  },

  // Connect Micro Styles
  ConnectPreview: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
  },
  ConnectAvatarsRow: {
    display: "grid",
    gridTemplateColumns: "1.4fr 1fr 1fr",
    gap: "6px",
  },
  ConnectAvatarCardActive: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "3px",
    padding: "6px 4px",
    backgroundColor: "#F0FDF4",
    border: "1px solid #86EFAC",
    borderRadius: "6px",
  },
  ConnectAvatarCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "3px",
    padding: "6px 4px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
  },
  ConnectAvatarCircleActive: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#16A34A",
    color: "#FFFFFF",
    fontSize: "10px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ConnectAvatarCircle: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#E2E8F0",
    color: "#475569",
    fontSize: "10px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ConnectAudioWave: {
    display: "flex",
    alignItems: "flex-end",
    gap: "2px",
    height: "10px",
  },
  ConnectWaveBar1: {
    width: "2px",
    height: "4px",
    backgroundColor: "#16A34A",
    borderRadius: "1px",
    animation: "$wavePulse 0.8s infinite alternate",
  },
  ConnectWaveBar2: {
    width: "2px",
    height: "9px",
    backgroundColor: "#16A34A",
    borderRadius: "1px",
    animation: "$wavePulse 0.5s infinite alternate",
  },
  ConnectWaveBar3: {
    width: "2px",
    height: "6px",
    backgroundColor: "#16A34A",
    borderRadius: "1px",
    animation: "$wavePulse 0.7s infinite alternate",
  },
  ConnectAvatarLabel: {
    fontSize: "9px",
    color: "#334155",
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },
  ConnectChatSnippet: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px 8px",
  },
  ConnectChannelTag: {
    fontSize: "9px",
    fontWeight: 700,
    color: "#0070E8",
    backgroundColor: "#EFF6FF",
    padding: "1px 5px",
    borderRadius: "4px",
    flexShrink: 0,
  },
  ConnectChatMsg: {
    fontSize: "9.5px",
    color: "#475569",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },

  // Streamline Micro Styles
  StreamlinePreview: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  KanbanBoard: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
  },
  KanbanCol: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px",
  },
  KanbanColHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "8.5px",
    fontWeight: 700,
    color: "#64748B",
    letterSpacing: "0.04em",
    padding: "0 2px",
  },
  KanbanCount: {
    backgroundColor: "#E2E8F0",
    borderRadius: "999px",
    padding: "0 4px",
    fontSize: "8px",
    color: "#334155",
  },
  KanbanCard: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #CBD5E1",
    borderRadius: "5px",
    padding: "5px 7px",
    boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
  },
  KanbanCardDone: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "5px",
    padding: "5px 7px",
    opacity: 0.9,
  },
  KanbanCardTitle: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#0F172A",
    lineHeight: 1.2,
  },
  KanbanTagAi: {
    fontSize: "8px",
    fontWeight: 700,
    color: "#6366F1",
    backgroundColor: "#EEF2FF",
    padding: "1px 4px",
    borderRadius: "3px",
  },
  KanbanTagDone: {
    fontSize: "8px",
    fontWeight: 600,
    color: "#16A34A",
    backgroundColor: "#DCFCE7",
    padding: "1px 4px",
    borderRadius: "3px",
  },
  KanbanPriority: {
    fontSize: "8px",
    fontWeight: 700,
    color: "#DC2626",
    backgroundColor: "#FEE2E2",
    padding: "1px 4px",
    borderRadius: "3px",
  },
  KanbanCheck: {
    fontSize: "9px",
    fontWeight: 800,
    color: "#16A34A",
  },

  // Drive Micro Styles
  DrivePreview: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  DriveVaultShield: {
    fontSize: "9.5px",
    fontWeight: 700,
    color: "#0284C7",
    backgroundColor: "#E0F2FE",
    padding: "2px 7px",
    borderRadius: "4px",
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
  },
  DriveFileList: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  DriveFileItem: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px 7px",
  },
  DriveFileIconPdf: {
    fontSize: "8.5px",
    fontWeight: 800,
    color: "#EF4444",
    backgroundColor: "#FEE2E2",
    padding: "2px 4px",
    borderRadius: "3px",
    flexShrink: 0,
  },
  DriveFileIconFolder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    flexShrink: 0,
  },
  DriveFileInfo: {
    flex: 1,
    minWidth: 0,
  },
  DriveFileName: {
    display: "block",
    fontSize: "10px",
    fontWeight: 600,
    color: "#0F172A",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  DriveFileSize: {
    display: "block",
    fontSize: "8.5px",
    color: "#64748B",
  },
  DriveAiPill: {
    fontSize: "8px",
    fontWeight: 700,
    color: "#D97706",
    backgroundColor: "#FEF3C7",
    padding: "1px 5px",
    borderRadius: "3px",
    flexShrink: 0,
  },
  DriveExpiringPill: {
    fontSize: "8px",
    fontWeight: 600,
    color: "#0284C7",
    backgroundColor: "#E0F2FE",
    padding: "1px 5px",
    borderRadius: "3px",
    flexShrink: 0,
  },

  // E-Office Micro Styles
  EofficePreview: {
    display: "flex",
    flexDirection: "column",
    gap: "7px",
  },
  EofficeHeaderBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "10px",
    fontWeight: 600,
    color: "#475569",
  },
  EofficePulseDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
  },
  EofficeCardsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
  },
  EofficeCard: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "6px 8px",
  },
  EofficeIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    borderRadius: "5px",
    backgroundColor: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.15)",
    flexShrink: 0,
  },
  EofficeNoteBanner: {
    backgroundColor: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    color: "#0072C4",
    fontSize: "9.5px",
    fontWeight: 600,
    padding: "5px 8px",
    borderRadius: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // Footer Button
  PreviewFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "4px",
    paddingTop: "8px",
    borderTop: "1px solid #E2E8F0",
  },
  PreviewExploreBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#0070E8",
    color: "#FFFFFF",
    padding: "8px 18px",
    borderRadius: "8px",
    fontWeight: 600,
    fontSize: "13px",
    border: "none",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#005bb5",
      transform: "translateY(-1px)",
    },
  },
  PreviewShortcut: {
    fontSize: "12px",
    color: "#64748B",
    fontWeight: 500,
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },

  // ─────────────────────────────────────────────────────────────────────
  // Mobile / Touchscreen Navigation Drawer
  // ─────────────────────────────────────────────────────────────────────
  MobileMenuBtn: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px",
    borderRadius: "8px",
    backgroundColor: "#F5F5F5",
    border: "none",
  },
  MobileDrawer: {
    position: "absolute",
    top: "80px",
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: "16px",
    borderBottomRightRadius: "16px",
    boxShadow: "0 16px 32px rgba(0, 0, 0, 0.12)",
    borderTop: `1px solid ${theme.light.neutral.border.light || "#E8E8E8"}`,
    padding: "20px 24px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    zIndex: 999,
    boxSizing: "border-box",
  },
  MobileNavItem: {
    display: "flex",
    flexDirection: "column",
  },
  MobileNavLink: {
    textDecoration: "none",
    color: theme.light.neutral.onSurface.title,
    fontWeight: 600,
    fontSize: "1rem",
    padding: "10px 0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    cursor: "pointer",
    borderBottom: "1px solid #F0F0F0",
  },
  MobileAccordion: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    paddingLeft: "12px",
    marginTop: "8px",
    marginBottom: "8px",
  },
  MobileAccordionItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px 12px",
    borderRadius: "8px",
    textDecoration: "none",
    color: theme.light.neutral.onSurface.title,
    fontSize: "0.9375rem",
    fontWeight: 500,
    "&:hover": {
      backgroundColor: "#F0F7FF",
      color: theme.light.brand.onSurface.default,
    },
  },
  MobileActionWrapper: {
    marginTop: "8px",
    display: "flex",
    width: "100%",
    "& button": {
      width: "100%",
    },
  },
  DesktopOnly: {
    display: "flex !important",
    alignItems: "center",
    gap: "32px",
    "@media (max-width: 860px)": {
      display: "none !important",
    },
  },
  MobileOnly: {
    display: "none !important",
    "@media (max-width: 860px)": {
      display: "flex !important",
    },
  },
}));
