import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const usestyles = createUseStyles((theme: Theme) => ({
  "@keyframes twinkle": {
    "0%, 100%": {
      opacity: 0.2,
      transform: "scale(0.8)",
    },
    "50%": {
      opacity: 0.65,
      transform: "scale(1.2)",
      boxShadow: `0 0 6px ${theme.light.brand.surface.medium}`,
    },
  },
  "@keyframes pulse": {
    "0%, 100%": {
      opacity: 1,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.4,
      transform: "scale(0.85)",
    },
  },
  "@keyframes bounce": {
    "0%, 100%": {
      transform: "translateY(0)",
    },
    "50%": {
      transform: "translateY(8px)",
    },
  },

  aboutPageWrapper: {
    width: "100%",
    minHeight: "100vh",
    position: "relative",
    overflowX: "hidden",
    background: `linear-gradient(180deg, #F0F6FE 0%, ${theme.light.brand.surface.lighter} 18%, #FAFDFE 45%, ${theme.light.neutral.surface.lighter} 70%, #F0F6FE 100%)`,
    color: theme.light.neutral.onSurface.title,
    paddingTop: "140px",
    paddingBottom: theme.spacing.s2000,
    boxSizing: "border-box",
    fontFamily: "'Open Sans', sans-serif",
    "@media (max-width: 768px)": {
      paddingTop: "110px",
      paddingBottom: theme.spacing.s1600,
    },
  },

  // Soft Ambient Glow
  ambientGlowTop: {
    position: "absolute",
    top: "-120px",
    left: "50%",
    transform: "translateX(-50%)",
    width: "850px",
    height: "550px",
    background: `radial-gradient(ellipse at center, ${theme.light.brand.border.light} 0%, rgba(176, 214, 255, 0.18) 50%, transparent 75%)`,
    filter: "blur(90px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 1,
  },

  // Subtle sparkling particles
  starCanvas: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    overflow: "hidden",
    zIndex: 1,
  },
  star: {
    position: "absolute",
    backgroundColor: theme.light.brand.surface.light,
    borderRadius: "50%",
    opacity: 0.45,
    animation: "$twinkle 4s infinite ease-in-out",
  },

  // Hero Section
  heroSection: {
    position: "relative",
    zIndex: 2,
    maxWidth: "900px",
    margin: "0 auto",
    padding: `0 ${theme.spacing.s600}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: theme.spacing.s200,
    padding: "6px 18px",
    borderRadius: `${theme.borderRadius.b2500}px`,
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.darker,
    fontSize: "13px",
    fontWeight: 600,
    fontFamily: "'Open Sans', sans-serif",
    letterSpacing: "0.03em",
    boxShadow: "0 2px 10px rgba(0, 114, 196, 0.08)",
    marginBottom: theme.spacing.s600,
    cursor: "pointer",
    transition: `all ${theme.duration.d4}s ease`,
    "&:hover": {
      backgroundColor: theme.light.brand.surface.lighter,
      borderColor: theme.light.brand.border.medium,
      transform: "translateY(-1px)",
    },
  },
  pulseDot: {
    width: theme.spacing.s200,
    height: theme.spacing.s200,
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    boxShadow: `0 0 8px ${theme.light.brand.surface.light}`,
    animation: "$pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  },
  heroTitle: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(2.2rem, 4.5vw, 3.4rem)",
    fontWeight: 700,
    color: theme.light.brand.surface.darker,
    lineHeight: 1.25,
    margin: `0 0 ${theme.spacing.s500} 0`,
    maxWidth: "820px",
    letterSpacing: "-0.02em",
  },
  heroSubtitle: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(0.95rem, 1.8vw, 1.12rem)",
    color: theme.light.neutral.onSurface.medium,
    fontWeight: 400,
    lineHeight: 1.7,
    maxWidth: "680px",
    margin: "0 auto 36px auto",
  },
  downArrowWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.surface.medium,
    opacity: 0.85,
    animation: "$bounce 2.2s infinite ease-in-out",
    marginBottom: theme.spacing.s500,
    transition: `color ${theme.duration.d4}s ease`,
    "&:hover": {
      color: theme.light.brand.surface.darker,
    },
  },

  // Main Letter Wrapper
  letterWrapper: {
    position: "relative",
    zIndex: 2,
    maxWidth: "760px",
    margin: `${theme.spacing.s600} auto 0 auto`,
    padding: `0 ${theme.spacing.s600}`,
    boxSizing: "border-box",
  },

  // Floating Polaroids (Outside of paper card on desktop >= 1240px, never hiding content)
  polaroidLeft: {
    position: "absolute",
    left: "-230px",
    top: "120px",
    width: "195px",
    backgroundColor: theme.light.neutral.surface.lighter,
    padding: "10px 10px 18px 10px",
    boxShadow: "0 18px 40px rgba(0, 52, 107, 0.14), 0 2px 8px rgba(0, 0, 0, 0.04)",
    border: `1px solid ${theme.light.brand.border.light}`,
    borderRadius: `${theme.borderRadius.b100}px`,
    transform: "rotate(-6deg)",
    zIndex: 10,
    transition: "transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.3s ease",
    cursor: "pointer",
    "&:hover": {
      transform: "rotate(0deg) scale(1.05)",
      boxShadow: "0 24px 48px rgba(0, 52, 107, 0.22)",
      zIndex: 25,
    },
    "@media (max-width: 1240px)": {
      display: "none",
    },
  },
  polaroidRight: {
    position: "absolute",
    right: "-230px",
    bottom: "160px",
    width: "195px",
    backgroundColor: theme.light.neutral.surface.lighter,
    padding: "10px 10px 18px 10px",
    boxShadow: "0 18px 40px rgba(0, 52, 107, 0.14), 0 2px 8px rgba(0, 0, 0, 0.04)",
    border: `1px solid ${theme.light.brand.border.light}`,
    borderRadius: `${theme.borderRadius.b100}px`,
    transform: "rotate(6deg)",
    zIndex: 10,
    transition: "transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.3s ease",
    cursor: "pointer",
    "&:hover": {
      transform: "rotate(0deg) scale(1.05)",
      boxShadow: "0 24px 48px rgba(0, 52, 107, 0.22)",
      zIndex: 25,
    },
    "@media (max-width: 1240px)": {
      display: "none",
    },
  },
  polaroidImg: {
    width: "100%",
    aspectRatio: "1 / 1",
    objectFit: "cover",
    display: "block",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    borderRadius: `${theme.borderRadius.b50}px`,
  },
  polaroidCaption: {
    fontFamily: "'Caveat', cursive",
    fontSize: "24px",
    fontWeight: 600,
    textAlign: "center",
    color: theme.light.brand.surface.darker,
    marginTop: theme.spacing.s200,
    lineHeight: 1.2,
  },

  // Responsive Polaroids Showcase (Displayed when side space is limited, cleanly above letter)
  mobilePolaroidsRow: {
    display: "none",
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing.s600,
    marginBottom: "36px",
    position: "relative",
    zIndex: 3,
    padding: `0 ${theme.spacing.s400}`,
    "@media (max-width: 1240px)": {
      display: "flex",
      flexWrap: "wrap",
    },
  },
  mobilePolaroidCard: {
    width: "175px",
    backgroundColor: theme.light.neutral.surface.lighter,
    padding: "10px 10px 16px 10px",
    boxShadow: "0 12px 30px rgba(0, 68, 140, 0.12), 0 2px 6px rgba(0, 0, 0, 0.04)",
    border: `1px solid ${theme.light.brand.border.light}`,
    borderRadius: `${theme.borderRadius.b100}px`,
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    "&:first-child": {
      transform: "rotate(-3deg)",
    },
    "&:last-child": {
      transform: "rotate(3deg)",
    },
    "&:hover": {
      transform: "rotate(0deg) scale(1.05)",
      boxShadow: "0 18px 36px rgba(0, 68, 140, 0.18)",
    },
    "@media (max-width: 480px)": {
      width: "140px",
      padding: "8px 8px 12px 8px",
    },
  },

  // Paper Card
  paperCard: {
    position: "relative",
    zIndex: 5,
    backgroundColor: theme.light.neutral.surface.lighter,
    backgroundImage: `radial-gradient(${theme.light.brand.border.light} 1.2px, transparent 1.2px)`,
    backgroundSize: "22px 22px",
    borderRadius: `${theme.borderRadius.b500}px`,
    padding: "64px 60px",
    boxShadow: "0 20px 60px -15px rgba(0, 68, 140, 0.12), 0 0 0 1px rgba(0, 114, 196, 0.08)",
    border: `1px solid ${theme.light.brand.border.light}`,
    overflow: "hidden",
    boxSizing: "border-box",
    fontFamily: "'Open Sans', sans-serif",
    "@media (max-width: 768px)": {
      padding: "40px 24px",
      borderRadius: `${theme.borderRadius.b400}px`,
    },
  },
  paperGradientTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "110px",
    background: `linear-gradient(180deg, ${theme.light.neutral.surface.lighter} 0%, rgba(255, 255, 255, 0) 100%)`,
    pointerEvents: "none",
    zIndex: 1,
  },

  // Quote
  letterQuote: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(1.1rem, 2vw, 1.35rem)",
    fontWeight: 400,
    fontStyle: "italic",
    color: theme.light.brand.surface.darker,
    textAlign: "center",
    lineHeight: 1.7,
    maxWidth: "640px",
    margin: "0 auto 42px auto",
    opacity: 0.95,
    position: "relative",
    zIndex: 2,
  },

  // Letter Content
  letterBody: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing.s600,
  },
  letterParagraph: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: "1.85",
    color: theme.light.neutral.onSurface.title,
    letterSpacing: "0.01em",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "15px",
      lineHeight: "1.75",
    },
  },
  boldLead: {
    fontFamily: "'Open Sans', sans-serif",
    fontWeight: 700,
    color: theme.light.brand.surface.darker,
    marginRight: "6px",
  },

  // Signature Block
  signatureArea: {
    position: "relative",
    marginTop: "52px",
    paddingTop: theme.spacing.s800,
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  watermarkSvg: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: "220px",
    height: "120px",
    pointerEvents: "none",
    opacity: 0.08,
    color: theme.light.brand.surface.medium,
  },
  signatureName: {
    fontFamily: "'Caveat', cursive",
    fontSize: "50px",
    fontWeight: 600,
    color: theme.light.brand.surface.darker,
    transform: "rotate(-2.5deg)",
    lineHeight: 1,
    marginBottom: "4px",
  },
  signatureRole: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.15em",
    color: theme.light.brand.onSurface.default,
  },

  // Bottom CTA Section
  ctaSection: {
    position: "relative",
    zIndex: 2,
    maxWidth: "800px",
    margin: "72px auto 0 auto",
    padding: `0 ${theme.spacing.s600}`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    fontFamily: "'Open Sans', sans-serif",
  },
  ctaText: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(1.02rem, 1.8vw, 1.2rem)",
    color: theme.light.neutral.onSurface.title,
    fontWeight: 400,
    lineHeight: 1.7,
    maxWidth: "680px",
    margin: `0 auto ${theme.spacing.s800} auto`,
  },
  ctaButtons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.s400,
    flexWrap: "wrap",
  },
  ctaPrimaryBtn: {
    fontFamily: "'Open Sans', sans-serif",
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    border: "none",
    padding: "14px 34px",
    borderRadius: `${theme.borderRadius.b2500}px`,
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 8px 24px rgba(0, 114, 196, 0.25)",
    transition: `all ${theme.duration.d4}s ease`,
    display: "inline-flex",
    alignItems: "center",
    gap: theme.spacing.s200,
    "&:hover": {
      backgroundColor: theme.light.brand.surface.darker,
      transform: "translateY(-2px)",
      boxShadow: "0 12px 28px rgba(0, 114, 196, 0.35)",
    },
  },
  ctaSecondaryBtn: {
    fontFamily: "'Open Sans', sans-serif",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.brand.surface.darker,
    border: `1px solid ${theme.light.brand.border.medium}`,
    padding: "14px 30px",
    borderRadius: `${theme.borderRadius.b2500}px`,
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: `all ${theme.duration.d4}s ease`,
    boxShadow: "0 2px 8px rgba(0, 52, 107, 0.06)",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.lighter,
      borderColor: theme.light.brand.surface.medium,
      transform: "translateY(-2px)",
    },
  },
}));
