import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const usestyles = createUseStyles((theme: Theme) => ({
  "@keyframes twinkle": {
    "0%, 100%": {
      opacity: 0.25,
      transform: "scale(0.8)",
    },
    "50%": {
      opacity: 0.95,
      transform: "scale(1.25)",
      boxShadow: "0 0 8px rgba(255, 255, 255, 0.9)",
    },
  },
  "@keyframes pulse": {
    "0%, 100%": {
      opacity: 1,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.4,
      transform: "scale(0.85)",
    },
  },
  "@keyframes bounce": {
    "0%, 100%": {
      transform: "translateY(0)",
    },
    "50%": {
      transform: "translateY(8px)",
    },
  },

  aboutPageWrapper: {
    width: "100%",
    minHeight: "100vh",
    position: "relative",
    overflowX: "hidden",
    background: "linear-gradient(180deg, #070B19 0%, #112246 32%, #183769 68%, #14294E 100%)",
    paddingTop: "140px",
    paddingBottom: "80px",
    boxSizing: "border-box",
    fontFamily: "'Open Sans', sans-serif",
    "@media (max-width: 768px)": {
      paddingTop: "110px",
      paddingBottom: "60px",
    },
  },

  // Starry Background Particles
  starCanvas: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    overflow: "hidden",
    zIndex: 1,
  },
  star: {
    position: "absolute",
    backgroundColor: "#FFFFFF",
    borderRadius: "50%",
    animation: "$twinkle 4s infinite ease-in-out",
  },

  // Hero Section
  heroSection: {
    position: "relative",
    zIndex: 2,
    maxWidth: "900px",
    margin: "0 auto",
    padding: "0 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 18px",
    borderRadius: "9999px",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.18)",
    color: "#E2E8F0",
    fontSize: "13px",
    fontWeight: 600,
    fontFamily: "'Open Sans', sans-serif",
    letterSpacing: "0.04em",
    backdropFilter: "blur(12px)",
    marginBottom: "24px",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.14)",
      borderColor: "rgba(255, 255, 255, 0.3)",
    },
  },
  pulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    boxShadow: "0 0 8px #0072C4",
    animation: "$pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
  },
  heroTitle: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(2.2rem, 4.5vw, 3.4rem)",
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.25,
    margin: "0 0 20px 0",
    textShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
    maxWidth: "820px",
  },
  heroSubtitle: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(0.95rem, 1.8vw, 1.12rem)",
    color: "#CBD5E1",
    fontWeight: 400,
    lineHeight: 1.7,
    maxWidth: "680px",
    margin: "0 auto 36px auto",
    textShadow: "0 2px 10px rgba(0, 0, 0, 0.4)",
  },
  downArrowWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#94A3B8",
    opacity: 0.7,
    animation: "$bounce 2.2s infinite ease-in-out",
    marginBottom: "20px",
  },

  // Main Letter Wrapper
  letterWrapper: {
    position: "relative",
    zIndex: 2,
    maxWidth: "760px",
    margin: "24px auto 0 auto",
    padding: "0 24px",
    boxSizing: "border-box",
  },

  // Polaroids
  polaroidLeft: {
    position: "absolute",
    left: "-130px",
    top: "140px",
    width: "200px",
    backgroundColor: "#FFFFFF",
    padding: "10px 10px 18px 10px",
    boxShadow: "0 18px 40px rgba(0, 0, 0, 0.45), 0 2px 6px rgba(0, 0, 0, 0.12)",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    borderRadius: "3px",
    transform: "rotate(-8deg)",
    zIndex: 10,
    transition: "transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.3s ease",
    cursor: "pointer",
    "&:hover": {
      transform: "rotate(0deg) scale(1.06)",
      boxShadow: "0 28px 55px rgba(0, 0, 0, 0.6)",
      zIndex: 25,
    },
    "@media (max-width: 1100px)": {
      left: "-50px",
      width: "170px",
    },
    "@media (max-width: 900px)": {
      display: "none",
    },
  },
  polaroidRight: {
    position: "absolute",
    right: "-130px",
    bottom: "160px",
    width: "200px",
    backgroundColor: "#FFFFFF",
    padding: "10px 10px 18px 10px",
    boxShadow: "0 18px 40px rgba(0, 0, 0, 0.45), 0 2px 6px rgba(0, 0, 0, 0.12)",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    borderRadius: "3px",
    transform: "rotate(6deg)",
    zIndex: 10,
    transition: "transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.3s ease",
    cursor: "pointer",
    "&:hover": {
      transform: "rotate(0deg) scale(1.06)",
      boxShadow: "0 28px 55px rgba(0, 0, 0, 0.6)",
      zIndex: 25,
    },
    "@media (max-width: 1100px)": {
      right: "-50px",
      width: "170px",
    },
    "@media (max-width: 900px)": {
      display: "none",
    },
  },
  polaroidImg: {
    width: "100%",
    aspectRatio: "1 / 1",
    objectFit: "cover",
    display: "block",
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    borderRadius: "2px",
  },
  polaroidCaption: {
    fontFamily: "'Caveat', cursive",
    fontSize: "24px",
    fontWeight: 600,
    textAlign: "center",
    color: "#1E293B",
    marginTop: "8px",
    lineHeight: 1.2,
  },

  // Mobile Polaroids Strip (Visible only on tablets/mobile)
  mobilePolaroidsRow: {
    display: "none",
    justifyContent: "center",
    gap: "20px",
    marginBottom: "28px",
    "@media (max-width: 900px)": {
      display: "flex",
      flexWrap: "wrap",
    },
  },
  mobilePolaroidCard: {
    width: "160px",
    backgroundColor: "#FFFFFF",
    padding: "8px 8px 14px 8px",
    boxShadow: "0 12px 28px rgba(0, 0, 0, 0.3)",
    borderRadius: "3px",
  },

  // Paper Card
  paperCard: {
    position: "relative",
    zIndex: 5,
    backgroundColor: "#FDFCF7",
    backgroundImage: "radial-gradient(#CBD5E1 1px, transparent 1px)",
    backgroundSize: "22px 22px",
    borderRadius: "20px",
    padding: "64px 60px",
    boxShadow: "0 30px 70px -12px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(255, 255, 255, 0.4) inset",
    borderTop: "1px solid rgba(255, 255, 255, 0.7)",
    overflow: "hidden",
    boxSizing: "border-box",
    fontFamily: "'Open Sans', sans-serif",
    "@media (max-width: 768px)": {
      padding: "40px 24px",
      borderRadius: "16px",
    },
  },
  paperGradientTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "110px",
    background: "linear-gradient(180deg, rgba(253, 252, 247, 0.95) 0%, rgba(253, 252, 247, 0) 100%)",
    pointerEvents: "none",
    zIndex: 1,
  },

  // Quote
  letterQuote: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(1.1rem, 2vw, 1.35rem)",
    fontWeight: 400,
    fontStyle: "italic",
    color: "#475569",
    textAlign: "center",
    lineHeight: 1.7,
    maxWidth: "640px",
    margin: "0 auto 42px auto",
    opacity: 0.92,
    position: "relative",
    zIndex: 2,
  },

  // Letter Content
  letterBody: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  letterParagraph: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: "1.85",
    color: "#334155",
    letterSpacing: "0.01em",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "15px",
      lineHeight: "1.75",
    },
  },
  boldLead: {
    fontFamily: "'Open Sans', sans-serif",
    fontWeight: 700,
    color: "#0F172A",
    marginRight: "6px",
  },

  // Signature Block
  signatureArea: {
    position: "relative",
    marginTop: "52px",
    paddingTop: "32px",
    borderTop: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  watermarkSvg: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: "220px",
    height: "120px",
    pointerEvents: "none",
    opacity: 0.06,
  },
  signatureName: {
    fontFamily: "'Caveat', cursive",
    fontSize: "50px",
    fontWeight: 600,
    color: "#0F172A",
    transform: "rotate(-2.5deg)",
    lineHeight: 1,
    marginBottom: "4px",
  },
  signatureRole: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.15em",
    color: "#64748B",
  },

  // Bottom CTA Section
  ctaSection: {
    position: "relative",
    zIndex: 2,
    maxWidth: "800px",
    margin: "64px auto 0 auto",
    padding: "0 24px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    fontFamily: "'Open Sans', sans-serif",
  },
  ctaText: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: "clamp(1.02rem, 1.8vw, 1.2rem)",
    color: "#E2E8F0",
    fontWeight: 400,
    lineHeight: 1.7,
    maxWidth: "680px",
    margin: "0 auto 32px auto",
    textShadow: "0 2px 10px rgba(0, 0, 0, 0.4)",
  },
  ctaButtons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  ctaPrimaryBtn: {
    fontFamily: "'Open Sans', sans-serif",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    border: "none",
    padding: "14px 34px",
    borderRadius: "9999px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 10px 25px rgba(0, 0, 0, 0.25), 0 0 20px rgba(255, 255, 255, 0.2)",
    transition: "all 0.25s ease",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      transform: "translateY(-2px)",
      boxShadow: "0 14px 30px rgba(0, 0, 0, 0.35), 0 0 28px rgba(255, 255, 255, 0.35)",
    },
  },
  ctaSecondaryBtn: {
    fontFamily: "'Open Sans', sans-serif",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    color: "#FFFFFF",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    padding: "14px 30px",
    borderRadius: "9999px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    backdropFilter: "blur(8px)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.16)",
      borderColor: "rgba(255, 255, 255, 0.4)",
      transform: "translateY(-2px)",
    },
  },
}));
