import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  page: {
    minHeight: "100vh",
    padding: "140px 20px 88px",
    position: "relative",
    overflow: "hidden",
    background: `linear-gradient(180deg, #F0F6FE 0%, ${theme.light.brand.surface.lighter} 18%, #FAFDFE 55%, ${theme.light.neutral.surface.lighter} 100%)`,
    color: theme.light.neutral.onSurface.title,
    fontFamily: "'Open Sans', sans-serif",
    "@media (max-width: 768px)": {
      padding: "112px 16px 64px",
    },
  },
  glow: {
    position: "absolute",
    top: "-180px",
    left: "50%",
    width: "900px",
    height: "560px",
    transform: "translateX(-50%)",
    background: `radial-gradient(ellipse at center, ${theme.light.brand.border.light} 0%, rgba(176, 214, 255, 0.2) 48%, transparent 74%)`,
    filter: "blur(80px)",
    opacity: 0.72,
    pointerEvents: "none",
  },
  container: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: "1160px",
    margin: "0 auto",
  },
  header: {
    maxWidth: "760px",
    margin: "0 auto 54px",
    textAlign: "center",
  },
  eyebrow: {
    display: "inline-flex",
    padding: "7px 14px",
    marginBottom: "18px",
    border: `1px solid ${theme.light.brand.border.light}`,
    borderRadius: `${theme.borderRadius.b500}px`,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.surface.darker,
    fontSize: "0.74rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  title: {
    margin: "0 0 18px",
    color: theme.light.brand.surface.darker,
    fontSize: "clamp(2.35rem, 5vw, 4.2rem)",
    lineHeight: 1.08,
    fontWeight: 800,
  },
  intro: {
    margin: 0,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "1.08rem",
    lineHeight: 1.75,
  },
  plans: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "24px",
    marginBottom: "86px",
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
      marginBottom: "64px",
    },
  },
  plan: {
    display: "flex",
    flexDirection: "column",
    padding: "32px",
    backgroundColor: theme.light.neutral.surface.lighter,
    backgroundImage: "radial-gradient(rgba(0, 114, 196, 0.06) 1px, transparent 1px)",
    backgroundSize: "24px 24px",
    border: `1px solid ${theme.light.brand.border.light}`,
    borderTop: `3px solid ${theme.light.brand.surface.medium}`,
    borderRadius: `${theme.borderRadius.b500}px`,
    boxShadow: "0 20px 60px -18px rgba(0, 68, 140, 0.15)",
    boxSizing: "border-box",
  },
  aiPlan: {
    borderTopColor: theme.light.info.surface.medium,
  },
  planHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "28px",
  },
  planTitle: {
    margin: "0 0 6px",
    color: theme.light.neutral.onSurface.title,
    fontSize: "1.55rem",
    lineHeight: 1.2,
  },
  planDescription: {
    margin: 0,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.9rem",
  },
  badge: {
    flexShrink: 0,
    padding: "6px 10px",
    border: `1px solid ${theme.light.brand.border.light}`,
    borderRadius: `${theme.borderRadius.b500}px`,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.surface.darker,
    fontSize: "0.72rem",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  infoBadge: {
    borderColor: theme.light.info.border.light,
    backgroundColor: theme.light.info.surface.lighter,
    color: theme.light.info.surface.dark,
  },
  price: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    marginBottom: "8px",
  },
  amount: {
    color: theme.light.neutral.onSurface.title,
    fontSize: "3.4rem",
    lineHeight: 1,
    fontWeight: 800,
  },
  perUser: {
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.85rem",
  },
  priceNote: {
    margin: "0 0 26px",
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.85rem",
  },
  action: {
    display: "block",
    padding: "13px 18px",
    marginBottom: "28px",
    border: 0,
    borderRadius: `${theme.borderRadius.b200}px`,
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    font: "inherit",
    fontSize: "0.92rem",
    fontWeight: 700,
    textAlign: "center",
    textDecoration: "none",
    cursor: "pointer",
    transition: "background-color 0.2s ease, transform 0.2s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.darker,
      transform: "translateY(-2px)",
    },
  },
  disabledAction: {
    backgroundColor: theme.light.neutral.surface.medium,
    color: theme.light.neutral.onSurface.dark,
    cursor: "not-allowed",
    "&:hover": {
      backgroundColor: theme.light.neutral.surface.medium,
      transform: "none",
    },
  },
  featureLabel: {
    margin: "0 0 16px",
    color: theme.light.brand.surface.darker,
    fontSize: "0.76rem",
    fontWeight: 800,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
  },
  features: {
    display: "grid",
    gap: "15px",
    padding: 0,
    margin: 0,
    listStyle: "none",
  },
  feature: {
    display: "grid",
    gridTemplateColumns: "18px 1fr",
    gap: "10px",
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.9rem",
    lineHeight: 1.55,
    "& strong": {
      display: "block",
      marginBottom: "2px",
      color: theme.light.neutral.onSurface.title,
    },
  },
  check: {
    color: theme.light.brand.surface.medium,
    fontWeight: 800,
  },
  section: {
    maxWidth: "900px",
    margin: "0 auto 82px",
  },
  sectionHeader: {
    marginBottom: "34px",
    textAlign: "center",
  },
  sectionTitle: {
    margin: "0 0 10px",
    color: theme.light.brand.surface.darker,
    fontSize: "2rem",
  },
  sectionIntro: {
    margin: 0,
    color: theme.light.neutral.onSurface.medium,
    lineHeight: 1.7,
  },
  timeline: {
    display: "grid",
    gap: "22px",
  },
  milestone: {
    display: "grid",
    gridTemplateColumns: "150px 18px 1fr",
    gap: "18px",
    alignItems: "start",
    padding: "20px 0",
    borderBottom: `1px solid ${theme.light.brand.border.light}`,
    "@media (max-width: 600px)": {
      gridTemplateColumns: "18px 1fr",
      gap: "14px",
    },
  },
  date: {
    color: theme.light.brand.surface.medium,
    fontSize: "0.82rem",
    fontWeight: 800,
    "@media (max-width: 600px)": {
      gridColumn: "2",
      gridRow: "1",
    },
  },
  dot: {
    width: "14px",
    height: "14px",
    marginTop: "3px",
    border: `3px solid ${theme.light.brand.border.light}`,
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    boxSizing: "border-box",
    "@media (max-width: 600px)": {
      gridColumn: "1",
      gridRow: "1 / span 2",
    },
  },
  milestoneTitle: {
    margin: "0 0 5px",
    color: theme.light.neutral.onSurface.title,
    fontSize: "1.08rem",
  },
  milestoneCopy: {
    margin: 0,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.92rem",
    lineHeight: 1.65,
  },
  details: {
    maxWidth: "760px",
    margin: "0 auto",
  },
  detail: {
    padding: "22px 24px",
    marginBottom: "14px",
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    borderRadius: `${theme.borderRadius.b300}px`,
    boxShadow: "0 10px 30px -24px rgba(0, 68, 140, 0.28)",
  },
  detailTitle: {
    margin: "0 0 8px",
    color: theme.light.neutral.onSurface.title,
    fontSize: "1rem",
  },
  detailCopy: {
    margin: 0,
    color: theme.light.neutral.onSurface.medium,
    fontSize: "0.9rem",
    lineHeight: 1.7,
  },
  link: {
    color: theme.light.brand.surface.medium,
    fontWeight: 700,
    textDecoration: "none",
    "&:hover": {
      textDecoration: "underline",
    },
  },
}));