import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  /* ─── Keyframe Animations ─── */
  "@keyframes eofficeFloatOrb": {
    "0%, 100%": { transform: "translate(0, 0) scale(1)" },
    "50%": { transform: "translate(20px, -18px) scale(1.05)" },
  },
  "@keyframes eofficePulseGlow": {
    "0%, 100%": { opacity: 0.3, transform: "scale(1)" },
    "50%": { opacity: 0.65, transform: "scale(1.06)" },
  },
  "@keyframes eofficeNodeBlink": {
    "0%, 100%": { opacity: 0.2, transform: "scale(0.88)" },
    "50%": { opacity: 0.9, transform: "scale(1.25)" },
  },
  "@keyframes eofficeScanLight": {
    "0%": { left: "-25%", opacity: 0 },
    "20%": { opacity: 0.75 },
    "80%": { opacity: 0.75 },
    "100%": { left: "120%", opacity: 0 },
  },
  "@keyframes starTwinkle": {
    "0%, 100%": { opacity: 0.45, transform: "scale(0.85) rotate(0deg)" },
    "50%": { opacity: 1, transform: "scale(1.2) rotate(15deg)" },
  },

  /* ─── Page Root ─── */
  page: {
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    width: "100%",
    maxWidth: "100vw",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────── */
  hero: {
    maxWidth: "1280px",
    margin: "0 auto",
    padding: "56px 24px 80px",
    textAlign: "center",
    position: "relative",
    zIndex: 1,
    boxSizing: "border-box",
    width: "100%",
    "@media (max-width: 768px)": {
      padding: "36px 14px 50px",
    },
  },
  heroGlow: {
    position: "absolute",
    width: "700px",
    height: "450px",
    top: "-80px",
    left: "50%",
    transform: "translateX(-50%)",
    background: "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.12) 0%, rgba(2, 132, 199, 0.05) 50%, rgba(255,255,255,0) 75%)",
    filter: "blur(60px)",
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
    "@media (max-width: 768px)": {
      width: "100%",
      maxWidth: "340px",
      height: "260px",
      top: "-20px",
    },
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    maxWidth: "780px",
    margin: "0 auto 48px",
    "@media (max-width: 768px)": {
      marginBottom: "28px",
    },
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "5px 14px",
    borderRadius: "999px",
    background: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.22)",
    color: "#0072C4",
    fontSize: "0.78rem",
    fontWeight: 700,
    letterSpacing: "0.02em",
    marginBottom: 22,
  },
  title: {
    fontSize: "clamp(2rem, 5vw, 3.4rem)",
    fontWeight: 800,
    lineHeight: 1.12,
    letterSpacing: "-0.025em",
    color: "#0F172A",
    margin: "0 0 18px",
  },
  titleAccent: {
    display: "block",
    background: "linear-gradient(135deg, #0072C4 0%, #0284C7 50%, #0369A1 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  heroDescription: {
    fontSize: "1.05rem",
    color: "#475569",
    maxWidth: "640px",
    margin: "0 auto 28px",
    lineHeight: 1.65,
  },
  heroBtnRow: {
    display: "flex",
    justifyContent: "center",
    gap: 14,
    "@media (max-width: 480px)": {
      flexDirection: "column",
      alignItems: "center",
    },
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "13px 30px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #0072C4, #0284C7)",
    color: "#FFFFFF",
    fontSize: "0.92rem",
    fontWeight: 700,
    border: "none",
    cursor: "pointer",
    boxShadow: "0 4px 18px rgba(0, 114, 196, 0.35)",
    transition: "transform 0.18s ease, box-shadow 0.18s ease",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 8px 28px rgba(0, 114, 196, 0.45)",
    },
  },
  mockupWrapper: {
    position: "relative",
    zIndex: 2,
    width: "100%",
    maxWidth: "1280px",
    margin: "0 auto",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION WRAPPER (shared)
     ───────────────────────────────────────────────────────────── */
  sectionWrapper: {
    padding: "80px 24px",
    position: "relative",
    "@media (max-width: 768px)": {
      padding: "52px 14px",
    },
  },
  sectionWrapperGray: {
    background: "linear-gradient(180deg, #F8FAFC 0%, #FFFFFF 100%)",
    borderTop: "1px solid #F1F5F9",
    borderBottom: "1px solid #F1F5F9",
  },
  sectionWrapperAnimated: {
    overflow: "hidden",
    background: "linear-gradient(160deg, #F0F7FF 0%, #E8F3FC 30%, #E0F0FE 60%, #F8FAFC 100%)",
    borderTop: "1px solid rgba(0, 114, 196, 0.12)",
    borderBottom: "1px solid rgba(0, 114, 196, 0.12)",
  },
  sectionInner: {
    maxWidth: "1100px",
    margin: "0 auto",
    position: "relative",
    zIndex: 2,
  },

  /* ─────────────────────────────────────────────────────────────
     ANIMATED BACKGROUND (Section 1 — Onboarding)
     ───────────────────────────────────────────────────────────── */
  ambientCanvas: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobBlue: {
    position: "absolute",
    width: "600px",
    height: "400px",
    borderRadius: "50%",
    background: "radial-gradient(ellipse at center, rgba(0, 114, 196, 0.1) 0%, transparent 65%)",
    filter: "blur(80px)",
    top: "-80px",
    right: "0",
    animation: "$eofficeFloatOrb 12s ease-in-out infinite",
  },
  ambientBlobSky: {
    position: "absolute",
    width: "400px",
    height: "300px",
    borderRadius: "50%",
    background: "radial-gradient(ellipse at center, rgba(2, 132, 199, 0.08) 0%, transparent 65%)",
    filter: "blur(70px)",
    bottom: "0",
    left: "10%",
    animation: "$eofficeFloatOrb 15s ease-in-out infinite reverse",
  },
  ambientScanTrack: {
    position: "absolute",
    top: "40%",
    left: 0,
    right: 0,
    height: "1px",
    background: "transparent",
    overflow: "hidden",
  },
  ambientScanLight: {
    position: "absolute",
    top: 0,
    width: "25%",
    height: "1px",
    background: "linear-gradient(90deg, transparent, rgba(0, 114, 196, 0.4), transparent)",
    animation: "$eofficeScanLight 8s linear infinite",
  },

  /* ─────────────────────────────────────────────────────────────
     SPLIT GRID (two-column layout)
     ───────────────────────────────────────────────────────────── */
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 60,
    alignItems: "center",
    "@media (max-width: 820px)": {
      gridTemplateColumns: "1fr",
      gap: 36,
    },
  },
  splitGridReverse: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 60,
    alignItems: "center",
    direction: "rtl" as const,
    "@media (max-width: 820px)": {
      gridTemplateColumns: "1fr",
      gap: 36,
      direction: "ltr" as const,
    },
    "& > *": {
      direction: "ltr" as const,
    },
  },

  /* ─────────────────────────────────────────────────────────────
     TEXT ELEMENTS (shared)
     ───────────────────────────────────────────────────────────── */
  kicker: {
    display: "inline-block",
    fontSize: "0.72rem",
    fontWeight: 800,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "#0072C4",
    marginBottom: 12,
  },
  kickerGreen: {
    display: "inline-block",
    fontSize: "0.72rem",
    fontWeight: 800,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "#059669",
    marginBottom: 12,
  },
  kickerRose: {
    display: "inline-block",
    fontSize: "0.72rem",
    fontWeight: 800,
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    color: "#E11D48",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: "clamp(1.55rem, 3.5vw, 2.3rem)",
    fontWeight: 800,
    lineHeight: 1.2,
    letterSpacing: "-0.02em",
    color: "#0F172A",
    margin: "0 0 16px",
  },
  sectionDescription: {
    fontSize: "1rem",
    color: "#475569",
    lineHeight: 1.65,
    margin: "0 0 20px",
  },
  sectionHeaderCenter: {
    textAlign: "center",
    maxWidth: "700px",
    margin: "0 auto 56px",
  },

  /* ─────────────────────────────────────────────────────────────
     PROCESS CARDS (One-Click Onboarding points)
     ───────────────────────────────────────────────────────────── */
  points: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 16,
    marginTop: 24,
  },
  pointCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    padding: "16px 18px",
    background: "#FFFFFF",
    borderRadius: 16,
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 10px rgba(0, 114, 196, 0.04), 0 1px 3px rgba(0, 0, 0, 0.02)",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    position: "relative" as const,
    "&:hover": {
      transform: "translateX(6px)",
      borderColor: "rgba(0, 114, 196, 0.35)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.09), 0 2px 6px rgba(0, 0, 0, 0.03)",
    },
    "@media (max-width: 600px)": {
      padding: "14px",
      gap: 12,
    },
  },
  pointIconWrap: {
    flexShrink: 0,
    width: 42,
    height: 42,
    borderRadius: 12,
    background: "linear-gradient(135deg, rgba(0, 114, 196, 0.08) 0%, rgba(56, 189, 248, 0.14) 100%)",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginTop: 2,
    transition: "transform 0.25s ease",
  },
  pointContent: {
    flex: 1,
    minWidth: 0,
  },
  pointHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 5,
  },
  pointTitle: {
    fontSize: "0.98rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  pointBadge: {
    fontSize: "0.65rem",
    fontWeight: 800,
    letterSpacing: "0.06em",
    color: "#0072C4",
    background: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    borderRadius: 5,
    padding: "2px 7px",
    textTransform: "uppercase" as const,
    flexShrink: 0,
  },
  pointText: {
    fontSize: "0.85rem",
    color: "#64748B",
    lineHeight: 1.55,
    margin: 0,
  },
  pointTagRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 6,
  },
  pointTagBlue: {
    background: "rgba(0, 114, 196, 0.06)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    borderRadius: 5,
    fontSize: "0.68rem",
    fontWeight: 600,
    padding: "2px 7px",
  },
  pointTagGray: {
    background: "#F8FAFC",
    color: "#64748B",
    border: "1px solid #E2E8F0",
    borderRadius: 5,
    fontSize: "0.68rem",
    fontWeight: 500,
    padding: "2px 7px",
  },
  point: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
  },
  pointNumber: {
    flexShrink: 0,
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: "rgba(0, 114, 196, 0.1)",
    border: "1px solid rgba(0, 114, 196, 0.3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.7rem",
    fontWeight: 800,
    color: "#0072C4",
    marginTop: 2,
  },

  /* ─────────────────────────────────────────────────────────────
     CONFIG CARD (Employee Configuration Console)
     ───────────────────────────────────────────────────────────── */
  configCard: {
    background: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: 18,
    padding: 28,
    boxShadow: "0 8px 40px rgba(0, 114, 196, 0.08), 0 1px 6px rgba(0,0,0,0.04)",
    position: "relative" as const,
    overflow: "hidden",
  },
  configCardGlow: {
    position: "absolute" as const,
    right: -20,
    bottom: -20,
    width: 160,
    height: 160,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(0, 114, 196, 0.12) 0%, transparent 70%)",
    filter: "blur(30px)",
    pointerEvents: "none" as const,
  },
  configCardHeader: {
    fontSize: "0.78rem",
    fontWeight: 700,
    color: "#0F172A",
    borderBottom: "1px solid #F1F5F9",
    paddingBottom: 12,
    marginBottom: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  configGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 14,
    marginBottom: 14,
  },
  configField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
  },
  configLabel: {
    fontSize: "0.65rem",
    fontWeight: 700,
    textTransform: "uppercase" as const,
    color: "#94A3B8",
    letterSpacing: "0.06em",
  },
  configValue: {
    background: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: "0.78rem",
    color: "#0F172A",
    fontWeight: 500,
  },
  configTagRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
    marginTop: 4,
  },
  configTagBlue: {
    background: "rgba(0, 114, 196, 0.08)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    borderRadius: 5,
    fontSize: "0.68rem",
    fontWeight: 700,
    padding: "3px 8px",
  },
  configTagGray: {
    background: "#F1F5F9",
    color: "#475569",
    border: "1px solid #E2E8F0",
    borderRadius: 5,
    fontSize: "0.68rem",
    fontWeight: 600,
    padding: "3px 8px",
  },
  configLeavePlan: {
    background: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    padding: "10px 12px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  configLeavePlanName: {
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "#0F172A",
  },
  configLeavePlanCount: {
    fontSize: "0.72rem",
    color: "#0072C4",
    fontWeight: 700,
  },
  configProvisionBtn: {
    marginTop: 18,
    width: "100%",
    background: "linear-gradient(135deg, #0072C4, #0284C7)",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 8,
    padding: "11px 0",
    fontSize: "0.8rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 3px 12px rgba(0, 114, 196, 0.3)",
    transition: "transform 0.15s, box-shadow 0.15s",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 6px 18px rgba(0, 114, 196, 0.4)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     5-MINUTE HIGHLIGHT BOX
     ───────────────────────────────────────────────────────────── */
  fiveMinBox: {
    marginTop: 64,
    background: "linear-gradient(145deg, #F0F7FF 0%, #E0F2FE 60%, #F8FAFC 100%)",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    borderRadius: 24,
    padding: "52px 40px",
    position: "relative" as const,
    overflow: "hidden",
    textAlign: "center",
    "@media (max-width: 640px)": {
      padding: "36px 20px",
    },
  },
  fiveMinBlobLeft: {
    position: "absolute" as const,
    left: -60,
    top: -60,
    width: 220,
    height: 220,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(0, 114, 196, 0.12) 0%, transparent 70%)",
    filter: "blur(40px)",
    pointerEvents: "none" as const,
  },
  fiveMinIconBox: {
    width: 56,
    height: 56,
    background: "rgba(0, 114, 196, 0.1)",
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 22px",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    color: "#0072C4",
  },
  fiveMinTitle: {
    fontSize: "clamp(1.4rem, 3vw, 2rem)",
    fontWeight: 800,
    color: "#0F172A",
    marginBottom: 32,
  },
  fiveMinGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    textAlign: "left" as const,
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  fiveMinCardOld: {
    background: "rgba(255, 255, 255, 0.75)",
    border: "1px solid #E2E8F0",
    borderRadius: 18,
    padding: "24px 22px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.02)",
  },
  fiveMinCardNew: {
    background: "linear-gradient(155deg, #FFFFFF 0%, #F4F9FF 40%, #E6F3FE 100%)",
    border: "1.5px solid rgba(0, 114, 196, 0.45)",
    borderRadius: 18,
    padding: "24px 22px",
    position: "relative" as const,
    transform: "translateY(-6px)",
    boxShadow: "0 16px 36px rgba(0, 114, 196, 0.15), 0 2px 8px rgba(0, 114, 196, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.95)",
    transition: "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
    "&:hover": {
      transform: "translateY(-9px)",
      boxShadow: "0 22px 48px rgba(0, 114, 196, 0.22), 0 4px 12px rgba(0, 114, 196, 0.12)",
      borderColor: "#0072C4",
    },
  },
  fiveMinCardGlow: {
    position: "absolute" as const,
    top: 0,
    right: 0,
    width: 160,
    height: 160,
    borderRadius: "0 18px 0 100px",
    background: "radial-gradient(circle at top right, rgba(56, 189, 248, 0.22) 0%, rgba(0, 114, 196, 0.06) 50%, transparent 80%)",
    pointerEvents: "none" as const,
  },
  fiveMinCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 8,
    position: "relative" as const,
    zIndex: 2,
  },
  fiveMinCardOldLabel: {
    fontSize: "0.72rem",
    fontWeight: 800,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    color: "#E11D48",
    marginBottom: 10,
  },
  fiveMinCardNewLabel: {
    fontSize: "0.72rem",
    fontWeight: 800,
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
    position: "relative" as const,
    zIndex: 2,
  },
  newWayDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#10B981",
    boxShadow: "0 0 8px rgba(16, 185, 129, 0.7)",
    display: "inline-block",
  },
  fiveMinCardText: {
    fontSize: "0.875rem",
    color: "#475569",
    lineHeight: 1.65,
    margin: 0,
  },
  fiveMinCardTextBright: {
    fontSize: "0.875rem",
    color: "#0F172A",
    lineHeight: 1.65,
    margin: 0,
    position: "relative" as const,
    zIndex: 2,
    fontWeight: 450,
  },
  starTopRight: {
    position: "absolute" as const,
    top: -12,
    right: -10,
    zIndex: 3,
    pointerEvents: "none" as const,
    animation: "$starTwinkle 3s ease-in-out infinite",
    filter: "drop-shadow(0 2px 6px rgba(0, 114, 196, 0.45))",
  },
  starBottomRight: {
    position: "absolute" as const,
    bottom: -8,
    right: 24,
    zIndex: 3,
    pointerEvents: "none" as const,
    animation: "$starTwinkle 2.6s ease-in-out infinite 0.7s",
    filter: "drop-shadow(0 2px 5px rgba(56, 189, 248, 0.5))",
  },
  starTopLeft: {
    position: "absolute" as const,
    top: -10,
    left: 20,
    zIndex: 3,
    pointerEvents: "none" as const,
    animation: "$starTwinkle 3.2s ease-in-out infinite 1.4s",
    filter: "drop-shadow(0 2px 5px rgba(245, 158, 11, 0.45))",
  },
  starBottomLeft: {
    position: "absolute" as const,
    bottom: -6,
    left: 40,
    zIndex: 3,
    pointerEvents: "none" as const,
    animation: "$starTwinkle 2.8s ease-in-out infinite 2s",
    filter: "drop-shadow(0 2px 4px rgba(0, 114, 196, 0.35))",
  },

  /* ─────────────────────────────────────────────────────────────
     ATTENDANCE SECTION (Section 2)
     ───────────────────────────────────────────────────────────── */
  trackingGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    "@media (max-width: 820px)": {
      gridTemplateColumns: "1fr",
    },
  },
  trackingCard: {
    background: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: 18,
    padding: "32px 28px",
    position: "relative" as const,
    overflow: "hidden",
    transition: "border-color 0.2s, box-shadow 0.2s, transform 0.2s",
    "&:hover": {
      borderColor: "#0072C4",
      boxShadow: "0 8px 30px rgba(0, 114, 196, 0.08)",
      transform: "translateY(-2px)",
    },
  },
  trackingCardTopBlue: {
    "&::before": {
      content: "''",
      position: "absolute" as const,
      top: 0,
      left: 0,
      right: 0,
      height: 3,
      background: "linear-gradient(90deg, #0072C4, #0284C7)",
      borderRadius: "18px 18px 0 0",
    },
  },
  trackingCardTopGreen: {
    "&::before": {
      content: "''",
      position: "absolute" as const,
      top: 0,
      left: 0,
      right: 0,
      height: 3,
      background: "linear-gradient(90deg, #059669, #10B981)",
      borderRadius: "18px 18px 0 0",
    },
  },
  trackingCardIconBox: {
    width: 48,
    height: 48,
    background: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: 20,
    transition: "background 0.2s, transform 0.2s",
  },
  trackingCardTitle: {
    fontSize: "1.1rem",
    fontWeight: 800,
    color: "#0F172A",
    marginBottom: 10,
  },
  trackingCardText: {
    fontSize: "0.875rem",
    color: "#64748B",
    lineHeight: 1.65,
    marginBottom: 18,
  },
  pillRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  pillGreen: {
    background: "rgba(16,185,129,0.08)",
    border: "1px solid rgba(16,185,129,0.25)",
    borderRadius: 5,
    fontSize: "0.65rem",
    fontWeight: 800,
    color: "#059669",
    padding: "3px 8px",
    letterSpacing: "0.04em",
    textTransform: "uppercase" as const,
  },
  pillBlue: {
    background: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    borderRadius: 5,
    fontSize: "0.65rem",
    fontWeight: 800,
    color: "#0072C4",
    padding: "3px 8px",
    letterSpacing: "0.04em",
    textTransform: "uppercase" as const,
  },
  leaveApprovalRow: {
    background: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: 10,
    padding: "10px 14px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  leaveApprovalLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  leaveApprovalText: {
    fontSize: "0.78rem",
    color: "#334155",
    fontWeight: 600,
  },
  leaveApprovalBadge: {
    background: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    borderRadius: 5,
    fontSize: "0.65rem",
    fontWeight: 700,
    padding: "3px 8px",
  },

  /* ─────────────────────────────────────────────────────────────
     ASSET AUDIT SECTION (Section 3)
     ───────────────────────────────────────────────────────────── */
  auditCard: {
    background: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: 18,
    padding: 24,
    boxShadow: "0 4px 24px rgba(0,0,0,0.04)",
    position: "relative" as const,
    overflow: "hidden",
  },
  auditCardGlow: {
    position: "absolute" as const,
    left: -20,
    bottom: -20,
    width: 140,
    height: 140,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(0, 114, 196, 0.12) 0%, transparent 70%)",
    filter: "blur(30px)",
    pointerEvents: "none" as const,
  },
  auditInner: {
    background: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: 12,
    padding: 18,
    position: "relative" as const,
  },
  auditActionRequired: {
    position: "absolute" as const,
    top: 12,
    right: 12,
    background: "rgba(225,29,72,0.1)",
    color: "#E11D48",
    border: "1px solid rgba(225,29,72,0.25)",
    borderRadius: 5,
    fontSize: "0.65rem",
    fontWeight: 800,
    padding: "3px 8px",
    display: "flex",
    alignItems: "center",
    gap: 4,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
  },
  auditAssetHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  auditAssetName: {
    fontSize: "0.88rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  auditAssetAssigned: {
    fontSize: "0.72rem",
    color: "#64748B",
    fontFamily: "monospace",
    marginTop: 2,
  },
  auditUploadBox: {
    background: "#FFFFFF",
    border: "1px dashed #CBD5E1",
    borderRadius: 10,
    padding: "20px 14px",
    textAlign: "center" as const,
  },
  auditUploadIconWrap: {
    width: 44,
    height: 44,
    margin: "0 auto 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
  },
  auditUploadTitle: {
    fontSize: "0.78rem",
    fontWeight: 600,
    color: "#334155",
    marginBottom: 4,
  },
  auditUploadSub: {
    fontSize: "0.72rem",
    color: "#94A3B8",
    maxWidth: 240,
    margin: "0 auto 14px",
  },
  auditUploadBtn: {
    background: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    borderRadius: 7,
    padding: "6px 16px",
    fontSize: "0.72rem",
    fontWeight: 700,
    color: "#0072C4",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      background: "#0072C4",
      color: "#FFFFFF",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     CULTURE GRID (Section 4)
     ───────────────────────────────────────────────────────────── */
  cultureGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 20,
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr 1fr",
    },
    "@media (max-width: 580px)": {
      gridTemplateColumns: "1fr",
    },
  },
  cultureCard: {
    background: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: 16,
    padding: "26px 22px",
    transition: "border-color 0.2s, transform 0.2s, box-shadow 0.2s",
    cursor: "default",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-3px)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.08)",
    },
  },
  cultureIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: 16,
  },
  cultureTitle: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: 8,
  },
  cultureText: {
    fontSize: "0.86rem",
    color: "#64748B",
    lineHeight: 1.6,
  },

  /* ─────────────────────────────────────────────────────────────
     MOBILE SECTION
     ───────────────────────────────────────────────────────────── */
  mobileSectionWrapper: {
    padding: "80px 24px",
    background: "linear-gradient(180deg, #FFFFFF 0%, #F8FAFC 100%)",
    "@media (max-width: 768px)": {
      padding: "52px 14px",
    },
  },
  mobileGrid: {
    maxWidth: "1100px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 60,
    alignItems: "center",
    "@media (max-width: 820px)": {
      gridTemplateColumns: "1fr",
      gap: 36,
    },
  },
  mobilePhoneWrapper: {
    display: "flex",
    justifyContent: "center",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 5: ENTERPRISE DATA INTEGRITY
     ───────────────────────────────────────────────────────────────────────────── */
  ediSection: {
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  ediContainer: {
    maxWidth: "1240px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  ediHeader: {
    textAlign: "center",
    maxWidth: "720px",
    margin: "0 auto 64px auto",
    "@media (max-width: 768px)": {
      marginBottom: "40px",
    },
  },
  ediKicker: {
    fontSize: "0.8125rem",
    fontWeight: 800,
    color: "#0072C4",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    marginBottom: "12px",
    display: "inline-block",
  },
  ediTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    lineHeight: 1.15,
    color: "#0F172A",
    margin: "0 0 16px 0",
    letterSpacing: "-0.03em",
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  ediDescription: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: "#475569",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  ediGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "28px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "24px",
      maxWidth: "540px",
      margin: "0 auto",
    },
  },
  ediCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "24px",
    padding: "36px 32px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 4px 20px -4px rgba(0,0,0,0.06), 0 2px 6px -1px rgba(0,0,0,0.03)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxSizing: "border-box",
    transition: "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
    position: "relative",
    overflow: "hidden",
    "&:hover": {
      transform: "translateY(-5px)",
      boxShadow: "0 20px 40px -10px rgba(0,0,0,0.09), 0 4px 12px -2px rgba(0,0,0,0.04)",
      borderColor: "#CBD5E1",
    },
    "@media (max-width: 600px)": {
      padding: "28px 24px",
    },
  },
  ediCardBlueBorder: {
    borderTop: "3px solid #3B82F6",
  },
  ediCardGreenBorder: {
    borderTop: "3px solid #22C55E",
  },
  ediCardPurpleBorder: {
    borderTop: "3px solid #A855F7",
  },
  ediCardTop: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    marginBottom: "24px",
  },
  ediIconBox: {
    width: "50px",
    height: "50px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "22px",
    flexShrink: 0,
    border: "1px solid transparent",
    transition: "transform 0.3s ease",
  },
  ediIconBlue: {
    backgroundColor: "#EFF6FF",
    border: "1px solid #BFDBFE",
    color: "#2563EB",
  },
  ediIconGreen: {
    backgroundColor: "#F0FDF4",
    border: "1px solid #BBF7D0",
    color: "#16A34A",
  },
  ediIconPurple: {
    backgroundColor: "#FAF5FF",
    border: "1px solid #E9D5FF",
    color: "#9333EA",
  },
  ediCardTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "0 0 12px 0",
    letterSpacing: "-0.01em",
  },
  ediCardText: {
    fontSize: "0.875rem",
    lineHeight: 1.65,
    color: "#64748B",
    margin: 0,
  },
  ediCardBottom: {
    marginTop: "auto",
    width: "100%",
  },
  ediBadgeRow: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  ediTagBadge: {
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    color: "#475569",
    fontSize: "0.6875rem",
    fontWeight: 700,
    padding: "5px 10px",
    borderRadius: "6px",
    letterSpacing: "0.04em",
  },
  ediFinanceBadge: {
    display: "inline-block",
    backgroundColor: "#F0FDF4",
    border: "1px solid #BBF7D0",
    color: "#15803D",
    fontSize: "0.6875rem",
    fontWeight: 800,
    padding: "6px 12px",
    borderRadius: "6px",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  ediTerminalBlock: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    padding: "14px 16px",
  },
  ediTerminalText: {
    fontFamily: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace",
    fontSize: "0.75rem",
    color: "#64748B",
    lineHeight: 1.5,
    display: "block",
  },
}));

