import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  dashboardRoot: {
    width: "100%",
    backgroundColor: "#F4F6F9",
    fontFamily: "'Inter', 'Open Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    color: "#1E293B",
    userSelect: "none",
    overflow: "hidden",
    boxSizing: "border-box",
    lineHeight: 1.4,
    fontSize: "12px",
  },

  // Top Dashboard Navbar
  topBar: {
    height: "44px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #E5E7EB",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    boxSizing: "border-box",
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
  },
  weblingsBrandLogo: {
    display: "flex",
    alignItems: "center",
    color: "#0066D8",
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  iconBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#4B5563",
    position: "relative",
    cursor: "pointer",
  },
  notifDot: {
    position: "absolute",
    top: "5px",
    right: "6px",
    width: "5px",
    height: "5px",
    borderRadius: "50%",
    backgroundColor: "#EF4444",
  },
  userAvatarCircle: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#F3F4F6",
    color: "#4B5563",
    fontWeight: 600,
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #E5E7EB",
  },

  // Dashboard Main Body (Sidebar + Content)
  bodyLayout: {
    display: "flex",
    minHeight: "560px",
  },

  // Two-tier slim sidebars matching the screenshot exactly
  sidebarCol1: {
    width: "42px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #E5E7EB",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "8px 0 16px",
    gap: "12px",
    flexShrink: 0,
  },
  sidebarCol2: {
    width: "42px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #E5E7EB",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "8px 0 16px",
    gap: "12px",
    flexShrink: 0,
    "@media (max-width: 900px)": {
      display: "none",
    },
  },
  sideChevron: {
    fontSize: "13px",
    color: "#6B7280",
    lineHeight: 1,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sideAvatar: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#EFF6FF",
    color: "#0072C4",
    border: "1.5px solid #BFDBFE",
    fontSize: "10px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sideIcon: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#4B5563",
    cursor: "pointer",
    position: "relative",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F3F4F6",
      color: "#0072C4",
    },
  },
  sideIconActiveBox: {
    backgroundColor: "#EFF6FF",
    color: "#0072C4 !important",
    border: "1px solid #93C5FD",
  },
  sideIconActiveBar: {
    color: "#0072C4 !important",
    "&::before": {
      content: '""',
      position: "absolute",
      left: "-7px",
      top: "4px",
      bottom: "4px",
      width: "3px",
      backgroundColor: "#0072C4",
      borderRadius: "0 2px 2px 0",
    },
  },
  sidebarSpacer: {
    flex: 1,
  },

  // Main Dashboard Content Area
  contentArea: {
    flex: 1,
    padding: "16px 20px",
    boxSizing: "border-box",
    backgroundColor: "#F3F4F6",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    minWidth: 0,
    overflowX: "hidden",
  },

  // Top Banner
  banner: {
    background: "linear-gradient(90deg, #1B84D8 0%, #2998E6 50%, #4DB2F8 100%)",
    borderRadius: "6px",
    padding: "16px 22px",
    color: "#FFFFFF",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05)",
  },
  bannerCurve: {
    position: "absolute",
    right: "-40px",
    top: "-50px",
    width: "360px",
    height: "200px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(255,255,255,0.18) 0%, rgba(255,255,255,0) 70%)",
    pointerEvents: "none",
  },
  bannerTitle: {
    margin: "0 0 4px 0",
    fontSize: "15px",
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "#FFFFFF",
  },
  bannerSubtext: {
    margin: 0,
    fontSize: "11px",
    color: "rgba(255, 255, 255, 0.9)",
    lineHeight: 1.4,
  },

  // Two-column dashboard grid
  dashGrid: {
    display: "grid",
    gridTemplateColumns: "310px 1fr",
    gap: "14px",
    alignItems: "start",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
    },
  },
  colLeft: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    minWidth: 0,
  },
  colRight: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    minWidth: 0,
  },

  // Card Basics
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "8px",
    border: "1px solid #E5E7EB",
    padding: "12px 14px",
    boxSizing: "border-box",
    transition: "box-shadow 0.2s ease, transform 0.2s ease",
    "&:hover": {
      boxShadow: "0 4px 12px rgba(15, 23, 42, 0.05)",
      transform: "translateY(-1px)",
    },
  },

  // Row with Holiday & Today
  holidayTodayRow: {
    display: "grid",
    gridTemplateColumns: "1.9fr 1fr",
    gap: "10px",
  },
  holidayCard: {
    backgroundColor: "#FFF5F5",
    borderRadius: "8px",
    border: "1px solid #FED7D7",
    padding: "12px 14px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    transition: "box-shadow 0.2s ease, transform 0.2s ease",
    "&:hover": {
      boxShadow: "0 4px 12px rgba(239, 68, 68, 0.06)",
      transform: "translateY(-1px)",
    },
  },
  kickerLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#4B5563",
    marginBottom: "8px",
  },
  holidayContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  holidayLeft: {
    display: "flex",
    flexDirection: "column",
  },
  subSmall: {
    fontSize: "10px",
    color: "#9CA3AF",
    lineHeight: 1.2,
    marginBottom: "2px",
  },
  holidayBold: {
    fontSize: "20px",
    fontWeight: 800,
    color: "#1F2937",
    lineHeight: 1.1,
    marginBottom: "3px",
  },
  holidayDate: {
    fontSize: "9px",
    color: "#6B7280",
    whiteSpace: "nowrap",
  },
  holidayDivider: {
    width: "1px",
    height: "38px",
    backgroundColor: "#FEB2B2",
    margin: "0 6px",
  },
  holidayRight: {
    display: "flex",
    flexDirection: "column",
  },
  holidayNextBold: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#374151",
    lineHeight: 1.2,
    marginBottom: "3px",
  },

  todayTime: {
    fontSize: "15px",
    fontWeight: 800,
    color: "#1F2937",
    lineHeight: 1.2,
    marginBottom: "3px",
  },
  todayDate: {
    fontSize: "10px",
    color: "#6B7280",
    lineHeight: 1.3,
  },

  // Attendance
  cardTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "8px",
  },
  cardTitle: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#1F2937",
    margin: 0,
  },
  cardActionLink: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#0072C4",
    textDecoration: "none",
    cursor: "pointer",
    lineHeight: 1.3,
    "&:hover": {
      textDecoration: "underline",
    },
  },
  attendanceRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "10px",
  },
  clockTime: {
    fontSize: "17px",
    fontWeight: 800,
    color: "#1F2937",
    marginTop: "2px",
  },
  onTimeCol: {
    textAlign: "right",
  },
  onTimeDash: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#1F2937",
    lineHeight: 1,
    marginBottom: "2px",
  },
  onTimeText: {
    fontSize: "10px",
    color: "#6B7280",
  },
  avatarGroup: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    marginTop: "5px",
  },
  initialCircle: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    backgroundColor: "#BFDBFE",
    color: "#1E40AF",
    fontSize: "10px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "translateY(-2px) scale(1.15)",
      zIndex: 5,
    },
  },
  plusCircle: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    backgroundColor: "#E5E7EB",
    color: "#4B5563",
    fontSize: "10px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },

  // Leave Balance Gauges
  leaveLinksContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "3px",
  },
  gaugesRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    padding: "6px 0 2px",
  },
  gaugeItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    cursor: "pointer",
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },
  gaugeLabel: {
    fontSize: "10px",
    fontWeight: 500,
    color: "#6B7280",
  },

  // On Leave Today
  teamRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "6px",
    marginTop: "4px",
  },
  memberItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    cursor: "pointer",
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "translateY(-2px)",
    },
  },
  memberAvatarFrame: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    overflow: "hidden",
    boxShadow: "0 1px 2px rgba(0,0,0,0.08)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "scale(1.1)",
      boxShadow: "0 3px 8px rgba(0,0,0,0.12)",
    },
  },
  memberName: {
    fontSize: "9px",
    color: "#4B5563",
    maxWidth: "46px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "center",
  },
  onLeavePlusCircle: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    border: "1.5px solid #0072C4",
    backgroundColor: "#FFFFFF",
    color: "#0072C4",
    fontSize: "11px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      transform: "scale(1.08)",
      backgroundColor: "#EFF6FF",
    },
  },

  // Mail List Items
  mailHeaderIcons: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#6B7280",
  },
  mailActionIcon: {
    display: "flex",
    alignItems: "center",
    color: "#9CA3AF",
    cursor: "pointer",
    transition: "transform 0.15s ease, color 0.15s ease",
    "&:hover": {
      transform: "scale(1.2)",
      color: "#0072C4",
    },
  },
  mailItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    padding: "8px 6px",
    borderRadius: "6px",
    borderBottom: "1px solid #F3F4F6",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      transform: "translateX(2px)",
    },
    "&:last-child": {
      borderBottom: "none",
      paddingBottom: 0,
    },
  },
  mailAvatarFrame: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    overflow: "hidden",
    flexShrink: 0,
  },
  mailBody: {
    flex: 1,
    minWidth: 0,
  },
  mailRowTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "2px",
  },
  mailSender: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#1F2937",
  },
  mailDate: {
    fontSize: "10px",
    color: "#6B7280",
  },
  mailSnippet: {
    fontSize: "10px",
    color: "#6B7280",
    margin: 0,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  // Announcement Items
  announcementItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    padding: "8px 6px",
    borderRadius: "6px",
    borderBottom: "1px solid #F3F4F6",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      transform: "translateX(2px)",
    },
    "&:last-child": {
      borderBottom: "none",
      paddingBottom: 0,
    },
  },
  announcementAvatarFrame: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    overflow: "hidden",
    flexShrink: 0,
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },
  announcementBody: {
    flex: 1,
    minWidth: 0,
  },
  announcementRowTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "2px",
  },
  announcementSender: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#1F2937",
  },
  announcementTime: {
    fontSize: "9px",
    color: "#6B7280",
  },
  announcementText: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#374151",
    margin: "1px 0",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  announcementSub: {
    fontSize: "9px",
    color: "#6B7280",
    margin: 0,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  teamBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "9px",
    fontWeight: 600,
    color: "#FFFFFF",
    backgroundColor: "#0072C4",
    padding: "2px 7px",
    borderRadius: "3px",
    marginTop: "3px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#0052A3",
    },
  },

  // Calendar Schedule Table
  scheduleGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(8, 1fr)",
    border: "1px solid #E5E7EB",
    borderRadius: "4px",
    overflow: "hidden",
    marginTop: "8px",
    height: "32px",
  },
  scheduleCell: {
    borderRight: "1px solid #E5E7EB",
    backgroundColor: "#FFFFFF",
    padding: "4px",
    boxSizing: "border-box",
    fontSize: "8px",
    color: "#9CA3AF",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#EFF6FF",
    },
    "&:last-child": {
      borderRight: "none",
    },
  },
}));
