import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  mockupFrame: {
    width: "100%",
    maxWidth: "1160px",
    margin: "0 auto",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 20px 50px -10px rgba(0, 0, 0, 0.08), 0 10px 25px -5px rgba(0, 0, 0, 0.04)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    userSelect: "none",
    position: "relative",
  },
  mockupFrameEmbedded: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: "0",
    border: "none",
    boxShadow: "none",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    flex: 1,
    height: "100%",
    minHeight: "680px",
    textAlign: "left",
    userSelect: "none",
    position: "relative",
  },


  /* ─────────────────────────────────────────────────────────────
     TOP APPLICATION BAR
     ───────────────────────────────────────────────────────────── */
  topBar: {
    height: "54px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #EAECF0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 20px",
    flexShrink: 0,
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  bellBtn: {
    position: "relative",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "6px",
    color: "#475569",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  bellDot: {
    position: "absolute",
    top: "6px",
    right: "6px",
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#E11D48",
    border: "1.5px solid #FFFFFF",
  },
  topProfileAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#F1F5F9",
    color: "#334155",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    fontSize: "0.8125rem",
    border: "1px solid #E2E8F0",
    cursor: "pointer",
    transition: "transform 0.2s",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     MAIN WORKSPACE BODY: LEFT RAIL + CENTER STAGE + RIGHT SIDEBAR
     ───────────────────────────────────────────────────────────── */
  mainBody: {
    display: "flex",
    flex: 1,
    minHeight: 0,
    backgroundColor: "#FFFFFF",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      minHeight: "auto",
    },
  },

  /* LEFT ICON RAIL */
  leftRail: {
    width: "56px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "12px 0",
    flexShrink: 0,
    gap: "10px",
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  railChevronBtn: {
    background: "transparent",
    border: "none",
    color: "#64748B",
    cursor: "pointer",
    fontSize: "0.875rem",
    padding: "4px",
    borderRadius: "4px",
    "&:hover": {
      color: "#0F172A",
      backgroundColor: "#F1F5F9",
    },
  },
  railAvatar: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#EBF5FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.875rem",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    cursor: "pointer",
  },
  railDivider: {
    width: "32px",
    height: "1px",
    backgroundColor: "#E2E8F0",
    margin: "4px 0",
  },
  railNavList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "100%",
    alignItems: "center",
  },
  railNavItem: {
    width: "42px",
    height: "42px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    background: "transparent",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
    position: "relative",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      color: "#0F172A",
    },
  },
  railNavItemActive: {
    color: "#0072C4",
    backgroundColor: "#F0F7FF",
    borderRadius: "0 8px 8px 0",
    width: "100%",
    borderLeft: "3px solid #0072C4",
    "&:hover": {
      backgroundColor: "#F0F7FF",
      color: "#0072C4",
    },
  },
  railBottomGroup: {
    marginTop: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    alignItems: "center",
  },

  /* CENTER STAGE WRAPPER */
  centerStageWrapper: {
    flex: 1,
    minWidth: 0,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#FAFAFA",
  },

  /* BLUE-BORDERED MEETING BOX (CENTER PIECE) */
  meetingCanvas: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "2px solid #0072C4",
    position: "relative",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 20px -2px rgba(0, 114, 196, 0.08)",
  },

  /* Screen share presentation overlay mode */
  screenShareOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "#0F172A",
    color: "#F8FAFC",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    padding: "20px",
  },
  screenShareBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 12px",
    borderRadius: "20px",
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    color: "#34D399",
    fontSize: "0.75rem",
    fontWeight: 700,
    marginBottom: "16px",
    border: "1px solid rgba(52, 211, 153, 0.3)",
  },
  screenShareTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    marginBottom: "8px",
  },
  screenShareSub: {
    fontSize: "0.875rem",
    color: "#94A3B8",
    textAlign: "center",
    maxWidth: "400px",
    marginBottom: "20px",
  },
  stopShareBtn: {
    backgroundColor: "#E11D48",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    padding: "8px 18px",
    fontWeight: 600,
    fontSize: "0.8125rem",
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#BE123C",
    },
  },

  /* ACTIVE SPEAKER AT THE CENTER */
  centerSpeakerHub: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 3,
  },
  centerAvatarContainer: {
    position: "relative",
    width: "120px",
    height: "120px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  circularSoundwaveSvg: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "150px",
    height: "150px",
    pointerEvents: "none",
    zIndex: 1,
    animation: "$pulseWave 2s ease-in-out infinite",
  },
  "@keyframes pulseWave": {
    "0%": {
      transform: "translate(-50%, -50%) scale(0.96)",
      opacity: 0.85,
    },
    "50%": {
      transform: "translate(-50%, -50%) scale(1.05)",
      opacity: 1,
    },
    "100%": {
      transform: "translate(-50%, -50%) scale(0.96)",
      opacity: 0.85,
    },
  },
  centerAvatarCircle: {
    width: "70px",
    height: "70px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    border: "2px solid #0072C4",
    boxShadow: "0 4px 18px rgba(0, 114, 196, 0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    fontSize: "1.875rem",
    fontWeight: 700,
    position: "relative",
    zIndex: 2,
    cursor: "pointer",
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "scale(1.06)",
    },
  },
  centerSpeakerNameTag: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "8px",
    color: "#0F172A",
    fontSize: "0.875rem",
    fontWeight: 700,
  },
  micActiveIcon: {
    color: "#0F172A",
  },

  /* SATELLITE PARTICIPANTS */
  satelliteNode: {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    transform: "translate(-50%, -50%)",
    cursor: "pointer",
    zIndex: 2,
    transition: "transform 0.2s cubic-bezier(0.34, 1.45, 0.64, 1)",
    "&:hover": {
      transform: "translate(-50%, -50%) scale(1.12)",
    },
  },
  satelliteAvatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#EBF5FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.9375rem",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)",
    position: "relative",
    overflow: "hidden",
  },
  pinnedSplitAvatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#EBF5FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.875rem",
    paddingTop: "2px",
    border: "1px solid #1E293B",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  pinnedBottomHalf: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "18px",
    backgroundColor: "#0F172A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
  },
  satelliteLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginTop: "4px",
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#475569",
  },
  satelliteMutedIcon: {
    color: "#94A3B8",
    fontSize: "0.6875rem",
  },

  /* ─────────────────────────────────────────────────────────────
     RIGHT SIDEBAR: PARTICIPANTS PANEL
     ───────────────────────────────────────────────────────────── */
  rightSidebar: {
    width: "290px",
    backgroundColor: "#FFFFFF",
    borderLeft: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    transition: "margin-right 0.3s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.3s ease",
    "@media (max-width: 900px)": {
      width: "100%",
      borderLeft: "none",
      borderTop: "1px solid #EAECF0",
    },
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 18px",
    borderBottom: "1px solid #F1F5F9",
  },
  sidebarTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  closeBtn: {
    background: "transparent",
    border: "none",
    color: "#64748B",
    cursor: "pointer",
    fontSize: "1rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px",
    borderRadius: "6px",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  sidebarBody: {
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    overflowY: "auto",
    flex: 1,
    minHeight: 0,
  },
  inviteRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    "&:focus-within": {
      borderColor: "#0072C4",
      boxShadow: "0 0 0 2px rgba(0, 114, 196, 0.15)",
    },
  },
  inviteInput: {
    border: "none",
    outline: "none",
    width: "100%",
    fontSize: "0.8125rem",
    color: "#0F172A",
    "&::placeholder": {
      color: "#94A3B8",
    },
  },
  accordionToggle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#1E293B",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    padding: "4px 0",
    textAlign: "left",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "7px 10px",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    "&:focus-within": {
      borderColor: "#0072C4",
    },
  },
  searchInput: {
    border: "none",
    outline: "none",
    width: "100%",
    fontSize: "0.8125rem",
    color: "#0F172A",
    "&::placeholder": {
      color: "#94A3B8",
    },
  },
  sectionSubheading: {
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0F172A",
    marginTop: "4px",
  },
  peoplesList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  peopleItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "6px 8px",
    borderRadius: "8px",
    transition: "background-color 0.15s",
    "&:hover": {
      backgroundColor: "#F8FAFC",
    },
  },
  peopleLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  peopleAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#EBF5FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.75rem",
  },
  peopleName: {
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "#1E293B",
  },
  peopleActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  actionMicBtn: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "4px",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    "&:hover": {
      backgroundColor: "#E2E8F0",
      color: "#0F172A",
    },
  },
  actionDotsBtn: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "4px",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    "&:hover": {
      backgroundColor: "#E2E8F0",
      color: "#0F172A",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     BOTTOM CONTROL DOCK / TOOLBAR
     ───────────────────────────────────────────────────────────── */
  bottomDock: {
    height: "64px",
    backgroundColor: "#FFFFFF",
    borderTop: "1px solid #EAECF0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 20px",
    flexShrink: 0,
    gap: "12px",
    "@media (max-width: 768px)": {
      flexWrap: "wrap",
      height: "auto",
      padding: "12px 16px",
      gap: "8px",
    },
  },
  dockLeft: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  meetingTitleRow: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  meetingTitleText: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  recordingBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "0.6875rem",
    fontWeight: 700,
    color: "#E11D48",
    cursor: "pointer",
  },
  recordingDotPulsing: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#E11D48",
    animation: "$recPulse 1.5s infinite",
  },
  "@keyframes recPulse": {
    "0%": {
      opacity: 1,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.4,
      transform: "scale(1.25)",
    },
    "100%": {
      opacity: 1,
      transform: "scale(1)",
    },
  },

  /* CENTER CONTROLS PILL GROUP */
  dockCenterGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  controlPillBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#F8FAFC",
    color: "#334155",
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontWeight: 600,
    transition: "all 0.2s",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      borderColor: "#CBD5E1",
    },
  },
  controlPillBlue: {
    backgroundColor: "#EBF5FF",
    borderColor: "#BFDBFE",
    color: "#0072C4",
    "&:hover": {
      backgroundColor: "#DBEAFE",
      borderColor: "#93C5FD",
    },
  },
  controlPillMuted: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FECACA",
    color: "#DC2626",
    "&:hover": {
      backgroundColor: "#FCA5A5",
    },
  },
  recordControlBtn: {
    width: "38px",
    height: "38px",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.2s",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      borderColor: "#CBD5E1",
    },
  },
  recordDotInner: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#E11D48",
  },
  endCallBtn: {
    backgroundColor: "#E11D48",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(225, 29, 72, 0.25)",
    transition: "all 0.2s",
    "&:hover": {
      backgroundColor: "#BE123C",
      transform: "scale(1.04)",
    },
  },

  /* RIGHT UTILITY GROUP */
  dockRightGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  dockUtilBtn: {
    position: "relative",
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "transparent",
    color: "#475569",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.2s",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  dockBadgeCount: {
    position: "absolute",
    top: "-3px",
    right: "-3px",
    backgroundColor: "#E11D48",
    color: "#FFFFFF",
    fontSize: "0.625rem",
    fontWeight: 800,
    borderRadius: "10px",
    padding: "1px 5px",
    lineHeight: "13px",
  },
}));
