import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes ping": {
    "75%, 100%": {
      transform: "scale(2)",
      opacity: 0,
    },
  },
  hud: {
    borderRadius: "24px",
    border: "1px solid rgba(255,255,255,0.06)",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    padding: "24px 28px",
    boxShadow: "0 25px 60px -15px rgba(15, 23, 42, 0.5)",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "20px",
      borderRadius: "20px",
    },
  },
  glowTopRight: {
    position: "absolute",
    right: "-80px",
    top: "-80px",
    width: "240px",
    height: "240px",
    background: "rgba(14, 165, 233, 0.15)",
    borderRadius: "50%",
    filter: "blur(60px)",
    pointerEvents: "none",
  },
  glowBottomLeft: {
    position: "absolute",
    left: "-80px",
    bottom: "-80px",
    width: "240px",
    height: "240px",
    background: "rgba(99, 102, 241, 0.15)",
    borderRadius: "50%",
    filter: "blur(60px)",
    pointerEvents: "none",
  },
  hudHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    paddingBottom: "16px",
    marginBottom: "20px",
  },
  hudHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  pingContainer: {
    display: "flex",
    height: "12px",
    width: "12px",
    position: "relative",
  },
  pingRing: {
    position: "absolute",
    display: "inline-flex",
    height: "100%",
    width: "100%",
    borderRadius: "50%",
    backgroundColor: "#34D399",
    opacity: 0.75,
    animation: "$ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
  },
  pingDot: {
    position: "relative",
    display: "inline-flex",
    borderRadius: "50%",
    height: "12px",
    width: "12px",
    backgroundColor: "#10B981",
  },
  hudLabel: {
    fontFamily: "monospace, sans-serif",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    color: "#CBD5E1",
    fontWeight: 600,
  },
  syncBadge: {
    padding: "2px 10px",
    borderRadius: "9999px",
    fontSize: "11px",
    fontFamily: "monospace, sans-serif",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    color: "#38BDF8",
    border: "1px solid rgba(56, 189, 248, 0.3)",
  },
  systemsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
    marginBottom: "20px",
  },
  systemNode: {
    backgroundColor: "rgba(30, 41, 59, 0.6)",
    borderRadius: "12px",
    padding: "12px",
    border: "1px solid rgba(51, 65, 85, 0.6)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  systemIcon: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "11px",
  },
  systemIconSky: {
    backgroundColor: "rgba(14, 165, 233, 0.15)",
    color: "#38BDF8",
  },
  systemIconIndigo: {
    backgroundColor: "rgba(99, 102, 241, 0.15)",
    color: "#818CF8",
  },
  systemIconBlue: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    color: "#60A5FA",
  },
  systemIconTeal: {
    backgroundColor: "rgba(20, 184, 166, 0.15)",
    color: "#2DD4BF",
  },
  systemInfo: {
    minWidth: 0,
  },
  systemName: {
    fontSize: "12px",
    fontWeight: 600,
    color: "#E2E8F0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  systemStatus: {
    fontSize: "10px",
    color: "#34D399",
    fontFamily: "monospace, sans-serif",
  },
  streamContainer: {
    backgroundColor: "rgba(2, 6, 23, 0.8)",
    borderRadius: "16px",
    padding: "16px",
    border: "1px solid rgba(30, 41, 59, 0.9)",
    fontFamily: "monospace, sans-serif",
    fontSize: "12px",
  },
  streamHeader: {
    fontSize: "11px",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    marginBottom: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  streamLabel: {
    color: "#38BDF8",
    fontSize: "10px",
  },
  streamEvents: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    fontSize: "11.5px",
    lineHeight: 1.5,
  },
  streamEvent: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    color: "#CBD5E1",
  },
  arrowSky: { color: "#38BDF8" },
  arrowIndigo: { color: "#818CF8" },
  arrowTeal: { color: "#2DD4BF" },
  highlight: { color: "#34D399" },
  highlightWhite: { color: "#FFFFFF" },
  highlightSky: { color: "#7DD3FC" },
  telemetry: {
    marginTop: "16px",
    paddingTop: "12px",
    borderTop: "1px solid rgba(30, 41, 59, 0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "11px",
    color: "#64748B",
    fontFamily: "monospace, sans-serif",
  },
  telemetryGreen: {
    color: "#34D399",
    fontWeight: 600,
  },
}));
