'use client';

import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes fadeIn": {
    "0%": {
      opacity: 0,
    },
    "100%": {
      opacity: 1,
    },
  },
  "@keyframes modalPop": {
    "0%": {
      opacity: 0,
      transform: "scale(0.92) translateY(16px)",
    },
    "100%": {
      opacity: 1,
      transform: "scale(1) translateY(0)",
    },
  },
  backdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 99999,
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    boxSizing: "border-box",
    animation: "$fadeIn 0.25s ease-out forwards",
  },
  modalCard: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    borderRadius: "24px",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    boxShadow:
      "0 25px 60px -15px rgba(15, 23, 42, 0.35), 0 0 0 1px rgba(15, 23, 42, 0.05)",
    width: "100%",
    maxWidth: "460px",
    padding: "36px 28px 28px 28px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxSizing: "border-box",
    animation: "$modalPop 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
  },
  closeBtn: {
    position: "absolute",
    top: "16px",
    right: "16px",
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#F1F5F9",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    zIndex: 10,
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#E2E8F0",
      color: "#0F172A",
      transform: "rotate(90deg)",
    },
  },
  // Static status icons for warning / error (no party animation)
  warningIconBox: {
    width: "72px",
    height: "72px",
    borderRadius: "50%",
    backgroundColor: "#FEF3C7",
    border: "2px solid #FCD34D",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#D97706",
    margin: "0 auto 16px auto",
    boxShadow: "0 8px 20px rgba(217, 119, 6, 0.15)",
    position: "relative",
    zIndex: 4,
  },
  errorIconBox: {
    width: "72px",
    height: "72px",
    borderRadius: "50%",
    backgroundColor: "#FEE2E2",
    border: "2px solid #FCA5A5",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#DC2626",
    margin: "0 auto 16px auto",
    boxShadow: "0 8px 20px rgba(220, 38, 38, 0.15)",
    position: "relative",
    zIndex: 4,
  },
  // Badge Pills
  badgePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 12px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "8px",
    position: "relative",
    zIndex: 4,
  },
  badgeSuccess: {
    backgroundColor: "#ECFDF5",
    border: "1px solid #A7F3D0",
    color: "#059669",
  },
  badgeWarning: {
    backgroundColor: "#FEF3C7",
    border: "1px solid #FDE68A",
    color: "#B45309",
  },
  badgeError: {
    backgroundColor: "#FEE2E2",
    border: "1px solid #FECACA",
    color: "#DC2626",
  },
  title: {
    fontSize: "1.375rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: "8px 0",
    lineHeight: 1.3,
    position: "relative",
    zIndex: 4,
  },
  message: {
    fontSize: "0.9375rem",
    color: "#475569",
    lineHeight: 1.6,
    margin: "0 0 24px 0",
    maxWidth: "390px",
    position: "relative",
    zIndex: 4,
    "& strong": {
      color: "#0F172A",
      fontWeight: 600,
    },
  },
  // Action Buttons
  actionBtn: {
    width: "100%",
    padding: "13px 24px",
    borderRadius: "12px",
    fontSize: "0.9375rem",
    fontWeight: 600,
    cursor: "pointer",
    border: "none",
    position: "relative",
    zIndex: 4,
    transition: "all 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.08)",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 6px 16px rgba(0, 0, 0, 0.12)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  actionBtnSuccess: {
    background: "linear-gradient(135deg, #059669 0%, #10B981 100%)",
    color: "#FFFFFF",
    "&:hover": {
      background: "linear-gradient(135deg, #047857 0%, #059669 100%)",
    },
  },
  actionBtnWarning: {
    background: "linear-gradient(135deg, #0F172A 0%, #1E293B 100%)",
    color: "#FFFFFF",
    "&:hover": {
      background: "linear-gradient(135deg, #1E293B 0%, #334155 100%)",
    },
  },
  actionBtnError: {
    background: "linear-gradient(135deg, #DC2626 0%, #EF4444 100%)",
    color: "#FFFFFF",
    "&:hover": {
      background: "linear-gradient(135deg, #B91C1C 0%, #DC2626 100%)",
    },
  },
}));
