import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  pageWrapper: {
    width: "100%",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────────────────────── */
  heroSection: {
    position: "relative",
    paddingTop: "56px",
    paddingBottom: "80px",
    paddingLeft: "24px",
    paddingRight: "24px",
    maxWidth: "1280px",
    margin: "0 auto",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      paddingTop: "40px",
      paddingBottom: "56px",
      paddingLeft: "16px",
      paddingRight: "16px",
    },
  },
  heroGlow: {
    position: "absolute",
    top: "30%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "600px",
    height: "380px",
    background: theme.light.brand.surface.lighter,
    filter: "blur(110px)",
    opacity: 0.85,
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobBrand: {
    position: "absolute",
    top: "80px",
    left: "12%",
    width: "420px",
    height: "420px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobInfo: {
    position: "absolute",
    bottom: "60px",
    right: "10%",
    width: "380px",
    height: "380px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.65,
    pointerEvents: "none",
    zIndex: 0,
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "44px",
  },
  eyebrowPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    marginBottom: "20px",
    boxShadow: theme.elevation.s,
    width: "fit-content",
  },
  eyebrowText: {
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
  },
  heroTitle: {
    fontSize: "3.5rem",
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 20px 0",
    maxWidth: "920px",
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.875rem",
    },
  },
  heroTitleAccent: {
    display: "block",
    backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`,
    WebkitBackgroundClip: "text",
    backgroundClip: "text",
    color: "transparent",
  },
  heroParagraph: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 32px 0",
    maxWidth: "800px",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroCtaButton: {
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    border: "none",
    borderRadius: theme.borderRadius.b300,
    padding: "14px 34px",
    fontSize: "1rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 6px 24px rgba(0, 114, 196, 0.35)",
    transition: "all 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.dark,
      transform: "translateY(-2px)",
      boxShadow: "0 10px 30px rgba(0, 114, 196, 0.45)",
    },
  },
  mockupWrapper: {
    position: "relative",
    zIndex: 2,
    marginTop: "24px",
    width: "100%",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 1: ENTERPRISE ARCHITECTURE CARDS
     ───────────────────────────────────────────────────────────────────────────── */
  sectionWrapper: {
    padding: "80px 24px",
    maxWidth: "1280px",
    margin: "0 auto",
    boxSizing: "border-box",
    position: "relative",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  sectionHeaderCenter: {
    textAlign: "center",
    maxWidth: "780px",
    margin: "0 auto 52px auto",
  },
  kicker: {
    fontSize: "0.8125rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
    marginBottom: "12px",
    display: "inline-block",
  },
  sectionTitle: {
    fontSize: "2.375rem",
    fontWeight: 800,
    letterSpacing: "-0.025em",
    lineHeight: 1.25,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 16px 0",
    "@media (max-width: 768px)": {
      fontSize: "1.75rem",
    },
  },
  sectionDescription: {
    fontSize: "1.0625rem",
    lineHeight: 1.65,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "24px",
  },
  featureCard: {
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: theme.borderRadius.b500,
    border: `1px solid ${theme.light.neutral.border.light}`,
    padding: "32px 24px",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    boxShadow: theme.elevation.s,
    transition: "all 0.25s cubic-bezier(0.34, 1.45, 0.64, 1)",
    position: "relative",
    cursor: "pointer",
    "&:hover": {
      transform: "translateY(-6px)",
      borderColor: theme.light.brand.border.medium,
      boxShadow: "0 18px 36px -10px rgba(0, 114, 196, 0.15)",
    },
  },
  featureCardHovered: {
    transform: "translateY(-6px)",
    borderColor: `${theme.light.brand.border.medium} !important`,
    boxShadow: "0 18px 36px -10px rgba(0, 114, 196, 0.15) !important",
  },
  featureIconWrapper: {
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "20px",
  },
  cardTitle: {
    fontSize: "1.1875rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 10px 0",
  },
  cardDescription: {
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 2: AUTOMATED SCOPE-TO-SPRINT PIPELINE (STEPPER)
     ───────────────────────────────────────────────────────────────────────────── */
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  pipelineContainer: {
    maxWidth: "1120px",
    margin: "0 auto",
    width: "100%",
  },
  pipelineGraphicCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "24px",
    border: "1.5px solid #E2E8F0",
    boxShadow: "0 20px 45px -12px rgba(0, 114, 196, 0.12), 0 4px 16px rgba(15, 23, 42, 0.04)",
    padding: "36px 40px",
    display: "flex",
    flexDirection: "column",
    gap: "28px",
    "@media (max-width: 768px)": {
      padding: "20px 16px",
      gap: "20px",
      borderRadius: "16px",
    },
  },
  pipelineStepsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gap: "12px",
    },
  },
  pipelineFlowStep: {
    display: "flex",
    alignItems: "flex-start",
    gap: "16px",
    padding: "20px",
    borderRadius: "14px",
    backgroundColor: "#F8FAFC",
    border: "1.5px solid #E2E8F0",
    transition: "all 0.25s cubic-bezier(0.34, 1.56, 0.64, 1)",
    cursor: "pointer",
    textAlign: "left",
    position: "relative",
    "&:hover": {
      transform: "translateY(-3px)",
      borderColor: "#93C5FD",
      backgroundColor: "#F0F7FF",
    },
  },
  pipelineFlowStepActive: {
    backgroundColor: "#FFFFFF !important",
    borderColor: "#0072C4 !important",
    boxShadow: "0 10px 25px -4px rgba(0, 114, 196, 0.18) !important",
    transform: "translateY(-3px) !important",
  },
  pipelineStepIconBadge: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    border: "1.5px solid #DBEAFE",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "1rem",
    flexShrink: 0,
    boxShadow: "0 2px 8px rgba(0, 114, 196, 0.08)",
  },
  pipelineStepText: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  pipelineStepHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "2px",
  },
  pipelineStepTag: {
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    padding: "2px 8px",
    borderRadius: "6px",
    backgroundColor: "#E0F2FE",
    color: "#0284C7",
  },
  pipelineStepTitle: {
    fontSize: "1rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
    lineHeight: 1.3,
  },
  pipelineStepSub: {
    fontSize: "0.8125rem",
    lineHeight: 1.5,
    color: "#64748B",
    margin: 0,
  },
  pipelineShowcaseCard: {
    borderRadius: "16px",
    padding: "24px 28px",
    border: "1.5px solid #E2E8F0",
    transition: "all 0.3s ease",
    "@media (max-width: 768px)": {
      padding: "16px",
    },
  },
  stepperList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  stepItem: {
    display: "flex",
    gap: "16px",
    padding: "18px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
    transition: "border-color 0.2s ease, background-color 0.2s ease, box-shadow 0.2s ease",
    cursor: "pointer",
    "&:hover": {
      borderColor: "#0072C4",
      backgroundColor: "#F8FAFC",
    },
  },
  stepItemActive: {
    borderColor: "#0072C4 !important",
    backgroundColor: "#F0F7FF !important",
    boxShadow: "0 4px 14px rgba(0, 114, 196, 0.1) !important",
  },
  stepNumberBadge: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontWeight: 800,
    fontSize: "0.9375rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },


  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 3: SEMANTIC VECTOR SEARCH
     ───────────────────────────────────────────────────────────────────────────── */
  searchDemoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.m,
    padding: "28px",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  searchQueryBox: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    borderRadius: "10px",
    backgroundColor: "#F1F5F9",
    border: "1.5px solid #CBD5E1",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "#0F172A",
  },
  searchResultCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #93C5FD",
    padding: "16px",
    boxShadow: "0 4px 14px rgba(0, 114, 196, 0.08)",
  },
  searchScoreTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "0.6875rem",
    fontWeight: 800,
    color: "#16A34A",
    backgroundColor: "#F0FDF4",
    padding: "2px 8px",
    borderRadius: "6px",
    marginBottom: "8px",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 4: IMMUTABLE AUDIT TRAIL
     ───────────────────────────────────────────────────────────────────────────── */
  auditCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.m,
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  auditRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    padding: "12px",
    borderRadius: "8px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #EEF2F6",
  },
  auditAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#E2E8F0",
    color: "#0F172A",
    fontWeight: 700,
    fontSize: "0.8125rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  auditText: {
    fontSize: "0.8125rem",
    lineHeight: 1.5,
    color: "#334155",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 5: MOBILE SECTION
     ───────────────────────────────────────────────────────────────────────────── */
  mobileSection: {
    padding: "80px 24px",
    maxWidth: "1280px",
    margin: "0 auto",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  mobileSplit: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  mobilePhoneCol: {
    display: "flex",
    justifyContent: "center",
  },
  mobileDetailsCol: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  mobileFeaturesList: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    marginTop: "8px",
  },
  mobileFeatureItem: {
    display: "flex",
    gap: "14px",
    alignItems: "flex-start",
  },
  mobileFeatureIcon: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: "2px",
  },
  storeButtonsRow: {
    display: "flex",
    gap: "14px",
    marginTop: "16px",
    flexWrap: "wrap",
  },
  appStoreBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    padding: "10px 20px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    borderRadius: "10px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 4px 14px rgba(15, 23, 42, 0.2)",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#1E293B",
      transform: "translateY(-2px)",
      boxShadow: "0 6px 18px rgba(15, 23, 42, 0.3)",
    },
  },
  appStoreBtnTextCol: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
  },
  appStoreSub: {
    fontSize: "0.625rem",
    fontWeight: 500,
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  appStoreTitle: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.2,
  },
  ratingBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "8px",
    fontSize: "0.8125rem",
    color: theme.light.neutral.onSurface.medium,
  },
  ratingStars: {
    color: "#F59E0B",
    display: "flex",
    gap: "2px",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 6: ENTERPRISE FEATURES GRID
     ───────────────────────────────────────────────────────────────────────────── */
  includedGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "20px",
    marginTop: "40px",
  },
  includedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    padding: "24px 20px",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    boxShadow: theme.elevation.s,
    transition: "all 0.2s ease",
    "&:hover": {
      borderColor: theme.light.brand.border.medium,
      transform: "translateY(-3px)",
      boxShadow: "0 12px 24px -6px rgba(0, 114, 196, 0.12)",
    },
  },
}));
