import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes eofficeBlink": {
    "0%, 100%": { opacity: 0.4 },
    "50%": { opacity: 1 },
  },
  "@keyframes eofficePulseSoft": {
    "0%, 100%": { transform: "scale(1)", opacity: 0.9 },
    "50%": { transform: "scale(1.05)", opacity: 1 },
  },

  mockupFrame: {
    width: "100%",
    maxWidth: "1160px",
    margin: "0 auto",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 20px 50px -10px rgba(0, 0, 0, 0.08), 0 10px 25px -5px rgba(0, 0, 0, 0.04)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    userSelect: "none",
    position: "relative",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },

  /* ─────────────────────────────────────────────────────────────
     TOP APPLICATION BAR
     ───────────────────────────────────────────────────────────── */
  topBar: {
    height: "54px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #EAECF0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 20px",
    flexShrink: 0,
    "@media (max-width: 640px)": {
      padding: "0 12px",
      height: "48px",
    },
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  appNameBadge: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  appName: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#0F172A",
    letterSpacing: "-0.01em",
  },
  appBreadcrumb: {
    fontSize: "0.75rem",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    "&::before": {
      content: "'/'",
      color: "#CBD5E1",
    },
    "@media (max-width: 640px)": {
      display: "none",
    },
  },

  topBarCenter: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    borderRadius: "20px",
    padding: "4px 12px",
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  shiftStatusDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    boxShadow: "0 0 6px #10B981",
    animation: "$eofficeBlink 2s infinite ease-in-out",
  },
  shiftText: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#0072C4",
  },
  shiftSub: {
    fontSize: "0.7rem",
    color: "#64748B",
  },

  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  punchButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "5px 12px",
    borderRadius: "8px",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    border: "none",
    transition: "all 0.2s ease",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    "&:hover": {
      backgroundColor: "#0284C7",
    },
  },
  punchButtonOut: {
    backgroundColor: "#FEF2F2",
    color: "#DC2626",
    border: "1px solid #FECDD3",
    "&:hover": {
      backgroundColor: "#FEE2E2",
    },
  },
  bellBtn: {
    position: "relative",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "6px",
    color: "#475569",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  bellDot: {
    position: "absolute",
    top: "6px",
    right: "6px",
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#E11D48",
    border: "1.5px solid #FFFFFF",
  },
  profileWrap: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "3px 8px 3px 4px",
    borderRadius: "20px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    cursor: "pointer",
  },
  topProfileAvatar: {
    width: "26px",
    height: "26px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.75rem",
  },
  topProfileName: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#0F172A",
    "@media (max-width: 640px)": {
      display: "none",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     MAIN BODY LAYOUT
     ───────────────────────────────────────────────────────────── */
  mainBody: {
    display: "flex",
    minHeight: "560px",
    backgroundColor: "#F8FAFC",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      minHeight: "auto",
    },
  },

  /* LEFT ICON RAIL */
  leftRail: {
    width: "60px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "14px 0",
    flexShrink: 0,
    gap: "8px",
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  railNavItem: {
    width: "38px",
    height: "38px",
    borderRadius: "10px",
    border: "none",
    background: "transparent",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.18s ease",
    position: "relative",
    "&:hover": {
      backgroundColor: "#F0F7FF",
      color: "#0072C4",
    },
  },
  railNavItemActive: {
    backgroundColor: "#EFF6FF",
    color: "#0072C4",
    fontWeight: 700,
    "&::before": {
      content: "''",
      position: "absolute",
      left: "-11px",
      top: "8px",
      bottom: "8px",
      width: "3px",
      borderRadius: "0 3px 3px 0",
      backgroundColor: "#0072C4",
    },
  },
  railDivider: {
    width: "28px",
    height: "1px",
    backgroundColor: "#E2E8F0",
    margin: "6px 0",
  },

  /* CENTER STAGE CANVAS */
  centerStage: {
    flex: 1,
    padding: "20px 24px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    "@media (max-width: 640px)": {
      padding: "14px",
      gap: "14px",
    },
  },

  /* Greeting Header */
  greetingBanner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    "@media (max-width: 640px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "8px",
    },
  },
  greetingTitle: {
    fontSize: "1.1rem",
    fontWeight: 800,
    color: "#0F172A",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  greetingSub: {
    fontSize: "0.78rem",
    color: "#64748B",
    marginTop: "2px",
  },
  locationPill: {
    fontSize: "0.72rem",
    fontWeight: 600,
    color: "#0072C4",
    backgroundColor: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    padding: "4px 10px",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },

  /* 3 Metric Cards Grid */
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "14px",
    "@media (max-width: 800px)": {
      gridTemplateColumns: "1fr",
    },
  },
  metricCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #E2E8F0",
    padding: "16px",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.02)",
    transition: "transform 0.18s ease, box-shadow 0.18s ease, border-color 0.18s ease",
    "&:hover": {
      borderColor: "#0072C4",
      boxShadow: "0 6px 18px rgba(0, 114, 196, 0.08)",
      transform: "translateY(-1px)",
    },
  },
  metricCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  metricLabel: {
    fontSize: "0.72rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "#64748B",
  },
  metricIconWrap: {
    width: "28px",
    height: "28px",
    borderRadius: "8px",
    backgroundColor: "#F0F7FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  metricIconWrapGreen: {
    backgroundColor: "#ECFDF5",
    color: "#059669",
  },
  metricIconWrapAmber: {
    backgroundColor: "#FFFBEB",
    color: "#D97706",
  },
  metricValue: {
    fontSize: "1.35rem",
    fontWeight: 800,
    color: "#0F172A",
    fontFamily: "monospace",
    letterSpacing: "-0.02em",
  },
  metricFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "8px",
    fontSize: "0.7rem",
    color: "#64748B",
  },
  progressBarBg: {
    width: "100%",
    height: "5px",
    borderRadius: "3px",
    backgroundColor: "#F1F5F9",
    marginTop: "8px",
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: "3px",
    backgroundColor: "#0072C4",
    transition: "width 0.4s ease",
  },

  /* Leave Balance Mini Row */
  leaveBalanceRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "4px",
  },
  leaveBalanceItem: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderRadius: "6px",
    padding: "6px 8px",
    border: "1px solid #E2E8F0",
    textAlign: "center",
  },
  leaveBalanceNum: {
    fontSize: "0.92rem",
    fontWeight: 800,
    color: "#0072C4",
  },
  leaveBalanceType: {
    fontSize: "0.62rem",
    color: "#64748B",
    fontWeight: 600,
    textTransform: "uppercase",
  },

  /* Culture / Town Square Social Feed Section */
  socialSection: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #E2E8F0",
    padding: "16px",
    boxShadow: "0 2px 6px rgba(0, 0, 0, 0.02)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  socialHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid #F1F5F9",
    paddingBottom: "10px",
  },
  socialTitle: {
    fontSize: "0.82rem",
    fontWeight: 700,
    color: "#0F172A",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  pinnedBadge: {
    fontSize: "0.65rem",
    fontWeight: 700,
    color: "#D97706",
    backgroundColor: "#FFFBEB",
    border: "1px solid #FDE68A",
    padding: "2px 6px",
    borderRadius: "4px",
  },

  /* Announcement Card */
  announcementCard: {
    backgroundColor: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    borderRadius: "10px",
    padding: "12px 14px",
    display: "flex",
    gap: "12px",
  },
  announcementIcon: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  announcementBody: {
    flex: 1,
  },
  announcementHeadline: {
    fontSize: "0.8rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "3px",
  },
  announcementSnippet: {
    fontSize: "0.72rem",
    color: "#475569",
    lineHeight: 1.45,
  },

  /* Interactive Poll Box */
  pollBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    padding: "12px 14px",
  },
  pollQuestion: {
    fontSize: "0.78rem",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pollMeta: {
    fontSize: "0.68rem",
    color: "#64748B",
    fontWeight: 500,
  },
  pollOptions: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  pollOptionBtn: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "7px 10px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "0.72rem",
    fontWeight: 600,
    color: "#334155",
    transition: "all 0.18s ease",
    position: "relative",
    overflow: "hidden",
    "&:hover": {
      borderColor: "#0072C4",
      backgroundColor: "#F0F7FF",
    },
  },
  pollOptionBtnActive: {
    borderColor: "#0072C4",
    backgroundColor: "#F0F7FF",
    color: "#0072C4",
    fontWeight: 700,
  },
  pollPctBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    zIndex: 0,
  },

  /* Praise/Kudos Box */
  praiseBox: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    padding: "10px 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
  },
  praiseLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  praiseAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#ECFDF5",
    color: "#059669",
    border: "1px solid #A7F3D0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.72rem",
    fontWeight: 700,
  },
  praiseText: {
    fontSize: "0.72rem",
    color: "#334155",
  },
  praiseBtn: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    backgroundColor: "#FEF2F2",
    color: "#E11D48",
    border: "1px solid #FECDD3",
    borderRadius: "6px",
    padding: "4px 8px",
    fontSize: "0.68rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:active": {
      transform: "scale(0.95)",
    },
  },

  /* RIGHT SIDEBAR PANEL */
  rightSidebar: {
    width: "280px",
    backgroundColor: "#FFFFFF",
    borderLeft: "1px solid #EAECF0",
    padding: "18px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    flexShrink: 0,
    overflowY: "auto",
    "@media (max-width: 900px)": {
      width: "100%",
      borderLeft: "none",
      borderTop: "1px solid #EAECF0",
    },
  },
  sidebarSection: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  sidebarHeader: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#0F172A",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sidebarCountBadge: {
    fontSize: "0.65rem",
    fontWeight: 700,
    color: "#0072C4",
    backgroundColor: "#F0F7FF",
    padding: "2px 6px",
    borderRadius: "10px",
  },

  /* Absence Item */
  absenceItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 8px",
    borderRadius: "8px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #F1F5F9",
  },
  absenceLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  absenceAvatar: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#E2E8F0",
    color: "#475569",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.68rem",
    fontWeight: 700,
  },
  absenceName: {
    fontSize: "0.72rem",
    fontWeight: 600,
    color: "#0F172A",
  },
  absenceType: {
    fontSize: "0.62rem",
    color: "#64748B",
  },
  absenceBadge: {
    fontSize: "0.62rem",
    fontWeight: 600,
    padding: "2px 6px",
    borderRadius: "4px",
  },
  badgeSick: {
    backgroundColor: "#FEF2F2",
    color: "#DC2626",
  },
  badgeVacation: {
    backgroundColor: "#FFFBEB",
    color: "#D97706",
  },

  /* Pending Approvals Card */
  approvalCard: {
    backgroundColor: "#F0F7FF",
    border: "1px solid rgba(0, 114, 196, 0.25)",
    borderRadius: "10px",
    padding: "10px 12px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  approvalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "0.72rem",
    fontWeight: 700,
    color: "#0072C4",
  },
  approvalBody: {
    fontSize: "0.7rem",
    color: "#334155",
    lineHeight: 1.4,
  },
  approvalActions: {
    display: "flex",
    gap: "6px",
    marginTop: "4px",
  },
  approveBtn: {
    flex: 1,
    backgroundColor: "#10B981",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "6px",
    padding: "5px 0",
    fontSize: "0.68rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "background 0.15s ease",
    "&:hover": {
      backgroundColor: "#059669",
    },
  },
  declineBtn: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    color: "#64748B",
    border: "1px solid #CBD5E1",
    borderRadius: "6px",
    padding: "5px 0",
    fontSize: "0.68rem",
    fontWeight: 600,
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#F1F5F9",
    },
  },
  approvedStatusNotice: {
    padding: "6px 8px",
    backgroundColor: "#ECFDF5",
    border: "1px solid #A7F3D0",
    borderRadius: "6px",
    color: "#047857",
    fontSize: "0.68rem",
    fontWeight: 700,
    textAlign: "center",
  },

  /* Assets mini summary */
  assetSummaryBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    padding: "8px 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  assetInfo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  assetNameText: {
    fontSize: "0.7rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  assetSerialText: {
    fontSize: "0.62rem",
    color: "#64748B",
  },
  assetVerifiedBadge: {
    fontSize: "0.62rem",
    fontWeight: 700,
    color: "#059669",
    backgroundColor: "#ECFDF5",
    padding: "2px 6px",
    borderRadius: "4px",
  },
}));
