import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  pageWrapper: {
    width: "100%",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────────────────────── */
  heroSection: {
    position: "relative",
    paddingTop: "56px",
    paddingBottom: "80px",
    paddingLeft: "24px",
    paddingRight: "24px",
    maxWidth: "1280px",
    margin: "0 auto",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      paddingTop: "40px",
      paddingBottom: "56px",
      paddingLeft: "16px",
      paddingRight: "16px",
    },
  },
  heroGlow: {
    position: "absolute",
    top: "30%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "600px",
    height: "380px",
    background: theme.light.brand.surface.lighter,
    filter: "blur(110px)",
    opacity: 0.85,
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobBrand: {
    position: "absolute",
    top: "80px",
    left: "12%",
    width: "420px",
    height: "420px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobInfo: {
    position: "absolute",
    bottom: "60px",
    right: "10%",
    width: "380px",
    height: "380px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.65,
    pointerEvents: "none",
    zIndex: 0,
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "44px",
  },
  eyebrowPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    marginBottom: "20px",
    boxShadow: theme.elevation.s,
    width: "fit-content",
  },
  eyebrowText: {
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
  },
  heroTitle: {
    fontSize: "3.5rem",
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 20px 0",
    maxWidth: "920px",
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.875rem",
    },
  },
  heroTitleAccent: {
    display: "block",
    backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`,
    WebkitBackgroundClip: "text",
    backgroundClip: "text",
    color: "transparent",
  },
  heroParagraph: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 32px 0",
    maxWidth: "800px",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroCtaButton: {
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    border: "none",
    borderRadius: theme.borderRadius.b300,
    padding: "14px 34px",
    fontSize: "1.0625rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 8px 24px rgba(0, 114, 196, 0.28)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.dark,
      transform: "translateY(-2px)",
      boxShadow: "0 12px 28px rgba(0, 114, 196, 0.38)",
    },
    "&:active": {
      transform: "scale(0.98)",
    },
  },

  /* Mockup Container Wrapper */
  mockupWrapper: {
    position: "relative",
    zIndex: 2,
    maxWidth: "1140px",
    margin: "0 auto",
    borderRadius: theme.borderRadius.b400,
    boxShadow: "0 24px 64px -12px rgba(15, 23, 42, 0.14)",
    overflow: "hidden",
    border: `1px solid ${theme.light.neutral.border.light}`,
    backgroundColor: "#FFFFFF",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     COMMON SECTION HEADERS & CONTAINERS
     ───────────────────────────────────────────────────────────────────────────── */
  sectionContainer: {
    maxWidth: "1280px",
    margin: "0 auto",
    padding: "88px 24px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  sectionHeaderCentered: {
    textAlign: "center",
    maxWidth: "760px",
    margin: "0 auto 52px auto",
  },
  kicker: {
    display: "block",
    fontSize: "0.8125rem",
    fontWeight: 800,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
    marginBottom: "12px",
  },
  sectionTitle: {
    fontSize: "2.5rem",
    fontWeight: 800,
    lineHeight: 1.2,
    letterSpacing: "-0.025em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 16px 0",
    "@media (max-width: 768px)": {
      fontSize: "1.875rem",
    },
  },
  sectionDescription: {
    fontSize: "1.0625rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "0.9375rem",
    },
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 1: INFRASTRUCTURE (SPLIT + CARDS + NETWORK GRAPHIC)
     ───────────────────────────────────────────────────────────────────────────── */
  infraSplit: {
    display: "grid",
    gridTemplateColumns: "1.1fr 0.9fr",
    gap: "48px",
    alignItems: "center",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "36px",
    },
  },
  infraCardsList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  infraCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: theme.borderRadius.b300,
    padding: "20px 24px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    display: "flex",
    gap: "18px",
    alignItems: "flex-start",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    cursor: "default",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateX(4px)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.12)",
    },
  },
  infraIconBox: {
    width: "44px",
    height: "44px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infraCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 6px 0",
  },
  infraCardText: {
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  /* Network Graphic Card */
  networkGraphicCard: {
    backgroundColor: "#0B132B",
    borderRadius: theme.borderRadius.b400,
    padding: "36px 28px",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 20px 48px -10px rgba(11, 19, 43, 0.4)",
    border: "1px solid #1E293B",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "420px",
  },
  networkAmbientPulse: {
    position: "absolute",
    width: "260px",
    height: "260px",
    borderRadius: "50%",
    backgroundColor: "rgba(0, 114, 196, 0.25)",
    filter: "blur(60px)",
    pointerEvents: "none",
  },
  networkRingOuter: {
    position: "absolute",
    width: "320px",
    height: "320px",
    borderRadius: "50%",
    border: "1px dashed rgba(255, 255, 255, 0.12)",
    pointerEvents: "none",
  },
  networkRingInner: {
    position: "absolute",
    width: "200px",
    height: "200px",
    borderRadius: "50%",
    border: "1px solid rgba(0, 114, 196, 0.3)",
    pointerEvents: "none",
  },
  networkCenterNode: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
  },
  networkGlobeIconWrap: {
    width: "72px",
    height: "72px",
    borderRadius: "50%",
    backgroundColor: "#0F172A",
    border: "2px solid #0072C4",
    boxShadow: "0 0 24px rgba(0, 114, 196, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#38BDF8",
    marginBottom: "16px",
  },
  networkNodeTitle: {
    fontSize: "1.125rem",
    fontWeight: 800,
    color: "#FFFFFF",
    letterSpacing: "0.04em",
    margin: "0 0 6px 0",
  },
  networkNodeSubtitle: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#38BDF8",
    textTransform: "uppercase",
    letterSpacing: "0.1em",
  },
  networkMetricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "12px",
    marginTop: "32px",
    width: "100%",
    position: "relative",
    zIndex: 2,
  },
  networkMetricBox: {
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: theme.borderRadius.b200,
    padding: "10px",
    textAlign: "center",
    backdropFilter: "blur(8px)",
  },
  networkMetricVal: {
    fontSize: "1.125rem",
    fontWeight: 800,
    color: "#10B981",
    display: "block",
  },
  networkMetricLbl: {
    fontSize: "0.6875rem",
    color: "#94A3B8",
    marginTop: "2px",
    display: "block",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 2: BUILT-IN AI INTELLIGENCE (2 BIG INTERACTIVE CARDS)
     ───────────────────────────────────────────────────────────────────────────── */
  aiTwoCardGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "28px",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "1fr",
    },
  },
  glassCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: theme.borderRadius.b400,
    padding: "36px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 4px 16px rgba(15, 23, 42, 0.04)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 16px 36px rgba(15, 23, 42, 0.08)",
    },
    "@media (max-width: 600px)": {
      padding: "24px",
    },
  },
  cardBorderBrand: {
    borderTop: "3px solid #0072C4",
    "&:hover": {
      borderColor: "#0072C4",
    },
  },
  cardBorderEmerald: {
    borderTop: "3px solid #10B981",
    "&:hover": {
      borderColor: "#10B981",
    },
  },
  aiCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "18px",
  },
  aiIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: theme.borderRadius.b250,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.surface.medium,
    flexShrink: 0,
  },
  aiIconBoxEmerald: {
    width: "48px",
    height: "48px",
    borderRadius: theme.borderRadius.b250,
    backgroundColor: "#ECFDF5",
    border: "1px solid #A7F3D0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#059669",
    flexShrink: 0,
  },
  aiCardTitle: {
    fontSize: "1.375rem",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    margin: 0,
  },
  aiCardText: {
    fontSize: "0.9375rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 24px 0",
  },

  /* Interactive AI Sub-Mockup Widgets */
  ticketPreviewBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: theme.borderRadius.b250,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  transcriptQuote: {
    padding: "10px 12px",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: "#FFFFFF",
    borderLeft: "3px solid #0072C4",
    fontSize: "0.8125rem",
    color: "#334155",
    lineHeight: 1.5,
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
  },
  ticketGeneratedRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 12px",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: "#F0FDF4",
    border: "1px solid #BBF7D0",
    fontSize: "0.8125rem",
  },
  ticketBadge: {
    backgroundColor: "#16A34A",
    color: "#FFFFFF",
    fontWeight: 700,
    fontSize: "0.6875rem",
    padding: "3px 8px",
    borderRadius: "4px",
    marginRight: "8px",
  },

  /* Search Preview Box */
  searchPreviewBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: theme.borderRadius.b250,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  searchBarMock: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #CBD5E1",
    borderRadius: theme.borderRadius.b150,
    padding: "8px 12px",
    fontSize: "0.8125rem",
    color: "#0F172A",
  },
  verifiedProofBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: "#EFF6FF",
    border: "1px solid #BFDBFE",
    fontSize: "0.75rem",
    color: "#1E40AF",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 3: ENTERPRISE USAGE (4 CARDS GRID)
     ───────────────────────────────────────────────────────────────────────────── */
  enterpriseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "20px",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 540px)": {
      gridTemplateColumns: "1fr",
    },
  },
  usageCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: theme.borderRadius.b300,
    padding: "24px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.03)",
    display: "flex",
    flexDirection: "column",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    cursor: "default",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-4px)",
      boxShadow: "0 12px 28px rgba(0, 114, 196, 0.1)",
    },
  },
  usageIconWrap: {
    width: "44px",
    height: "44px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: "16px",
    transition: "all 0.2s ease",
  },
  usageCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 8px 0",
  },
  usageCardDesc: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 4: UNIFIED MOBILE EXPERIENCE
     ───────────────────────────────────────────────────────────────────────────── */
  mobileSection: {
    maxWidth: "1280px",
    margin: "0 auto",
    padding: "88px 24px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  mobileSplit: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  mobilePhoneCol: {
    display: "flex",
    justifyContent: "center",
  },
  mobileDetailsCol: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  mobileFeaturesList: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    marginTop: "8px",
  },
  mobileFeatureItem: {
    display: "flex",
    gap: "14px",
    alignItems: "flex-start",
  },
  mobileFeatureIcon: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: "2px",
  },
  mobileFeatureTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 4px 0",
  },
  mobileFeatureText: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  /* Store Buttons */
  downloadButtonsRow: {
    display: "flex",
    gap: "14px",
    marginTop: "8px",
    flexWrap: "wrap",
  },
  storeButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    borderRadius: theme.borderRadius.b300,
    padding: "12px 20px",
    textDecoration: "none",
    boxShadow: theme.elevation.s,
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#1E293B",
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.m,
    },
  },
  storeIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  storeTextCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  storeSubtitle: {
    fontSize: "0.6875rem",
    color: "#94A3B8",
    lineHeight: 1,
    marginBottom: "2px",
  },
  storeTitle: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.2,
  },

  /* Ratings */
  reviewsRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginTop: "4px",
  },
  starRatingGroup: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  starsGroup: {
    display: "flex",
    color: "#F59E0B",
  },
  ratingNumber: {
    fontWeight: 800,
    fontSize: "0.9375rem",
    color: theme.light.neutral.onSurface.title,
  },
  reviewsCountText: {
    fontSize: "0.8125rem",
    color: theme.light.neutral.onSurface.medium,
  },
}));
