import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  page: { backgroundColor: theme.light.neutral.surface.lighter, color: theme.light.neutral.onSurface.title, fontFamily: "'Inter', 'Open Sans', sans-serif", overflow: "hidden" },
  hero: { maxWidth: "1200px", margin: "0 auto", padding: "56px 32px 80px", textAlign: "center", position: "relative", "@media (max-width: 600px)": { padding: "40px 20px 56px" } },
  glow: { position: "absolute", width: "520px", height: "360px", top: "54px", left: "50%", transform: "translateX(-50%)", backgroundColor: theme.light.negative.surface.lighter, filter: "blur(90px)", opacity: 0.8, borderRadius: "50%", pointerEvents: "none" },
  heroContent: { position: "relative", zIndex: 1 },
  badge: { display: "inline-flex", alignItems: "center", gap: "8px", padding: "6px 14px", borderRadius: theme.borderRadius.b2500, backgroundColor: theme.light.brand.surface.lighter, color: theme.light.brand.onSurface.default, border: `1px solid ${theme.light.brand.border.light}`, fontSize: "0.875rem", fontWeight: 600, boxShadow: theme.elevation.s },
  title: { maxWidth: "900px", margin: "0 auto 24px auto", fontSize: "3.5rem", lineHeight: 1.15, letterSpacing: "-0.025em", fontWeight: 800, "@media (max-width: 768px)": { fontSize: "2.25rem" } },
  titleAccent: { display: "block", backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`, WebkitBackgroundClip: "text", backgroundClip: "text", color: "transparent" },
  description: { maxWidth: "820px", margin: "0 auto 36px auto", color: theme.light.neutral.onSurface.medium, fontSize: "1.125rem", lineHeight: 1.7, "@media (max-width: 768px)": { fontSize: "1rem", padding: "0 12px" } },
  primaryButton: { border: "none", borderRadius: theme.borderRadius.b300, backgroundColor: theme.light.brand.surface.medium, color: theme.light.neutral.onSurface.inverse, padding: "14px 32px", fontFamily: "inherit", fontSize: "1.0625rem", fontWeight: 700, cursor: "pointer", boxShadow: theme.elevation.m, transition: "all 0.25s ease", "&:hover": { backgroundColor: theme.light.brand.surface.dark, transform: "translateY(-2px)" } },
  workspace: { maxWidth: "1120px", minHeight: "500px", margin: "72px auto 0", display: "grid", gridTemplateColumns: "230px minmax(0, 1fr)", textAlign: "left", overflow: "hidden", backgroundColor: theme.light.neutral.surface.lighter, border: `1px solid ${theme.light.neutral.border.light}`, borderRadius: theme.borderRadius.b500, boxShadow: theme.elevation.l, "@media (max-width: 700px)": { display: "block", minHeight: "auto" } },
  workspaceBar: { gridColumn: "1 / -1", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 20px", backgroundColor: theme.light.neutral.surface.light, borderBottom: `1px solid ${theme.light.neutral.border.light}`, color: theme.light.neutral.onSurface.medium, fontSize: "0.75rem" },
  dots: { display: "flex", gap: "6px" }, dot: { width: "9px", height: "9px", borderRadius: "50%", backgroundColor: theme.light.neutral.border.medium },
  recording: { padding: "5px 8px", borderRadius: theme.borderRadius.b2500, backgroundColor: theme.light.negative.surface.lighter, color: theme.light.negative.onSurface.medium, border: `1px solid ${theme.light.negative.border.light}`, fontSize: "0.625rem", fontWeight: 800 },
  sidebar: { padding: "18px 14px", backgroundColor: theme.light.neutral.surface.light, borderRight: `1px solid ${theme.light.neutral.border.light}`, "@media (max-width: 700px)": { display: "none" } },
  label: { color: theme.light.neutral.onSurface.dark, fontSize: "0.625rem", fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "10px" },
  channel: { padding: "10px 11px", borderRadius: theme.borderRadius.b100, color: theme.light.neutral.onSurface.medium, fontSize: "0.8125rem", marginBottom: "4px" },
  channelActive: { backgroundColor: theme.light.brand.surface.lighter, color: theme.light.brand.onSurface.default, borderLeft: `3px solid ${theme.light.brand.surface.medium}`, fontWeight: 700 },
  people: { display: "grid", gap: "10px", marginTop: "24px" },
  person: { display: "flex", alignItems: "center", gap: "9px", color: theme.light.neutral.onSurface.medium, fontSize: "0.75rem" },
  personAvatar: { width: "26px", height: "26px", display: "grid", placeItems: "center", borderRadius: theme.borderRadius.b100, backgroundColor: theme.light.info.surface.medium, color: theme.light.neutral.onSurface.inverse, fontSize: "0.625rem", fontWeight: 800 },
  chat: { minWidth: 0, backgroundColor: theme.light.neutral.surface.lighter },
  videoGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px", padding: "16px", minHeight: "230px", borderBottom: `1px solid ${theme.light.neutral.border.light}`, backgroundColor: theme.light.neutral.surface.light, "@media (max-width: 520px)": { gridTemplateColumns: "1fr" } },
  video: { minHeight: "190px", display: "flex", alignItems: "flex-end", padding: "10px", borderRadius: theme.borderRadius.b300, backgroundColor: theme.light.neutral.surface.medium, border: `1px solid ${theme.light.neutral.border.medium}`, color: theme.light.neutral.onSurface.title, fontSize: "0.6875rem", fontWeight: 700 },
  videoActive: { borderColor: theme.light.negative.border.medium, boxShadow: theme.elevation.s },
  subtitle: { alignSelf: "flex-end", width: "100%", marginBottom: "22px", padding: "8px", textAlign: "center", borderRadius: theme.borderRadius.b100, backgroundColor: theme.light.neutral.surface.inverse, color: theme.light.neutral.onSurface.inverse, fontSize: "0.6875rem" },
  thread: { padding: "18px", minHeight: "220px" },
  aiRow: { display: "flex", gap: "10px", alignItems: "flex-start" },
  aiIcon: { width: "30px", height: "30px", display: "grid", placeItems: "center", borderRadius: theme.borderRadius.b100, backgroundColor: theme.light.info.surface.lighter, border: `1px solid ${theme.light.info.border.light}`, color: theme.light.info.onSurface.medium, fontSize: "0.625rem", fontWeight: 800, flexShrink: 0 },
  aiName: { color: theme.light.info.onSurface.medium, fontSize: "0.6875rem", fontWeight: 800, marginBottom: "5px" },
  aiMessage: { padding: "12px", borderRadius: theme.borderRadius.b150, backgroundColor: theme.light.neutral.surface.light, border: `1px solid ${theme.light.neutral.border.light}`, color: theme.light.neutral.onSurface.medium, fontSize: "0.75rem", lineHeight: 1.6 },
  actionButton: { marginTop: "12px", border: "none", borderRadius: theme.borderRadius.b100, backgroundColor: theme.light.brand.surface.medium, color: theme.light.neutral.onSurface.inverse, padding: "7px 10px", fontFamily: "inherit", fontSize: "0.6875rem", fontWeight: 700 },
  section: { maxWidth: "1200px", margin: "0 auto", padding: "88px 32px", borderTop: `1px solid ${theme.light.neutral.border.light}`, "@media (max-width: 600px)": { padding: "60px 20px" } },
  split: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "64px", alignItems: "center", "@media (max-width: 800px)": { gridTemplateColumns: "1fr", gap: "32px" } },
  kicker: { color: theme.light.brand.onSurface.default, fontSize: "0.8125rem", fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "12px", display: "block" },
  sectionTitle: { margin: "0 0 16px 0", fontSize: "2.5rem", lineHeight: 1.2, fontWeight: 800, letterSpacing: "-0.02em", color: theme.light.neutral.onSurface.title, "@media (max-width: 768px)": { fontSize: "1.875rem" } },
  sectionText: { color: theme.light.neutral.onSurface.medium, fontSize: "1.125rem", lineHeight: 1.7, margin: 0, "@media (max-width: 768px)": { fontSize: "1rem" } },
  points: { display: "grid", gap: "20px", marginTop: "28px" },
  point: { display: "flex", gap: "12px", alignItems: "flex-start" },
  pointIcon: { width: "25px", height: "25px", display: "grid", placeItems: "center", borderRadius: "50%", backgroundColor: theme.light.brand.surface.lighter, border: `1px solid ${theme.light.brand.border.light}`, color: theme.light.brand.onSurface.default, fontSize: "0.75rem", flexShrink: 0 },
  pointTitle: { margin: "0 0 6px 0", fontSize: "1.125rem", fontWeight: 700, color: theme.light.neutral.onSurface.title },
  pointText: { margin: 0, color: theme.light.neutral.onSurface.medium, fontSize: "0.9375rem", lineHeight: 1.6 },
  graphic: { minHeight: "390px", display: "grid", placeItems: "center", position: "relative", overflow: "hidden", borderRadius: theme.borderRadius.b400, backgroundColor: theme.light.neutral.surface.light, border: `1px solid ${theme.light.neutral.border.light}`, boxShadow: theme.elevation.m },
  ring: { position: "absolute", width: "220px", height: "220px", borderRadius: "50%", border: `1px solid ${theme.light.brand.border.light}` },
  ringLarge: { width: "310px", height: "310px", borderColor: theme.light.neutral.border.light },
  globe: { position: "relative", zIndex: 1, textAlign: "center", color: theme.light.neutral.onSurface.medium },
  aiGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px", "@media (max-width: 700px)": { gridTemplateColumns: "1fr" } },
  card: { padding: "28px", borderRadius: theme.borderRadius.b300, backgroundColor: theme.light.brand.surface.lighter, border: `1px solid ${theme.light.brand.border.light}`, borderTop: `3px solid ${theme.light.brand.border.medium}`, transition: "transform 0.2s ease, box-shadow 0.2s ease", "&:hover": { transform: "translateY(-3px)", boxShadow: theme.elevation.m } },
  cardIcon: { width: "48px", height: "48px", display: "grid", placeItems: "center", borderRadius: theme.borderRadius.b200, backgroundColor: theme.light.brand.surface.light, border: `1px solid ${theme.light.brand.border.medium}`, fontSize: "1.5rem", marginBottom: "18px" },
  cardTitle: { margin: "0 0 12px 0", fontSize: "1.375rem", fontWeight: 700, color: theme.light.neutral.onSurface.title },
  cardText: { margin: 0, color: theme.light.neutral.onSurface.medium, fontSize: "0.9375rem", lineHeight: 1.7 },
  phone: { width: "250px", height: "500px", margin: "0 auto", padding: "38px 14px 14px", border: `8px solid ${theme.light.neutral.surface.inverse}`, borderRadius: "40px", backgroundColor: theme.light.neutral.surface.lighter, position: "relative", boxSizing: "border-box", boxShadow: theme.elevation.l },
  notch: { position: "absolute", top: 0, left: "50%", transform: "translateX(-50%)", width: "110px", height: "22px", borderRadius: "0 0 22px 22px", backgroundColor: theme.light.neutral.surface.inverse },
  phoneHeader: { display: "flex", alignItems: "center", gap: "10px", marginBottom: "20px", fontWeight: 800 },
  callView: { height: "330px", display: "grid", placeItems: "center", borderRadius: theme.borderRadius.b200, backgroundColor: theme.light.neutral.surface.medium, color: theme.light.neutral.onSurface.medium },
  callBadge: { marginTop: "10px", color: theme.light.negative.onSurface.medium, fontSize: "0.6875rem", fontWeight: 700 },
  callControls: { display: "flex", justifyContent: "center", gap: "12px", marginTop: "14px" },
  control: { width: "42px", height: "42px", display: "grid", placeItems: "center", borderRadius: "50%", backgroundColor: theme.light.neutral.surface.medium, border: `1px solid ${theme.light.neutral.border.light}` },
  controlActive: { backgroundColor: theme.light.brand.surface.medium, color: theme.light.neutral.onSurface.inverse },
  includedGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "18px", "@media (max-width: 800px)": { gridTemplateColumns: "repeat(2, 1fr)" }, "@media (max-width: 480px)": { gridTemplateColumns: "1fr" } },
  included: { padding: "22px", borderRadius: theme.borderRadius.b300, backgroundColor: theme.light.info.surface.lighter, border: `1px solid ${theme.light.info.border.light}`, transition: "transform 0.2s ease", "&:hover": { transform: "translateY(-2px)", boxShadow: theme.elevation.m } },
}));
