import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  "@keyframes floatSignalCyan": {
    "0%, 100%": {
      transform: "translate(0, 0) scale(1)",
    },
    "50%": {
      transform: "translate(24px, -20px) scale(1.06)",
    },
  },
  "@keyframes floatSignalEmerald": {
    "0%, 100%": {
      transform: "translate(0, 0) scale(1)",
    },
    "50%": {
      transform: "translate(-22px, 24px) scale(0.95)",
    },
  },
  "@keyframes signalRipple": {
    "0%": {
      transform: "scale(0.8)",
      opacity: 0.5,
    },
    "50%": {
      opacity: 0.2,
    },
    "100%": {
      transform: "scale(1.4)",
      opacity: 0,
    },
  },
  "@keyframes pulseGlow": {
    "0%, 100%": {
      opacity: 0.35,
      transform: "scale(1)",
    },
    "50%": {
      opacity: 0.75,
      transform: "scale(1.08)",
    },
  },
  "@keyframes nodeBlink": {
    "0%, 100%": {
      opacity: 0.15,
      transform: "scale(0.85)",
    },
    "50%": {
      opacity: 0.95,
      transform: "scale(1.3)",
    },
  },
  "@keyframes packetBeamSweep": {
    "0%": {
      left: "-25%",
      opacity: 0,
    },
    "20%": {
      opacity: 0.9,
    },
    "80%": {
      opacity: 0.9,
    },
    "100%": {
      left: "120%",
      opacity: 0,
    },
  },
  pageWrapper: {
    width: "100%",
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflowX: "hidden",
    position: "relative",
    boxSizing: "border-box",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     HERO SECTION
     ───────────────────────────────────────────────────────────────────────────── */
  heroSection: {
    position: "relative",
    paddingTop: "56px",
    paddingBottom: "80px",
    paddingLeft: "24px",
    paddingRight: "24px",
    maxWidth: "1280px",
    margin: "0 auto",
    textAlign: "center",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      paddingTop: "40px",
      paddingBottom: "56px",
      paddingLeft: "16px",
      paddingRight: "16px",
    },
  },
  heroGlow: {
    position: "absolute",
    top: "30%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "600px",
    height: "380px",
    background: theme.light.brand.surface.lighter,
    filter: "blur(110px)",
    opacity: 0.85,
    borderRadius: "50%",
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobBrand: {
    position: "absolute",
    top: "80px",
    left: "12%",
    width: "420px",
    height: "420px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobInfo: {
    position: "absolute",
    bottom: "60px",
    right: "10%",
    width: "380px",
    height: "380px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.65,
    pointerEvents: "none",
    zIndex: 0,
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "44px",
  },
  eyebrowPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    marginBottom: "20px",
    boxShadow: theme.elevation.s,
    width: "fit-content",
  },
  eyebrowText: {
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
  },
  heroTitle: {
    fontSize: "3.5rem",
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 20px 0",
    maxWidth: "920px",
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
    "@media (max-width: 480px)": {
      fontSize: "1.875rem",
    },
  },
  heroTitleAccent: {
    display: "block",
    backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`,
    WebkitBackgroundClip: "text",
    backgroundClip: "text",
    color: "transparent",
  },
  heroParagraph: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 32px 0",
    maxWidth: "800px",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroCtaButton: {
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    border: "none",
    borderRadius: theme.borderRadius.b300,
    padding: "14px 34px",
    fontSize: "1.0625rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 8px 24px rgba(0, 114, 196, 0.28)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.dark,
      transform: "translateY(-2px)",
      boxShadow: "0 12px 28px rgba(0, 114, 196, 0.38)",
    },
    "&:active": {
      transform: "scale(0.98)",
    },
  },

  /* Mockup Container Wrapper */
  mockupWrapper: {
    position: "relative",
    zIndex: 2,
    width: "100%",
    maxWidth: "1280px",
    margin: "0 auto",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     COMMON SECTION HEADERS & CONTAINERS
     ───────────────────────────────────────────────────────────────────────────── */
  sectionContainer: {
    width: "100%",
    margin: "0 auto",
    padding: "88px 24px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  sectionContainerAnimated: {
    backgroundColor: "#FAFBFD",
    borderTop: "1px solid rgba(226, 232, 240, 0.7)",
    borderBottom: "1px solid rgba(226, 232, 240, 0.7)",
  },
  sectionInner: {
    position: "relative",
    zIndex: 1,
    maxWidth: "1280px",
    margin: "0 auto",
  },
  signalAmbientCanvas: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    overflow: "hidden",
    zIndex: 0,
  },
  signalMeshOverlay: {
    position: "absolute",
    inset: 0,
    backgroundImage: `
      linear-gradient(to right, rgba(14, 165, 233, 0.045) 1px, transparent 1px),
      linear-gradient(to bottom, rgba(16, 185, 129, 0.04) 1px, transparent 1px)
    `,
    backgroundSize: "40px 40px",
    maskImage: "radial-gradient(ellipse 75% 65% at 50% 50%, #000 35%, transparent 90%)",
    WebkitMaskImage: "radial-gradient(ellipse 75% 65% at 50% 50%, #000 35%, transparent 90%)",
  },
  signalBlobCyan: {
    position: "absolute",
    top: "30px",
    left: "-60px",
    width: "560px",
    height: "560px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(14, 165, 233, 0.13) 0%, rgba(56, 189, 248, 0.035) 50%, transparent 70%)",
    filter: "blur(75px)",
    animation: "$floatSignalCyan 18s ease-in-out infinite",
  },
  signalBlobEmerald: {
    position: "absolute",
    bottom: "30px",
    right: "-60px",
    width: "560px",
    height: "560px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(16, 185, 129, 0.12) 0%, rgba(52, 211, 153, 0.035) 50%, transparent 70%)",
    filter: "blur(75px)",
    animation: "$floatSignalEmerald 22s ease-in-out infinite",
  },
  signalBlobCenter: {
    position: "absolute",
    top: "48%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "520px",
    height: "380px",
    borderRadius: "50%",
    background: "radial-gradient(ellipse at center, rgba(14, 165, 233, 0.06) 0%, transparent 70%)",
    filter: "blur(70px)",
    animation: "$pulseGlow 8s ease-in-out infinite",
  },
  signalPulseRing: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: "440px",
    height: "440px",
    marginTop: "-220px",
    marginLeft: "-220px",
    borderRadius: "50%",
    border: "1.5px solid rgba(14, 165, 233, 0.18)",
    animation: "$signalRipple 6s ease-out infinite",
    pointerEvents: "none",
  },
  signalBeamTrack: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "1px",
    background: "linear-gradient(90deg, transparent 0%, rgba(14, 165, 233, 0.25) 30%, rgba(16, 185, 129, 0.25) 70%, transparent 100%)",
    overflow: "hidden",
  },
  signalBeamLight: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "160px",
    height: "100%",
    background: "linear-gradient(90deg, transparent 0%, rgba(14, 165, 233, 0.95) 40%, rgba(16, 185, 129, 0.85) 80%, transparent 100%)",
    boxShadow: "0 0 6px rgba(14, 165, 233, 0.45)",
    animation: "$packetBeamSweep 7s cubic-bezier(0.4, 0, 0.2, 1) infinite",
  },
  signalBeamTrackBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "1px",
    background: "linear-gradient(90deg, transparent 0%, rgba(16, 185, 129, 0.25) 30%, rgba(14, 165, 233, 0.25) 70%, transparent 100%)",
    overflow: "hidden",
  },
  signalBeamLightBottom: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "160px",
    height: "100%",
    background: "linear-gradient(90deg, transparent 0%, rgba(16, 185, 129, 0.95) 40%, rgba(14, 165, 233, 0.85) 80%, transparent 100%)",
    boxShadow: "0 0 6px rgba(16, 185, 129, 0.45)",
    animation: "$packetBeamSweep 8s cubic-bezier(0.4, 0, 0.2, 1) infinite 2.5s",
  },
  signalNodeDot: {
    position: "absolute",
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    animation: "$nodeBlink 4s ease-in-out infinite",
  },
  signalNodeCyan1: {
    top: "24%",
    left: "15%",
    backgroundColor: "rgba(14, 165, 233, 0.8)",
    boxShadow: "0 0 10px rgba(14, 165, 233, 0.85)",
  },
  signalNodeCyan2: {
    bottom: "26%",
    left: "22%",
    backgroundColor: "rgba(14, 165, 233, 0.8)",
    boxShadow: "0 0 10px rgba(14, 165, 233, 0.85)",
    animationDelay: "1.8s",
  },
  signalNodeEmerald1: {
    top: "28%",
    right: "17%",
    backgroundColor: "rgba(16, 185, 129, 0.8)",
    boxShadow: "0 0 10px rgba(16, 185, 129, 0.85)",
    animationDelay: "1s",
  },
  signalNodeEmerald2: {
    bottom: "22%",
    right: "24%",
    backgroundColor: "rgba(16, 185, 129, 0.8)",
    boxShadow: "0 0 10px rgba(16, 185, 129, 0.85)",
    animationDelay: "2.6s",
  },
  sectionHeaderCentered: {
    textAlign: "center",
    maxWidth: "760px",
    margin: "0 auto 52px auto",
  },
  kicker: {
    display: "block",
    fontSize: "0.8125rem",
    fontWeight: 800,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
    marginBottom: "12px",
  },
  sectionTitle: {
    fontSize: "2.5rem",
    fontWeight: 800,
    lineHeight: 1.2,
    letterSpacing: "-0.025em",
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 16px 0",
    "@media (max-width: 768px)": {
      fontSize: "1.875rem",
    },
  },
  sectionDescription: {
    fontSize: "1.0625rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "0.9375rem",
    },
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 1: INFRASTRUCTURE (SPLIT + CARDS + NETWORK GRAPHIC)
     ───────────────────────────────────────────────────────────────────────────── */
  infraSplit: {
    display: "grid",
    gridTemplateColumns: "1.08fr 0.92fr",
    gap: "40px",
    alignItems: "stretch",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "36px",
    },
  },
  infraLeftCol: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  infraCardsList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    marginTop: "8px",
  },
  infraCard: {
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    backdropFilter: "blur(12px)",
    borderRadius: theme.borderRadius.b300,
    padding: "18px 22px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    display: "flex",
    gap: "18px",
    alignItems: "center",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    cursor: "default",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateX(4px)",
      boxShadow: "0 8px 24px rgba(0, 114, 196, 0.12)",
    },
  },
  infraIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infraCardTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 4px 0",
  },
  infraCardText: {
    fontSize: "0.9375rem",
    lineHeight: 1.55,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  /* High Quality Animated Network Telemetry Graphic Card */
  networkGraphicCard: {
    backgroundColor: "#060D1E",
    backgroundImage: "radial-gradient(circle at 50% 45%, #0D224A 0%, #050B18 80%)",
    borderRadius: theme.borderRadius.b400,
    padding: "24px 22px 20px 22px",
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 24px 56px -12px rgba(2, 6, 23, 0.7), inset 0 1px 0 rgba(255, 255, 255, 0.12)",
    border: "1px solid #1E2E4A",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    minHeight: "480px",
    boxSizing: "border-box",
  },
  networkHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    zIndex: 3,
    padding: "0 4px 10px 4px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
  },
  networkLiveTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#10B981",
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    border: "1px solid rgba(16, 185, 129, 0.3)",
    padding: "3px 9px",
    borderRadius: "12px",
  },
  networkLiveDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    boxShadow: "0 0 8px #10B981",
  },
  networkHeaderRight: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#38BDF8",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  networkCanvasWrap: {
    position: "relative",
    width: "100%",
    height: "260px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    margin: "6px 0",
  },
  networkMetricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "10px",
    width: "100%",
    position: "relative",
    zIndex: 3,
  },
  networkMetricBox: {
    backgroundColor: "rgba(15, 23, 42, 0.75)",
    border: "1px solid rgba(255, 255, 255, 0.09)",
    borderRadius: theme.borderRadius.b200,
    padding: "10px 8px",
    textAlign: "center",
    backdropFilter: "blur(10px)",
    transition: "all 0.25s ease",
    "&:hover": {
      backgroundColor: "rgba(15, 23, 42, 0.95)",
      borderColor: "rgba(56, 189, 248, 0.35)",
      transform: "translateY(-1px)",
    },
  },
  networkMetricVal: {
    fontSize: "1.1875rem",
    fontWeight: 800,
    color: "#10B981",
    display: "block",
    letterSpacing: "-0.01em",
  },
  networkMetricLbl: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#94A3B8",
    marginTop: "2px",
    display: "block",
  },
  networkMetricSub: {
    fontSize: "0.625rem",
    color: "#38BDF8",
    marginTop: "2px",
    display: "block",
    fontWeight: 600,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 2: BUILT-IN AI INTELLIGENCE (2 BIG INTERACTIVE CARDS)
     ───────────────────────────────────────────────────────────────────────────── */
  aiTwoCardGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "28px",
    alignItems: "stretch",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "1fr",
    },
  },
  glassCard: {
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    backdropFilter: "blur(12px)",
    borderRadius: theme.borderRadius.b400,
    padding: "36px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 4px 16px rgba(15, 23, 42, 0.04)",
    transition: "transform 0.25s ease, box-shadow 0.25s ease, border-color 0.25s ease",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "100%",
    boxSizing: "border-box",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 16px 32px rgba(15, 23, 42, 0.08)",
      borderColor: "rgba(14, 165, 233, 0.35)",
    },
    "@media (max-width: 600px)": {
      padding: "24px",
    },
  },
  cardBorderBrand: {
    borderTop: "3px solid #0072C4",
    "&:hover": {
      borderColor: "#0072C4",
    },
  },
  cardBorderEmerald: {
    borderTop: "3px solid #10B981",
    "&:hover": {
      borderColor: "#10B981",
    },
  },
  aiCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "18px",
  },
  aiIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: theme.borderRadius.b250,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.surface.medium,
    flexShrink: 0,
  },
  aiIconBoxEmerald: {
    width: "48px",
    height: "48px",
    borderRadius: theme.borderRadius.b250,
    backgroundColor: "#ECFDF5",
    border: "1px solid #A7F3D0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#059669",
    flexShrink: 0,
  },
  aiCardTitle: {
    fontSize: "1.375rem",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    margin: 0,
  },
  aiCardText: {
    fontSize: "0.9375rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 24px 0",
  },

  /* Interactive AI Sub-Mockup Widgets */
  ticketPreviewBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: theme.borderRadius.b250,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  transcriptQuote: {
    padding: "10px 12px",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: "#FFFFFF",
    borderLeft: "3px solid #0072C4",
    fontSize: "0.8125rem",
    color: "#334155",
    lineHeight: 1.5,
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
  },
  ticketGeneratedRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 12px",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: "#F0FDF4",
    border: "1px solid #BBF7D0",
    fontSize: "0.8125rem",
  },
  ticketBadge: {
    backgroundColor: "#16A34A",
    color: "#FFFFFF",
    fontWeight: 700,
    fontSize: "0.6875rem",
    padding: "3px 8px",
    borderRadius: "4px",
    marginRight: "8px",
  },

  /* Search Preview Box */
  searchPreviewBox: {
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: theme.borderRadius.b250,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  searchBarMock: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #CBD5E1",
    borderRadius: theme.borderRadius.b150,
    padding: "8px 12px",
    fontSize: "0.8125rem",
    color: "#0F172A",
  },
  verifiedProofBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 12px",
    borderRadius: theme.borderRadius.b150,
    backgroundColor: "#EFF6FF",
    border: "1px solid #BFDBFE",
    fontSize: "0.75rem",
    color: "#1E40AF",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 3: ENTERPRISE USAGE (4 CARDS GRID)
     ───────────────────────────────────────────────────────────────────────────── */
  enterpriseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "20px",
    alignItems: "stretch",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 540px)": {
      gridTemplateColumns: "1fr",
    },
  },
  usageCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: theme.borderRadius.b300,
    padding: "24px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.03)",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    boxSizing: "border-box",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
    cursor: "default",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-4px)",
      boxShadow: "0 12px 28px rgba(0, 114, 196, 0.1)",
    },
  },
  usageIconWrap: {
    width: "44px",
    height: "44px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    marginBottom: "16px",
    flexShrink: 0,
    transition: "all 0.2s ease",
  },
  usageCardTitle: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 8px 0",
  },
  usageCardDesc: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
    flex: 1,
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     ENTERPRISE REALITIES: CTO TRUST BLOCKS
     ───────────────────────────────────────────────────────────────────────────── */
  enterpriseRealitiesSection: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: theme.light.neutral.surface.lighter,
    overflow: "hidden",
    boxSizing: "border-box",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  enterpriseRealitiesContainer: {
    maxWidth: "1240px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  enterpriseRealitiesHeader: {
    textAlign: "center",
    maxWidth: "768px",
    margin: "0 auto 64px auto",
    "@media (max-width: 768px)": {
      marginBottom: "40px",
    },
  },
  enterpriseRealitiesKicker: {
    fontSize: "0.8125rem",
    fontWeight: 800,
    color: theme.light.negative.surface.dark,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    marginBottom: "12px",
    display: "inline-block",
  },
  enterpriseRealitiesTitle: {
    fontSize: "2.75rem",
    fontWeight: 800,
    lineHeight: 1.2,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 16px 0",
    letterSpacing: "-0.03em",
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  enterpriseRealitiesDescription: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },
  enterpriseRealitiesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "28px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "24px",
      maxWidth: "540px",
    },
  },
  realityCard: {
    backgroundColor: theme.light.neutral.surface.lighter,
    borderRadius: "24px",
    padding: "36px 32px",
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: "0 10px 30px -5px rgba(0, 0, 0, 0.04), 0 2px 6px -1px rgba(0, 0, 0, 0.02)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxSizing: "border-box",
    transition: "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
    position: "relative",
    overflow: "hidden",
    height: "100%",
    "&:hover": {
      transform: "translateY(-5px)",
      boxShadow: "0 20px 40px -10px rgba(0, 0, 0, 0.09), 0 4px 12px -2px rgba(0, 0, 0, 0.04)",
      borderColor: theme.light.neutral.border.medium,
    },
    "@media (max-width: 600px)": {
      padding: "28px 24px",
    },
  },
  cardGuestBorder: {
    borderTop: `3px solid ${theme.light.warning.surface.medium}`,
  },
  cardDeepWorkBorder: {
    borderTop: `3px solid ${theme.light.brand.surface.medium}`,
  },
  cardEdiscoveryBorder: {
    borderTop: `3px solid ${theme.light.positive.surface.medium}`,
  },
  realityCardContentTop: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  realityIconContainer: {
    width: "50px",
    height: "50px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "24px",
    transition: "transform 0.3s ease",
  },
  iconGuest: {
    backgroundColor: theme.light.warning.surface.lighter,
    border: `1px solid ${theme.light.warning.border.light}`,
    color: theme.light.warning.surface.dark,
  },
  iconDeepWork: {
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
  },
  iconEdiscovery: {
    backgroundColor: theme.light.positive.surface.lighter,
    border: `1px solid ${theme.light.positive.border.light}`,
    color: theme.light.positive.surface.medium,
  },
  realityCardTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 12px 0",
    letterSpacing: "-0.01em",
  },
  realityCardDescription: {
    fontSize: "0.875rem",
    lineHeight: 1.65,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 28px 0",
  },
  realityCardBottom: {
    marginTop: "auto",
    width: "100%",
  },
  guestBadge: {
    backgroundColor: theme.light.warning.surface.lighter,
    border: `1px solid ${theme.light.warning.border.light}`,
    color: theme.light.warning.surface.dark,
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "9px 14px",
    borderRadius: "8px",
    textAlign: "center",
    display: "block",
    letterSpacing: "0.02em",
  },
  deepWorkBadge: {
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    color: theme.light.neutral.onSurface.title,
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "9px 14px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    letterSpacing: "0.02em",
  },
  deepWorkDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.negative.surface.medium,
  },
  ediscoveryBadge: {
    backgroundColor: theme.light.positive.surface.lighter,
    border: `1px solid ${theme.light.positive.border.light}`,
    color: theme.light.positive.surface.dark,
    fontSize: "0.75rem",
    fontWeight: 700,
    padding: "9px 14px",
    borderRadius: "8px",
    textAlign: "center",
    display: "block",
    letterSpacing: "0.02em",
  },

  /* ─────────────────────────────────────────────────────────────────────────────
     SECTION 4: UNIFIED MOBILE EXPERIENCE
     ───────────────────────────────────────────────────────────────────────────── */
  mobileSection: {
    maxWidth: "1280px",
    margin: "0 auto",
    padding: "88px 24px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  mobileSplit: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  mobilePhoneCol: {
    display: "flex",
    justifyContent: "center",
  },
  mobileDetailsCol: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  mobileFeaturesList: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    marginTop: "8px",
  },
  mobileFeatureItem: {
    display: "flex",
    gap: "14px",
    alignItems: "flex-start",
  },
  mobileFeatureIcon: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    color: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: "2px",
  },
  mobileFeatureTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: "0 0 4px 0",
  },
  mobileFeatureText: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    margin: 0,
  },

  /* Store Buttons */
  downloadButtonsRow: {
    display: "flex",
    gap: "14px",
    marginTop: "8px",
    flexWrap: "wrap",
  },
  storeButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    borderRadius: theme.borderRadius.b300,
    padding: "12px 20px",
    textDecoration: "none",
    boxShadow: theme.elevation.s,
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#1E293B",
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.m,
    },
  },
  storeIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  storeTextCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  storeSubtitle: {
    fontSize: "0.6875rem",
    color: "#94A3B8",
    lineHeight: 1,
    marginBottom: "2px",
  },
  storeTitle: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.2,
  },

  /* Ratings */
  reviewsRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginTop: "4px",
  },
  starRatingGroup: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  starsGroup: {
    display: "flex",
    color: "#F59E0B",
  },
  ratingNumber: {
    fontWeight: 800,
    fontSize: "0.9375rem",
    color: theme.light.neutral.onSurface.title,
  },
  reviewsCountText: {
    fontSize: "0.8125rem",
    color: theme.light.neutral.onSurface.medium,
  },
}));
