import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  page: {
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    overflow: "hidden",
  },

  /* ─────────────────────────────────────────────────────────────
     HERO SECTION WITH EMBEDDED INTERACTIVE WEB APP MOCKUP
     ───────────────────────────────────────────────────────────── */
  hero: {
    maxWidth: "1240px",
    margin: "0 auto",
    padding: "56px 24px 80px",
    textAlign: "center",
    position: "relative",
    "@media (max-width: 600px)": {
      padding: "36px 16px 56px",
    },
  },
  glow: {
    position: "absolute",
    width: "580px",
    height: "380px",
    top: "30px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(110px)",
    opacity: 0.85,
    borderRadius: "50%",
    pointerEvents: "none",
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    marginBottom: "52px",
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
    fontSize: "0.875rem",
    fontWeight: 600,
    boxShadow: theme.elevation.s,
    marginBottom: "20px",
  },
  heroTitle: {
    maxWidth: "920px",
    margin: "0 auto 20px auto",
    fontSize: "3.5rem",
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
  },
  heroTitleAccent: {
    display: "block",
    backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`,
    WebkitBackgroundClip: "text",
    backgroundClip: "text",
    color: "transparent",
  },
  heroDescription: {
    maxWidth: "820px",
    margin: "0 auto 36px auto",
    color: theme.light.neutral.onSurface.medium,
    fontSize: "1.125rem",
    lineHeight: 1.7,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroPrimaryButton: {
    border: "none",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "14px 34px",
    fontFamily: "inherit",
    fontSize: "1.0625rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: theme.elevation.m,
    transition: "transform 0.2s ease, background-color 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.darker,
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.l,
    },
  },
  webMockupWrapper: {
    position: "relative",
    zIndex: 2,
    marginTop: "20px",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 1: ZERO-DAY ONBOARDING
     ───────────────────────────────────────────────────────────── */
  sectionOne: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: theme.light.neutral.surface.lighter,
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "64px 16px",
    },
  },
  ambientBlobBrand: {
    position: "absolute",
    top: "40px",
    left: "15%",
    width: "400px",
    height: "400px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobInfo: {
    position: "absolute",
    bottom: "20px",
    right: "10%",
    width: "360px",
    height: "360px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.6,
    pointerEvents: "none",
    zIndex: 0,
  },
  container: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  eyebrowPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    width: "fit-content",
  },
  pingDot: {
    position: "relative",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    boxShadow: `0 0 0 3px ${theme.light.brand.surface.lighter}`,
  },
  eyebrowText: {
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
  },
  sectionTitle: {
    marginTop: "20px",
    marginBottom: "16px",
    fontSize: "2.75rem",
    lineHeight: 1.2,
    letterSpacing: "-0.03em",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  sectionTitleWavy: {
    color: theme.light.brand.onSurface.default,
    textDecoration: "underline",
    textDecorationStyle: "wavy",
    textDecorationColor: theme.light.brand.border.medium,
    textUnderlineOffset: "8px",
  },
  sectionSubtitle: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 36px 0",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
    },
  },

  /* Stepper Timeline */
  timelineWrapper: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    marginTop: "28px",
  },
  timelineLine: {
    position: "absolute",
    left: "17px",
    top: "20px",
    bottom: "20px",
    width: "2px",
    background: `linear-gradient(180deg, ${theme.light.brand.surface.medium} 0%, ${theme.light.info.surface.medium} 50%, ${theme.light.neutral.border.light} 100%)`,
  },
  stepItem: {
    position: "relative",
    display: "flex",
    alignItems: "flex-start",
    gap: "18px",
    zIndex: 2,
    cursor: "default",
  },
  stepNumberCircle: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.onSurface.default,
    fontWeight: 700,
    fontSize: "0.9375rem",
    flexShrink: 0,
    boxShadow: theme.elevation.s,
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },
  stepNumberCircleActive: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.9375rem",
    flexShrink: 0,
    boxShadow: theme.elevation.m,
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },
  stepContentBox: {
    flex: 1,
    padding: "16px 20px",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.s,
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.m,
    },
  },
  stepContentBoxActive: {
    flex: 1,
    padding: "16px 20px",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: "#F8FBFF",
    border: `1.5px solid ${theme.light.brand.border.medium}`,
    boxShadow: theme.elevation.m,
  },
  stepTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "4px",
  },
  stepTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
    margin: 0,
  },
  stepTag: {
    padding: "3px 8px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    fontSize: "0.6875rem",
    fontWeight: 700,
  },
  stepDescription: {
    fontSize: "0.875rem",
    lineHeight: 1.55,
    color: theme.light.neutral.onSurface.medium,
    margin: "4px 0 0",
  },

  /* Interactive Glass Showcase Card (Right Column) */
  glassShowcaseCard: {
    position: "relative",
    width: "100%",
    maxWidth: "500px",
    margin: "0 auto",
    padding: "24px",
    borderRadius: theme.borderRadius.b400,
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.l,
    boxSizing: "border-box",
  },
  glassWindowBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: "16px",
    marginBottom: "18px",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
  },
  trafficDots: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  dotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: theme.light.negative.surface.medium,
  },
  dotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: theme.light.warning.surface.medium,
  },
  dotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: theme.light.positive.surface.medium,
  },
  pipelineUrl: {
    marginLeft: "10px",
    fontSize: "0.75rem",
    color: theme.light.neutral.onSurface.dark,
    fontFamily: "monospace",
  },
  liveSyncBadge: {
    padding: "3px 8px",
    borderRadius: "6px",
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.06em",
  },
  canvasFlow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "14px",
    padding: "6px 0",
  },
  nodeRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxSizing: "border-box",
    transition: "all 0.2s ease",
    "&:hover": {
      boxShadow: theme.elevation.s,
    },
  },
  nodeRowHighlighted: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1.5px solid ${theme.light.brand.border.medium}`,
    boxShadow: theme.elevation.m,
    boxSizing: "border-box",
  },
  nodeLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  nodeIconBox: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.onSurface.default,
  },
  nodeIconBoxBrand: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: theme.light.brand.surface.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.neutral.onSurface.inverse,
  },
  nodeTitle: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.title,
  },
  nodeEmailText: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: theme.light.brand.onSurface.default,
    fontFamily: "monospace",
  },
  nodeTag: {
    padding: "3px 8px",
    borderRadius: "9999px",
    backgroundColor: theme.light.neutral.surface.medium,
    color: theme.light.neutral.onSurface.title,
    fontSize: "0.6875rem",
    fontWeight: 600,
  },
  nodeSpeedBadge: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 10px",
    borderRadius: "9999px",
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
  },
  connectorPulsing: {
    position: "relative",
    width: "2px",
    height: "28px",
    backgroundColor: theme.light.brand.border.medium,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  connectorPingDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    boxShadow: `0 0 0 3px ${theme.light.brand.surface.lighter}`,
  },
  branchingFork: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  forkTopStem: {
    width: "2px",
    height: "14px",
    backgroundColor: theme.light.neutral.border.medium,
  },
  forkBar: {
    width: "75%",
    height: "2px",
    backgroundColor: theme.light.neutral.border.medium,
  },
  forkBottomStems: {
    width: "75%",
    display: "flex",
    justifyContent: "space-between",
  },
  forkBottomStem: {
    width: "2px",
    height: "14px",
    backgroundColor: theme.light.neutral.border.medium,
  },
  bottomNodesGrid: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
  },
  bottomNodeCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "12px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: theme.light.neutral.onSurface.title,
    boxShadow: theme.elevation.s,
  },
  glassCardFooter: {
    marginTop: "18px",
    paddingTop: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    fontSize: "0.6875rem",
    color: theme.light.neutral.onSurface.dark,
    fontFamily: "monospace",
  },
  footerStatusOk: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  footerDotGreen: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: theme.light.positive.surface.medium,
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 2: GLOBAL ARCHITECTURE & COMPLIANCE
     ───────────────────────────────────────────────────────────── */
  sectionTwo: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#FAFCFE",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    "@media (max-width: 768px)": {
      padding: "64px 16px",
    },
  },
  secTwoHeader: {
    maxWidth: "800px",
    display: "flex",
    flexDirection: "column",
  },
  topologyCard: {
    marginTop: "44px",
    padding: "32px",
    borderRadius: theme.borderRadius.b400,
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.m,
    "@media (max-width: 768px)": {
      padding: "20px",
    },
  },
  topologyHeaderRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    paddingBottom: "20px",
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
  },
  topologyHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  topologyIconBox: {
    width: "42px",
    height: "42px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.brand.surface.lighter,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.onSurface.default,
  },
  topologyTitle: {
    margin: 0,
    fontSize: "1.125rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
  },
  topologySubtitle: {
    margin: "3px 0 0",
    fontSize: "0.8125rem",
    color: theme.light.neutral.onSurface.medium,
  },
  topologyBadgesRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  complianceBadgePositive: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "5px 12px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.positive.surface.lighter,
    color: theme.light.positive.onSurface.medium,
    border: `1px solid ${theme.light.positive.border.light}`,
    fontSize: "0.75rem",
    fontWeight: 700,
  },
  complianceBadgeBrand: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "5px 12px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
    fontSize: "0.75rem",
    fontWeight: 700,
  },
  latencyMatrixGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "16px",
    marginTop: "24px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 520px)": {
      gridTemplateColumns: "1fr",
    },
  },
  edgeNodeCard: {
    padding: "18px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: theme.light.neutral.surface.lighter,
      borderColor: theme.light.brand.border.light,
      boxShadow: theme.elevation.s,
    },
  },
  edgeNodeHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  edgeRegionName: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    fontFamily: "monospace",
    color: theme.light.neutral.onSurface.medium,
    letterSpacing: "0.05em",
  },
  edgeStatusPulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.positive.surface.medium,
    boxShadow: `0 0 0 2px ${theme.light.positive.surface.lighter}`,
  },
  edgeLatencyBig: {
    fontSize: "1.75rem",
    fontWeight: 800,
    fontFamily: "monospace",
    color: theme.light.neutral.onSurface.title,
    lineHeight: 1,
  },
  edgeLatencyUnit: {
    fontSize: "0.875rem",
    fontWeight: 500,
    color: theme.light.neutral.onSurface.medium,
    marginLeft: "2px",
  },
  progressBarBg: {
    width: "100%",
    height: "6px",
    borderRadius: "9999px",
    backgroundColor: theme.light.neutral.surface.medium,
    margin: "12px 0 10px",
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: "9999px",
    backgroundColor: theme.light.brand.surface.medium,
  },
  edgeLocationSub: {
    fontSize: "0.75rem",
    color: theme.light.neutral.onSurface.dark,
  },

  /* 3 Supporting Security Cards */
  securityGridThree: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    marginTop: "32px",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "1fr",
      gap: "18px",
    },
  },
  securityMiniCard: {
    padding: "26px",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.s,
    display: "flex",
    flexDirection: "column",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: theme.elevation.m,
    },
  },
  securityIconBox: {
    width: "44px",
    height: "44px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.brand.surface.lighter,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.light.brand.onSurface.default,
    marginBottom: "16px",
  },
  securityCardTitle: {
    margin: "0 0 10px 0",
    fontSize: "1.1875rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
  },
  securityCardText: {
    margin: 0,
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 3: UNRESTRICTED EMAIL, FULLY INCLUDED
     ───────────────────────────────────────────────────────────── */
  sectionThree: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: theme.light.neutral.surface.lighter,
    "@media (max-width: 768px)": {
      padding: "64px 16px",
    },
  },
  centerHeader: {
    textAlign: "center",
    maxWidth: "760px",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  fourCardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "22px",
    marginTop: "52px",
    "@media (max-width: 1024px)": {
      gridTemplateColumns: "repeat(2, 1fr)",
    },
    "@media (max-width: 560px)": {
      gridTemplateColumns: "1fr",
    },
  },
  featureBenefitCard: {
    padding: "28px 24px",
    borderRadius: theme.borderRadius.b400,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexDirection: "column",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundColor: theme.light.neutral.surface.lighter,
      borderColor: theme.light.brand.border.light,
      transform: "translateY(-4px)",
      boxShadow: theme.elevation.l,
      "& $hoverLink": {
        opacity: 1,
        transform: "translateX(2px)",
      },
    },
  },
  featureBenefitIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "20px",
  },
  featureBenefitTitle: {
    margin: "0 0 10px 0",
    fontSize: "1.1875rem",
    fontWeight: 700,
    color: theme.light.neutral.onSurface.title,
  },
  featureBenefitText: {
    margin: 0,
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: theme.light.neutral.onSurface.medium,
    flexGrow: 1,
  },
  hoverLink: {
    marginTop: "20px",
    paddingTop: "12px",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    color: theme.light.brand.onSurface.default,
    fontSize: "0.8125rem",
    fontWeight: 700,
    opacity: 0.85,
    transition: "all 0.2s ease",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 4: INTELLIGENT ORGANIZATION
     ───────────────────────────────────────────────────────────── */
  sectionFour: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#F8FAFD",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    borderBottom: `1px solid ${theme.light.neutral.border.light}`,
    "@media (max-width: 768px)": {
      padding: "64px 16px",
    },
  },
  twoCardComparisonGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "32px",
    marginTop: "52px",
    "@media (max-width: 860px)": {
      gridTemplateColumns: "1fr",
      gap: "24px",
    },
  },
  intelligentCard: {
    padding: "36px",
    borderRadius: theme.borderRadius.b400,
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    boxShadow: theme.elevation.m,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    "@media (max-width: 600px)": {
      padding: "24px",
    },
  },
  searchMockupBar: {
    marginTop: "28px",
    padding: "14px 16px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  searchQueryText: {
    flex: 1,
    fontSize: "0.875rem",
    fontStyle: "italic",
    color: theme.light.neutral.onSurface.medium,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  kbdShortcut: {
    padding: "3px 8px",
    borderRadius: "6px",
    backgroundColor: theme.light.neutral.surface.lighter,
    border: `1px solid ${theme.light.neutral.border.light}`,
    color: theme.light.neutral.onSurface.dark,
    fontSize: "0.6875rem",
    fontFamily: "monospace",
    fontWeight: 700,
  },
  tagsCollectionMockup: {
    marginTop: "28px",
    padding: "16px",
    borderRadius: theme.borderRadius.b200,
    backgroundColor: theme.light.neutral.surface.light,
    border: `1px solid ${theme.light.neutral.border.light}`,
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },
  tagChipRed: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.negative.surface.lighter,
    color: theme.light.negative.onSurface.medium,
    border: `1px solid ${theme.light.negative.border.light}`,
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipAmber: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.warning.surface.lighter,
    color: theme.light.warning.surface.dark,
    border: `1px solid ${theme.light.warning.border.light}`,
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipBlue: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipGreen: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.positive.surface.lighter,
    color: theme.light.positive.surface.dark,
    border: `1px solid ${theme.light.positive.border.light}`,
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 5: UNIFIED MOBILE EXPERIENCE
     ───────────────────────────────────────────────────────────── */
  sectionFive: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: theme.light.neutral.surface.lighter,
    overflow: "hidden",
    "@media (max-width: 768px)": {
      padding: "64px 16px",
    },
  },
  mobileSplitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
      gap: "48px",
    },
  },
  mobileLeftCol: {
    display: "flex",
    justifyContent: "center",
    order: 1,
    "@media (max-width: 960px)": {
      order: 2,
    },
  },
  mobileRightCol: {
    display: "flex",
    flexDirection: "column",
    order: 2,
    "@media (max-width: 960px)": {
      order: 1,
    },
  },
  downloadButtonsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "16px",
    marginTop: "32px",
  },
  storeButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 22px",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: theme.light.neutral.surface.inverse,
    color: theme.light.neutral.onSurface.inverse,
    textDecoration: "none",
    boxShadow: theme.elevation.m,
    transition: "all 0.2s ease",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#111827",
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.l,
    },
  },
  storeIcon: {
    width: "24px",
    height: "24px",
    fill: "currentColor",
  },
  storeTextCol: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
  },
  storeSubtitle: {
    fontSize: "0.6875rem",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    opacity: 0.75,
  },
  storeTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    lineHeight: 1.2,
  },
  reviewsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "16px",
    marginTop: "36px",
    paddingTop: "24px",
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
  },
  starRatingGroup: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  starsGroup: {
    display: "flex",
    color: theme.light.warning.surface.medium,
  },
  ratingNumber: {
    marginLeft: "6px",
    fontSize: "1.125rem",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
  },
  reviewsCountText: {
    fontSize: "0.875rem",
    color: theme.light.neutral.onSurface.medium,
  },
}));
