import { createUseStyles } from "react-jss";
import { Theme } from "../../../../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  page: {
    backgroundColor: theme.light.neutral.surface.lighter,
    color: theme.light.neutral.onSurface.title,
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    width: "100%",
    overflowX: "hidden",
  },

  /* ─────────────────────────────────────────────────────────────
     HERO SECTION WITH EMBEDDED INTERACTIVE WEB APP MOCKUP
     ───────────────────────────────────────────────────────────── */
  hero: {
    maxWidth: "1240px",
    margin: "0 auto",
    padding: "56px 24px 80px",
    textAlign: "center",
    position: "relative",
    "@media (max-width: 600px)": {
      padding: "36px 16px 56px",
    },
  },
  glow: {
    position: "absolute",
    width: "580px",
    height: "380px",
    top: "30px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(110px)",
    opacity: 0.85,
    borderRadius: "50%",
    pointerEvents: "none",
  },
  heroContent: {
    position: "relative",
    zIndex: 2,
    marginBottom: "52px",
  },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 16px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    color: theme.light.brand.onSurface.default,
    border: `1px solid ${theme.light.brand.border.light}`,
    fontSize: "0.875rem",
    fontWeight: 600,
    boxShadow: theme.elevation.s,
    marginBottom: "20px",
  },
  heroTitle: {
    maxWidth: "920px",
    margin: "0 auto 20px auto",
    fontSize: "3.5rem",
    lineHeight: 1.15,
    letterSpacing: "-0.03em",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    "@media (max-width: 768px)": {
      fontSize: "2.25rem",
    },
  },
  heroTitleAccent: {
    display: "block",
    backgroundImage: `linear-gradient(90deg, ${theme.light.brand.surface.medium}, ${theme.light.info.surface.medium})`,
    WebkitBackgroundClip: "text",
    backgroundClip: "text",
    color: "transparent",
  },
  heroDescription: {
    maxWidth: "820px",
    margin: "0 auto 36px auto",
    color: theme.light.neutral.onSurface.medium,
    fontSize: "1.125rem",
    lineHeight: 1.7,
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      padding: "0 12px",
    },
  },
  heroPrimaryButton: {
    border: "none",
    borderRadius: theme.borderRadius.b300,
    backgroundColor: theme.light.brand.surface.medium,
    color: theme.light.neutral.onSurface.inverse,
    padding: "14px 34px",
    fontFamily: "inherit",
    fontSize: "1.0625rem",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: theme.elevation.m,
    transition:
      "transform 0.2s ease, background-color 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      backgroundColor: theme.light.brand.surface.darker,
      transform: "translateY(-2px)",
      boxShadow: theme.elevation.l,
    },
  },
  webMockupWrapper: {
    position: "relative",
    zIndex: 2,
    marginTop: "20px",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 1: ZERO-DAY ONBOARDING
     ───────────────────────────────────────────────────────────── */
  sectionOne: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: theme.light.neutral.surface.lighter,
    borderTop: `1px solid ${theme.light.neutral.border.light}`,
    overflow: "hidden",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  ambientBlobBrand: {
    position: "absolute",
    top: "40px",
    left: "15%",
    width: "400px",
    height: "400px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.7,
    pointerEvents: "none",
    zIndex: 0,
  },
  ambientBlobInfo: {
    position: "absolute",
    bottom: "20px",
    right: "10%",
    width: "360px",
    height: "360px",
    borderRadius: "50%",
    backgroundColor: theme.light.info.surface.lighter,
    filter: "blur(100px)",
    opacity: 0.6,
    pointerEvents: "none",
    zIndex: 0,
  },
  container: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: "1200px",
    margin: "0 auto",
    boxSizing: "border-box",
  },
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.15fr) minmax(0, 0.85fr)",
    gap: "clamp(32px, 4vw, 56px)",
    alignItems: "center",
    "@media (max-width: 1040px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "44px",
    },
  },
  gridCol: {
    minWidth: 0,
    width: "100%",
  },
  eyebrowPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 14px",
    borderRadius: theme.borderRadius.b2500,
    backgroundColor: theme.light.brand.surface.lighter,
    border: `1px solid ${theme.light.brand.border.light}`,
    width: "fit-content",
  },
  pingDot: {
    position: "relative",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: theme.light.brand.surface.medium,
    boxShadow: `0 0 0 3px ${theme.light.brand.surface.lighter}`,
  },
  eyebrowText: {
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: theme.light.brand.onSurface.default,
  },
  sectionTitle: {
    marginTop: "20px",
    marginBottom: "16px",
    fontSize: "2.75rem",
    lineHeight: 1.2,
    letterSpacing: "-0.03em",
    fontWeight: 800,
    color: theme.light.neutral.onSurface.title,
    "@media (max-width: 768px)": {
      fontSize: "2rem",
    },
  },
  sectionTitleWavy: {
    color: theme.light.brand.onSurface.default,
    textDecoration: "underline",
    textDecorationStyle: "line",
    textDecorationColor: theme.light.brand.border.medium,
    textUnderlineOffset: "8px",
    whiteSpace: "nowrap",
  },
  sectionSubtitle: {
    fontSize: "1.125rem",
    lineHeight: 1.7,
    color: theme.light.neutral.onSurface.medium,
    margin: "0 0 36px 0",
    "@media (max-width: 768px)": {
      fontSize: "1rem",
      margin: "0 0 24px 0",
    },
  },

  /* Stepper Timeline */
  timelineWrapper: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    marginTop: "28px",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      gap: "10px",
      marginTop: "16px",
    },
  },
  timelineLine: {
    position: "absolute",
    left: "17px",
    top: "20px",
    bottom: "20px",
    width: "2px",
    background:
      "linear-gradient(180deg, #0072C4 0%, #0284C7 50%, #E2E8F0 100%)",
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  stepItem: {
    position: "relative",
    display: "flex",
    alignItems: "flex-start",
    gap: "18px",
    zIndex: 2,
    cursor: "pointer",
    transition: "all 0.2s ease",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      display: "block",
      gap: 0,
    },
  },
  stepNumberCircle: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    border: "1.5px solid #CBD5E1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    fontWeight: 700,
    fontSize: "0.9375rem",
    flexShrink: 0,
    boxShadow: "0 1px 3px rgba(15, 23, 42, 0.06)",
    boxSizing: "border-box",
    transition:
      "background-color 0.25s ease, border-color 0.25s ease, color 0.25s ease, box-shadow 0.25s ease",
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  stepNumberCircleActive: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    border: "1.5px solid #0072C4",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: "0.9375rem",
    flexShrink: 0,
    boxShadow: "0 0 0 4px rgba(0, 114, 196, 0.18)",
    boxSizing: "border-box",
    transition:
      "background-color 0.25s ease, border-color 0.25s ease, color 0.25s ease, box-shadow 0.25s ease",
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  stepContentBox: {
    flex: 1,
    width: "100%",
    padding: "18px 22px",
    borderRadius: "16px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    boxSizing: "border-box",
    transition: "border-color 0.25s ease, box-shadow 0.25s ease",
    "&:hover": {
      borderColor: "#0072C4",
      boxShadow: "0 8px 20px -2px rgba(0, 114, 196, 0.08)",
    },
    "@media (max-width: 768px)": {
      padding: "16px 18px",
    },
  },
  stepContentBoxActive: {
    flex: 1,
    width: "100%",
    padding: "18px 22px",
    borderRadius: "16px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #0072C4",
    boxShadow:
      "0 10px 25px -4px rgba(0, 114, 196, 0.12), 0 2px 6px -2px rgba(0, 114, 196, 0.04)",
    boxSizing: "border-box",
    transition: "border-color 0.25s ease, box-shadow 0.25s ease",
    "@media (max-width: 768px)": {
      padding: "16px 18px",
    },
  },
  stepTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "4px",
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  stepTitle: {
    fontSize: "1.0625rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
    "@media (max-width: 768px)": {
      fontSize: "0.9375rem",
    },
  },
  stepTag: {
    padding: "3px 10px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    fontSize: "0.6875rem",
    fontWeight: 700,
    border: "1px solid rgba(0, 114, 196, 0.2)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  stepDescription: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: "#64748B",
    margin: "4px 0 0",
    "@media (max-width: 768px)": {
      fontSize: "0.8125rem",
      lineHeight: 1.5,
    },
  },

  /* Mobile Stepper Quick Bar & Header */
  mobileQuickTabs: {
    display: "none",
    "@media (max-width: 768px)": {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: "8px",
      marginBottom: "16px",
      width: "100%",
      boxSizing: "border-box",
    },
  },
  mobileQuickTabBtn: {
    padding: "8px 6px",
    borderRadius: "10px",
    border: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    color: "#64748B",
    fontSize: "0.75rem",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  mobileQuickTabBtnActive: {
    padding: "8px 6px",
    borderRadius: "10px",
    border: "1.5px solid #0072C4",
    backgroundColor: "#F0F7FF",
    color: "#0072C4",
    fontSize: "0.75rem",
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.12)",
  },
  mobileQuickTabNum: {
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    backgroundColor: "#E2E8F0",
    color: "#475569",
    fontSize: "0.6875rem",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mobileQuickTabNumActive: {
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mobileCardHeader: {
    display: "none",
    "@media (max-width: 768px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexWrap: "wrap",
      gap: "8px",
      marginBottom: "6px",
    },
  },
  mobileBadgeAndTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    flex: 1,
  },
  mobileStepBadge: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#F1F5F9",
    border: "1.5px solid #CBD5E1",
    color: "#64748B",
    fontSize: "0.75rem",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mobileStepBadgeActive: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    border: "1.5px solid #0072C4",
    color: "#FFFFFF",
    fontSize: "0.75rem",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxShadow: "0 0 0 3px rgba(0, 114, 196, 0.2)",
  },
  mobileStepConnector: {
    display: "none",
    "@media (max-width: 768px)": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "2px 0",
      zIndex: 1,
    },
  },
  mobileConnectorLine: {
    width: "2px",
    height: "10px",
    backgroundColor: "#CBD5E1",
    borderRadius: "1px",
  },

  /* Interactive Glass Showcase Card (Right Column) */
  glassShowcaseCard: {
    position: "relative",
    width: "100%",
    maxWidth: "500px",
    margin: "0 auto",
    padding: "26px",
    borderRadius: "24px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow:
      "0 20px 40px -10px rgba(15, 23, 42, 0.08), 0 4px 12px -2px rgba(15, 23, 42, 0.03)",
    boxSizing: "border-box",
    "@media (max-width: 600px)": {
      padding: "16px",
      borderRadius: "18px",
    },
  },
  glassWindowBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: "16px",
    marginBottom: "18px",
    borderBottom: "1px solid #E2E8F0",
    gap: "8px",
    "@media (max-width: 480px)": {
      paddingBottom: "12px",
      marginBottom: "14px",
    },
  },
  trafficDots: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexShrink: 0,
  },
  dotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#EF4444",
  },
  dotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#F59E0B",
  },
  dotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
  },
  pipelineUrl: {
    marginLeft: "10px",
    fontSize: "0.75rem",
    color: "#64748B",
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 480px)": {
      fontSize: "0.6875rem",
      maxWidth: "130px",
      marginLeft: "6px",
    },
  },
  liveSyncBadge: {
    padding: "3px 10px",
    borderRadius: "6px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.06em",
    flexShrink: 0,
    "@media (max-width: 480px)": {
      fontSize: "0.625rem",
      padding: "2px 8px",
    },
  },
  canvasFlow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "14px",
    padding: "6px 0",
    width: "100%",
    boxSizing: "border-box",
  },
  nodeRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    borderRadius: "14px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxSizing: "border-box",
    transition: "all 0.25s ease",
    boxShadow: "0 2px 6px rgba(15, 23, 42, 0.03)",
    gap: "8px",
    "&:hover": {
      boxShadow: "0 4px 14px rgba(15, 23, 42, 0.06)",
      borderColor: "rgba(0, 114, 196, 0.25)",
    },
    "@media (max-width: 480px)": {
      padding: "12px 12px",
    },
  },
  nodeRowHighlighted: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    borderRadius: "14px",
    backgroundColor: "#F0F7FF",
    border: "1.5px solid rgba(0, 114, 196, 0.4)",
    boxShadow: "0 8px 24px -3px rgba(0, 114, 196, 0.15)",
    boxSizing: "border-box",
    transition: "all 0.25s ease",
    transform: "scale(1.02)",
    gap: "8px",
    "@media (max-width: 600px)": {
      transform: "none",
    },
    "@media (max-width: 480px)": {
      padding: "12px 12px",
    },
  },
  nodeLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
    flex: 1,
  },
  nodeIconBox: {
    width: "34px",
    height: "34px",
    borderRadius: "10px",
    backgroundColor: "rgba(241, 245, 249, 0.9)",
    border: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    flexShrink: 0,
  },
  nodeIconBoxBrand: {
    width: "34px",
    height: "34px",
    borderRadius: "10px",
    backgroundColor: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#FFFFFF",
    boxShadow: "0 2px 8px rgba(0, 114, 196, 0.3)",
    flexShrink: 0,
  },
  nodeTitle: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "#0F172A",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 480px)": {
      fontSize: "0.8125rem",
    },
  },
  nodeEmailText: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#0072C4",
    fontFamily: "monospace",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 480px)": {
      fontSize: "0.8125rem",
    },
  },
  nodeTag: {
    padding: "3px 8px",
    borderRadius: "9999px",
    backgroundColor: "#F1F5F9",
    color: "#64748B",
    fontSize: "0.6875rem",
    fontWeight: 600,
    border: "1px solid #E2E8F0",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  nodeTagActive: {
    padding: "3px 8px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    fontSize: "0.6875rem",
    fontWeight: 700,
    border: "1px solid rgba(0, 114, 196, 0.2)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  nodeSpeedBadge: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 10px",
    borderRadius: "9999px",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    fontWeight: 800,
    letterSpacing: "0.04em",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.3)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  connectorPulsing: {
    position: "relative",
    width: "2px",
    height: "28px",
    backgroundColor: "#CBD5E1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.3s ease",
  },
  connectorPulsingActive: {
    backgroundColor: "#0072C4",
  },
  connectorPingDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    boxShadow: "0 0 0 3px rgba(0, 114, 196, 0.2)",
  },
  branchingFork: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    transition: "opacity 0.3s ease",
  },
  branchingForkActive: {
    "& $forkTopStem, & $forkBar, & $forkBottomStem": {
      backgroundColor: "#10B981",
    },
  },
  forkTopStem: {
    width: "2px",
    height: "14px",
    backgroundColor: "#CBD5E1",
    transition: "background-color 0.3s ease",
  },
  forkBar: {
    width: "75%",
    height: "2px",
    backgroundColor: "#CBD5E1",
    transition: "background-color 0.3s ease",
  },
  forkBottomStems: {
    width: "75%",
    display: "flex",
    justifyContent: "space-between",
  },
  forkBottomStem: {
    width: "2px",
    height: "14px",
    backgroundColor: "#CBD5E1",
    transition: "background-color 0.3s ease",
  },
  bottomNodesGrid: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
    boxSizing: "border-box",
    "@media (max-width: 480px)": {
      gap: "8px",
    },
    "@media (max-width: 360px)": {
      gridTemplateColumns: "1fr",
    },
  },
  bottomNodeCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "14px 10px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "#334155",
    boxShadow: "0 2px 6px rgba(15, 23, 42, 0.03)",
    transition: "all 0.25s ease",
    boxSizing: "border-box",
    textAlign: "center",
    whiteSpace: "nowrap",
    "@media (max-width: 480px)": {
      fontSize: "0.75rem",
      padding: "10px 6px",
      gap: "5px",
    },
  },
  bottomNodeCardHighlighted: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "14px 10px",
    borderRadius: "12px",
    backgroundColor: "#F0FDF4",
    border: "1.5px solid rgba(16, 185, 129, 0.4)",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#065F46",
    boxShadow: "0 8px 20px -3px rgba(16, 185, 129, 0.15)",
    transform: "scale(1.03)",
    transition: "all 0.25s ease",
    boxSizing: "border-box",
    textAlign: "center",
    whiteSpace: "nowrap",
    "@media (max-width: 600px)": {
      transform: "none",
    },
    "@media (max-width: 480px)": {
      fontSize: "0.75rem",
      padding: "10px 6px",
      gap: "5px",
    },
  },
  glassCardFooter: {
    marginTop: "18px",
    paddingTop: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: "1px solid #E2E8F0",
    fontSize: "0.6875rem",
    color: "#64748B",
    fontFamily: "monospace",
    flexWrap: "wrap",
    gap: "6px",
    "@media (max-width: 480px)": {
      fontSize: "0.625rem",
    },
  },
  footerStatusOk: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  footerDotGreen: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    boxShadow: "0 0 0 2px rgba(16, 185, 129, 0.2)",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 2: GLOBAL ARCHITECTURE & COMPLIANCE
     ───────────────────────────────────────────────────────────── */
  sectionTwo: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    borderBottom: "1px solid #E2E8F0",
    overflow: "hidden",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  secTwoHeader: {
    maxWidth: "800px",
    display: "flex",
    flexDirection: "column",
  },
  topologyCard: {
    marginTop: "44px",
    padding: "36px",
    borderRadius: "24px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow:
      "0 16px 36px -6px rgba(15, 23, 42, 0.07), 0 4px 10px -2px rgba(15, 23, 42, 0.03)",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "18px 14px",
      borderRadius: "18px",
      marginTop: "28px",
    },
  },
  topologyHeaderRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    paddingBottom: "20px",
    borderBottom: "1px solid #E2E8F0",
  },
  topologyHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  topologyIconBox: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
  },
  topologyTitle: {
    margin: 0,
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  topologySubtitle: {
    margin: "3px 0 0",
    fontSize: "0.8125rem",
    color: "#64748B",
  },
  topologyBadgesRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "10px",
  },
  complianceBadgePositive: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "#059669",
    border: "1px solid rgba(16, 185, 129, 0.2)",
    fontSize: "0.75rem",
    fontWeight: 700,
  },
  complianceBadgeBrand: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    fontSize: "0.75rem",
    fontWeight: 700,
  },
  latencyMatrixGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "18px",
    marginTop: "28px",
    boxSizing: "border-box",
    "@media (max-width: 1040px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 520px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
    },
  },
  edgeNodeCard: {
    padding: "20px",
    borderRadius: "16px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.03)",
    boxSizing: "border-box",
    transition: "all 0.25s cubic-bezier(0.4, 0, 0.2, 1)",
    "&:hover": {
      backgroundColor: "#FFFFFF",
      borderColor: "rgba(0, 114, 196, 0.35)",
      boxShadow: "0 12px 28px -4px rgba(0, 114, 196, 0.12)",
      transform: "translateY(-3px)",
    },
  },
  edgeNodeHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "12px",
  },
  edgeRegionName: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    fontFamily: "monospace",
    color: "#64748B",
    letterSpacing: "0.05em",
  },
  edgeStatusPulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#10B981",
    boxShadow: "0 0 0 2px rgba(16, 185, 129, 0.2)",
  },
  edgeLatencyBig: {
    fontSize: "1.75rem",
    fontWeight: 800,
    fontFamily: "monospace",
    color: "#0F172A",
    lineHeight: 1,
  },
  edgeLatencyUnit: {
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "#64748B",
    marginLeft: "2px",
  },
  progressBarBg: {
    width: "100%",
    height: "6px",
    borderRadius: "9999px",
    backgroundColor: "#F1F5F9",
    margin: "14px 0 10px",
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: "9999px",
    backgroundColor: "#0072C4",
    backgroundImage: "linear-gradient(90deg, #0072C4 0%, #10B981 100%)",
  },
  edgeLocationSub: {
    fontSize: "0.75rem",
    color: "#64748B",
    fontWeight: 500,
  },

  /* 3 Supporting Security Cards */
  securityGridThree: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "24px",
    marginTop: "32px",
    boxSizing: "border-box",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "18px",
    },
  },
  securityMiniCard: {
    padding: "28px",
    borderRadius: "22px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow: "0 4px 20px -2px rgba(15, 23, 42, 0.04)",
    display: "flex",
    flexDirection: "column",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    boxSizing: "border-box",
    "&:hover": {
      transform: "translateY(-5px)",
      boxShadow:
        "0 20px 35px -5px rgba(0, 114, 196, 0.12), 0 10px 10px -5px rgba(15, 23, 42, 0.03)",
      borderColor: "rgba(0, 114, 196, 0.25)",
    },
    "@media (max-width: 600px)": {
      padding: "20px 16px",
      borderRadius: "16px",
    },
  },
  securityIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "18px",
  },
  securityIconBlue: {
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.18)",
  },
  securityIconPurple: {
    backgroundColor: "rgba(124, 58, 237, 0.08)",
    color: "#7C3AED",
    border: "1px solid rgba(124, 58, 237, 0.18)",
  },
  securityIconRose: {
    backgroundColor: "rgba(225, 29, 72, 0.08)",
    color: "#E11D48",
    border: "1px solid rgba(225, 29, 72, 0.18)",
  },
  securityCardTitle: {
    margin: "0 0 10px 0",
    fontSize: "1.1875rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  securityCardText: {
    margin: 0,
    fontSize: "0.875rem",
    lineHeight: 1.65,
    color: "#64748B",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 3: UNRESTRICTED EMAIL, FULLY INCLUDED
     ───────────────────────────────────────────────────────────── */
  sectionThree: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  centerHeader: {
    textAlign: "center",
    maxWidth: "760px",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  fourCardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "22px",
    marginTop: "52px",
    boxSizing: "border-box",
    "@media (max-width: 1080px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
      marginTop: "36px",
    },
    "@media (max-width: 560px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "16px",
    },
  },
  featureBenefitCard: {
    position: "relative",
    padding: "32px 26px",
    borderRadius: "22px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow: "0 4px 20px -2px rgba(15, 23, 42, 0.04)",
    display: "flex",
    flexDirection: "column",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    overflow: "hidden",
    boxSizing: "border-box",
    "&:hover": {
      backgroundColor: "#FFFFFF",
      transform: "translateY(-6px)",
      boxShadow:
        "0 20px 35px -5px rgba(0, 114, 196, 0.12), 0 10px 10px -5px rgba(15, 23, 42, 0.04)",
      borderColor: "rgba(0, 114, 196, 0.35)",
      "& $hoverLink": {
        opacity: 1,
        transform: "translateX(3px)",
        color: "#0072C4",
      },
    },
    "@media (max-width: 600px)": {
      padding: "20px 16px",
      borderRadius: "16px",
    },
  },
  benefitCardBlue: {
    borderTop: "3px solid #0072C4",
  },
  benefitCardPurple: {
    borderTop: "3px solid #7C3AED",
  },
  benefitCardGreen: {
    borderTop: "3px solid #10B981",
  },
  benefitCardAmber: {
    borderTop: "3px solid #F59E0B",
  },
  featureBenefitIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "20px",
  },
  benefitIconBlue: {
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.18)",
  },
  benefitIconPurple: {
    backgroundColor: "rgba(124, 58, 237, 0.08)",
    color: "#7C3AED",
    border: "1px solid rgba(124, 58, 237, 0.18)",
  },
  benefitIconGreen: {
    backgroundColor: "rgba(16, 185, 129, 0.08)",
    color: "#059669",
    border: "1px solid rgba(16, 185, 129, 0.18)",
  },
  benefitIconAmber: {
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    color: "#D97706",
    border: "1px solid rgba(245, 158, 11, 0.18)",
  },
  featureBenefitTitle: {
    margin: "0 0 10px 0",
    fontSize: "1.1875rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  featureBenefitText: {
    margin: 0,
    fontSize: "0.875rem",
    lineHeight: 1.65,
    color: "#64748B",
    flexGrow: 1,
  },
  hoverLink: {
    marginTop: "22px",
    paddingTop: "14px",
    borderTop: "1px solid #F1F5F9",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    color: "#0072C4",
    fontSize: "0.8125rem",
    fontWeight: 700,
    opacity: 0.9,
    transition: "all 0.25s ease",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 4: INTELLIGENT ORGANIZATION
     ───────────────────────────────────────────────────────────── */
  sectionFour: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    borderBottom: "1px solid #E2E8F0",
    overflow: "hidden",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  twoCardComparisonGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "32px",
    marginTop: "52px",
    boxSizing: "border-box",
    "@media (max-width: 960px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "24px",
      marginTop: "32px",
    },
  },
  intelligentCard: {
    padding: "36px",
    borderRadius: "24px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    boxShadow: "0 6px 24px -2px rgba(15, 23, 42, 0.05)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    boxSizing: "border-box",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 20px 35px -5px rgba(0, 114, 196, 0.10)",
      borderColor: "rgba(0, 114, 196, 0.25)",
    },
    "@media (max-width: 600px)": {
      padding: "20px 16px",
      borderRadius: "18px",
    },
  },
  intelligentIconPurple: {
    backgroundColor: "rgba(124, 58, 237, 0.08)",
    color: "#7C3AED",
    border: "1px solid rgba(124, 58, 237, 0.18)",
  },
  intelligentIconBlue: {
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.18)",
  },
  searchMockupContainer: {
    marginTop: "28px",
    width: "100%",
    boxSizing: "border-box",
  },
  searchMockupBar: {
    padding: "14px 18px",
    borderRadius: "14px",
    backgroundColor: "#F8FAFC",
    border: "1.5px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    transition: "all 0.2s ease",
    boxSizing: "border-box",
    maxWidth: "100%",
    "&:hover": {
      borderColor: "rgba(124, 58, 237, 0.3)",
      boxShadow: "0 4px 12px rgba(124, 58, 237, 0.08)",
    },
  },
  searchMockupBarFocused: {
    backgroundColor: "#FFFFFF",
    borderColor: "#7C3AED !important",
    boxShadow: "0 0 0 3px rgba(124, 58, 237, 0.12), 0 4px 14px rgba(124, 58, 237, 0.08) !important",
  },
  searchMockupInput: {
    flex: 1,
    minWidth: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: "0.875rem",
    fontStyle: "italic",
    color: "#0F172A",
    padding: 0,
    margin: 0,
    fontFamily: "inherit",
    "&::placeholder": {
      color: "#64748B",
      fontStyle: "italic",
    },
  },
  searchClearButton: {
    background: "none",
    border: "none",
    color: "#94A3B8",
    cursor: "pointer",
    fontSize: "14px",
    lineHeight: 1,
    padding: "2px 5px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.15s ease",
    flexShrink: 0,
    "&:hover": {
      color: "#0F172A",
      backgroundColor: "rgba(0, 0, 0, 0.06)",
    },
  },
  searchInteractiveFeedback: {
    marginTop: "8px",
    padding: "8px 12px",
    borderRadius: "10px",
    backgroundColor: "rgba(124, 58, 237, 0.05)",
    border: "1px solid rgba(124, 58, 237, 0.12)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.75rem",
    color: "#475569",
    transition: "all 0.2s ease",
  },
  searchFeedbackDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#7C3AED",
    flexShrink: 0,
  },
  searchFeedbackText: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchFeedbackBadge: {
    fontSize: "0.625rem",
    fontWeight: 700,
    textTransform: "uppercase",
    padding: "2px 6px",
    borderRadius: "4px",
    backgroundColor: "rgba(124, 58, 237, 0.1)",
    color: "#7C3AED",
    letterSpacing: "0.05em",
    flexShrink: 0,
  },
  searchQueryText: {
    flex: 1,
    minWidth: 0,
    fontSize: "0.875rem",
    fontStyle: "italic",
    color: "#64748B",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  kbdShortcut: {
    padding: "3px 8px",
    borderRadius: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #CBD5E1",
    color: "#475569",
    fontSize: "0.6875rem",
    fontFamily: "monospace",
    fontWeight: 700,
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
    flexShrink: 0,
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      borderColor: "#94A3B8",
    },
  },
  tagsCollectionMockup: {
    marginTop: "28px",
    padding: "18px",
    borderRadius: "14px",
    backgroundColor: "#F8FAFC",
    border: "1.5px solid #E2E8F0",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    boxShadow: "0 2px 8px rgba(15, 23, 42, 0.04)",
    boxSizing: "border-box",
    maxWidth: "100%",
  },
  tagChipRed: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    color: "#DC2626",
    border: "1px solid rgba(239, 68, 68, 0.2)",
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipAmber: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    color: "#D97706",
    border: "1px solid rgba(245, 158, 11, 0.2)",
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipBlue: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(0, 114, 196, 0.1)",
    color: "#0072C4",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipGreen: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "9999px",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "#059669",
    border: "1px solid rgba(16, 185, 129, 0.2)",
    fontSize: "0.8125rem",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
  tagChipDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
  },

  /* ─────────────────────────────────────────────────────────────
     SECTION 5: UNIFIED MOBILE EXPERIENCE
     ───────────────────────────────────────────────────────────── */
  sectionFive: {
    position: "relative",
    width: "100%",
    padding: "96px 24px",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    boxSizing: "border-box",
    "@media (max-width: 768px)": {
      padding: "56px 16px",
    },
  },
  mobileSplitGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    gap: "clamp(32px, 4vw, 64px)",
    alignItems: "center",
    boxSizing: "border-box",
    "@media (max-width: 1040px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      gap: "40px",
    },
  },
  mobileLeftCol: {
    display: "flex",
    justifyContent: "center",
    order: 1,
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 1040px)": {
      order: 2,
    },
  },
  mobileRightCol: {
    display: "flex",
    flexDirection: "column",
    order: 2,
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 1040px)": {
      order: 1,
    },
  },
  downloadButtonsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "16px",
    marginTop: "32px",
  },
  storeButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 22px",
    borderRadius: "14px",
    backgroundColor: "#0F172A",
    color: "#FFFFFF",
    textDecoration: "none",
    boxShadow: "0 10px 25px -4px rgba(15, 23, 42, 0.18)",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    transition: "all 0.25s cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: "pointer",
    boxSizing: "border-box",
    "&:hover": {
      backgroundColor: "#1E293B",
      transform: "translateY(-3px)",
      boxShadow: "0 16px 32px -4px rgba(0, 114, 196, 0.25)",
      borderColor: "rgba(0, 114, 196, 0.4)",
    },
    "@media (max-width: 480px)": {
      padding: "10px 16px",
      gap: "10px",
    },
  },
  storeIcon: {
    width: "24px",
    height: "24px",
    fill: "currentColor",
    flexShrink: 0,
  },
  storeTextCol: {
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
  },
  storeSubtitle: {
    fontSize: "0.6875rem",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    opacity: 0.75,
  },
  storeTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    lineHeight: 1.2,
  },
  reviewsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "16px",
    marginTop: "36px",
    paddingTop: "24px",
    borderTop: "1px solid #E2E8F0",
  },
  starRatingGroup: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  starsGroup: {
    display: "flex",
    color: "#F59E0B",
  },
  ratingNumber: {
    marginLeft: "6px",
    fontSize: "1.125rem",
    fontWeight: 800,
    color: "#0F172A",
  },
  reviewsCountText: {
    fontSize: "0.875rem",
    color: "#64748B",
  },
}));
