import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  // Root outer frame
  mockupFrame: {
    maxWidth: "1140px",
    margin: "56px auto 0",
    backgroundColor: "#FFFFFF",
    borderRadius: "14px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 24px 70px -12px rgba(15, 23, 42, 0.18), 0 0 0 1px rgba(0, 114, 196, 0.08)",
    overflow: "hidden",
    fontFamily: "'Inter', 'Open Sans', -apple-system, BlinkMacSystemFont, sans-serif",
    textAlign: "left",
    boxSizing: "border-box",
    lineHeight: 1.45,
    fontSize: "12px",
    color: "#1E293B",
  },

  // Window Top Title Bar
  windowBar: {
    height: "44px",
    backgroundColor: "#F8FAFC",
    borderBottom: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    boxSizing: "border-box",
    userSelect: "none",
  },
  windowDots: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  dotRed: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#FF5F56",
  },
  dotYellow: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#FFBD2E",
  },
  dotGreen: {
    width: "11px",
    height: "11px",
    borderRadius: "50%",
    backgroundColor: "#27C93F",
  },
  addressBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "5px 14px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "9999px",
    fontSize: "11px",
    color: "#64748B",
    maxWidth: "380px",
    flex: 1,
    justifyContent: "center",
    boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  authenticatedBadge: {
    fontSize: "9px",
    fontWeight: 700,
    color: "#16A34A",
    backgroundColor: "rgba(22, 163, 74, 0.1)",
    padding: "2px 6px",
    borderRadius: "4px",
    marginLeft: "4px",
    letterSpacing: "0.03em",
  },
  windowActionBadge: {
    fontSize: "10px",
    fontWeight: 700,
    color: "#0072C4",
    backgroundColor: "rgba(0, 114, 196, 0.08)",
    border: "1px solid rgba(0, 114, 196, 0.2)",
    padding: "3px 9px",
    borderRadius: "5px",
    letterSpacing: "0.02em",
  },

  // 3-Pane Body Layout
  bodyLayout: {
    display: "grid",
    gridTemplateColumns: "220px 320px minmax(0, 1fr)",
    minHeight: "560px",
    maxHeight: "680px",
    backgroundColor: "#FFFFFF",
    position: "relative",
    "@media (max-width: 1024px)": {
      gridTemplateColumns: "190px 280px minmax(0, 1fr)",
    },
    "@media (max-width: 860px)": {
      gridTemplateColumns: "64px 280px minmax(0, 1fr)",
    },
    "@media (max-width: 680px)": {
      gridTemplateColumns: "1fr",
    },
  },

  // ── LEFT SIDEBAR (matches webcode/src/components/mailSidebar) ──────────────
  sidebar: {
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    padding: "16px 12px",
    boxSizing: "border-box",
    overflowY: "auto",
    gap: "16px",
    "@media (max-width: 680px)": {
      display: "none",
    },
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 4px",
  },
  sidebarTitle: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#1E293B",
  },
  collapseBtn: {
    color: "#64748B",
    cursor: "pointer",
    padding: "2px",
    fontSize: "13px",
    lineHeight: 1,
    "&:hover": {
      color: "#0072C4",
    },
  },
  composeButton: {
    width: "100%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    padding: "10px 14px",
    fontSize: "12px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.25)",
    transition: "background-color 0.15s ease, transform 0.15s ease",
    "&:hover": {
      backgroundColor: "#005BA6",
      transform: "translateY(-1px)",
    },
  },
  categoryGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  categoryLabel: {
    fontSize: "10px",
    fontWeight: 700,
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    padding: "4px 8px",
    marginBottom: "2px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  categoryItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 10px",
    borderRadius: "6px",
    color: "#475569",
    fontSize: "12px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.12s ease",
    userSelect: "none",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  categoryItemActive: {
    backgroundColor: "#EFF6FF !important",
    color: "#0072C4 !important",
    fontWeight: 700,
  },
  itemLeft: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
  },
  unreadBadge: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    fontSize: "10px",
    fontWeight: 700,
    padding: "1px 6px",
    borderRadius: "10px",
    lineHeight: 1.2,
  },
  tagDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    flexShrink: 0,
  },

  // ── MIDDLE PANE: MAIL LIST (matches webcode/src/pages/mail/mailList) ───────
  mailListPane: {
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #E2E8F0",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  },
  searchBarWrap: {
    padding: "12px 14px",
    borderBottom: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#FFFFFF",
  },
  selectAllCheckbox: {
    width: "15px",
    height: "15px",
    accentColor: "#0072C4",
    cursor: "pointer",
  },
  searchBox: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchInput: {
    width: "100%",
    padding: "6px 10px 6px 30px",
    fontSize: "11px",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    backgroundColor: "#F8FAFC",
    color: "#1E293B",
    outline: "none",
    boxSizing: "border-box",
    "&:focus": {
      borderColor: "#0072C4",
      backgroundColor: "#FFFFFF",
    },
  },
  searchIcon: {
    position: "absolute",
    left: "9px",
    color: "#94A3B8",
    pointerEvents: "none",
  },
  mailRowsScroll: {
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
  },
  mailRow: {
    padding: "12px 14px",
    borderBottom: "1px solid #F1F5F9",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    cursor: "pointer",
    transition: "background-color 0.12s ease",
    userSelect: "none",
    position: "relative",
    "&:hover": {
      backgroundColor: "#F8FAFC",
    },
  },
  mailRowSelected: {
    backgroundColor: "#EFF6FF !important",
    "&::before": {
      content: '""',
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      width: "3px",
      backgroundColor: "#0072C4",
    },
  },
  mailRowTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
  },
  mailRowSenderWrap: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  },
  rowAvatar: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "10px",
    fontWeight: 700,
    flexShrink: 0,
  },
  rowSender: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#1E293B",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowSenderUnread: {
    fontWeight: 800,
    color: "#0F172A",
  },
  rowDate: {
    fontSize: "10px",
    color: "#94A3B8",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  rowSubject: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#334155",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowSubjectUnread: {
    fontWeight: 700,
    color: "#0F172A",
  },
  rowSnippet: {
    fontSize: "10px",
    color: "#64748B",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: 1.3,
  },
  rowBadgesWrap: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "3px",
    flexWrap: "wrap",
  },
  tagPill: {
    fontSize: "9px",
    fontWeight: 700,
    padding: "1px 6px",
    borderRadius: "4px",
    lineHeight: 1.2,
  },
  attachmentIconSmall: {
    fontSize: "11px",
    color: "#94A3B8",
    display: "inline-flex",
    alignItems: "center",
  },

  // ── RIGHT PANE: MAIL CONTENT (matches webcode/src/pages/mail/mailContent) ──
  readerPane: {
    backgroundColor: "#FFFFFF",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    padding: "20px 24px",
    boxSizing: "border-box",
    minWidth: 0,
  },
  readerActionsBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: "14px",
    borderBottom: "1px solid #F1F5F9",
    marginBottom: "16px",
  },
  actionIconGroup: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  actionBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    cursor: "pointer",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    transition: "all 0.12s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0072C4",
      borderColor: "#CBD5E1",
    },
  },
  readerSubject: {
    fontSize: "17px",
    fontWeight: 800,
    color: "#0F172A",
    margin: "0 0 10px 0",
    letterSpacing: "-0.01em",
  },
  readerSenderCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderRadius: "8px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    marginBottom: "18px",
    gap: "12px",
  },
  senderCardLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minWidth: 0,
  },
  senderAvatarLarge: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: "13px",
    flexShrink: 0,
  },
  senderDetails: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  senderName: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#0F172A",
  },
  senderAddress: {
    fontSize: "10px",
    color: "#64748B",
  },
  readerTime: {
    fontSize: "10px",
    color: "#94A3B8",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  emailBody: {
    fontSize: "12px",
    color: "#334155",
    lineHeight: 1.7,
    marginBottom: "20px",
    "& p": {
      margin: "0 0 12px 0",
    },
  },

  // Attachment Card matching Weblings Drive Integration
  attachmentBox: {
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    backgroundColor: "#F8FAFC",
    padding: "14px 16px",
    marginTop: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  attachmentHeader: {
    fontSize: "10px",
    fontWeight: 700,
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  attachmentCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "10px 14px",
    gap: "12px",
  },
  attachmentLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  attachmentFileIcon: {
    width: "32px",
    height: "32px",
    borderRadius: "6px",
    backgroundColor: "#EFF6FF",
    color: "#0072C4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  attachmentFileName: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#1E293B",
  },
  attachmentFileSize: {
    fontSize: "10px",
    color: "#64748B",
  },
  downloadBtn: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #0072C4",
    color: "#0072C4",
    borderRadius: "5px",
    padding: "5px 10px",
    fontSize: "10px",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.12s ease",
    "&:hover": {
      backgroundColor: "#0072C4",
      color: "#FFFFFF",
    },
  },
  driveBypassNote: {
    fontSize: "10px",
    color: "#16A34A",
    display: "flex",
    alignItems: "center",
    gap: "5px",
    fontWeight: 600,
  },

  // Compose Modal (floating, matches webcode compose)
  composeModal: {
    position: "absolute",
    right: "24px",
    bottom: "20px",
    width: "440px",
    backgroundColor: "#FFFFFF",
    borderRadius: "10px 10px 0 0",
    border: "1px solid #CBD5E1",
    boxShadow: "0 20px 40px rgba(15, 23, 42, 0.25)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    zIndex: 20,
    animation: "$fadeIn 0.2s ease",
    "@media (max-width: 600px)": {
      left: "12px",
      right: "12px",
      width: "auto",
    },
  },
  "@keyframes fadeIn": {
    from: { opacity: 0, transform: "translateY(10px)" },
    to: { opacity: 1, transform: "translateY(0)" },
  },
  composeHeader: {
    backgroundColor: "#1E293B",
    color: "#FFFFFF",
    padding: "8px 14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "11px",
    fontWeight: 700,
  },
  composeClose: {
    cursor: "pointer",
    color: "#94A3B8",
    fontSize: "13px",
    "&:hover": {
      color: "#FFFFFF",
    },
  },
  composeFields: {
    display: "flex",
    flexDirection: "column",
    padding: "10px 14px",
    gap: "8px",
    borderBottom: "1px solid #F1F5F9",
  },
  composeRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "11px",
    color: "#64748B",
  },
  composeInput: {
    flex: 1,
    border: "none",
    borderBottom: "1px solid #E2E8F0",
    padding: "4px 0",
    fontSize: "11px",
    outline: "none",
    color: "#1E293B",
    "&:focus": {
      borderColor: "#0072C4",
    },
  },
  composeTextarea: {
    width: "100%",
    height: "110px",
    padding: "10px 14px",
    border: "none",
    outline: "none",
    fontSize: "11px",
    fontFamily: "inherit",
    boxSizing: "border-box",
    resize: "none",
    color: "#334155",
  },
  composeFooter: {
    padding: "8px 14px",
    backgroundColor: "#F8FAFC",
    borderTop: "1px solid #E2E8F0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  composeSendBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "5px",
    padding: "6px 14px",
    fontSize: "11px",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    "&:hover": {
      backgroundColor: "#005BA6",
    },
  },
}));
