import { createUseStyles } from "react-jss";
import { Theme } from "../../theme/themeType";

export const useStyles = createUseStyles((theme: Theme) => ({
  mockupFrame: {
    width: "100%",
    maxWidth: "1160px",
    margin: "0 auto",
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 20px 50px -10px rgba(0, 0, 0, 0.08), 0 10px 25px -5px rgba(0, 0, 0, 0.04)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
    userSelect: "none",
    position: "relative",
  },

  /* ─────────────────────────────────────────────────────────────
     TOP APPLICATION BAR
     ───────────────────────────────────────────────────────────── */
  topBar: {
    height: "52px",
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #EAECF0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 20px",
    flexShrink: 0,
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  topBarRight: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  bellBtn: {
    position: "relative",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "6px",
    color: "#475569",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  topProfileAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#F1F5F9",
    color: "#334155",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    fontSize: "0.8125rem",
    border: "1px solid #E2E8F0",
    cursor: "pointer",
    transition: "transform 0.2s",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     MAIN BODY: DUAL LEFT RAILS + MAIN CONTENT
     ───────────────────────────────────────────────────────────── */
  mainBody: {
    display: "flex",
    minHeight: "620px",
    backgroundColor: "#FFFFFF",
    position: "relative",
    overflow: "hidden",
    "@media (max-width: 900px)": {
      flexDirection: "column",
      minHeight: "auto",
    },
  },

  /* OUTER SUITE RAIL (Leftmost) */
  outerRail: {
    width: "50px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "10px 0",
    flexShrink: 0,
    gap: "8px",
    zIndex: 3,
    "@media (max-width: 768px)": {
      display: "none",
    },
  },
  railCollapseBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "transparent",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "13px",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  railAvatarCircle: {
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    backgroundColor: "#EFF6FF",
    border: "1px solid #DBEAFE",
    color: "#0072C4",
    fontSize: "13px",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    marginBottom: "4px",
    transition: "transform 0.15s ease",
    "&:hover": {
      transform: "scale(1.06)",
    },
  },
  railItem: {
    width: "100%",
    height: "38px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748B",
    cursor: "pointer",
    position: "relative",
    transition: "all 0.15s ease",
    "&:hover": {
      color: "#0072C4",
      backgroundColor: "#F8FAFC",
    },
  },
  railItemActive: {
    width: "100%",
    height: "38px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0072C4",
    cursor: "pointer",
    position: "relative",
    backgroundColor: "#F0F7FF",
    borderLeft: "3px solid #0072C4",
  },

  /* INNER SECONDARY RAIL (Project shortcuts) */
  innerRail: {
    width: "48px",
    backgroundColor: "#FFFFFF",
    borderRight: "1px solid #EAECF0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "10px 0",
    flexShrink: 0,
    gap: "8px",
    zIndex: 2,
    "@media (max-width: 640px)": {
      display: "none",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     CENTER STAGE WORKSPACE
     ───────────────────────────────────────────────────────────── */
  stageContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    minWidth: 0,
    padding: "16px 20px 24px",
    gap: "14px",
  },

  /* PROJECT HEADER & VIEWS TABS */
  projectHeaderBar: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    paddingBottom: "4px",
  },
  projectTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  backButton: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    backgroundColor: "#0072C4",
    border: "none",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0, 114, 196, 0.25)",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#005ea6",
    },
  },
  projectName: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  tabsRow: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    borderBottom: "1px solid #EAECF0",
    overflowX: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  tabBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 2px 10px",
    background: "transparent",
    border: "none",
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "#64748B",
    cursor: "pointer",
    position: "relative",
    whiteSpace: "nowrap",
    transition: "color 0.15s ease",
    "&:hover": {
      color: "#0F172A",
    },
  },
  tabBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 2px 10px",
    background: "transparent",
    border: "none",
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "#0072C4",
    cursor: "pointer",
    position: "relative",
    whiteSpace: "nowrap",
    "&::after": {
      content: '""',
      position: "absolute",
      bottom: "-1px",
      left: 0,
      right: 0,
      height: "2px",
      backgroundColor: "#0072C4",
      borderRadius: "2px 2px 0 0",
    },
  },
  tabCountBadge: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    backgroundColor: "#F1F5F9",
    color: "#64748B",
    padding: "1px 6px",
    borderRadius: "10px",
  },

  /* ─────────────────────────────────────────────────────────────
     TIMELINE CARD & GANTT ROADMAP
     ───────────────────────────────────────────────────────────── */
  timelineCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #E2E8F0",
    boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },

  /* TIMELINE CARD TOP BAR */
  timelineCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderBottom: "1px solid #EAECF0",
    gap: "12px",
    flexWrap: "wrap",
  },
  timelineTitleArea: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  timelineHeading: {
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },
  searchInputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute",
    left: "10px",
    color: "#94A3B8",
    pointerEvents: "none",
  },
  searchInput: {
    padding: "6px 12px 6px 32px",
    borderRadius: "6px",
    border: "1px solid #E2E8F0",
    fontSize: "0.8125rem",
    color: "#0F172A",
    backgroundColor: "#FFFFFF",
    width: "210px",
    outline: "none",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
    "&:focus": {
      borderColor: "#0072C4",
      boxShadow: "0 0 0 3px rgba(0, 114, 196, 0.1)",
    },
    "&::placeholder": {
      color: "#94A3B8",
    },
  },
  viewModeSwitcher: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: "8px",
    padding: "2px",
    border: "1px solid #E2E8F0",
  },
  viewModeBtn: {
    padding: "5px 12px",
    fontSize: "0.8125rem",
    fontWeight: 500,
    color: "#64748B",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      color: "#0F172A",
    },
  },
  viewModeBtnActive: {
    padding: "5px 12px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0072C4",
    backgroundColor: "#EBF5FF",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },

  /* GANTT MATRIX TABLE */
  ganttContainer: {
    flex: 1,
    overflowX: "auto",
    position: "relative",
  },
  ganttTable: {
    width: "100%",
    minWidth: "780px",
    borderCollapse: "collapse",
    position: "relative",
  },
  ganttHeaderRow: {
    height: "38px",
    borderBottom: "1px solid #E2E8F0",
  },
  ganttTreeHeaderCol: {
    width: "280px",
    minWidth: "280px",
    padding: "0 12px",
    borderRight: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  ganttMonthCol: {
    padding: "0 16px",
    textAlign: "center",
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "#475569",
    borderRight: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    width: "25%",
  },
  ganttMonthColCurrent: {
    padding: "0 16px",
    textAlign: "center",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0F172A",
    borderRight: "1px solid #E2E8F0",
    backgroundColor: "#F1F5F9",
    width: "25%",
    position: "relative",
  },

  /* TODAY BLUE LINE OVERLAY */
  todayLine: {
    position: "absolute",
    top: "38px",
    bottom: 0,
    width: "2px",
    backgroundColor: "#0072C4",
    zIndex: 10,
    pointerEvents: "none",
  },
  todayHandle: {
    position: "absolute",
    top: "-4px",
    left: "-3px",
    width: "8px",
    height: "8px",
    backgroundColor: "#0072C4",
    borderRadius: "1px",
  },

  /* GANTT ROWS */
  ganttRow: {
    height: "42px",
    borderBottom: "1px solid #F1F5F9",
    transition: "background-color 0.12s ease",
    "&:hover": {
      backgroundColor: "#F8FAFC",
    },
  },
  ganttTreeCell: {
    padding: "0 12px",
    borderRight: "1px solid #E2E8F0",
    backgroundColor: "#FFFFFF",
    verticalAlign: "middle",
  },
  ganttCellContent: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    whiteSpace: "nowrap",
  },
  expandChevron: {
    cursor: "pointer",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    height: "18px",
    border: "none",
    backgroundColor: "transparent",
    padding: 0,
    outline: "none",
    transition: "color 0.15s ease, transform 0.15s ease",
    "&:hover": {
      color: "#0072C4",
    },
  },
  chevronPlaceholder: {
    width: "18px",
    height: "18px",
  },

  /* TYPE BADGES */
  badgeEpic: {
    width: "18px",
    height: "18px",
    borderRadius: "3px",
    backgroundColor: "#9333EA",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  badgeTask: {
    width: "18px",
    height: "18px",
    borderRadius: "3px",
    backgroundColor: "#0284C7",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  badgeStory: {
    width: "18px",
    height: "18px",
    borderRadius: "3px",
    backgroundColor: "#16A34A",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  badgeBug: {
    width: "18px",
    height: "18px",
    borderRadius: "3px",
    backgroundColor: "#DC2626",
    color: "#FFFFFF",
    fontSize: "0.6875rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  itemTitle: {
    fontSize: "0.8125rem",
    color: "#0F172A",
    fontWeight: 600,
    cursor: "pointer",
    "&:hover": {
      color: "#0072C4",
    },
  },
  itemKey: {
    color: "#64748B",
    fontWeight: 500,
    marginRight: "4px",
  },

  /* MONTH DATA CELLS */
  ganttMonthCell: {
    borderRight: "1px solid #E2E8F0",
    padding: "0 8px",
    verticalAlign: "middle",
    position: "relative",
  },
  ganttMonthCellCurrent: {
    borderRight: "1px solid #E2E8F0",
    backgroundColor: "rgba(241, 245, 249, 0.65)",
    padding: "0 8px",
    verticalAlign: "middle",
    position: "relative",
  },

  /* GANTT SCHEDULE BAR */
  ganttBarWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  dateLabel: {
    fontSize: "0.6875rem",
    color: "#64748B",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  ganttBar: {
    flex: 1,
    height: "22px",
    backgroundColor: "#D8B4FE",
    borderRadius: "4px",
    position: "relative",
    display: "flex",
    alignItems: "center",
    boxShadow: "0 1px 3px rgba(147, 51, 234, 0.15)",
    cursor: "grab",
    transition: "filter 0.15s ease",
    "&:hover": {
      filter: "brightness(0.96)",
    },
  },
  ganttBarHandleLeft: {
    position: "absolute",
    left: "2px",
    top: "3px",
    bottom: "3px",
    width: "3px",
    backgroundColor: "#9333EA",
    borderRadius: "2px",
  },
  ganttBarHandleRight: {
    position: "absolute",
    right: "2px",
    top: "3px",
    bottom: "3px",
    width: "3px",
    backgroundColor: "#9333EA",
    borderRadius: "2px",
  },
  durationPill: {
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "#64748B",
    backgroundColor: "#F1F5F9",
    padding: "1px 6px",
    borderRadius: "8px",
    whiteSpace: "nowrap",
  },

  /* ─────────────────────────────────────────────────────────────
     ALTERNATIVE INTERACTIVE BOARD / KANBAN VIEW
     ───────────────────────────────────────────────────────────── */
  kanbanArea: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
    padding: "16px",
    backgroundColor: "#F8FAFC",
    borderRadius: "8px",
  },
  kanbanCol: {
    backgroundColor: "#FFFFFF",
    borderRadius: "8px",
    border: "1px solid #E2E8F0",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  kanbanColHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0F172A",
    borderBottom: "1px solid #F1F5F9",
    paddingBottom: "8px",
  },
  kanbanCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "6px",
    border: "1px solid #E2E8F0",
    padding: "10px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.02)",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      borderColor: "#0072C4",
      transform: "translateY(-1px)",
      boxShadow: "0 3px 8px rgba(0, 114, 196, 0.08)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     BREADCRUMB & TOP HEADER CONTROLS
     ───────────────────────────────────────────────────────────── */
  headerTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
  },
  breadcrumb: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "0.875rem",
    color: "#64748B",
  },
  breadcrumbLink: {
    color: "#64748B",
    cursor: "pointer",
    "&:hover": {
      color: "#0072C4",
    },
  },
  breadcrumbCurrent: {
    fontWeight: 700,
    color: "#0F172A",
  },
  createBtn: {
    backgroundColor: "#0072C4",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "6px",
    fontSize: "0.8125rem",
    fontWeight: 600,
    padding: "6px 16px",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 114, 196, 0.2)",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#005ea6",
      boxShadow: "0 3px 8px rgba(0, 114, 196, 0.3)",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     FILTER BAR (SEARCH + EPIC, PRIORITY, TAG)
     ───────────────────────────────────────────────────────────── */
  filterBarRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
    marginBottom: "4px",
  },
  filterSearchBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px 10px",
    width: "260px",
    transition: "border-color 0.15s ease",
    "&:focus-within": {
      borderColor: "#0072C4",
      boxShadow: "0 0 0 2px rgba(0, 114, 196, 0.12)",
    },
  },
  filterSearchInput: {
    border: "none",
    outline: "none",
    fontSize: "0.75rem",
    color: "#0F172A",
    width: "100%",
    background: "transparent",
    "&::placeholder": {
      color: "#94A3B8",
    },
  },
  filterSelectGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  filterDropdownBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    padding: "5px 10px",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#475569",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      borderColor: "#CBD5E1",
      backgroundColor: "#F8FAFC",
      color: "#0F172A",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     BACKLOG & SPRINT VIEWS LAYOUT
     ───────────────────────────────────────────────────────────── */
  backlogSplitLayout: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    minWidth: 0,
    "@media (max-width: 960px)": {
      gridTemplateColumns: "1fr",
    },
  },
  sprintFullLayout: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minWidth: 0,
    width: "100%",
  },
  paneCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    position: "relative",
    boxShadow: "0 1px 3px rgba(0,0,0,0.02)",
  },
  paneHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: "10px",
    borderBottom: "1px solid #F1F5F9",
    position: "relative",
  },
  paneHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  paneHeaderCount: {
    fontSize: "0.75rem",
    fontWeight: 500,
    color: "#64748B",
  },
  paneHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  paneActionLink: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#0072C4",
    cursor: "pointer",
    background: "none",
    border: "none",
    padding: 0,
    transition: "color 0.15s ease",
    "&:hover": {
      color: "#005ea6",
      textDecoration: "underline",
    },
  },
  paneIconBtn: {
    background: "none",
    border: "none",
    color: "#64748B",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2px",
    borderRadius: "4px",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
      color: "#0F172A",
    },
  },
  showSprintDropdownMenu: {
    position: "absolute",
    top: "36px",
    right: "60px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    boxShadow: "0 10px 25px -5px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)",
    padding: "10px 12px",
    zIndex: 20,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minWidth: "130px",
  },
  showSprintMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.75rem",
    color: "#0F172A",
    cursor: "pointer",
    userSelect: "none",
    "&:hover": {
      color: "#0072C4",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     ISSUES LIST & TICKET ROWS
     ───────────────────────────────────────────────────────────── */
  issuesList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  issueItemRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 10px",
    borderRadius: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #F1F5F9",
    gap: "8px",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#F8FAFC",
      borderColor: "#CBD5E1",
      boxShadow: "0 1px 4px rgba(0,0,0,0.03)",
    },
  },
  issueItemLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    flex: 1,
  },
  issueCheckbox: {
    width: "14px",
    height: "14px",
    borderRadius: "3px",
    border: "1px solid #CBD5E1",
    cursor: "pointer",
    accentColor: "#0072C4",
  },
  issueKeyText: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#64748B",
    whiteSpace: "nowrap",
  },
  issueTitleText: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#0F172A",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    cursor: "pointer",
    "&:hover": {
      color: "#0072C4",
    },
  },
  issueItemRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  epicPill: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    backgroundColor: "#FAF5FF",
    border: "1px solid #E9D5FF",
    color: "#7E22CE",
    fontSize: "0.6875rem",
    fontWeight: 600,
    padding: "2px 7px",
    borderRadius: "4px",
    whiteSpace: "nowrap",
  },
  epicMiniBadge: {
    width: "13px",
    height: "13px",
    borderRadius: "2px",
    backgroundColor: "#9333EA",
    color: "#FFFFFF",
    fontSize: "0.5625rem",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  statusPill: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    backgroundColor: "#F1F5F9",
    border: "1px solid #E2E8F0",
    color: "#475569",
    fontSize: "0.6875rem",
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: "4px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "#E2E8F0",
      color: "#0F172A",
    },
  },
  createIssueRowBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "7px 10px",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#64748B",
    background: "none",
    border: "1px dashed #CBD5E1",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    marginTop: "4px",
    "&:hover": {
      color: "#0072C4",
      borderColor: "#93C5FD",
      backgroundColor: "#F0F7FF",
    },
  },

  /* ─────────────────────────────────────────────────────────────
     SPRINTS ACCORDION
     ───────────────────────────────────────────────────────────── */
  sprintAccordion: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  sprintHeaderBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "7px 10px",
    backgroundColor: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "#F1F5F9",
    },
  },
  sprintHeaderTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "#0F172A",
  },
  sprintChevronBtn: {
    background: "none",
    border: "none",
    color: "#64748B",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    cursor: "pointer",
  },
  sprintMetaText: {
    fontSize: "0.6875rem",
    fontWeight: 500,
    color: "#64748B",
  },
  sprintActionGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sprintGhostBtn: {
    backgroundColor: "#FFFFFF",
    color: "#475569",
    border: "1px solid #CBD5E1",
    borderRadius: "4px",
    fontSize: "0.6875rem",
    fontWeight: 600,
    padding: "3px 8px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      borderColor: "#94A3B8",
      backgroundColor: "#F8FAFC",
      color: "#0F172A",
    },
  },
}));
